compiler-explorer/compiler-explorer

lib/parsers/llvm-pass-dump-parser.ts
test/llvm-ir-parser-tests.js

Per [Matt's request](https://github.com/compiler-explorer/compiler-explorer/pull/4127#pullrequestreview-1134515833) added some simple tests.
The struggle against `prettier` took longer than the actual code and resulted in my loss (==`prettier-ignore`). Suspect I stumbled upon `prettier` bugs but left them alone.
When `fiterAllMetadata` (or similar) is added to LLVMOptPipelineBackendOptions, adding tests for it should now be trivial. Might be worth awhile to test other LLVMOptPipelineBackendOptions fields later - but some are not intra-line filters and require more logic.

Add tests to LlvmPassDumpParser intra-line filters

---

etc/config/c++.amazon.properties

The "auto NSDMI" branch has not actually fully supported non static members in a while, as the patch was initially written for clang 9, and I have not gotten around to fix it.
The branch now contains a number of experimentals proposals including
* parameter pack indexing (https://isocpp.org/files/papers/D2632R0.pdf)
* magic char8_t cast function
* _ for variable names
* non trailing parameter packs
* constexpr structured bindings
* constexpr cast from void*
* And more to come
P2632 is the paper presenting the majority of these features, and the current plan is to implement as much of it in clang as possible.
The wg21.link link will become active at publication of the paper next week.

Change the name of the "auto NSDMI" branch.

---

lib/compilers/zig.ts

Compilations that may panic reference this function which now has an additional `ret_addr` parameter. This updates to the new function signature.
See also https://github.com/ziglang/zig/blob/697e22caa49716369dff6c86461b94fe10b0a009/lib/std/builtin.zig#L758 as a reference.

fix: Zig trunk compile error

---

static/panes/editor.js

We were not checking that the execution response was for one of the editor's executors
Fixes #4137

Fixes editor annotations showing for unreleated exec panes

---

etc/config/cuda.amazon.properties

As mentioned in #4097, this needed to be done to allow proper semver ordering

Fully specifies rocm compiler names

---

static/options.interfaces.ts
static/panes/compiler.ts

The options were being properly passed in the state, but the UI was being initialized before the value was set to the member, causing it not to be displayed.
Closes #4207

Fixes compiler init order by using initializeStateDependentProperties

---

static/panes/compiler.ts

Fixes 6yo variable typo

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

Fixes #4156, fixes #3166
Previously these were all set to use an x86_64 toolchain which clearly isn't right. This lead to things like uintptr_t being smaller than void*.
Use the same toolchain and sysroot for the "all architectural features" as for the rest of the configurations.
This also changes the -target to "gnu" not "android" to match the new settings.

Correct gcc-toolchain for "all architectural features" armv8 clang

---

etc/config/c++.amazon.properties

These configs are missing for C++ (already present for C).
refs #4158

Add clang++ 12, 13, 14 and 15 for aarch64

---

etc/config/c++.amazon.properties

Adds [`std::exec`](https://github.com/NVIDIA/stdexec/) as a C++ library.
Related PR: https://github.com/compiler-explorer/infra/pull/854

Add stdexec C++ library

---

etc/config/python.amazon.properties

Another year, another stable Python has been released. Please double check my changes because I believe I missed something last year.
Related PR in infra: https://github.com/compiler-explorer/infra/pull/860

Add Python 3.11 and make it the default

---

views/popups/settings.pug

Where possible this abstracts away the setting html specifics, which reduces repetition

Use mixins in settings to make it easier to maintain

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

Add config for newly supported target: Loongarch64
Our support starts from GCC 12.2.0 for C, C++, Fortran and D.
fixes #4162

Add config for Loongarch64

---

lib/parsers/llvm-pass-dump-parser.ts
static/panes/llvm-opt-pipeline.ts
test/llvm-pass-dump-parser-tests.js
types/compilation/llvm-opt-pipeline-output.interfaces.ts
views/templates/panes/llvm-opt-pipeline.pug

Following [comments ](https://github.com/compiler-explorer/compiler-explorer/pull/4127#issuecomment-1272102949) from @jeremy-rifkin and @jryans, this PR is an addition of an option to hide all IR metadata:
Notes:
1. Names were changed from 'filter' to 'hide', seems more natural UI phrasing.
2. This is _not_ a superset of 'hide debug'. `llvm-debug` intrinsics _are_ unfiltered by the new option - can be filtered by checking both old an new options.
3. This filters also attribute-groups on function definitions, but not individual attributes.
4. There's also a small addition to the 'hide debug' option - hiding rows that include `debug-location` which typically appear in later stages of the pipeline.
5. Added a test too

Add `Hide metadata` option to LLVM pipeline

---

lib/languages.ts
static/panes/compiler.ts
static/panes/editor.interfaces.ts
static/panes/editor.ts
types/languages.interfaces.ts
views/templates/panes/codeEditor.pug

This would close #703, but mayeb we want to keep iterating on it before marking it as completed. Right now it shows the built-in browser tooltip for titles, but maybe we want to use Bootstrap's popups at least for the button?

Add language tooltips

---

etc/config/c.amazon.properties

The GCC compiler for "static analysis" was used before the work was merged in GCC's trunk. There's no need to track the `devel/analyzer` branch anymore.
The C++ compiler is already hidden (d5b0e2011a5208e80460b47c63d45bd08fe1e34e). This changes does the same for the C compiler.
fixes #4256

Hide gcc static analysis compiler

---

static/panes/compiler.ts

This fixes popular argument iteration to pluck out the argument via the object key instead of showing an array index.
Regressed by https://github.com/compiler-explorer/compiler-explorer/pull/4132

Fix popular arguments iteration in UI

---

lib/handlers/compile.js

Fixes bug found while triaging another bug ![image](https://user-images.githubusercontent.com/51220084/201390683-dabb22f2-bc4a-4f63-9b7d-f438b7235a96.png)
`CompilationResult` expects stdout to never be undefined

Fix "stdout is undefined"

---

etc/config/c++.amazon.properties

This seems like the better of the alternatives,
but happy to change if anyone thinks otherwise
Closes #4092

Use gcc trunk for clang-tidy

---

etc/config/c++.amazon.properties

Incorrect name was used for 12.2.0.
Also removed useless .name properties as baseName+semVer give the same name.

Fix ppc64le gcc names

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

Add C, C++, Fortran for sparc, sparc64, sparc-leon.
Add Ada and Go for sparc and sparc64.
Not adding D (same issue as
https://github.com/compiler-explorer/compiler-explorer/pull/4096#issuecomment-1264304330)
Fixes #266

Add config for sparc, sparc64 and sparc-leon

---

lib/base-compiler.ts
types/compilation/compilation.interfaces.ts

Taken from https://github.com/compiler-explorer/compiler-explorer/pull/4230 - but that might take a while to merge, while this is useful for more things.
Offers no way to see in the UI, but we can see it in the network traffic so we can debug buildsteps better.

store compilationOptions so that we can debug buildsteps better

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add new ACB 4.10.0 version.
Also add missing objdumper for c++ compiler for 4.9 and 4.8. It's not a good idea to mix binutils versions for this arch, better stick with coherent versions.
fixes #4280

Add new version of Kalray' KVX compiler

---

etc/config/c.amazon.properties

This adds the llvm-mos 6502 SDK and toolchain. See http://llvm-mos.org and https://github.com/llvm-mos/llvm-mos-sdk for details.
See compiler-explorer/infra#874.

Add llvm-mos trunk.

---

etc/config/python.defaults.properties
etc/scripts/docenizers/docenizer-python.py
lib/asm-docs/generated/asm-docs-python.js
lib/asm-docs/python.ts

This follows the code from `docenizer.py`, but simplified a lot as Python offers them all in the same place

Add Python instruction docs

---

etc/config/c++.amazon.properties

The llvm-mos clang supports freestanding C++ as well, so this adds a corresponding C++ configuration.

Add C++ configuration of llvm-mos trunk.

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

This updates the command line options to include:
* armv8.8-a as the baseline architecture, which is the latest.
* New extensions:
* brbe - Branch Record Buffer
* f32mm - SVE FP32 single-precision floating-point matrix
multiplication
* f64mm - SVE FP64 double-precision floating-point matrix
multiplication
* fp16fml - Floating-point half-precision multiplication
* hbc - Hinted conditional branches (implied by v8.8-a)
* ls64 - Atomic single-copy 64-byte loads and stores
without return
* mops - Standardization of memory operations (implied by v8.8-a)
* sme - Scalable matrix extension
* sme-f64f64 - Double-precision floating-point outer product
* sme-i16i64 - 16-bit to 64-bit integer widening outer product
* sme2 - Extension to SME with multi-vector operations,
multi-vector predicates, range …

Update feature set for "all architectural features" armv8-a clang

---

etc/config/c++.amazon.properties
etc/config/cuda.amazon.properties

This change adds ROCm 5.3.2 for C++ and HIP. It depends on:
- https://github.com/compiler-explorer/misc-builder/pull/49
- https://github.com/compiler-explorer/infra/pull/857

Add ROCm 5.3.2

---

etc/config/c++.amazon.properties

Also adds instructionSet to the aarch64 version

Fixes nvc++ compilers missing groupName/baseName

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Manually setting --target=mos on the various llvm-mos targets prevents the clang driver from picking up the configuration files shipped with the llvm-mos SDK. This prevents include files from working.
Instead, this change uses -fno-lto -mllvm -zp-avail=224 to set up a reasonable standalone build configuration. This disables the default LTO so that assembly can be produced, and it configures the compiler to report that the full 256 bytes of zero page are available. (32 bytes of implicit "imaginary registers", and 224 bytes of explictly managed zero page. This isn't accurate per-target, but good for standalone demonstration purposes. It would take some compiler work to add a flag to expose the per-target LTO zero page configurations to a -fno-lto build.)

Fix llvm-mos clang config file usage.

---

lib/compilers/golang.ts
test/golang-tests.js

Some change in the front made this error surface, change it to something we can handle

Fix error with null stderr

---

app.js
lib/compiler-finder.js

If discovery fails for whatever reason (no compilers; compiler creation threw an exception) we now see this:
```
error: Exception while processing compilers: ...blah some thing that went wrong goes here...
error: #### No compilers found: no compilation will be done!
error: Top-level error (shutting down): No compilers found due to error or no configuration {"stack":"Error: No compilers found due to error or no configuration\n    at CompilerFinder.find (/home/matthew/dev/ce/compiler-explorer/lib/compiler-finder.js:408:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async main (/home/matthew/dev/ce/compiler-explorer/app.js:476:36)"}
```
and the process exits.

Fail if compiler discovery fails

---

lib/compilers/dotnet.ts

We need to pass the directory instead of files as the input to `-r`
/cc: @mattgodbolt

Fix crossgen2 arguments

---

.husky/pre-commit

As briefly discussed on discord, this turns off testing during precommit. Motivation: Our tests our slow which has led to a lot of committing with `-n` and ultimately gets in the way of some more important precommit actions such as linting and formatting files being committed.

Don't test during precommit

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties
examples/csharp/default.cs
examples/fsharp/default.fs
examples/vb/default.vb
lib/base-compiler.ts
lib/compilers/dotnet.ts

- Support trunk version for .NET
- Support execution for .NET
- Change how we detect supportsObjdump (the value can be `undefined`)
This time it should be pretty straightforward.
/cc: @mattgodbolt

Support trunk and execution for .NET

---

static/modes/asm-mode.ts

.NET uses them, it seems. Closes #4350

Support backticks in labels

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties
lib/compilers/dotnet.ts

we are tied to `sdk.version` internally used by runtime repo https://github.com/dotnet/runtime/blob/main/global.json#L3  so we can't use `net8.0` yet.
it is "possible" to build daily build of sdk (or download binaries directly from https://github.com/dotnet/installer#table), but we don't need that because all we build an msil using the sdk, then crossgen with given runtime (in this case the bleeding edge version), so sdk doesn't matter.
fix error:

dynamically set targetFramework

---

etc/nsjail/execute.cfg
lib/compilers/dotnet.ts

Removes shared variable that would conflict with simultaneous compilations
Also ups pids max because of an issue I was hitting locally

.net - compileToBinary fix

---

etc/config/cuda.amazon.properties

This library with C++ compiler already
library source and details here: https://gitlab.com/correaa/boost-multi
Corresponding changes in infra don't seem to be necessary since they were already in place for C++ and Circle compiler.

Add Multi library to CUDA compiler

---

.husky/pre-commit

`lint-staged --verbose` will print eslint output even when it fails so the dev is notified about linter warnings during pre-commit

Invoke lint-staged with --verbose

---

.eslintrc.yml
lib/mapfiles/map-file-delphi.ts
lib/mapfiles/map-file-vs.ts
lib/mapfiles/map-file.ts

First pass ts conversion for lib/mapfiles

---

etc/config/rust.amazon.properties

gccrs is still in heavy dev and to avoid anyone missing this crucial info, it has introduced a very explicit option and required option:
-frust-incomplete-and-experimental-compiler-do-not-use
The compiler emits a very verbose error if this option is missing.
refs https://github.com/Rust-GCC/gccrs/pull/1540

Add special option for gccrs

---

static/styles/explorer.scss

Quick fix for a bug that happens in staging and never locally

Fix tomselect arrow padding

---

etc/config/c++.amazon.properties
lib/base-compiler.ts
lib/compiler-finder.ts
types/compiler.interfaces.ts

`--debug-to-stdout` is currently the parameter name to change the llvm ir pass output to (buffered) stdout instead of the default unbuffer stderr
Speeds up opt pipeline view from 12+ seconds to 4-5ish seconds.
requires this to be patched into llvm https://github.com/llvm/llvm-project/compare/main...compiler-explorer:llvm-project:dbg-to-stdout?expand=1

Support patched clang for faster opt-view

---

etc/config/dart.amazon.properties

Infra PR: https://github.com/compiler-explorer/infra/pull/895
Adds dart version 2.18.5 (I think it makes sense not to include all patch versions) and the latest dev channel build (currently version 3.0).

Add more dart versions

---

etc/config/carbon.defaults.properties
lib/base-compiler.ts
lib/compilers/carbon.ts
types/compilation/compilation.interfaces.ts

Carbon tried to synthesize "having run" by overriding and hacking a result routine...but did so _after_ it had been cached. So cached results were broken, but live results not.
This "fixes" by adding a post-compilation, but pre-cache hook and uses that instead. Naming is terrible.
I also took the time to fix the `CompilationResult`'s `buildResult`
Closes #4426

Don't try and hack the compilation results

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties

Depends on https://github.com/compiler-explorer/infra/pull/899 and fixes https://github.com/compiler-explorer/compiler-explorer/issues/4405
update pahole version and name

update pahole name

---

Makefile

This provides a simple interface for build scripts that want to pre-run the webpack and ts-compile steps (e.g. when producing a container image) ahead of time rather, without requiring them to copy the current set of commands needed for each part and hope they don't change.
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/3287

Makefile: Split run into new prebuild and run-only targets

---

static/settings.ts
static/themes.ts
static/widgets/site-templates-widget.ts

Apparently it's possible for the theme to be `undefined` which is causing errors like `Error: Cannot find module './LLVMIR.undefined.png'`, see COMPILER-EXPLORER-9D4 in sentry. Previously addressed a similar issue in #4107/#4108.

Handle undefined theme in the site template widget

---

lib/compilers/_all.js
lib/compilers/clangcl.ts
lib/demangler/_all.js
lib/demangler/win32-llvm.js
lib/parsers/asm-parser.ts

This PR adds support for clang-cl and llvm-undname.
This makes it possible to cross-compile from linux to windows with clang-cl and make it behave like msvc.
There is also a bugfix that fixes the parsing of `.cv_file`.
Here is an example configuration for cross-compiling with clang-cl:
```
group.clangcl.compilers=clangcl
group.clangcl.groupName=clang-cl win64
group.clangcl.instructionSet=amd64
group.clangcl.compilerType=clang-cl
group.clangcl.options=/winsdkversion 10.0.22000.0 /winsysroot /path/to/sysroot
group.clangcl.demangler=/usr/local/bin/llvm-undname
group.clangcl.demanglerType=win32-llvm
group.clangcl.supportsBinary=false
```

Add support for clang-cl and llvm-undname

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add GCC for C and C++, for BPF target.
fixes #4408

add: gcc bpf cross compiler

---

static/panes/compiler.ts

This fixes the the bug with the hex labels being colored blue (in light mode they look fine until you hover)
They are also clickable, but when you click them they error:
I think this has come up in sentry, I'll have to look for which issue.
This was an inadvertent change during the ts conversion, [`monaco.languages.Command`][1] expects an `id` which we didn't use to pass. Passing it makes the code lens decorations clickable.
[1]: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.Command.html

Fix binary lable issue

---

etc/config/rust.amazon.properties

This adds Subtle #4449 and Rayon #3927

Add new rust crates

---

lib/base-compiler.ts
lib/options-handler.ts
lib/tooling/base-tool.ts
static/panes/compiler.ts
test/options-handler.js
types/compiler.interfaces.ts
types/tool.interfaces.ts

I realised we were using the "Tool" on both client and server, but the client only has the JSON-able data of Tool, not the interface/object Tool (now renamed to `ITool`).

Separate shareable tool type from server ITool

---

views/_layout.pug

The logic to avoid the flash assumed only "default" or "dark" theme, so it was not ready for the new ones. Avoids white flashes by assuming that anything not "default" will be "dark"
Closes #4487

Avoid flash on pageload for System and Dark+ themes

---

lib/llvm-ir.ts
test/llvm-ir-parser-tests.js
types/asmresult/asmresult.interfaces.ts

untested as i changed this on windows
(npm run format really makes a mess of things on windows O_o but adding `endOfLine: 'crlf',` to the `.prettierrc.js` fixes that)

minimal ts conv of llvm-ir

---

lib/base-compiler.ts
lib/compilers/assembly.ts
lib/compilers/beebasm.ts

I think this should be enough for most compilers under the assembly language that would have good support out-of-the-box
For #4399

Mark Assembly compilers cfg-able

---

etc/scripts/parsed_pug_file.js
webpack.config.esm.js

If we don't have a `.git` directory during build, then don't try and run `git` commands to get e.g. history and last changed for policy files and changelog.
Closes #4497

Don't rely on git if .git isn't there during build

---

static/panes/cfg-view.ts
static/styles/explorer.scss
views/templates/panes/cfg.pug

This PR adds a rough order of magnitude size estimate for the png export button:
This is an attempt to warn a user what they're getting into in the event someone produces a massive CFG :)

Show a size estimate for the png export button

---

app.js

We've seen some uncaught exceptions where the process exits before logs are apparently flushed. This hopefully addresses that.
With ref to https://github.com/winstonjs/winston/issues/1504#issuecomment-1033087411 and https://nodejs.org/api/process.html#event-uncaughtexception

Different uncaughtException handling

---

lib/base-compiler.ts

Fixcrashissue

---

lib/buildenvsetup/ceconan.ts

To fix issue where conan server is being spammed with /v1/conans/gnulibbacktrace/autodetect/gnulibbacktrace/autodetect/search which obviously doesn't exist

dont query conan if library is autodetect

---

lib/buildenvsetup/ceconan.ts

Handle zero-sized files
It appears that having a zero-sized file won't call our `next()` handler which means we wedge forever and eventually time out.
This is a workaround. Upstream issue filed as https://github.com/mafintosh/tar-stream/issues/145

Handle zero-sized files

---

etc/config/csharp.defaults.properties
lib/compilers/dotnet.ts

follow up https://github.com/compiler-explorer/misc-builder/pull/55
* the version shown in the info box
is sdk version used by dotnet/runtime repo. it updates once or twice a year. it is not very useful for user interested in assembly codegen...
* comment added here is for crossgen2 version, which has useful version+commit info of dotnet/runtime repo
dotnet 6 and 7 will also show the version once there is a new deployment. for now they are showing `7.0.0-dev` and `<unknown version>` respectively

display crossgen2 version in asm output

---

etc/config/jakt.amazon.properties

The way that jakt calls out to a C++ compiler to compile the C++ source files it generates is sensitive to which compiler compiled its runtime library. Rather than using clang-trunk, use the same compiler that was used in misc-builder: gcc-12.1.0. This does cause a warning or two, as it seems gcc 12.1.0 doesn't implement [[unlikely]] yet, but that's better than not being able to link executables at all.
This issue will likely come up again if the compiler used in misc-builder to build the jakt compiler changes.
This will likely make jakt main work again on CE, after https://github.com/SerenityOS/jakt/pull/1298 is pulled in. The version that last built properly on the live site should also work after this change, it just won't be main :)

Jakt: Ensure cxx-compiler-path matches the compiler that compiled jakt

---

static/panes/tree.ts

Does not solve issues with corrupt .zip files (will result in console errors), but is a thing for in case people think they can load any file with the option

Show error when not loading a zip through the IDE - Project - load from file

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

4.11.0 as published on github is not compatible with ubuntu 18.04. Use their new release build for 20.04 instead of one for 22.04.
We don't usually remove a compiler to preserve existing links. But ACB 4.11.0 has never been working, so we can forget about it.
fixes #4523

fix: use Kalray's ACB 4.11.1

---

lib/tooling/base-tool.ts

An empty value for exclude prop for tool ends up being interpreted as a * wildcard. The variable is a string[] and is set to a single empty string.
fixes #4544

fix: empty exclude value in option file badly handled

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add 3 latest clang version aliases to BPF target.
refs #4408

Add few clang compiler alias for BPF target

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Use cross GCC for driving a link to binary.
refs #4408

bpf: use gcc for linking BPF binaries

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

... until we have a fix for either:
- calling gcc to drive the link
- don't link to get an object file
Downcase CLANG name, no need to shout.
refs #4408

bpf: disable binary support for Clang

---

views/options-output.pug

With the merge of #3232, we need to distinguish "compile to binary object" (compiler + assembler) and "compile to binary" (compiler + assembler + linker).
Renaming "compile to binary" as "link to binary" is more correct in this context and less confusing.
We don't rename the internal field (kept as 'binary') because it's part of the API and we can't break it.

rename: compile to binary -> link to binary

---

lib/base-compiler.ts
lib/compilers/beebasm.ts
lib/compilers/cc65.ts
lib/compilers/llvm-mos.ts
lib/compilers/z88dk.ts
static/panes/compiler.ts
types/compilation/compilation.interfaces.ts
types/tool.interfaces.ts

As discussed a while ago in discord, this breaks API, but I think it's acceptable in this case.
Tested:

Move emulation related fields to artifact system

---

lib/tooling/pahole-tool.js

Condition was badly changed in #3232 (compiling to binary objects)

fix: pahole wrongly refuses to do anything

---

etc/scripts/docenizers/docenizer-amd64.py

I think the more https the better

chore: use https for links

---

static/sharing.ts

This fixes the core issue with #4541 and closes #4541, separately I'll add better diagnostics for the user for when things go wrong

Use double quotes for embed iframes

---

Makefile
etc/scripts/docenizers/Makefile
etc/scripts/docenizers/docenizer-java.js

Add `make asm-docs`

---

etc/config/hook.amazon.properties
etc/config/hook.defaults.properties
lib/compilers/hook.ts
test/compilers/hook-tests.js

* Ignore trim (Horizontal whitespace) filter;
* Update instructionSet, and
* Fix core module loading

Ignore trim filter for Hook

---

etc/config/rust.amazon.properties

Add a cross-gcc targeting BPF.
Also do some cleaning of group names.

rust: add cross gcc for BPF

---

static/styles/themes/dark-theme.scss

Added the property to match the dark theme on the tooltip arrow.

issue : #4628 , Dark theme arrow property corrected

---

etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

This change removes any references to Arm in SPIR-V compiler for OpenCL as there isn't anything specific to Arm in the compilation process. It also avoids using Arm specific workaround because SPIR-V compilation in clang doesn't suffer from the same limitation.
This change also makes explicit the fact that compilation uses llvm-spirv as clang now has internal SPIR-V support too which should be added here once it matures.

Clean up OpenCL compilation into SPIR-V.

---

etc/config/cpp_for_opencl.amazon.properties

Since clspv compiler supports C++ for OpenCL add this compiler mode to the language just the same way as it's done for OpenCL C.
Note that the use of C++ for OpenCL with clspv at present requires extra flags: "-cl-std=CLC++" and
"-inline-entry-points".

Add clspv compiler to C++ for OpenCL.

---

etc/config/c++.amazon.properties

Adding new compilers to the configuration. This depends on compiler-explorer/infra#926

Adds new Xtensa Esp32 compilers.

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Adjust config for aliasing clang 15, 14 and 13 for targeting MIPS, MIPS64, MIPSEL and MIPS64EL.
Disabling binary support as it's causing errors when reusing gcc toolchain.
fixes #3282

Add cross clang config for MIPS

---

lib/llvm-ast.ts

Baseline for converting lib/llvm-ast, I have not tested locally yet

Tsify llvm-ast

---

lib/handlers/source.ts
lib/sources/browser.ts
lib/sources/builtin.ts
lib/sources/index.ts
test/handlers/source-tests.js

Also some small refactors, including deleting the `save` action that wasn't ever implemented for either builtin or browser

Tsify and refactor lib/handlers/source.js

---

docs/AddingAssemblyDocumentation.md
package-lock.json
package.json
test/handlers/asm-docs-tests.ts
test/utils.ts
tsconfig.backend.json

Adds the final few bits needed in tsconfig to properly run the chai-http test infrastructure as well as turning the asm docs tests into ts

Tsify asm-docs-tests to typescript with utils

---

etc/scripts/julia_wrapper.jl

`code_typed` in Julia also takes the optimize option.

[Julia] pass optimize to typed

---

lib/tooling/clang-tidy-tool.ts
types/tool.interfaces.ts

Tsify `clang-tidy-tool` and added optional fields to `ToolResult`.

Tsify clang-tidy-tool

---

etc/scripts/julia_wrapper.jl
lib/compilers/argument-parsers.ts

https://github.com/compiler-explorer/compiler-explorer/pull/4674 wasn't quite finished.
This goes the last mile, and shows the user the options from the compiler-wrapper.

[Julia] show options from compiler wrapper not Julia runtime

---

lib/cache/from-config.ts
test/cache-tests.ts
test/nim-tests.ts

Added generic typing to lib/cache/from-config
nim-tests got added after a make lint (--fix)

Converted cache-tests to typescript

---

.eslintrc.yml
package.json
test/.eslintrc.yml

- make all things we mention in our lintrc `errors`
- `max-warnings=0` too
- allow `!` null checks in tests

Precommit errors

---

etc/config/go.amazon.properties

GO compiler naming was not coherent (and some were incorrect). Try to make them more homogeneous.
fixes #4733

fix: GO compiler names

---

etc/config/c++.amazon.properties

- The old version was getting libstdc++ from gcc-9.2.0 instead of trunk (13.x). After this patch, passing `-stdlib=libstdc++` will get you libstdc++ trunk, which includes things like `<ranges>` that are missing from 9.x.
- While I'm in the vicinity, let's stop defaulting to -std=c++2a; this was more appealing when Clang trunk defaulted to -std=c++98, but now that trunk defaults to -std=c++17, I don't think the divergence buys me anything.
- For the record, I added `-g0` in 4128fcc57 (back in 2019) to fix a crash with DWARF info, and never got around to investigating it. It's probably no longer needed, but I don't know, so I'm leaving it in place.

compiler.clang_p1144: get libstdc++ headers from trunk, remove -std=c++2a

---

.github/labeler.yml
etc/config/modula2.amazon.properties
etc/config/modula2.defaults.properties
examples/modula2/default.mod
lib/compilers/_all.ts
lib/compilers/gm2.ts
lib/languages.ts
static/modes/modula2-mode.ts
types/languages.interfaces.ts

With the upcoming gcc 13 release and it's shiny Modula-2 frontend, we
are introducing Modula-2 support in Compiler Explorer :)
Currently, only the gcc-snapshot build supports modula-2.
fixes #4688

 Initial support for Modula-2 language

---

.github/workflows/test-frontend.yml

This should fix the issue of cypress CI frequently timing out and having to manually re-run to get checks to be OK

Fix cypress timeout issue

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Final CC part for new toolchains
Related infra patch https://github.com/compiler-explorer/infra/pull/935
Related cross-gcc patch https://github.com/compiler-explorer/gcc-cross-builder/pull/50

Add GCC 9.4, 9.5, 10.4 for Arm and AArch64 and And Morello Alpha 2

---

etc/config/ispc.amazon.properties

Adding ISPC v1.19.0.
Corresponding infra commit PR, which needs to be merged before this PR: https://github.com/compiler-explorer/infra/pull/950 (so ISPC v1.19.0 is available in the infra).

Add ISPC v1.19.0

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties

adding new versions without hiding the old ones. when we will reach about 10+ versions, then we can hide the oldest ones (.hidden=true) to keep the permalinks. right now there is no point in hiding few months old versions as the dropdown is pretty much empty

update dotnet versions

---

lib/tooling/pahole-tool.ts
lib/tooling/readelf-tool.ts
lib/tooling/strings-tool.ts

Closes #4772 by outputing the `.name` property if it exists, falling back to the class specific one if not.

Add name to binary tools error response

---

static/components.interfaces.ts
static/components.ts

When adding the Tree, cmake_build_type is automically set to debug
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/4825

Add default cmake arg

---

etc/config/c++.amazon.properties
lib/base-compiler.ts
lib/toolchain-utils.ts

Fixes https://github.com/compiler-explorer/compiler-explorer/issues/4827
Seems to not break anything.
Toolchain is filtered out because that's passed as `-DCMAKE_TOOLCHAIN_etc`
Can always be overridden by https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS (`-DCMAKE_CXX_FLAGS=etc` as cmake arg or `set(CMAKE_CXX_FLAGS "etc")`)

Pass compiler options to cmake

---

lib/s3-handler.ts

I hope it's OK to reuse the same client for multiple in-flight requests, as effectively this means we'll have one client only. I'm pretty sure we're effectively doing this already in the cache where multiple in-flight requests from users will be served from the one cache's S3 client, but couldn't find any documentation about this.

Cache S3Bucket clients by region

---

package-lock.json
package.json
static/modes/cppp-mode.ts
static/panes/editor.ts

Currently blocked as during dev we see:
```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 76:0-57
Module not found: Error: Can't resolve './contrib/stickyScroll/browser/stickyScroll.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
@ ./static/themes.ts 29:22-46
@ ./static/main.ts 47:34-56
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 84:0-77
Module not found: Error: Can't resolve './contrib/viewportSemanticTokens/browser/viewportSemanticTokens.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
@ ./static/themes.ts 29:22-46
@ ./static/main.ts 47:34-56
```
which seem to be related to newer features in monaco. Filed https://github.com/microsoft/monaco-editor/issues/3796 to …

Bump to latest monaco

---

lib/compilers/gnucobol.ts

Fair warning: this was just edited online, I've no clue if this works (or at least still compiles)

GnuCOBOL: allow use of default copybooks

---

static/panes/editor.interfaces.ts
static/panes/editor.ts

Following discussion at #4817 and with partouf/matt. An editor's state.lang being undefined should probably always be an error since it'll be susceptible to the same default language shenanigans. 
Closes #4817

Give an error when no editor language is specified

---

etc/config/c.amazon.properties
lib/compilers/_all.ts
lib/compilers/compcert.ts

Add support for CompCert (https://github.com/AbsInt/CompCert) from AbsInt.
As a first step, only x86 and x86_64 are supported.
fixes #595

Support for CompCert

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/objc.amazon.properties

Add vax-netbsdelf cross compilers for C, C++ and Objective-C.
Also fix minor naming inconsistencies in ppc compilers.
fixes #4783

First support for VAX cross compiler

---

etc/config/cobol.amazon.properties
lib/compilers/_all.ts
lib/compilers/gcccobol.ts

Support for GCC cobol snapshot for external repository (until it is
merged in GCC, someday).
fixes https://github.com/compiler-explorer/compiler-explorer/issues/4893

Initial support for GCC cobol

---

etc/config/javascript.amazon.properties
etc/config/javascript.defaults.properties
examples/javascript/default.mjs
lib/compilers/_all.ts
lib/compilers/v8.ts
lib/languages.ts
types/languages.interfaces.ts
views/resources/logos/js.svg

For this issue: 
https://github.com/compiler-explorer/compiler-explorer/issues/264

Add d8 for disassembling javascript

---

docs/AddingACompiler.md
lib/base-compiler.ts
lib/compiler-finder.ts
lib/compilers/clang.ts
lib/compilers/java.ts
lib/compilers/pascal-win.ts
lib/compilers/ptxas.ts
lib/compilers/turboc.ts
lib/compilers/z88dk.ts
lib/demangler/base.ts
lib/demangler/nvhpc.ts
lib/demangler/pascal.ts
lib/demangler/win32.ts
lib/objdumper/base.ts
types/compiler.interfaces.ts

Some toolchains require passing non-standard, mandatory arguments to the CLI tools in order to execute them (configuring licenses, selecting CPU targets, etc.). This PR allows configuring extra command-line arguments for the demangler, object dumper and the execution wrapper. The version flag argument has been refactored into an array, so that more than one argument can be passed, if necessary.
The changes are fully backwards compatible.

Support configuring extra arguments for the demangler, objdumper and execution wrapper

---

etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties

Updated OSACA to version 0.5.0 with more supported uarchs and functionalities.
Please see also the corresponding [PR #979 in compiler-explorer/infra](https://github.com/compiler-explorer/infra/pull/979).

updated OSACA version to 0.5.0

---

lib/compiler-finder.ts
types/compiler.interfaces.ts

Closes #4921
```
> a = ("")?.split("|")
[ '' ]
> a = (undefined)?.split("|")
undefined
> a = ("a|b")?.split("|")
[ 'a', 'b' ]
```

Fix unset versionFlags

---

lib/compiler-finder.ts
test/properties-test.ts

Also means `blah=` will also be `[]` and not `['']`

Ensure missing split args are treated as `[]` and not `['']`

---

.github/workflows/browserslist.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-win.yml
.github/workflows/label.yml
.github/workflows/test-and-deploy.yml
.github/workflows/test-frontend.yml
.github/workflows/test-win.yml
CONTRIBUTORS.md

- Update the actions in the GitHub Actions workflows to their latest versions.
- Run the workflows on the latest versions of the platforms where appropriate.
- Set the `check-latest` field of the `actions/setup-node` action to `true` to use the latest release of the specified Node.js version instead of using the cached one when there's a new release available.
- Explicitly specify the action versions instead of using the `latest` tag.

tools: update GitHub Actions workflows

---

package.json

This command no longer works and the PR is fixing that.
```
npm run debugger
```

Modify debugger command so that node inspector works with ts-node-esm

---

lib/compilers/golang.ts

Fixes #4566
Aside from the group thing, goenv vars also didn't get put into .env

fix golang env vars

---

lib/compilers/solidity.ts

fixes https://github.com/compiler-explorer/compiler-explorer/issues/4938

solidity dont fail on missing generatedSources

---

lib/base-compiler.ts
lib/compilers/clang.ts
static/panes/compiler.ts
types/compilation/compilation.interfaces.ts
types/tool.interfaces.ts

When you do `-ftime-trace` with clang, a file is generated called `output.json` or however you named your executable/objectfile dot json (I think).
Checks if it's actually the expected json and then offers it to the user as a download.
If you drag the downloaded json to https://www.speedscope.app/ - you can see the things.
Would be an option to fix https://github.com/compiler-explorer/compiler-explorer/issues/1186

Offer timetrace json to view somewhere

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties
etc/config/objc.amazon.properties

The compiler was incorrectly built using gcc's master branch instead of
12.2.0 release tarball.
A correct 12.2.0 is now avail as 12.2.0-1. The previous one is kept, but
hidden to preserve possible existing shared link.
fixes #4994

Fix sparc-leon gcc 12.2.0

---

static/panes/compiler.ts

Noticed that on startup things got called that shouldn't have been called.
Then I noticed someone already commented on this:
```
// Note that the .d.ts file lies in more than 1 way!
// createDragSource returns the newly created DragSource
// the second parameter can be a function that returns the config!
```
We invoked most of these functions instead of just passing it (probably because of the type error you get)

Fix drag source component state creation in compiler pane

---

etc/scripts/util/propscheck.py
etc/scripts/util/propschecktest.py

Catch invalid lines (i.e. not a comment and not a prop).
Also refine the PROP_RE so that the 'key' can't have a space (this could
be made more correct by allowing space around '=', but we don't have
any, so....)

propcheck: catch one more small error

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties

GCC 12.3.0 has been released:
https://inbox.sourceware.org/gcc/nycvar.YFH.7.77.849.2305081249040.4723@jbgna.fhfr.qr/T/#u
fixes #5030

Add native GCC 12.3.0

---

static/modes/asm-mode.ts

Solving the issue #4876 @jeremy-rifkin

Assembly syntax highlight of comments after code

---

etc/config/ispc.amazon.properties

Adding ISPC v1.20.0.
Corresponding infra commit PR, which needs to be merged before this PR: https://github.com/compiler-explorer/infra/pull/1011 (so ISPC v1.20.0 is available in the infra).

Add ISPC v1.20.0

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Restores the reverted #4568, as the latest version is built on Ubuntu 20.04.
Depends on compiler-explorer/infra#1012 to pull in the latest version.

Add FRC 2023 Compilers

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties

GCC 11.4.0 has been released:
https://inbox.sourceware.org/gcc/20230529101203.u1gOJtp3gjkZM4Kahj3TgGmIRlZDagFSKcgleNN33_U@z/T/#t
fixes #5089

Add native GCC 11.4.0

---

static/panes/editor.ts

In case anyone asks why "Paste" is missing from the context menu in the future:
Paste is present in chrome and other browsers that support the clipboard api, just not firefox. This should change upstream some day. https://github.com/microsoft/vscode/blob/1052813be23485fd9c17ac77b517241479c21142/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L27-L30 
Closes #3113

Add something to the context menu in place of paste when not supported

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties

This patch specifies path to GCC toolchain for those ancient Clang versions. Ancient Clang versions are still very useful when revisiting equally ancient bug reports, or figuring out when an ancient C or C++ defect report was implemented.
Note that modern spelling of this option is `--gcc-toolchain=`, which is used for Clang 3.4 onwards, but those ancient versions has it in a slightly different form.

Add -gcc-toolchain option for Clang 3.1, 3.2, and 3.3

---

lib/languages.ts

Currently, asm docs are not enabled on the CPU assembly generated by the CUDA compiler, this PR attempts to fix that.

enable CPU asm docs for CUDA C++

---

lib/compiler-finder.ts
static/widgets/compiler-picker-popup.ts
types/compiler.interfaces.ts

No more of this nonsense, long overdue fix

Fix ordering in the compiler picker popup

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties

Adds 12.3.0 for 20 cross targets.
Adds 11.4.0 for 4 targets.
Not listing all languages as it depends on the targets, but the goal is
always to enable as much as possible.
fixes #5088
fixes #5087

Add GCC 11.4.0 and 12.3.0 for cross targets

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
lib/instructionsets.ts

Initially wanted to simply add 'vax' in the compiler picker, but ended
up trying to cleanup a bit how ISA property is set.
For gcc compilers, I've tried to rely on the executable name matching
mechanism instead of having the property set all around in .properties
files.

Kind of ISA cleanup

---

lib/base-compiler.ts

Adding a little something to capture info on why #2984 happens

Try to capture more details about a bug

---

static/settings.ts

Closes #2590
This took a lot of printbugging for such a simple fix. At least a 10:1 ratio of console.log to diff lines (not including the renaming in fillColourSchemeSelector).

Fix color scheme being overwritten on load

---

etc/config/c++.amazon.properties

See also: https://github.com/compiler-explorer/infra/pull/1032

Add HPC SDK 23.3 and 23.5 to c++.amazon.properties

---

lib/base-compiler.ts

Could not be found when using cmake, because that uses a different cwd
Issue found here: https://github.com/compiler-explorer/compiler-explorer/discussions/2763#discussioncomment-6281688 by @DESX
Obviously doesn't work in situations where someone setup a local CE with a working conan link but not using nsjail... Should save and check whether nsjail is used, and if not used then the temporary directory should be used (will required some passing of extra arguments) - nor Windows. But will make different issue for that.

hotfix libraries

---

lib/base-compiler.ts
lib/compilers/clang.ts
test/base-compiler-tests.ts

This PR should make cfg generation available for all clang compilers, icc, and any compiler whose instructionSet property is x86, arm, or llvm.

Support control flow graphs for more compilers

---

lib/compilers/ada.ts

GNAT is gcc based, but its --help doesn't show all of gcc's option and
the base compiler doesn't detect its support for -fstack-usage.
Force the support (currently we only GNAT as an Ada compiler).

ada: add stack-usage support for GNAT

---

etc/config/c++.amazon.properties

Following https://github.com/compiler-explorer/infra/issues/1045
Mark the reinstalled compilers as `debugPatched` so we'll send the right flag
Originates from https://github.com/compiler-explorer/compiler-explorer/pull/4416

Mark older clang versions as debugpatched

---

lib/parsers/asm-parser-dotnet.ts

Adapt changes from https://github.com/dotnet/runtime/pull/88033.
- Filter tier name while recognizing method names
- Keeps comments from asm output 
Without this fix, the code navigation is broken in dotnet languages.

AsmParser update for dotnet

---

lib/parsers/asm-parser-dotnet.ts

Remove the unnecessary `/g` in the regex pattern.
Fix the issue where comment filter cannot remove all comment lines from the output.

Fix the comment test regex for dotnet

---

lib/cfg/cfg-parsers/llvm-ir.ts

Fixes some issues noticed in https://github.com/compiler-explorer/compiler-explorer/pull/5155#issuecomment-1617709720 - confusing coloring and hyphens not being part of the label regex
CC @OfekShilon

Quick llvm ir cfg parsing patches

---

lib/compilers/swift.ts

This PR adds support for the LLVM optimisation pipeline view pane for the Swift family of compilers.

Add LLVMOptPipelineView support for Swift compilers

---

etc/config/ada.defaults.properties
etc/config/analysis.defaults.properties
etc/config/c.defaults.properties
etc/config/hlsl.defaults.properties
etc/config/modula2.defaults.properties
etc/config/objc.defaults.properties
etc/config/openclc.defaults.properties
etc/config/toit.defaults.properties
etc/scripts/util/propscheck.py

Applies to local config and fix existing issues.
By defaults, local and defaults are not checked for suspicious path (exe
not starting with /opt/compiler-explorer). This can be forced with the
--check-suspicious-in-local-prop.

propcheck: applies to local config

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

fixes #5223
+ minor cleanup in compiler names.
+ minor reordering caused by the gcc-cross-builder script used to update
the config.

gcc: add cross for 10.5.0 arm/arm64

---

README.md

The file has been converted to a TypeScript module in #4504 and the link to it
in README.md has not been updated then. Fix that.

README: Fix link to tinyurl URL shortener implementation

---

static/history.ts
static/local.ts
static/main.ts
static/presentation.ts
static/settings.ts
static/sharing.ts
static/widgets/compiler-overrides.ts
static/widgets/compiler-picker.ts
static/widgets/libs-widget.ts
static/widgets/load-save.ts
static/widgets/site-templates-widget.ts

In conversation with @mknejp he pointed out that it can be frustating when having a browser loaded up with many tabs of CE links, then reloading the browser (e.g. a reboot, or open/closing the tabs), that upon reload all the tabs will have the same, shared state (corresponding to whichever saved to local storage last).
This change:
- stores state in _both_ session and local storage
- removes from both on UI reset
- loads first from session storage and then falls back to local storage
The net result is:
- tabs reopened with "ctrl-shift T" will regain their prior state, as do any other tabs for which the browser thinks are part of the same session (like on a "reopen tabs" plugins etc)
- newly-opened tabs still have the prior behaviour of using whatever the most recently opened tab had as …

Use session _then_ local storage for saved state

---

etc/config/c++.amazon.properties

To make it consistent with newer Clang releases, all Clang assertion builds, and user expectations.
The problem
========
Release Clang builds 3.1 through 4.0.1 are using newer GCC 6.3.0 toolchain by default. Major GCC 6.1 release happened 2.5 years after Clang 3.1 release, which makes Clang 3.1 on CE non-period-correct experience. We at LLVM were bitten by that while trying to triage old Clang bugs, so I claim that current experience is off from user expectations.
Starting with release builds of Clang 5, CE defaults to latest GCC release for toolchain, providing period-correct experience. That makes old Clang builds inconsistent with your current policy regarding newer release Clang builds.
Recently introduced Clang builds with assertions enabled use period-correct GCC toolchains in all …

Use period-correct GCC toolchains for old Clang releases (3.1-4.0)

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/modula2.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties

Following 13.2.0 release: https://inbox.sourceware.org/gcc/nycvar.YFH.7.77.849.2307270924461.12935@jbgna.fhfr.qr/T/#u
refs https://github.com/compiler-explorer/compiler-explorer/issues/5283

Add GCC 13.2.0 native

---

static/settings.ts

Fixes #5007
I tried to investigate a bit further into why the keys aren't sorted when returned from server, but concluded that it probably depends on what order the config files were loaded.
It's probably not worth changing anything on the server, and we already do this sorting for the language dropdown https://github.com/compiler-explorer/compiler-explorer/blob/4260313e13aa3ec057806979dfac3fe6fd856b19/static/panes/editor.ts#L555-L556

Sort settings language keys before presenting in ui

---

etc/config/c++.amazon.properties
lib/compilers/_all.ts
lib/compilers/clang.ts
lib/parsers/asm-parser-hexagon.ts
lib/parsers/asm-parser.ts

**Related to:** compiler-explorer/infra#1061
**Goal:-**
To enable back-end support for hexagon clang compiler so that it can be used on the Compiler Explorer's website ([https://godbolt.org/.](https://godbolt.org/)) This will be particularly useful to people working on Hexagon Digital Signal Processor (DSP) developed by Qualcomm Technologies.
**Information about Hexagon DSP:-**
[https://developer.qualcomm.com/software/hexagon-dsp-sdk/dsp-processor](https://developer.qualcomm.com/software/hexagon-dsp-sdk/dsp-processor)

New Compiler: Hexagon-clang

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This change adds support for [libbpf](https://github.com/libbpf/libbpf). libbpf can be used as either a C/C++ library, so please correct if the configuration is incorrect. I tested locally by copying the config to the local config.

C/C++ Add support for libbpf

---

lib/base-compiler.ts

Should fix issues when libraries are selected in other languages than c/c++/circle/rust
Example that gave an error https://godbolt.org/z/hTe6EoGez

Fix execution with library selection in different languages

---

.github/workflows/test-and-deploy.yml

Fix for...
> The following actions uses node12 which is deprecated and will be forced to run on node16: tvdias/github-tagger@v0.0.2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Attempt at using a tag script instead of a (soon to be deprecated) workflow

---

etc/config/c.amazon.properties
lib/instructionsets.ts
types/instructionsets.ts

Some compilers were badly assigned the default ISA (amd64).
Also fix rv32 GCC 10.3.0 that was pointing to the rv64 toolchain.
fix #5328

fix: correct some compiler categories

---

lib/compilers/v.ts

Currently, the `.vmodules` path is not writable. This PR changes the path to a writable (temporary) directory.
Putting `.vmodules` into the compilation folder seems to be not that simple since the env vars are created before a compilation folder is assigned.

Fix V `.vmodules` path

---

etc/config/c++.amazon.properties
etc/config/objc++.amazon.properties

rename the std::execution library to "stdexec (std::execution)"

---

etc/config/c++.amazon.properties

A while ago, I opened https://github.com/compiler-explorer/compiler-explorer/issues/3818. Work started on it, but it stalled. In the meantime, I learned how to add a library to CE, and tested my changes on a local instance.
YOMM2
YOMM2 implements fast, open multi-methods that closely follow the proposal by Peter Pirkelbauer, Yuriy Solodkyy and Bjarne Stroustrup [in this paper](https://www.stroustrup.com/multimethods.pdf)
https://github.com/jll63/yomm2

Add YOMM2 1.4.0

---

lib/compilers/dotnet.ts

instead of ENOENT from the next line (fs.readFile), return the failed compilation result.

dotnet: show the actual error when compilation fails

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

Depends on: https://github.com/compiler-explorer/infra/pull/1080
oneapi 2023.2.1 release. It is the same compiler as 2023.2.0.
Resolves #5408 
The TBB path was wrong. TBB is used by opencl for CPU, and SYCL execution for CE target the CPU opencl device
Note that I tested the new configuration on my local setup but did not reproduce the original problem so it is possible there are other problems.

oneapi 2023.2.1 release + fix sycl execution

---

lib/compilers/dotnet.ts
lib/parsers/asm-parser-dotnet.ts

It turns out we still need crossgen2 for net6.0.
So bring crossgen2 back for net6.0 only.
Also fix some bugs around `indexOf`.
No image rebuilding is required.

Bring back crossgen2

---

lib/compilers/dotnet.ts

This is an improvement that can improve the disassembly format to make it more friendly to a diff checker.
All versions tested:
net6.0:
net7.0:
trunk:

Improve the disassembly format for dotnet

---

static/panes/editor.ts

Prefer unobtrusive error messaging + fix bug when it's the user's 1st visit of the website when SiteSettings have not been initialized yet.
I don't think the order of SiteSettings creation can be fixed (it's done in a function After the layout config has been loaded), or not easily anyway, but the defaultLanguage set to the hub should be correct and that's all we need here.

Fix for old links where language is not set in the editor

---

docs/API.md

Changed Link "https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.amazon.properties#L43" to a relative link and fixed the display to be less huge.

Fix link to formatter section

---

etc/config/c++.amazon.properties

This is the counterpart to https://github.com/compiler-explorer/infra/pull/1086 adding Qt 6.5.2 to Compiler Explorer.

Add Qt version 6.5.2

---

lib/compilers/hlsl.ts
lib/parsers/asm-parser-spirv.ts

My main motivation for this change is that SPIR-V output currently isn't highlighting source lines (for example, see https://godbolt.org/z/4vYb3PbM7 - there's `OpLine` instructions, but they aren't being parsed).
It looks like there's an existing SPIR-V parser, so I'm just updating the HLSL compiler to detect SPIR-V output and use the parser if so.
There's probably a couple of other ergonomic improvements that could be made - for example, treating `OpSource` and `OpName` as directives for filtering. I might make a followup PR with some of these.

Use the SPIR-V parser for DXC SPIR-V output

---

lib/parsers/asm-parser-spirv.ts

This is following up on #5418 by adding a couple of improvements to the parser.
First, `OpString`, `OpSource`, and `OpName` are added to the directives filter, since they only provide debug information. (And `OpSource` provides the entire source of the input file, which is redundant when viewing the output in Compiler Explorer)
Secondly, label definitions and uses are now parsed.

Improve SPIR-V parser

---

static/widgets/libs-widget.ts

Closes #5439
As covered in linked issue, currently default libraries are added unconditionally to loaded state. Even if state was created by removing the default libraries.
The fix makes following changes in libs-widget:
* `updateAvailableLibraries` will only add default libraries to state if the langugage has changed.
* `loadState` will check if `libs` exists in the loading state and if they do clear currently used libraries.
* `setNewLangId` will check if langauges is changed (or just the compiler) and pass this into `updateAvailableLibraries`.

fix: Do not add default libraries to state if previous state exists

---

app.ts
docs/WindowsSubsystemForLinux.md
lib/compilers/wsl-vc.ts
lib/exec.ts

Attempt to fix #5476. As far as I can tell `process.env.winTmp` is needed just for windows executables and WslVcCompiler. It should be possible to just ignore the exec error and continue. If for some reason the user doesn't have windows paths in their WSL but does want to run windows executables they can pass `-tmpDir`.

Fix WSL for systems that don't have windows paths

---

.github/workflows/browserslist.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-win.yml
.github/workflows/test-and-deploy.yml
.github/workflows/test-frontend.yml
.github/workflows/test-win.yml
CONTRIBUTORS.md

Upgrade checkout action to v4 to make use of Node 20.
Node 16, which v3 is using, reaches end of life on 2023-09-11.

Update checkout action to v4

---

etc/config/c++.amazon.properties
etc/config/objc++.amazon.properties

Similar to #3612, starting with GCC 14, using `<stacktrace>` now requires linking to `libstdc++exp.a`.
I added the autodetect to ObjC++ as well because `stdc++_libbacktrace` is also present in that file.
Ref: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using.html

Add autodetect for staticlib `stdc++exp`

---

examples/jakt/default.jakt
static/modes/jakt-mode.ts

In a precious version of the language, functions were defined with the `function` keyword. They are now defined with `fn`.
Currently, the default example doen't compile.

jakt: Fix signature of default example's main

---

lib/compilers/gnucobol.ts

As this is done with other compilers like C/C++ and doesn't add extra code (like plain `-g` would).
(this supersedes the broken #5503)

GnuCOBOL: always pass -g to the C compiler

---

etc/config/c.amazon.properties

The compiler was installed but missing its config in site's config.
fix #5523

fix(config): Add gcc 7.5 to C config

---

etc/config/assembly.amazon.properties
etc/config/pascal.amazon.properties

Closes #5506 
See PR in infra: [Update NASM version to 2.16.01](https://github.com/compiler-explorer/infra/pull/1101)
Decided to have a go at adding latest NASM release. Let me know if there is anything I missed.

Add NASM 2.16.01

---

CONTRIBUTORS.md

Can I add my name to `CONTRIBUTORS.md`?
I have contributed to the stack usage viewer, CUDA PTX/SASS documentations, and a few other issues.
https://github.com/compiler-explorer/compiler-explorer/pulls?q=is%3Apr+author%3Aguoci

add name to `CONTRIBUTORS.md`

---

.github/labeler.yml
CONTRIBUTING.md
CONTRIBUTORS.md
docs/AddingACompiler.md
docs/AddingALanguage.md
docs/AddingAssemblyDocumentation.md
docs/AddingCustomCompilersOverview.md
docs/SystemdSocketActivation.md
docs/WindowsSubsystemForLinux.md
docs/internal/FrontendTesting.md

While reading the (excellent) documentation here, I noticed a few stale references to `.js` files that are now implemented in TypeScript.
* Update `*.js` to `*.ts` in Markdown documentation.
* Update `app.js` to `out/dist/app.js` in `docs/SystemdSocketActivation.md`.
_I managed to follow these instructions and locally run Compiler Explorer through socket activation after that change._
* Update `*.js` to `*.ts` in the GitHub labeller config `.github/labeler.yml`.
_Also correct some misnamed files here. I have checked the new version with `ls $(grep -E "^  - " .github/labeler.yml | sed "s/  - //g")`. If I were more familiar here, I would have liked to add a similar check to the automated tests._
- Sheepishly add myself to the contributors list, despite this being a tiny find-and-replace …

Update `.js` to `.ts` in documentation

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add an arm-unknown-eabi GCC 13.2 as asked by GBA community.
fix #5545

add arm-unknown-eabi GCC 13.2

---

etc/config/rust.defaults.properties

`rustc` by default only gives a short version output like this
```console
$ rustc --version
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
```
There is, however, a more verbose version info that also includes the LLVM version used:
```console
$ rustc --version --verbose
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
binary: rustc
commit-hash: 42b1224e9eb37177f608d3f6a6f2be2ee13902e4
commit-date: 2023-10-15
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```
This is useful information, so it should be accessible.
---
I’d normally have used `--version --verbose`, but it seems that the `versionFlag` property is passed as one single argument to `rustc` and not split on spaces, so I used the short form `-vV` instead.

Use verbose version flag to get `rustc` version

---

docs/AddingALanguage.md

This needs to import `base-compiler.js` not `base-compiler`. All the existing files import `.js`.

Fix compilers language file template in "Adding a Language" doc

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/post-create.sh
CONTRIBUTING.md
CONTRIBUTORS.md

For `Hacktoberfest`, I have been adding `GitHub Codespaces` / `VS Code Remote Containers` configuration for OSS projects to make it easier for contributors to the project to get up and running with the correct developer setup. Including the appropriate configuration for a project allows contributors to work entirely within a web browser via `GH Codespaces`, or inside of fully, and correctly configured containers on their own computer with `VS Code Remote Containers` (both of these use the same configuration, as `GH Codespaces` leverages the `Remote Containers` features under the hood).
For the `compiler-explorer` project, this configuration includes the following:
- Preinstalled `Node 20`
- Preinstalled `ESLint`,  `Prettier`, and `EditorConfig` extensions
- Preinstalled `cypress` …

feat(devcontainers): add the ability to use GitHub Codespaces and VS Code remote containers

---

static/modes/cppfront-mode.ts

This is an update to #5061.
The test cases: <https://highlight-cpp2.godbolt.org/z/o685vYdv9>.
<details><summary>Preview</summary>
</details>

feat: update grammar of Cpp2

---

etc/config/assembly.amazon.properties

Add the 4 versions of RISC-V binutils (2.31.1, 2.35.1, 2.37.0, 2.38.0) bundled with gcc versions used by compiler explorer as assembly targets.

Add support for RISC-V GNU as

---

.devcontainer/post-create.sh

This is a quick follow up to https://github.com/compiler-explorer/compiler-explorer/pull/5631 to add a missing environment check that would prevent the `devcontainer` _post-create.sh_ from running when using `GitHub Codespaces`. Sorry I missed this in the first PR, but now with this the experience in Codespaces is the same as locally in VS Code :+1:

fix(devcontainer): ensure post-create runs in GitHub Codespaces

---

.github/labeler.yml
etc/config/tablegen.amazon.properties
etc/config/tablegen.defaults.properties
examples/tablegen/default.td
lib/compilers/_all.ts
lib/compilers/tablegen.ts
lib/languages.ts
static/modes/_all.ts
static/modes/tablegen-mode.ts
types/languages.interfaces.ts

LLVM TableGen is used to generate complex output files in the llvm project. A generic description of classes and definitions produces "records" that can then be walked by a TableGen backend to produce things like C++ code, configuration files, etc.
The biggest examples are LLVM's assembler and disassembler where all the targets' instructions are defined in TableGen.
https://llvm.org/docs/TableGen/ProgRef.html
An example:
```
class Register<int _size, string _alias=""> {
int size = _size;
string alias = _alias;
}
def X0: Register<8> {}
def X29: Register<8, "frame pointer"> {}
```
```
------------- Classes -----------------
class Register<int Register:_size = ?, string Register:_alias = ""> {
int size = Register:_size;
string alias = Register:_alias;
}
------------- Defs ----------------- …
```

Add the LLVM TableGen language

---

lib/cfg/instruction-sets/arm.ts

Turns out `ArmInstructionSetInfo.unconditionalJumps` and `ArmInstructionSetInfo.conditionalJumps` are not disjoint, and the order in which they are tested matters. Specifically an opcode like `b.lt` provides a match for `ArmInstructionSetInfo.unconditionalJumps` in the single char `b` and so erroneously returned `InstructionType.jmp`.
One can imagine a better solution in modifying the regexes to make them properly disjoint, but AFAICT this is good enough, at least to un-break the ARM CFG.

Another fix on the way to resolving #5617

---

lib/demangler/base.ts
lib/llvm-ir.ts

Fixes #5655
The llvm-ir demangling stage doesn't check supportsDemangle, and we can't really check correctly here. So just slapped on a canDemangle() function that checks if the exe is set.

Dont attempt to demangle (llvm-ir) if we cant

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

Fixes #5641
The "all architectural features" compiler is trunk, plus a whole bunch of `-march` flags to enable the kitchen sink for AArch64. Which is useful for some, but as pointed out in the issue, not representative of what the average clang on the average system will produce. So plain trunk is a better first entry for this category.
To fix this, I've changed the semver value so that we will have this order:
```
(trunk)
(all architectural features, trunk)
17.0.1
<more versions...>
```
`(trunk)` is not treated as a valid semver so it's sorted by the string value. So the shorter `(trunk)` was shown before the longer `(trunk, all...`.
This is why the other special compiler versions sort as they do, because they are `(` then something < `t` (and I didn't find any special workarounds …

Sort Armv8 all architectural features clang below trunk version

---

lib/base-compiler.ts
lib/llvm-opt-transformer.ts
test/llvm-opt-transformer-test.ts

Previously an error in e.g. YAML parsing would take down the whole process.
Part of #5686 but doesn't fix the underlying issue.

Handle errors in the LLVM transform

---

etc/config/c++.amazon.properties

The existing seastar version 1808 is more than five years old and lots of exciting changes have occurred since then. This patch adds seastar 2211 from last last year as well as trunk.
The 2211 version of seastar requires PR compiler-explorer/infra#1134 to be accepted first to add it on the infra side.
`make check` passes.

Add seastar trunk and 2211 versions to CE

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This change fixes the include paths for libbpf.
Tested on a local install. I think in the original PR I had libbpf headers on the system and were being picked up.
The same code fails in the current version:
```
// Type your code here, or load an example.
#include <lib/libbpf.h>
int square(int num) {
return libbpf_major_version();
}
```
Error:
```
<source>:2:10: fatal error: 'lib/libbpf.h' file not found
#include <lib/libbpf.h>
^~~~~~~~~~~~~~
1 error generated.
ASM generation compiler returned: 1
<source>:2:10: fatal error: 'lib/libbpf.h' file not found
#include <lib/libbpf.h>
^~~~~~~~~~~~~~
1 error generated.
Execution build compiler returned: 1
```

Fix libbpf includes

---

etc/config/tablegen.amazon.properties
lib/compilers/tablegen.ts

Since trunk will be a moving target, I've left the default compiler as 17.01.
The standard include path will allow for examples that include files like `include "llvm/TableGen/SearchableTable.td"`, without extra options. This is useful if you want to create a minimal example of the records that an existing backend expects to see.

LLVM TableGen: Add trunk compiler and default include path

---

etc/config/c++.amazon.properties

LLVM-MCA is supported for X86-64 clang compilers, but not for armv8-a clang.  This enables LLVM-MCA support for AArch64 because it is supported for many AArch64 cores.
Fixes request #5649.

Support LLVM-MCA for armv8-a clang

---

lib/compilers/argument-parsers.ts
lib/compilers/tablegen.ts
test/compilers/argument-parsers-tests.js
types/compilation/compiler-overrides.interfaces.ts

"actions" are TableGen's version of the target for a compiler like clang. Where clang might target "Arm" TableGen will target a backend that produces some format like `gen-searchable-tables` which generates C++ code.
Actions are gathered from `--help` and appear in the UI as:
```
<option without -->: <description>
```
For example:
```
gen-searchable-tables: Generate generic binary-searchable table
```
The option name means if you are trying replicate an example from inside llvm, you can match it to the options passed in the build system. The long description is there if you are just browsing the options and want to know what it does. When passed to the compiler I add back the `--` to create the right option.
The default action is `--print-records` which is the same as passing no action, …

LLVM TableGen: Add actions to Overrides menu

---

etc/config/hlsl.defaults.properties
lib/compilers/hlsl.ts

Fairly minor tweaks to hlsl.ts to set the right flags for the opt pipeline view.

Support the opt pipeline view in dxc for HLSL

---

examples/tablegen/searchable_tables.td
lib/compilers/tablegen.ts

A majority of the actions/backends expect to find certain classes and definitions in the source code. There's no canonical reference for this so it's a combination of incomplete docs and the actual uses in llvm-project.
(most of the time I expect people will come from llvm-project to experiment, rather than the other way around)
I've added an example that uses the Searchable Tables backend.

LLVM TableGen: Improve docstring for Actions Override and add example

---

static/styles/explorer.scss

Closes #5707
Boostrap 4 [does not define a zindex for toasts](https://github.com/twbs/bootstrap/blob/e5643aaa89eb67327a5b4abe7db976f0ea276b70/scss/_variables.scss#L692), but Boostrap 5 [does](https://github.com/twbs/bootstrap/blob/a4d2f597029cb36169bb2e20252317198cdd988d/scss/_variables.scss#L1142) - This gets toast in line with 5's priorities, where it has greater index than everything else (There's a comment saying that the order is like that on pourpose)

Fix z-index of toasts in Boostreap 4

---

.github/labeler.yml
etc/config/c++.amazon.properties
etc/config/c++.defaults.properties
etc/config/c.amazon.properties
etc/config/c.defaults.properties
etc/config/objc++.amazon.properties
etc/config/objc++.defaults.properties
etc/config/objc.amazon.properties
etc/config/objc.defaults.properties
lib/tooling/llvm-dwarfdump-tool.ts

https://llvm.org/docs/CommandGuide/llvm-dwarfdump.html
This dumps the DWARF debugging information in a human readable form:
```
<source>: file format ELF64-x86-64
.debug_info contents:
0x00000000: Compile Unit: length = 0x00000063 version = 0x0004 abbr_offset = ... 
0x0000000b: DW_TAG_compile_unit
DW_AT_producer  ("GNU C17 9.4.0 ...)
```
This tool would be useful to have when comparing the debug output of two 
compiler versions or compiler targets. For instance I wanted to find out 
recently how AArch64 and X86 targets represent TLS variables.
The tool runs on the compiled binary, so is post compilation. If the binary
has no debug information the tool does not crash, it just tells you that
there is no information.
To fit the other llvm/clang tools, I've just added an "llvm-dwarfdump …

Add llvm-dwarfdump tool for C/C++ languages

---

lib/compilers/dotnet.ts

Since .NET 8.0, the JIT disasm no longer prints encoded bytes of instructions by default, so we can disable diffable asm by default.

Disable diffable asm for dotnet 8.0+ by default

---

etc/config/racket.amazon.properties

This extends existing Racket support (https://github.com/compiler-explorer/compiler-explorer/pull/4098) by adding a nightly snapshot version.
Depends on https://github.com/compiler-explorer/infra/pull/1173

Add Racket nightly snapshot

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/objc.amazon.properties

The compiler has an explicit reference to a timestamp corresponding to
the NetBSD commit used to build the compiler.
It corresponds to (using https://github.com/NetBSD/src/commit/cd217f2d265f3f9781aa873c348052ee05002ce6):
```
commit cd217f2d265f3f9781aa873c348052ee05002ce6
Author: msaitoh <msaitoh@NetBSD.org>
Date:   Wed Nov 15 03:50:22 2023 +0000
ixgbe: Clear the WTHRESH bit field before writing it.
```
fixes https://github.com/compiler-explorer/compiler-explorer/issues/5708

vax: add built 10.5.0 gcc-vax cross compiler

---

static/widgets/compiler-overrides.ts

And include a tooltip to tell the user why the button is disabled.
One example would be: 
* You favourite TableGen's "action" override.
* You then switch to GCC.
* GCC doesn't support "action" so the button is shown, but is disabled.
* If you go back to TableGen, "action" is now enabled again.

Disable buttons for favorite overrides that are incompatible with the current compiler

---

lib/base-compiler.ts
static/panes/compiler.ts
static/panes/gccdump-view.interfaces.ts
static/panes/gccdump-view.ts
types/compilation/compilation.interfaces.ts
views/templates/panes/gccdump.pug

This PR adds an option to the gcc tree/rtl dump viewer to dump syntax that the gimple frontend can accept

Add gimple front-end syntax option for gcc tree/rtl viewer

---

etc/config/llvm.defaults.properties
static/modes/llvm-ir-mode.ts

The main point of this is to make ctrl+/ work, also added an entry to llvm.defaults.properties

Add LanguageConfiguration for llvm ir

---

etc/config/c++.amazon.properties
etc/config/objc++.amazon.properties

fix typo in the name of the tl::expected library

---

etc/config/cmakescript.amazon.properties
etc/config/compiler-explorer.amazon.properties

CMake 3.28.0 has just been released. This PR replaces the cmake v3.28.0.rc5 to cmake v3.28.0
I believe that we need changes to the images using by the amazon instance (as I can infer).
In addition to it, it sets cmake 3.28.0 as the cmake version to be used when building projects with cmake (IDE mode). This is important since 3.28 brings key features such as the support of non-experimental C++ modules.
Let me now if I need to add anything else.
New cmake release: https://github.com/Kitware/CMake/releases/tag/v3.28.0
Thanks!
X-ref: #5815

Update cmake to 3.28.0

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties
lib/compilers/clang.ts

* directory structure has changed
* no more releases of icc
Depends on deployment of https://github.com/compiler-explorer/infra/pull/1188

oneapi 2024.0.0 release

---

lib/compilers/racket.ts
static/panes/opt-pipeline.ts
types/compiler.interfaces.ts

This allows each compiler to override the default Monaco language used by the opt pipeline view.

Customise opt pipeline language by compiler

---

static/panes/opt-pipeline.ts
static/panes/tree.ts

`CompilerPicker` already set the language dropdown `maxOptions` to 1000 (the default is 50 and currently there are 66 languages). This does the same for `Tree` and similarly for the passes in `OptPipeline`

Fix #5883: the default maxOptions=50 isn't enough

---

lib/base-compiler.ts

Fixing the root issues is too risky at this point. 
If more unwanted side-effects of other switches arise, or other cases of compilation tasks messing with each other's output - maybe reconsider.

Fix #5854: just filter out `-E` when generating IR

---

lib/base-compiler.ts
lib/compilers/racket.ts
lib/exec.ts
test/exec-tests.ts
types/compilation/compilation.interfaces.ts
types/execution/execution.interfaces.ts

Some operations set `exec`'s `maxOutput` to a value larger than the max string length. This change ensures we always cap output to the engine's string limit (currently 512 MB in recent Node versions).
This also tweaks handling when reaching the string limit to ensure adding the "truncated" message itself does not send us beyond the limit.

Limit exec streams to max string length

---

docs/Cerberus.md
etc/config/c.defaults.properties
lib/compilers/_all.ts
lib/compilers/cerberus.ts
lib/instructionsets.ts
types/instructionsets.ts

[Cerberus](https://www.cl.cam.ac.uk/~pes20/cerberus/) offers executable semantics for a substantial fragment of C and
CHERI-C languages. It is implemented via an elaboration into a simpler Core language, which is displayed as the compiler
output in the Compiler Explorer. Evaluation of C programs (execution) is also supported.
The easiest way to install both the Cerberus and Cerberus-CHERI compilers is by using Docker:
`docker pull vzaliva/cerberus-cheri`
Then, for example, you can print the _Core_ elaboration for `test.c` using ISO C semantics:
`docker run -v $HOME/tmp:/mnt -it vzaliva/cerberus-cheri cerberus --pp=core --exec /mnt/test.c`
The file `etc/config/c.defaults.properties` defines a group of two compilers: 'cerberus' for ISO C and 'cerberus-cheri'
for CHERI-C. It assumes that the …

Compilers for exectuable Cerberus CHERI C and ISO C semantics

---

etc/config/rust.amazon.properties

I noticed the default Rust version was outdated, and we didn't have an upgrade of the `objdumper` and `linker` for a while, so I decided to send this in advance of tomorrow's Rust version upgrade.
I don't know what is the policy to update `objdumper` and `linker` though. We have 13.2, 13.1, 12.1, 11.2 and 11.1 around, so I went with the latest. Hopefully that is OK, please let me know if there is some kind of rule about it.

rust: update objdumper, linker and defaultCompiler

---

lib/llvm-ast.ts
test/ast/bug-5889.ast
test/ast/bug-5889.cpp
test/llvm-ast-parser-tests.ts

The code here assumes a top-level AST subtree can be in 3 states:
1. The header line indicates it's system code (e.g. includes `/usr` etc.)
2. The header line indicates it's user code (includes `<source>`)
3. The header contains no such info (typically it includes `<invalid sloc>`)
For the 3rd case this PR looks-ahead inside the current subtree and decides based on its contents.
This is enough to filter out `<vector>` or `<string>` contents, as demonstrated in issue #5889 (added a test). This solution holds also for the case from issue #3849.
@partouf you're the last one who tried to tackle AST-filtering in PR #3860, I'd appreciate if you could approve or comment.

Fix #5889: add block-lookahead logic to processAST

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties

Fixes #5897
Not only causes issues on Windows (that are non-crashing on Linux???)
On the main site it uses the same id for both kotlin and java, this is Ok in the current situation where the kotlin settings are duplicated with java, but if kotlin started to deviate from java this would result in unexpected situations.

fix android-d8 compiler ids

---

etc/config/gimple.amazon.properties

After the initial support of GIMPLE, many cross-gcc were missing.
fixes #5837

gimple: add all missing cross gcc

---

lib/compilers/mrustc.ts

Fix #5941: mark mrustc compilation result with languageId='c'

---

CONTRIBUTORS.md
lib/parsers/llvm-pass-dump-parser.ts

This patch makes a small change in how functions are handled while parsing LLVM opt pipeline output. Specifically, it differentiates between IR function and machine function, and while checking for the close of function, it only checks if the corresponding function is open.
This was needed because in some targets like hexagon, the machine functions could contain `BUNDLE`s as part of the dump and `BUNDLE`s are also represented with opening and closing braces ({}). This was causing assertion because the close brace for a BUNDLE was considered to be a IR function close statement.

Handle ir and machine functions separately in OptPipeline

---

etc/config/c++.amazon.properties

First, thanks for maintaining compiler explorer. It is a wonderful tool.
I have been playing with EDG/reflections on godbolt.org and decided to make a proof of concept library for python bindings that relies on reflections. To make my life easier, I wanted to depend on pybind11, instead of re-learning CPython API.
That brings me to this pull request. I would appreciate having pybind11 available in godbolt.
I am not sure if I am missing anything regarding this. Pybind11 is header-only and the path specified is the one that should be passed to `-isystem`.
Also, the issue template mentions tests, but I am not sure how or even if tests are needed for this change.
I will also understand if you would rather not add more libraries to the compiler explorer image for the sake of its size.

Add pybind11 library

---

lib/options-handler.ts
lib/utils.ts
test/utils-tests.ts

Fix #5951
Fix #5085
Extended the fictitious version number for non-numbers, so that trunk can be listed higher than a `yyyymmdd` as a version (EVE uses this)

Fix semver ordering for libraries

---

static/widgets/compiler-overrides.ts

The previous fix applied only to runtime-tools.

Fix #5847 but seriously this time - addition to PR #5882

---

lib/compilers/rust.ts
static/widgets/compiler-overrides.ts

Seems I missed this one when doing PR #5700. This caused *some* of the grief mentioned in the discussion of issue #5667, but certainly not all of it.

Fix a leftover case of bad file-extension replacement in rust

---

etc/config/c++.amazon.properties

Use gcc-12.3 until gcc-13.3 is released (includes a fix for a bug in
current 13.2).
Should be switch back to gcc-13.3 when it is released.
fixes #5943

icc: workaround bug in libstdc++

---

app.ts
lib/base-compiler.ts
lib/buildenvsetup/cliconan.ts
lib/compilation-env.ts
lib/compilers/hlsl.ts
lib/compilers/ispc.ts
lib/compilers/pony.ts
lib/compilers/spirv.ts
lib/compilers/tinyc.ts
lib/compilers/win32.ts
lib/compilers/zig.ts
lib/handlers/compile.ts
lib/properties.ts
lib/tooling/compiler-dropin-tool.ts
lib/tooling/x86to6502-tool.ts
static/multifile-service.ts
static/panes/compiler.ts
static/panes/editor.ts

Mindless replacements of the form 
`_.filter(options, option =>...`  --> `options.filter(option =>...`.
One not *entirely* mindless replacement at the bottom of compiler-dropin-tool.ts :
```
-        return _.filter(pathFilteredFlags) as string[];
+        return pathFilteredFlags.filter(Boolean) as string[];
```
6 files can now stop importing underscore.

Since ES6 there's no reason to use `underscore`s map and filter

---

etc/config/rust.amazon.properties

Resolves #5983.
This is not 100% accurate as it matches `target-cpu=native` without a preceding `-C`, but there isn’t an obvious case where this would occur in an otherwise valid compiler invocation, so it’s probably good enough?

rust: display unwise option warning for `-C target-cpu=native`

---

lib/base-compiler.ts
lib/compilers/rust.ts

With a small added ts'ification in base-compiler.

Fix #5630: filter out `--emit mir=..` in RustCompiler.buildExecutable

---

etc/config/cuda.amazon.properties

According to the [CUDA 11.3 installation guide](https://docs.nvidia.com/cuda/archive/11.3.0/cuda-installation-guide-linux/index.html) only `gcc 9.*` are supported for it:
This PR pins the gcc used to 9.3.
I have no way to test locally but I think it is safe - these compilations currently don't work anyway, and I can't see any way this would mess up any other compilations.

Fix #5832: cuda 11.3.1 is incompatible with gcc 10+

---

etc/config/python.amazon.properties

Resolves #5761.
I originally also wanted to include PyPy2.7 (which is still supported and would be the only Python2 on Compiler Explorer), but it doesn’t support `-I` which CE uses: https://github.com/compiler-explorer/compiler-explorer/blob/37f68bfa4ac97f1ae0dd710744c76532748e7315/lib/compilers/python.ts#L79
infra PR: https://github.com/compiler-explorer/infra/pull/1212

Add PyPy 3.9 and 3.10

---

etc/config/assembly.amazon.properties

The previous highest version was 2.35.1 and between then and 2.38, support for many new extensions has been added.
This includes the Scalable Vector Extension (SVE), it's own extension SVE2, memcopy acceleration (MOPS) and many more.
I checked the version number by installing locally:
```
/opt/compiler-explorer/arm64/gcc-13.2.0/aarch64-unknown-linux-gnu/bin$ ./aarch64-unknown-linux-gnu-as --version
GNU assembler (GNU Binutils) 2.38
```
So that we can handle the new encodings, the objdumper for this category is also updated to the same version.

Add latest GNU assembler for Arm64

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/zig.amazon.properties

Fixes #5351
I just copied the changes in #4358 and checked that it works locally with
```sh
make debug EXTRA_ARGS='--language zig'
```
although I had to make the following changes to get it to work locally:
```diff
diff --git a/etc/config/zig.defaults.properties b/etc/config/zig.defaults.properties
index 008aa215..f4db084c 100644
--- a/etc/config/zig.defaults.properties
+++ b/etc/config/zig.defaults.properties
@@ -1,4 +1,4 @@
-compilers=/usr/bin/zig
+compilers=/opt/homebrew/bin/zig
supportsBinary=true
compilerType=zig
objdumper=objdump
diff --git a/lib/compilers/zig.ts b/lib/compilers/zig.ts
index b0d55432..8e33767f 100644
--- a/lib/compilers/zig.ts
+++ b/lib/compilers/zig.ts
@@ -44,6 +44,7 @@ export class ZigCompiler extends BaseCompiler {
super(info, env);
this.compiler.supportsIntel = …
```

Add Zig 0.11.0

---

etc/config/c++.amazon.properties

This adds the latest version of Glaze, as well as adding `/include` to the paths per a request from #5901. Thanks!

Fixing paths for Glaze and adding latest version

---

examples/rust/default.rs

Resolves #5939.
Rust issue about this problem: https://github.com/rust-lang/rust/issues/119850
Hopefully this can be reverted again when there is a fix on the Rust side.

Add note to Rust example explaining why functions are missing in the output

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties

This was present in the default properties files for android-java and android-kotlin but missing for the amazon properties files.

Add artArtifactDir to Android config files

---

examples/javascript/default.mjs

Without this additional line, v8 trunk produces no output, and v8 11.3 produces a bunch of assembly with no `imull` instruction.
I don't actually know much about v8 or javascript, but based on [this mailing list post](https://groups.google.com/g/v8-users/c/xlx22gScRNs/m/yE2-boWsBQAJ) and testing on godbolt.org, this works.

Add prepare hint to javascript example

---

etc/scripts/julia_wrapper.jl

This PR slightly improves compilation time with Julia by moving the code to a function, and marking the help text as a constant, which are the very basic [performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/) recommended when writing Julia code.  Note that most of the changes involve indentation, so the diff is easier to read by ignoring whitespace changes.
With this change, on my machine (Intel i7-4870HQ CPU) I get a runtime improvement in the range 10%-40%, depending on the julia version used.  It isn't a huge saving, but I guess shaving off a few hundreds milliseconds isn't too bad :slightly_smiling_face: 
<details><summary>Details of benchmarks</summary>
<p>
`input.jl` file:
```julia
function axpy(a, x, y)
@simd for idx in eachindex(x, y)
@inbounds y[idx] = …
```

[julia_wrapper] Slightly improve performance

---

etc/config/c++.amazon.properties

Resolves #4977.
[GCEM](https://github.com/kthohr/gcem/) is a header-only library for C++11 that provides `constexpr` implementations of various math functions.
Infra PR: https://github.com/compiler-explorer/infra/pull/1215

Add gcem library

---

etc/config/fortran.amazon.properties

The latest builds contain:
```
$ ./bin/flang-
flang-new             flang-to-external-fc
```
The script that was `flang` is now `flang-to-external-fc`.
I've renamed "(old)" to be more specific. I don't think anyone who knew what "old" meant will be confused by "flang-to-external-fc", and anyone who didn't know what it meant can at least Google that name and find out that it's a script.

Update LLVM Flang file names

---

static/event-hub.ts

Pane contents are populated by `<pane>.onCompileResult`, triggered by `eventHub.emit('compileResult'..)` in `compiler.ts`.
The contents' colors are updated by `<pane>.onColours`, triggered mainly by `eventHub.emit('colours'...)`  invoked indirectly by `editor.onCompileResult`.  (colors are an editor property).
The order of invocations is governed by the order of registration and is hard to control, and so a mechanism was devised to cache `onColours` arguments and invoke it only after `onCompileResult`: `mediateDependentCalls`:
https://github.com/compiler-explorer/compiler-explorer/blob/ab937c5d151807eeff8d0735ca999ae36ff10392/static/event-hub.ts#L93-L116
It is coded as a generic mechanism but used only for this color->compileResult dependency in ir-view and ast-view. 
I imagine this …

Fix #5126:  fix event_hub.mediateDependentCalls

---

app.ts
docs/WindowsSubsystemForLinux.md
lib/base-compiler.ts
lib/compilers/ewarm.ts
lib/compilers/ewavr.ts
lib/compilers/win32.ts
lib/compilers/wsl-vc.ts
lib/exec.ts
test/cache-tests.ts
test/packager-tests.ts
test/utils.ts
test/win-path-tests.ts

Instead of having several globals, set via environment variables, explicitly set the "correct" env var if passed `--tmpDir` and then consistently use it in the rest of the program.
See @apmorton's comments in #1707

Unify the way tmp dir is used

---

views/noscript/compiler.pug

The `input` field for compiler arguments in noscript has `autocomplete` set to off, which results in the field being cleared between each compilation on Safari & Samsung Internet. 
Also, autocorrect and auto capitalization are enabled in the source code `textarea`, which makes it incredibly tedious to type anything on mobile. This PR addresses both of these issues.

Minor improvements to noscript for mobile users 

---

lib/compilers/argument-parsers.ts
lib/compilers/flang.ts

flang supports the -emit-llvm option but the difference from clang is that while clang allows `-Xclang -emit-llvm`, flang does not allow `-Xflang -emit-llvm`. Instead we need to use `-emit-llvm` alone.
This is a deliberate choice by the flang driver to make sure the user isn't asking the compiler to do 2 things at once. In this case assemble and emit llvm IR.
The way compiler explorer calls clang, the IR ends up not in the `-o` file path but in a file named after the input file but with the extension `.ll`. For flang we will get the IR in the file specified by `-o`.
To handle this I've copied code from ISPCCompiler which does the same thing. We could dedupe this, but I'm not sure whether it's worth it while we have only 2 compilers doing this.
(clang supports `clang ... -emit-llvm` as …

flang: Enable llvm-ir viewer for flang-new

---

static/colour.ts
static/modes/no-highlight-mode.ts
static/panes/ast-view.ts
static/panes/compiler.ts
static/panes/device-view.ts
static/panes/editor.ts
static/panes/gccdump-view.ts
static/panes/gnatdebug-view.ts
static/panes/gnatdebugtree-view.ts
static/panes/haskellcmm-view.ts
static/panes/haskellcore-view.ts
static/panes/haskellstg-view.ts
static/panes/ir-view.ts
static/panes/opt-pipeline.ts
static/panes/opt-view.ts
static/panes/pane.ts
static/panes/pp-view.ts
static/panes/rusthir-view.ts
static/panes/rustmacroexp-view.ts
static/panes/rustmir-view.ts
static/panes/stack-usage-view.ts
static/panes/tool-input-view.ts
static/panes/tool.ts

…with `monaco.editor.IEditorDecorationsCollection`
Seems that today the official way of colouring monaco editors is having them `createDecorationsCollection`, keep the resulting decorations-collection and call `set` on it with new decorations whenever needed. 
There are many possible design choices on where to put it, I opted to put `editorDecorations` in `MonacoPane`, and have `MonacoPane.createEditor` initialize it only in panes where decorations are actually used. 
Also some signatures changed which had a broad (but non-interesting) impact.

Replace the deprecated `monaco.editor.ICodeEditor.deltaDecorations` 

---

lib/exec.ts
test/exec-tests.ts

Maps env vars just like we map everything else, to catch all cases where "app dir" is an input to jailed processes, the jailed process only sees the "right" path (`/app/something`).
Tested locally and fixes the dot net "read only `/nosym`" thing while keeping the `/nosym` behaviour etc

Fix nsjail environment variables that need mapping to destination paths

---

lib/compilers/golang.ts
lib/exec.ts

- warns
- fixes the case I found

Check for non-string values in exec's env

---

etc/config/fortran.defaults.properties

And enable exectution for flang-new.
This assumes that LLVM flang is installed from `ninja install` rather
than a package manager, since I'm not sure any have it yet. So
it's `/usr/local/bin` instead of `/usr/bin`.
gfortran I've assumed is in `/usr/bin` to match the existing
settings in the file.
I removed the `ldPath` settings that the `amazon` config has because:
* Most of them refer to /opt/compiler-explorer.
* Removing the rest didn't prevent me from linking/running binaries.
flang-new used to require a seperate libpgmath library to produce
exectuables but this requirement has been removed so I've enabled
execution.

Fortran: Add LLVM Flang to default compiler config

---

etc/config/fortran.amazon.properties

Flang used to require that libpgmath be installed
(https://github.com/flang-compiler/flang/blob/master/docs/libpgmath.rst).
This is no longer the case (https://reviews.llvm.org/D140236), so we should be able to build executable binaries without it.

fortran: Enable running binaries with flang-new

---

static/compiler-service.ts

This restores the sorting behavior for the compiler picker to about two years ago before the ts conversion. I'm not sure what the effect of `.localeCompare() === 0` on .sort is, since that's only giving equality information. The `@types` for underscorejs says `_._Chain.sort`'s compare function should return a boolean but I can't actually find the definition of any `sort` function in underscorejs nor are there docs about what its compare function should return, but I think it's really calling `Array.prototype.sort` which expects a negative/0/positive.

Fix issue with compiler picker group sorting

---

etc/config/c.amazon.properties

clang trunk for C was using gcc-9, which caused mismatch between compiler and actual binutils supports:
/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/bin/ld:
warning: /lib/x86_64-linux-gnu/libc.so.6: unsupported
GNU_PROPERTY_TYPE (5) type: 0xc0008002
This is not the case in the C++ config where we correctly use nightly gcc.

fix: clang trunk should use gcc trunk

---

lib/parsers/asm-parser-spirv.ts

Filter `OpMemberName` as directive, to be consistent with `OpName`.

[SPIR-V parser] Filter OpMemberName as directive

---

.github/labeler.yml
.github/workflows/label.yml

This pr fixes the failing labeler action labeling pull requests, which was probably broken by renovate when upgrading the action from v4 to v5.
I wasn't able to test the configuration, but let's hope it works.

[CI] Fix labeler configuration vor labler@v5

---

etc/config/rust.amazon.properties

This PR enables the llvm-dwarfdump tool for Rust (inspired by https://github.com/compiler-explorer/compiler-explorer/pull/5726). The default backend for the Rust compiler is LLVM and being able to inspect the debuginfo it generates would be really useful.

Enable the llvm-dwarfdump tool for Rust.

---

etc/config/d.amazon.properties

Also update llvm-symbolizer to LLVM 17 (I hope the clang 17 package contains llvm-symbolizer like before ;-)

Add LDC 1.36.0 and make it the default

---

lib/compilers/argument-parsers.ts

flang-new doesn't support `-masm=intel` (though it seems likely it eventually will), so this uses `-mllvm ...` to achieve the same thing.
flang-to-external-fc is a wrapper script that will be removed once flang-new becomes flang, so it is not being updated and won't support -masm or -mllvm ever.
(and you'll get the same output by choosing a gfortran compiler, since that's what the script uses for codegen)

flang: Enable the Intel asm syntax option

---

etc/config/compiler-explorer.amazon.properties

Should fix https://github.com/compiler-explorer/compiler-explorer/issues/6074
Tested the regular formatting, Preprocessor and clang-format tool. Don't think this should break anything.

fix clang-format formatter name

---

etc/config/spice.amazon.properties

Previously the compiler has thrown an error like:
```
terminate called after throwing an instance of 'spice::compiler::LinkerError'
what():  [Error|Linker] Linker not found: Please check if you have installed clang and added it to the PATH variable
Program terminated with signal: SIGSEGV
Compiler returned: 139
```
This fix makes clang and lld available to compiler executable.

[Spice] Make clang and lld available to compiler executable

---

lib/base-compiler.ts
lib/compilers/clang.ts
static/panes/compiler.ts
static/panes/executor.ts

Fixes #6120 
Problems were:
* filename of the time trace json is actually different with a build
* the execution pane didn't read the trace artifact
* builds are done separately where you don't know what the "compilationresult" object is yet
The bad:
* the artifact only shows up in the api if its the first time or you recompile, not when you only fetch the cached build and execute the executable, but it's better than nothing for the moment

Clang time trace support in execution pane

---

lib/compilers/spice.ts

This provides the Spice compiler with the `SPICE_STD_DIR` env variable. This is required as soon as an input program tries to use the stdlib.

[Spice] Add std dir to default exec options

---

lib/compilers/argument-parsers.ts

Since https://github.com/llvm/llvm-project/commit/9ca1a1575a337931d0e49859f83a0d5b70916abd, flang supports the use of `-masm` without having to use `-mllvm`. flang converts this into `-mllvm...` so the result is the same.
The check still looks for `-mllvm`, as this is the best way to tell flang and flang-to-external-fc apart. As `-masm` doesn't appear in the --help output of flang.

flang: Use -masm to enable Intel syntax

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties
lib/compilers/d8.ts

This change adds recent D8 versions (8.1.72, 8.2.33, 8.2.42). Properties for D8 have been reformatted to use groups in order to avoid duplication of java/kotlin references.

Update D8 versions (up to 8.2.42)

---

static/panes/executor.ts

Fixes #4801
Similar to https://github.com/compiler-explorer/compiler-explorer/commit/d9030cf41e744f93672afdb40a4eeed8674d4212
The push was done too early when the files hadn't been populated yet

Fix executor pane url inclusion

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

- Updates VAST to appear in the C compilers dropdown.
- Corrects paths to resources so that VAST can locate C standard library.
- Adds clarification to the pop-up, recommending the use of the -vast-emit-mlir option.

Add VAST as a C compiler and fix paths to resources & toolchain.

---

lib/handlers/compile.ts

Fixes https://github.com/compiler-explorer/compiler-explorer/issues/6179
Noscript forwarding was partially fixed with https://github.com/compiler-explorer/compiler-explorer/pull/4524 but it was incomplete.
This fixes the json object and adds some extra filters

Fix json that is forwarded to remote when in noscript

---

lib/base-compiler.ts
lib/compilers/clang.ts
lib/compilers/cppfront.ts
lib/compilers/d8.ts
lib/compilers/dex2oat.ts
lib/compilers/gnucobol.ts
lib/compilers/jakt.ts
lib/compilers/mlir.ts
lib/compilers/mrustc.ts
lib/compilers/opt.ts
lib/compilers/ruby.ts
lib/compilers/v.ts
lib/compilers/vala.ts
lib/compilers/wyrm.ts

The getCompilerResultLanguageId() method can be overridden by compiler
classes to report what mode the monaco editor should be using to display
what the compiler is emitting. The method was not provided with the
"filters" (badly named...) object that contains the user selected options
for "link to binary", "compile to object", etc. Some compilers may need
different monaco settings depending on how they are called.
refs #6079

Change getCompilerResultLanguageId prototype

---

static/panes/ast-view.ts
static/panes/ir-view.ts

'colours' event is emitted with editor-id and not compiler-id, needs to be handled as such too.

Fix mis-coloured IR panes

---

.github/labeler.yml
etc/config/python.amazon.properties
lib/compilers/_all.ts
lib/compilers/pythran.ts

Pythran is a python to c++ transpiler.
Our supports both the C++ and the full link to a share library (a python module).
See https://pypi.org/project/pythran/ for more information.
fixes #6079

pythran: initial support

---

static/sharing.ts

Fixes #2545
The text box containing the link was already read only. So I think the intention was always to set the clipboard button to disabled, but the author used the wrong object by mistake.
I've changed it so that it finds the clipboard button and disables it on error, and enables it on success.
The modal is constructed once and updated if re-opened, so we need to set the state each time in case the result has changed.
I tested this locally by making the code always take the error path.

Disable sharing clipboard button when link generation fails

---

etc/config/erlang.amazon.properties

Hi,
in this PR I port the jitted decimpiled view to the amazon properties, as we already have in the default properties ([here](https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/erlang.defaults.properties))

Add assembly dump to erlang amazon configuration

---

lib/compilers/spice.ts

- Use the `--abort-after-dump` flag not only for IR, but also for assembly
- Add `test` subcommand to forbidden options

[Spice] Also apply abort-after-dump option to assembly output

---

etc/config/spice.amazon.properties

Add version 0.19.4
Infra PR: https://github.com/compiler-explorer/infra/pull/1249

[Spice] Add version 0.19.4

---

lib/languages.ts
shared/common-utils.ts
static/panes/compiler.ts
test/common-utils-tests.ts
types/languages.interfaces.ts

Long numbers are sometimes hard to read in the numeric tooltip. To improve readability, this PR adds language-specific digit separators to the numeric tooltip.
Decimal numbers are grouped into chunks of three digits while hexadecimal numbers are grouped into chunks of length four.
The digit separator is language-specific and chosen so that the number is a valid token in the source language.
[Examples](https://godbolt.org/z/s86cMbjeK):
* for C++, hovering the number `8583909746840200552` shows this tooltip: `8'583'909'746'840'200'552 = 0x7720'2C6F'6C6C'6568 = 6.5188685003648344e+265`
* for Python, hovering the number `-12345678` shows this tooltip: `-123_456_789 = 0xFFFF_FFFF_F8A4_32EB = -2.66427945e+34f`
For languages that don’t have a `digitSeparator` set, the tooltip is not changed.

Add digit separators to long numbers in numeric tooltip

---

lib/sources/builtin.ts

I feel this is the least surprising behaviour most of the time. This will help when packaging and distributing the application.
It may also make sense to base this at rootDir, but examples/ sits outside etc/ at the moment and I didn't want to disturb that too much.
Thanks!

builtin.ts: treat EXAMPLES_PATH as relative to app root.

---

lib/sources/builtin.ts

Reverts compiler-explorer/compiler-explorer#6237.
This PR broke the recommended `make run` workflow. When using `make run`, the dist folder does not contain the needed resources.

Revert "builtin.ts: treat EXAMPLES_PATH as relative to app root."

---

static/panes/compiler.ts
static/panes/device-view.ts
static/utils.ts
test/static/utils-tests.ts

Compilers like to encode short-ish strings into immediate arguments to various assembly instructions. This makes it hard to read the assembly.
To improve readability, show a string representation of a number’s bytes when they’re valid UTF-8.
This now also shows a string representation for *unprintable* ASCII characters, such as `10` being shown as `"\n"` or `1` as `"\u0001"`.
Resolves #6220.
([link](https://godbolt.org/z/7hzn6b8YG))
* 8583909746840200552: `8'583'909'746'840'200'552 = 0x7720'2C6F'6C6C'6568 = 6.5188685003648344e+265 = "hello, w"`
* 1684828783: `1'684'828'783 = 0x646C'726F = 1.74467096e+22f = "orld"`
* -6934491452449512253: `-6'934'491'452'449'512'253 = 0x9FC3'BCC3'B6C3'A4C3 = -1.1500622354593239e-155 = "äöüß"`
* 1633837924: `1'633'837'924 = 0x6162'6364 = 2.61007876e+20f = …

Decode UTF-8 encoded strings in numeric tooltip

---

lib/compilers/julia.ts

I was looking together with @vchuravy into adding the LLVM IR tool to the Julia compiler, and I was having some troubles because the `runCompiler` function overridden in `julia.ts` modifies in-place the input argument `options`, and then when it's called at https://github.com/compiler-explorer/compiler-explorer/blob/5bcc3bf74f2c7fe0f9076930faa3110672ea38f9/lib/base-compiler.ts#L1372 the arguments are `<input file> <output file> compiler.irArg <output file>`, with the duplicate argument `<output file>` coming from https://github.com/compiler-explorer/compiler-explorer/blob/5bcc3bf74f2c7fe0f9076930faa3110672ea38f9/lib/compilers/julia.ts#L124 I hope this makes sense :slightly_smiling_face:

[julia] Do not modify in-place `options` in `runCompiler`

---

etc/config/pascal.amazon.properties
lib/compilers/_all.ts
lib/compilers/argument-parsers.ts
lib/compilers/madpascal.ts
lib/parsers/asm-parser-mads.ts

Fixes #6143
MadPascal is a crosscompiler for 6502 targets
Currently only shows assembly (pretty much unparsed)
For the Assembler, we also need to build https://github.com/tebe6502/Mad-Assembler and use that to assemble executables to use in possible vms - this a task for later
Todo:

Add MadPascal

---

.github/labeler.yml
etc/config/solidity.amazon.properties
etc/config/solidity.defaults.properties
lib/compilers/_all.ts
lib/compilers/argument-parsers.ts
lib/compilers/solidity-eravm.ts
lib/instructionsets.ts

`zksolc` is the Solidity compiler of the zkSync L2 solution for Ethereum.
It introduces the new instruction set created by Matter Labs for the zkSync's zkEVM.
Dependencies:
1. The **zksolc** binary, which can be downloaded from [here](https://github.com/matter-labs/zksolc-bin) and put at `/usr/bin/zksolc` just like `solc`.
2. `solc`, which is called by `zksolc` via `$PATH` as a subprocess, and the `solc` is already expected to be at `/usr/bin/solc` by the Solidity integration.

Integrate zksolc

---

etc/config/hlsl.amazon.properties

DXC has come out with a couple new releases!
This depends on the new tags added in https://github.com/compiler-explorer/infra/pull/1262, which also need to be built.

Add DXC 1.8.2403 releases

---

etc/scripts/julia_wrapper.jl
lib/base-compiler.ts
lib/compilers/julia.ts

Julia is based on LLVM like other toolchains supported by Compiler Explorer, and it can emit LLVM IR, but at the moment we only expose it via the flag `--format=llvm` to the compiler wrapper.
With this PR we add a proper LLVM IR viewer, like the other LLVM-based toolchains.  We add a new option for the wrapper to emit the entire LLVM module, which has the benefit of being parsable by Compiler Explorer, so that we can automatically filter out debug information and metadata annotations.
Preview (from https://github.com/compiler-explorer/compiler-explorer/issues/4597#issuecomment-2018956112):
We removed the custom `<[source code line] [number of output lines] [function name] [method types]>` line in the output of the `code_*` functions, together with the custom ASM parsing, because they …

[julia] Add LLVM IrView

---

static/widgets/libs-widget.ts

Hey friends, it's been a while since last time :)
There are quite a few conditions/cases where the library alert will pop up, without anything meaningful inside of it. This is particularly the case for Rust where you have the 100 crates on stable, but zero support in beta/nightly. I figured informing the user in cases like this would be nice to have.
This PR adds a rather simple alerting mechanism to alert the user of any conditions that might not be as apparent (such as Rust crates only being on stable)
Below is a small gif of how it works. I'm not sure this is the easiest way to convey this information (especially considering the modal popup overshadows the alert) so please share any other ideas. Maybe it's better to have the content fill the modal instead?
Relevant issues: #3766 #6250

Implement alert filters for library dialog

---

docs/API.md

This adds a section on the ASM opcode docs endpoint.

docs/API.md: Document /api/asm/<instructionSet>/<opcode>

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties
lib/compilers/d8.ts
lib/compilers/dex2oat.ts

updates intermediate compiler exe input to refer to the compiler's getInfo().exe so that paths don't need to be hardcoded in properties.

Simplify Android compiler properties

---

lib/compilers/dex2oat.ts

Adds '--copy-dex-files=always', as it is needed in newer versions of dex2oat. This doesn't affect older versions.

Update dex2oat input arguments

---

lib/compilers/dex2oat.ts

Updates dex2oat to specify a valid boot image for accurate compilations. For example, these two methods should now (correctly) compile to the same native code:
```
static int insertAndReturn(int num) {
int[] arr = {num};
return arr[0];
}
static int justReturn(int num) {
return num;
}
```

Support compilation with boot image for Android

---

etc/config/assembly.amazon.properties
etc/config/llvm.amazon.properties
etc/config/llvm_mir.amazon.properties
etc/config/tablegen.amazon.properties

Fixes #6260
This uses the 18.1.0 llvm install that C is already using.
It also updates TableGen's default to 18.1.0 and adds 16 and 17 compilers to MIR where they were missing.

Add llvm 18 compilers for LLVM IR/MIR, assembly and TableGen

---

etc/config/hlsl.amazon.properties

This change adds the new DXC 1.8.2403.2 release. This PR depends on the infra PR below being merged and compilers built:
https://github.com/compiler-explorer/infra/pull/1266

[HLSL] Add DXC 1.8.2403.2 release

---

CONTRIBUTORS.md
etc/config/rust.amazon.properties

Hi! Thanks for the amazing tool that is CE.
I would like to have the rust `phf` crate added on the website because I think it would be nice to have an easy way to see how static maps performs compare to non static ones.
Feel free to reject the PR if you think that it is not relevant 🥲
I also opened a PR on the `infra` repository since the crates data is actually generated from it.
See: https://github.com/compiler-explorer/infra/pull/1280

Add the `phf` crate for Rust

---

lib/compilers/java.ts

Removed UseDynamicNumberOfCompilerThreads command-line argument when running on java <11

---

static/panes/opt-view.ts

No idea how this worked on my machine prior to submitting...
Anyway, fixed now.

Fix inline opt-remarks: toggling a filter off did not remove the remarks from the display.

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties
examples/android-java/default.java
examples/android-kotlin/default.kt
lib/compilers/dex2oat.ts

dex2oat supports profile-guided compilation. In addition to taking dex code as an input, it can take a profile as another input, to guide the compilation. The profile determines which methods need to be compiled, how calls can be inlined, and so on.
Because Compiler Explorer doesn't support multiple input files, the profile is added as a comment block in the Java/Kotlin source code. A post-processor extracts the profile from the comment block into a separate file, in order to input it to dex2oat.

Add profile support for dex2oat.

---

etc/config/cmakescript.amazon.properties

Cmake updates

---

etc/config/rust.amazon.properties

Adding bincode Rust crate support. Serialization/deserialization is perf sensitive, so adding bincode crate support helps evaluate bincode assembly generation for different struct types.
infra repo PR is: https://github.com/compiler-explorer/infra/pull/1287

Add bincode support for Rust

---

etc/config/c++.amazon.properties

These were present for C but not C++.

Add missing clang versions for armv7-a C++

---

lib/llvm-ir.ts
lib/parsers/llvm-pass-dump-parser.ts

Fixes #6416. Additionally escapes a dot in another copy of an `@llvm.dbg` check.
Didn't find any existing tests for IR filtering to update where this filter applies, but did make sure locally that it does start hiding the instructions for clang-17 and clang-18.

Hanfle filtering `tail call void @llvm.dbg.*` in LLVM IR

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/objc.amazon.properties

Add 3.4.6, 4.0.4 and 6.5.0.
fixes #6323

gcc: add old renovated versions

---

lib/base-compiler.ts

This fixes #6449 - I carelessly ignored the case of empty IR output.
Repro link for verification: https://godbolt.org/z/4d46dahqq

Fix exception in case of empty IR

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cpp_for_opencl.amazon.properties
etc/config/llvm.amazon.properties
etc/config/objc++.amazon.properties
etc/config/openclc.amazon.properties
lib/compilers/clang.ts

(1) Restore explicit specification of `group.*.demangler=/opt/compiler-explorer/clang-trunk/bin/llvm-cxxfilt` for all clang compiler groups, except bpf and windows.
(2) Make the ClangCompiler` constructor adjust the path of `llvm-cxxfilt`, so that a compiler-local version is preferred, if one exists.
(3) Pass-by update: bump the version of llvmDisassembler from clang-14 to clang-18.1.
Hopefully this addresses all demangling issues known so far.

Suggestion to update llvm-cxxfilt logic

---

static/panes/opt-view.ts

Fix #6460: trying to access an `undefined` this.optRemarks.
The order of opt-view.ts invocations at opt-view pane open is:
1. `constructor`,
2. `registerButtons`,
3. `onCompileResult`
If someone manages to click the filter checkboxes after (2) but before (3), then `showOptRemarks` would be triggered before `this.optRemakrs` is initialized and this exception would ensue. The solution here is to initialize `this.optRemakrs` at the constructor.
Couldn't reproduce, the solution is entirely hypothetical. If it would happen again we'll revisit this.

Init optRemarks in ctor

---

static/hub.ts
static/main.ts

Fix #6464, following the discord discussion.
2 protections are added here:
(1) Make the first code editor non-closable, to avoid an empty layout,
(2) If a loaded config has empty layout - fallback to the default config.

Fix #6464: defend against empty saved layout

---

.github/labeler.yml
etc/config/fortran.amazon.properties
lib/compilers/_all.ts
lib/compilers/flang-fc1.ts

"This pull request introduces the Flang frontend driver as a new compiler, as discussed in issue #6400. with minimal support. 
With this change, users can now specify LLVM Flang frontend-related options such as _**-emit-hlfir, -fdebug-dump-parse-tree**_, etc.,(no explicit **_-fc1_** needed) by selecting the compiler (**flang-trunk-fc1**)."

Add Flang frontend driver to Fortran Compilers

---

lib/base-compiler.ts
lib/compilers/assembly.ts
lib/compilers/beebasm.ts
lib/compilers/golang.ts
lib/compilers/ispc.ts
lib/compilers/movfuscator.ts
lib/compilers/nim.ts
lib/compilers/racket.ts
lib/compilers/rust.ts
lib/compilers/snowball.ts
lib/compilers/solidity-eravm.ts
lib/compilers/solidity.ts
lib/compilers/swift.ts
lib/compilers/zig.ts

Following #6439: mark the go compiler `gc` as not supporting cfg.
Also, don't pass argument to `isCfgCompiler` - the base-compiler implementation uses `this.compiler.instructionSet` anyway.

Mark the go compiler `gc` as not supporting cfg

---

etc/config/crystal.amazon.properties

Add Crystal 1.12.1

---

static/panes/opt-view.ts
static/panes/stack-usage-view.ts

... they can be true for compilations that failed and really have no `stackUsageOutput`/`optOutput`
This fixes #6468 alright, but I'm not sure about the followup questions:
(1) Is there really a point in keeping the boolean members `hasStackUsageOutput`/`hasOptOutput`?
(2) What about other `has*` members - `hasPpOutput`, `hasAstOutput`, `hasIrOutput` etc?    I didn't give them similar treatment as I couldn't reproduce similar problems. 
I tend to stick with this quick-n-dirty-ish solution but would appreciate opinions.

Don't trust `hasStackUsageOutput`/`hasOptOutput`

---

etc/config/c++.amazon.properties

The upstream has changed from `-fclangir-enable` to `-fclangir`. Update here as well.

Update clangir compiler options

---

CONTRIBUTORS.md
etc/config/rust.amazon.properties

This PR fixes #6212 and infra PR is here: https://github.com/compiler-explorer/infra/pull/1299
It adds the nix crate that will be useful when users need to access more user friendly *nix APIs.
Thanks!

Add the "nix" Rust crate

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

[widberg-defs](https://github.com/widberg/widberg-defs) is a simple single header library with some utilities for recompiling decompiled code. I often find myself prepending this to CE sources when using the [llvm-project-widberg-extensions](https://github.com/widberg/llvm-project-widberg-extensions) compiler. It would be nice to be able to use it like a normal library on CE.
Infra PR: https://github.com/compiler-explorer/infra/pull/1303

Add widberg-defs C/C++ library

---

etc/config/c++.amazon.properties

ICC was using gcc 12.3 headers as a workaround for a know bug. This bug has been fixed in gcc 13.3, so switching ICC back to using GCC 13.
fixes #6004

Switch back some ICC to use recent gcc 13.3 headers

---

lib/parsers/asm-parser.ts
test/filters-cases/bug-660.asm.directives.comments.json
test/filters-cases/bug-660.asm.directives.json
test/filters-cases/bug-660.asm.directives.labels.comments.json
test/filters-cases/bug-660.asm.directives.labels.comments.library.dontMaskFilenames.json
test/filters-cases/bug-660.asm.directives.labels.comments.library.json
test/filters-cases/bug-660.asm.directives.labels.json
test/filters-cases/bug-660.asm.directives.library.json
test/filters-cases/mips5-square.asm.directives.comments.json
test/filters-cases/mips5-square.asm.directives.json
test/filters-cases/mips5-square.asm.directives.labels.comments.json
test/filters-cases/mips5-square.asm.directives.labels.comments.library.dontMaskFilenames.json
test/filters-cases/mips5-square.asm.directives.labels.comments.library.json
test/filters-cases/mips5-square.asm.directives.labels.json
test/filters-cases/mips5-square.asm.directives.library.json

For obscure reasons (see [comment here](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/config/mips/mips.h;h=9d965966f2fa9b16f8320b628a6885666aa6cf8a;hb=refs/heads/trunk#l2948)) GCC MIPS inserts DWARF debug labels with the format `$LXX = .` instead of `$LXX:`. So this updates the regexes in that scenario using the existing MIPS detection, to explicitly consider that specific pattern as a directive instead of an assignment. That way they are filtered correctly in the assembly output with the "Directives" option like on all other architectures.
This shouldn't need any additional tests, just updating the existing ones to say those labels should now be filtered. Currently it causes test failures though, I couldn't find any testing docs or if there is an automatic way to regenerate the test …

Detect local label assignments as directives on MIPS (#6392)

---

etc/config/hlsl.amazon.properties

This adds the latest DXC version 1.8.2405, the May 2024 release of DXC

[HLSL] Add DXC 1.8.2405 release

---

static/widgets/timing-info-widget.ts

This is the crash:  https://compiler-explorer.sentry.io/issues/5427865018/
Looking at [where these values are populated](https://github.com/compiler-explorer/compiler-explorer/blob/2307e16fa485bf5d92dd28e0d88bfde9cf6d9b99/lib/base-compiler.ts#L2711-L2715) my conjecture is that `BigInt.toString` failed and returned undefined / null, but I see no documented conditions that can trigger this (maybe [just for ridiculous values](https://stackoverflow.com/a/75593358/89706)).

Some extra safety, following sentry-caught exceptions

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties
lib/compilers/d8.ts
lib/compilers/dex2oat.ts

Updates the d8 and dex2oat compiler implementations so that android.jar is included in the classpath for javac/kotlinc.

Support Android API stubs

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties

D8: 8.2.47, 8.3.36, 8.3.37
dex2oat: 34.13, 34.14, 34.15, 34.16

Update Android compilers (D8, dex2oat)

---

lib/demangler/llvm.ts
test/demangler-tests.ts

This fixes one of the two problems reported in #6558.

Also demangle quoted identifiers in LLVM IR

---

etc/scripts/find-node

`which` isn't in POSIX and some Linux distributions (e.g. Debian, Gentoo) are trying to remove it from their base installs. See https://lwn.net/Articles/874049/.

etc: find-node: use `command -v`, not `which`

---

static/main.ts
static/sentry.ts

I couldn't test this locally.  Is there a way to test in staging?

Add full-url capture for sentry messages triggered in front end

---

etc/config/wasm.amazon.properties

👋 Hey,
The Webassembly language was recently added (in #6429). I tested it today on the live enviornment, and it appears to not be working (example: https://godbolt.org/z/YP5KdscEM).
I don't really know how to debug this, there is no other output other than `objdump returned 255` which doesn't tell me a whole lot. (If someone can help me investigate this it would be appreciated)
Looking at the configs for the other languages, they always specify a objdump binary in the `/opt` path, so maybe `llvm-objdump` is not available in the system?
This PR attempts to fix it by changing to a fixed version of `llvm-objdump` in the `/opt` install path. (I've also double checked, and that version does work locally)

Update llvm-objdump for Webassembly

---

static/panes/ir-view.interfaces.ts
static/panes/ir-view.ts
views/templates/panes/ir.pug

Mostly for rust - IR line length there can be legendary.

Add 'wrap lines' toggle to ir-view

---

.idea/jsLibraryMappings.xml
static/panes/opt-pipeline.ts
views/templates/panes/opt-pipeline.pug

Somewhat of a rough sketch in the matching department, I'd like something more like TomSelect does with the fuzzy matching, but need to look into getting that behaviour without using the select iself
Closes #6569 
(Else, we could always just move this to be a multi selector no?)

Add a way to filter opt-pipeline passes

---

.github/labeler.yml
etc/config/solidity.amazon.properties
etc/config/solidity.defaults.properties
lib/compilers/_all.ts
lib/compilers/solidity-zksync.ts

Adds two latest releases of **ZK**sync solidity compiler (`zksolc`) `v1.4.1` and `v1.5.0`.
Related infra change: https://github.com/compiler-explorer/infra/pull/1324

Add ZKsync solidity compiler 1.4.1 and 1.5.0

---

etc/config/c++.amazon.properties
etc/config/c++.amazonwin.properties
lib/base-compiler.ts
lib/compilers/win32.ts

* Adds number of VS2019 compilers, compatible with list from godbolt.ms
* Missing VS2022 (and theres a few for 2017)
* Missing tools
* Missing libraries
* Missing C

add some msvc compilers

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties

This config was removed unexpectedly. Adding it back to make dotnet execution work.
Fixes #6620

Add missing ExecutionEnvironmentClass for dotnet

---

static/modes/nc-mode.ts

This PR adds new C23 keywords from https://en.cppreference.com/w/c/keyword. I have some FUD about always highlighting things like `bool`, since what most people think of as C is not C23. I think ideally we'd be able to only highlight C23 keywords when `-std=c23` is being used, but that of course makes things a good deal more complex. But also, it probably makes sense to just go ahead and highlight these.
Possibly related to #6568.

Add C23 keywords to our C highlighting mode

---

docs/Privacy.md
etc/config/c++.amazonwin.properties
etc/config/c.amazonwin.properties
etc/scripts/parsed-pug/parsed_pug_file.js
lib/base-compiler.ts
lib/compiler-finder.ts
static/generated/privacy.pug
types/compiler.interfaces.ts

- Ensure MSVC license terms are clearly shown to the user.
- Simplify config of vc and vcpp slightly by extracting common stuff into a group.
- Remove reference to MS privacy policy

Comply with some MS terms

---

lib/compilers/rustc-cg-gcc.ts

Adjust a bit how we call the compiler:
- panics are handled, no need to force abort (and -Cpanic=abord doesn't work without other tuning)
- adjust some paths
refs https://github.com/compiler-explorer/compiler-explorer/issues/5342

Adjust rustc_cg_gcc compiler invocation

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Upgrade gcc-toolchain version used for clang 7-9

---

etc/config/c++.amazon.properties

Add Beman.Optional26 library trunk version - #6651. 
Infra linked PR [#1347](https://github.com/compiler-explorer/infra/pull/1347).
Notes: 
* Tested these changes on my local VM, Ubuntu 24.04, arm64:  https://github.com/compiler-explorer/infra/assets/8947836/075c29cf-1417-4110-beb3-caa46c21054d
* It's not clear for me if the infrastructure will automatically re-install `main` version of this library over night (`nightly`). If not, but it can be done, please help me to adjust my diff.
* Currently we don't have an official release version. We would like to be able to play with latest `main` from Beman.Optional26 this week in WG21 Saint Louis meeting. Please help us to deploy this "alpha" version.

Add Beman.Optional26 library trunk version

---

etc/config/c++.amazonwin.properties

Microsoft's latest versions were more recent, however, if we can at least provide the latest we have links will be a little less broken.

Setup temporary msvc latest aliases for the latest versions we have

---

static/panes/editor.ts

Closes https://github.com/compiler-explorer/compiler-explorer/issues/6525
I found that the pane does not use the normal getCurrentState/update state pattern because it does not conform to its own EditorState interface, which I _think_ is due to legacy links being different than expressed there?
Either way, this PR modifies the min code needed to get it working, and maybe we can homeogenize the rest later
Note that even moving the state to a `getCurrentState()` fails because the history panes then don't know how to handle the editor and you get some "missing `componentState`" errors

Fix paneRenaming not affecting source editor

---

static/styles/themes/default-theme.scss

Setting font-size in css does not respond to resizing:
I suspect (1) this is a monaco limitation (based on [this](https://github.com/microsoft/monaco-editor/discussions/3717#discussioncomment-5190536)), and (2) they're not keen on improving their font control (based on [this](https://github.com/microsoft/monaco-editor/issues/2242#issuecomment-1433466832)).
Reverting the css fontsize makes it behave properly:
@RubenRBS Sorry, I too preferred your idea of smaller decoration text.

Stop fixing stack-usage/opt-remarks font size

---

static/settings.ts
views/popups/settings.pug

Following some high-traffic alerts an idea was raised on discord to increase the default delay between typing and re-compilation - as today every slight hesitation triggers re-compilation.
The default delay was 750ms. This PR doubles it while trying to limit the change to users who didn't set it explicitly. On first navigation after this fix *all* 750's would be converted to 1500, but if a user later sets the delay to 750 it *won't* be converted (with a little help from `localStorage`).
This also sets a single place to centrally control the default delay in the future (personally I think it can be higher, but it can wait).
A new checkbox in the settings is added, and future modifications to the default delay would apply only when this is checked:

Change the default delay before re-compilation from 750 to 1500 ms

---

etc/config/ruby.amazon.properties

Not the latest 3.2 version, but what is listed at:
https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-AL2023.5.html

Adding ruby 3.2.2 to ruby.amazon.properties

---

etc/config/cuda.amazon.properties

Use default device libs path determined by --rocm-path

Fix HIP/CUDA for rocm-6.1.2

---

etc/config/c++.amazon.properties

Adding experimental clang to support P3309 (constexpr atomic & atomic_ref)

Add p3309 (+ fix description of P3068 clang)

---

examples/circt/default.mlir

As the circt project has evolved over the past two years, the old example no longer work with the current circt compiler. This commit corrects the IR examples according to the new HW dialect, Seq dialect definitions.

Update test example for circt

---

lib/instructionsets.ts
lib/tooling/llvm-mca-tool.ts

Currently if an MCA instance is constructed on a compiler, MCA runs with
the default target for the host it is running on.
Make it respect the target architecture by passing an -mtarget to MCA
conditioned on the detected instructionSet of the compiler.
Additionally, pass through any -mcpu, -march or -mtriple specified to
the compiler.

Pass instructionSet, -mcpu, -march and -mtriple through to llvm-mca

---

lib/base-compiler.ts
lib/compilers/argument-parsers.ts
types/compiler.interfaces.ts

~~This removes useless comments (namely repeated function/label names, `<n>-byte Folded Spill` and others) from the generated assembly.~~
Fixes #5964

Set -fverbose-asm/-fno-verbose-asm from Comment filter

---

lib/demangler/base.ts
lib/demangler/llvm.ts
lib/demangler/prefix-tree.ts
test/demangler-tests.ts

This code had some problems:
https://github.com/compiler-explorer/compiler-explorer/blob/07d5c3312fce98d2742fa7ed738d4084f3a6975f/lib/demangler/base.ts#L200-L203
There
`PrefixTree.replaceAll` replaces mangled to demangled names 'blindly', with no notion of labels. Later `demangleLabels` runs separate logic to update the column-range of each label in hope of mimicking the `replaceAll` action.  This fails in some cases: 
(1) the `demangleLables` code handles only a single occurrence of each label in a line, 
(2) It also diverges from `replaceAll` in case that a string which is a label-name appears in the line *not* as part of a label (this does happen!).
This fix makes `replaceAll` return detailed account of its actions, and then use these to properly adjust the label ranges.
This fix might …

Fix #6083: rewrite demangleLabels

---

lib/compilers/d8.ts
lib/compilers/r8.ts

The minimum API is currently not set, meaning that some bytecodes are
mising (invoke-polymorphic from API level 26; const-method-handle and
const-method-type from API level 27). This change sets a default minimum
API level of 27, while allowing for the option to still be overridden.

 Set default min API to 27 for R8/D8

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/zig.amazon.properties

zig `0.12.1` released on 2024-06-08
zig `0.13.0` released on 2024-06-07
I also updated the zig license preamble, which was changed in 2023.
infra PR: https://github.com/compiler-explorer/infra/pull/1366

Add zig 0.12.1 and 0.13.0

---

static/panes/diff.interfaces.ts
static/panes/diff.ts

Add support for diffing clang ASTs, LLVM IR, and Rust HIR, MIR and macro expansions. These new options are only shown in the picker when the compiler supports the respective output type (e. g. when diffing `g++` output, there will be no item to select LLVM IR).
Because the specified output must be activated manually, this PR also adds help texts so that the user isn’t shown an empty pane. E. g. when diffing execution stdout but “Execute the code” is not checked, the diff viewer will show “<activate 'Output...' → 'Execute the code' in this compiler's pane>”.
Resolves #6726.

Implement more diff types

---

etc/config/ruby.amazon.properties

Made changes that I think will help maintainability, dropping the patch level version from all the variables... 
You might want to consider dropping 2.5 and 2.6... they're ancient. Happy to add.

Bump all extant versions of ruby, add ruby 3.1 for completeness

---

etc/nsjail/compilers-and-tools.cfg

This allows running compilers that use these, for example ones that link in TCMalloc. I'm just implementing the suggestion in #6734, it seems reasonable and targeted. Hoping a PR lets a fix move forward here.
I've left this as mandatory given that `/proc` is mandatory. This might still have an issue on more unusual Linux images, but I suspect not.
Not sure how to test this, wasn't clear how to just check the contents of a file in the jail from the test suite examples I looked at. That said, if you can point me to some example for how to do it, happy to add one.
Fixes #6734

Attempt to add CPU sysfs entries to the jail.

---

lib/base-compiler.ts
lib/llvm-opt-transformer.ts
test/llvm-opt-transformer-test.ts

… to be synchronous and not fail on bad document
Fixes #6745.
The main problem is already described in [this comment](https://github.com/compiler-explorer/compiler-explorer/issues/6745#issuecomment-2266054446). Beyond it, this addresses cases where clang actually generates [invalid yaml documents](https://github.com/llvm/llvm-project/issues/101839).
Also, moved to the library function `yaml.parseAllDocuments` which doesn't throw. Which means one test and several sentry calls were eliminated.

Rewrite the llvm-opt-transformer functionality

---

lib/base-compiler.ts
lib/stack-usage-transformer.ts

Minor added tsification
Fixes #6714 : "No demangling in opt-remarks for clang <=17"
This is probably a regression introduced by my PR #6451 - which changed the version of the llvm-cxxfilt demanglers used. Up until llvm 18 these demanglers did not support the `-p` switch ("Skip function parameters and return types"). 
The fix here is to remove the switch (why would we want it?? We wish to distinguish overloads in opt remarks too).

Remove '-p' from forced demangler args

---

etc/config/hlsl.amazon.properties

This change adds the new DXC 1.8.2407 release. This PR depends on the infra PR below being merged and compilers built:
compiler-explorer/infra#1381

[HLSL] Add DXC 1.8.2407 release

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties

Left out sh GNAT and GDC.
But they are installed, so at least GDC 14.2 can be added along with the rest in https://github.com/compiler-explorer/compiler-explorer/issues/6520.
refs https://github.com/compiler-explorer/compiler-explorer/issues/6741

Add 23 cross GCC 14.2

---

static/utils.ts
static/widgets/alert.ts

All `Alert` modal windows reuse the same yesButton/noButton.
The callback are setup in the Alert ctor -
```
const yesNoModal = $('#yes-no');
yesNoModal.find('button.yes').on('click', () => {
this.yesHandler?.();
});
yesNoModal.find('button.no').on('click', () => {
this.noHandler?.();
});
}
```
On every yes/no click, *All* callbacks of *All* alert instances are called.
So each `Alert` instance needs to cleanup its callbacks after usage, and it tries to - via the weirdly named `toggleEventListener`. `toggleEventListener` only did
```
element.off(eventName);
```
Some of the renaming problems were caused by persistance of [this callback](https://github.com/compiler-explorer/compiler-explorer/blob/00648a7e1c38c9172c5226d1f64511b8bebfe1c9/static/widgets/pane-renaming.ts#L68-L72).
Extending the …

fix `Alert`

---

static/event-map.ts
static/panes/ast-view.ts
static/panes/conformance-view.ts
static/panes/executor.ts
static/panes/ir-view.ts
static/panes/pane.ts
static/panes/tree.ts
static/widgets/pane-renaming.ts

When each `Pane` (and others) create their own `PaneRenaming`, which extends `EventEmitter.EventEmitter`, when one actor emits `renamePane` no other actor can hear it.
This PR makes `PaneRenaming` stop using its own event emission, and instead use the central `Hub` it now  receives at its ctor.

Make pane-renaming central

---

static/panes/editor.ts

Pane has `Pane.paneName`, and Editor - which extends it - has `Editor.filename`. 
Is there really any reason to keep these two distinct? This seems to just add opportunities for bugs.
If you think not, I'll remove `Editor.filename` in a future PR.

add paneName fallback to filename in editor.getPaneName()

---

static/multifile-service.ts
static/panes/editor.ts
static/panes/tree.ts

I gave renaming a proper beat-up, and a few more fixes ensued.
TODO: eliminate `editor.filename` in favour of `pane.paneName`, this could have saved some of these fixes.

More fixes for pane-renaming in various scenarios

---

lib/tooling/clang-format-tool.ts

Fix #6765: don't let an empty `stdin` override explicit args

Fix in clang-format arg handling

---

lib/compilers/dex2oat.ts

This allows for inlining behavior that is more similar to the inlining that will occur when compiling on a device.

Enable --force-allow-oj-inlines

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties

This change adds newer R8 versions (8.5.10, 8.5.27, 8.5.35) and ART dex2oat versions (34.17, 34.18) for Android Java/Kotlin. This should be submitted after:
- https://github.com/compiler-explorer/infra/pull/1392
- https://github.com/compiler-explorer/infra/pull/1394

Add new R8 and ART versions

---

lib/base-compiler.ts
lib/compilers/rust.ts
lib/compilers/win32.ts

Fix #5429, #6559 
This particular fix was chosen -
(1) To make the behavior match future rust versions ([as this suggestion](https://github.com/rust-lang/compiler-team/issues/731) was accepted), 
(2) because of the pains reported [here](https://github.com/compiler-explorer/compiler-explorer/issues/3765#issuecomment-1666847807) and [here](https://github.com/compiler-explorer/compiler-explorer/issues/3765#issuecomment-1666861622)
Along the way made `fixIncompatibleOptions` and `changeOptionsBasedOnOverrides` operate on arguments by reference, just seem to make more sense.

When rust `edition` appears in both overrides and compiler-options, prefer the options

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties
lib/compilers/_all.ts
lib/compilers/dotnet.ts

Adding support for mono and NativeAOT.
As for NativeAOT, we have some upstream issues need to be resolved before we can use `JitDisasmAssemblies` to print disasm for the specified assembly only, where it would fail with: 
```
Unhandled exception: ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]<Module>..cctor()'
---> System.NotImplementedException: getClassModule
at Internal.JitInterface.CorInfoImpl.getClassModule(CORINFO_CLASS_STRUCT_*) + 0x2b
at Internal.JitInterface.CorInfoImpl._getClassModule(IntPtr, IntPtr*, CORINFO_CLASS_STRUCT_*) + 0x39
--- End of inner exception stack trace ---
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode, MethodIL) + 0x273
at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode, …
```

.NET: Add mono and NativeAOT support

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

- Seems like `djggp` compiler output is incompatible with serveral tools including `bloaty` tool. `bloaty: unknown file type for file '<source>'`

Exclude `bloaty` tool from running on `djggp` compiler output 

---

etc/config/c++.amazon.properties

Since version 16.0.0, LLVM has supported the LoongArch64[^1], and now we are attempting to integrate it.
[^1]: https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#loongarch-support
Closes #6794, closes #4191

[loongarch] Add Loongarch64 LLVM support

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties

This ensures that the looked-up hovertext instruction documentation is for the correct architecture.
Towards #6807.

Specify dex2oat's output instruction set is aarch64

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/gimple.amazon.properties

Compilers were missing their config.
fixes #6767

Add missing arm-unknown GCC cross for latest versions

---

etc/config/c++.amazon.properties
lib/buildenvsetup/ceconan.ts
lib/options-handler.ts
static/options.interfaces.ts
static/widgets/libs-widget.ts

Etc etc we build boost now, but its under a different name otherwise it would have become even more of a mess
(why arent the unittests failing? im confused?)

Add library lookupname to support binary builds for boost

---

etc/config/android-java.amazon.properties
etc/config/android-java.defaults.properties
etc/config/android-kotlin.amazon.properties
etc/config/android-kotlin.defaults.properties
lib/instructionsets.ts
types/instructionsets.ts

And use it for Android d8 compiler.
It's empty for now. But it lets you filter in the compiler pop out box. And it may let us attach hover assembly documentation later.
I've left it empty in `lib/instructionsets.ts` like `java` is, which I'm modelling this off.
Towards #6819

Add a new dex instruction set

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties
lib/compilers/dotnet.ts

1. filter out non-assemblies from reference
2. scan reflection by default
3. suppress aot warnings
4. update compiler names to distinguish between each other

.NET: Enhance NativeAOT compilation

---

etc/config/cmakescript.amazon.properties

Cmake updates attempt 2

---

etc/config/c++.amazon.properties

In pr #6793, we misconfigured the `target`. This patch addresses and corrects the problem. Additionally, the GCC toolchain has been updated to handle the `ld` linker’s mismatch with the latest relocation type.

[LoongArch] Fix llvm config for #6793

---

static/widgets/fontscale.ts

This fixes an ordering issue with font scales. The issue would happen if you changed the default font scale and then e.g. opened a tool window. It would have the "default" size selected; but it wouldn't apply to the editor window.

Apply the font scale when we know the target

---

etc/config/rust.amazon.properties

see https://crates.io/crates/bumpalo
`bumpalo` is a bump allocator and as such intended to be fast. It would be nice if it was available on CE to easily check the generated assembly.
Infra PR: https://github.com/compiler-explorer/infra/pull/1416

[rust] add `bumpalo` crate

---

etc/config/tablegen.amazon.properties

From the same Clang install added in 6139c19e3b81d1a3d437eb413dfb00c187069578.
And change the default version to trunk.

LLVM TableGen: Add 19.1.0 compiler

---

lib/cfg/cfg-parsers/_all.ts
lib/cfg/cfg-parsers/base.ts
lib/cfg/cfg-parsers/oat.ts
lib/cfg/cfg.ts

This currently only covers the default arm64 output, and isn't compatible with the custom '--full-output' flag. If there's demand for it, both of these can be fixed by updating how the oatdump output is parsed in OatCFGParser.

Add CFG support to dex2oat

---

lib/cfg/cfg-parsers/oat.ts

We need to account for latest versions of dex2oat saving jump targets in non-truncated form, for example,
(old) "b #+0x28 (addr 0x416c)" vs. (new) "b.hs #+0x24 (addr 0x00008074)"

Update OatCFGParser's jump target format

---

lib/base-compiler.ts
lib/compilers/argument-parsers.ts
lib/parsers/llvm-pass-dump-parser.ts
static/panes/opt-pipeline.ts
static/widgets/toggles.ts
types/compiler.interfaces.ts

Thank @Lancern for the CIR flags analogous to clang's `--print-before|after-all.`

Introduce opt-pipeline for ClangIr

---

etc/config/c++.amazonwin.properties

As pointed out in https://github.com/compiler-explorer/compiler-explorer/pull/6738#issuecomment-2384120341, it doesn't really work, and I don't have the bandwidth to fix this in a timely manner.

Temporarily disable linking and execution for clang-cl

---

etc/config/fortran.amazon.properties
etc/config/fortran.defaults.properties
lib/compilers/argument-parsers.ts
lib/compilers/flang.ts

In anticipation of https://discourse.llvm.org/t/proposal-rename-flang-new-to-flang/69462 happening, which will rename flang-new to simply "flang".
I have added aliases to keep old links working.
gfortranpath has been removed because it was only used for flang-to-external-fc to find the gfortran binary. It was not adding any library paths current flang would need for linking. It was set for the `flang-new` compiler but this was a mistake, `flang-new` can generate code without the help of `gfortran`.
The binary name will remain "flang-new" until main llvm makes the change.

Flang: Remove flang-to-external-fc support and "new" from names

---

CONTRIBUTORS.md
docs/API.md
lib/handlers/route-api.ts
test/handlers/route-api-test.ts

I encountered a problem with large URLs when using the "clientstate" API with base64 strings: see #6918 
* I found that it was quite easy to include this feature, just by searching for `/clientstate/`.
* I "tested" my feature interactively with `npm run dev` and this [link](http://localhost:10240/zclientstate/eNq1VduK2zAQ/ZXBhWITJc6lVye7sBT6uIWl9CUOiyJPYm1syUjyZsOSf+/Idm5tWuhD7YCs0cyZM5doXgOL1kqtbJDA/DWQGa0jBkHB1brma6RtIHq9gERW10Y0glTFMYiqMrhCg0pgArlzlU3iGNXg/GAgdBlvYxLFQivHpUITl5mtuErVG6lEUWcIM6mtM8jL23PhAdLw7WAtXV4va4vGw6ByDfBGbzbadnixlWpdYD9Hnh2dDPKqIlDFS6StQLAuwxe48es0Vf51WFYFdzgTBbcW7m6BgpNrpQ2Cy6WFNDiopAHkFBeDlTZ0hlDqkrik6lnLDCojlRtnITG0Du7e8ghegR6Cu/KEN1ztwO0qhLsoVV5EqCFBgCR+wyktM+ADfPHhhsNoCr2eJMhW91z/qdV/OtcfNfpPF/r+obiTROjawYy0Q8lIhb4osjSYeqpfer3xJAE+p6PFyXZ/+ryASIOUkhhM22PS2v8WK …

feat: added ability to receive a base64 with compressed clientstate, #6918

---

etc/config/vb.defaults.properties
lib/compilers/dotnet.ts

After this PR, compilers will be invoked directly instead of relying on the built-in `dotnet build` command which involves restore and many other expensive resolution operations.
This should speed up the compilation process a lot.

.NET: Invoke compiler directly to speed up compilation

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cuda.amazon.properties
etc/config/fortran.amazon.properties

Fixed the errors found with the first PR, which was
Add HPC SDK 24.9 to etc/config/c.amazon.properties
Add HPC SDK 24.9 to etc/config/c++.amazon.properties
Add HPC SDK 24.9 to etc/config/fortran.amazon.properties
Add CUDA 12.6 to etc/config/cuda.amazon.properties
nvc and nvfortran are new additions to CE.

Changes for NVIDIA HPC SDK 24.9 (fixed)

---

lib/compilers/dotnet.ts

Using a response file can prevent nsjail from replacing the file name in args. Passing all args directly to the compiler instead. 
Fixes https://github.com/compiler-explorer/compiler-explorer/pull/6928#issuecomment-2398361491

.NET: Stop using a response file

---

etc/config/zig.amazon.properties

zig: update default version to 0.13.0

---

static/widgets/compiler-picker-popup.ts

Removes clearing of isa, group and search
Works across different compiler panes where they remember the individual settings, so you can filter one on clangs and the other on gccs and that is remembered when you want to switch compilers. (because the dialog is cloned and not reused like some of our other dialogs)

Remember the compiler pickers isa and group filters + search

---

etc/config/fortran.amazon.properties
etc/config/fortran.defaults.properties

Since https://github.com/llvm/llvm-project/commit/06eb10dadfaeaadc5d0d95d38bea4bfb5253e077 the binary is called "flang" not "flang-new". "flang-new" is now a symlink to "flang". This symlink will probably remain for the next release and then be removed.
So I see no reason to not move to "flang" now. You can see the new layout in the most recent nightly build logs:
```
2024-10-11T01:27:26.5073126Z -- Installing: /root/staging/bin/flang-20
2024-10-11T01:27:26.7519042Z -- Installing: /root/staging/bin/flang
2024-10-11T01:27:26.7519829Z -- Set runtime path of "/root/staging/bin/flang-20" to "$ORIGIN/../lib"
2024-10-11T01:27:26.7520792Z -- Up-to-date: /root/staging/bin/flang-20
2024-10-11T01:27:26.7521292Z -- Up-to-date: /root/staging/bin/flang
2024-10-11T01:27:26.7543999Z -- Creating …
```

LLVM Flang: Use "flang" binary instead of "flang-new" symlink

---

etc/config/c++.amazon.properties

[LIBRARY_REQUEST] beman_optional26: fix deployment after the library was renamed inside the Beman project
Related to #6651
Library was introduced in #6652 
Current naming -> https://github.com/beman-project/optional26/tree/main/include/beman/optional26.

[LIBRARY_REQUEST] beman_optional26: fix deployment after the library was renamed inside the Beman project

---

etc/config/c++.amazon.properties

relates to: https://github.com/compiler-explorer/infra/pull/1430

Add mimic++ as c++ header-only library

---

etc/config/ispc.amazon.properties

Adding ISPC v1.25.0.
Corresponding infra commit PR, which needs to be merged before this PR: https://github.com/compiler-explorer/infra/pull/1434 (so ISPC v1.25.0 is available in the infra).

Add ISPC v1.25.0

---

etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/gimple.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/spice.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties

Updated OSACA from v0.5.2 to v0.6.1, which includes bug fixes, more supported instructions for existing architectures and new architectures like Intel Sapphire Rapids, Nvidia Grace Superchip/Neoverse V2, and AMD Zen 4.

use OSACA v0.6.1

---

lib/compilers/dotnet.ts

Godbolt caches the compiler instance so that the version string won't be recalculated if there's an update to the compiler image. 
Do not cache that information, instead reevaluate them whenever we do the compilation.

Do not cache the sdk version and compiler path

---

compiler-args-app.ts
lib/cfg/cfg-parsers/clang.ts
lib/handlers/api.ts
lib/utils.ts
test/utils-tests.ts

_No functional change intended_
Our padRight and trimRight implementations have been in standard javascript for quite a long time now (node 10.x and 8.x repsectively) so I've replaced their usages with the builtins.
The replaceAll function had zero uses (as we already use String.replaceAll everywhere)

Replace old utils with JavaScript builtins

---

package-lock.json
package.json
vitest.config.ts

We previously used c8 for coverage before vitest.
This patch removes the c8 dependency since it's no longer used, and adds config for vitest-v8 (We will now get both html, json, and terminal outputs for the coverage)

Remove c8 coverage reporter

---

static/panes/compiler.ts
static/styles/explorer.scss
views/templates/panes/compiler.pug

When a new pane (such as the LLVM IR view) is opened using a button in the “Add new...” or “Add tool...” menu, the button is disabled. This can be confusing when the pane is not visible (e. g. when it is in a tab in the background), because it can also be interpreted as “this is not supported“.
This PR adds an `[already open]` to the button when it is disabled.

Show that pane is already open when disabling the button to create a new pane

---

static/components.ts
static/multifile-service.ts
static/panes/editor.ts
static/panes/tree.ts

When doing 'Add new...'/'Source editor' from, e.g., a Rust editor - open a new Rust editor and not a C++ one.

Make 'new source editor' preserve the origin language

---

static/panes/compiler.ts

Fixing the merge conflicts in #6974 accidentally removed the `new-pane-button` class from the buttons in the “Add tool...” menu from #7002:
https://github.com/compiler-explorer/compiler-explorer/pull/6974/files#diff-40ca496bc7fcf6c9bcd41d530708fe3a7bcc5f58cd9bad27ab919b5033f557deL2695-L2696
See https://godbolt.org/z/fd7v8zfE5 (click on “Add tool...”, `ldd` is disabled but does say `[already open]`).
This PR reintroduces that change. However, the implementation in #7002 would also show `[already open]` for the “No tools available” button if there are no tools. In this PR, the `new-pane-button` class is only added to the “real” new tool buttons.

Reintroduce `[already open]` for “new tool” buttons

---

etc/config/rust.amazon.properties

see https://crates.io/crates/clap
`clap` is a popular argument parsing library. This PR adds version 4.5.20 because the version currently supported on CE is quite old and `clap` has had a major version bump in the meantime.
Infra PR: https://github.com/compiler-explorer/infra/pull/1442

[rust] update `clap` crate

---

lib/clientstate.ts

Just a small fix concerning the type (and the default value!) of `ClientStateExecutor.arguments`.
This solves #7037 .
**Please have a detailed look at my changes**, since I have no deep insight in all dependencies of this software (however, the tests pass)!
I tested the new code with the link in #7037 - and I tested the error (wrong type) with [this link (the arguments are a list here)](http://localhost:10240/clientstate/eNpNUEFqwzAQ/MqiQrCJS0jSk5205AW9hF7qHGRFuAJ5baQVpAj9vSvjmCKENLOj2dVE4bX3ZkQvaviOwtz53FcgrMQ+yF4zFGq7FUz5MTg1Ey2+GFQ23DWcJmeQ3lv05IIiuEBkDI/qt0lNiy2SHiYriZXKSu/hylqD1qAGxW0JrhsY5AOKBcFGVrDeuxIiu5DTFByChBN08MG7Bsn2KXfI/QZpsJi1AJ7udT2PZbFoBZsXx+qtPMfU8jeesGyydrebiUvcV4dUXSJXUq6k/GE1DpOx2s3Z3JjQD60CjW4JS7o+DBpprT8fMF6iFL1HOfmfkbKhNd2qHSdaYhevPPGZQz4cRfrn8hloCvRlvOlsjp0D1unG6w9 …

fix: changed ClientStateExecutor.arguments type to string (was: any[]) - closes #7037

---

lib/base-compiler.ts
static/event-map.ts
static/panes/clangir-view.ts
static/panes/compiler.ts
types/compilation/clangir.interfaces.ts
types/compilation/compilation.interfaces.ts
views/templates/panes/clangir.pug
views/templates/templates.pug

This patch adds two options to the clangir pane that affects the clangir compilation pipeline:
* Flat CIR enables the emission of flat clangir CFG;
* -fclangir-mem2reg enables the mem2reg pass on the flat clangir CFG.

Add ClangIR compilation options

---

lib/parsers/asm-parser-spirv.ts

SPIR-V is like LLVM in there are "Blocks" used for Control Flow, `OpLabel` has a special text in the SPIR-V spec
> A block always starts with an [OpLabel](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpLabel) instruction. This may be immediately preceded by an [OpLine](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpLine) instruction, but the OpLabel is considered as the beginning of the block.
But currently the coloring is off-by-1
This change now moves it up a line so it is the start of the block
This can be better seen why looking at the [SPIR-V Visualizer](spirv-visualizer) tool output

Fix OpLabel being in previous block

---

.idea/compiler-explorer.iml

Vitest outputs coverage information into `/coverage`.

Mark coverage as excluded in IntelliJ

---

lib/compilers/clspv.ts
lib/compilers/glsl.ts
lib/compilers/spirv-tools.ts
lib/compilers/spirv.ts
lib/parsers/asm-parser-spirv.ts

`spirv-dis` has a `--comment` that provides nice information to the output of the SPIR-V
(Note that when the `comment` filter is on, the SPIR-V looks the same)
We only showed the comments that appear at the top
We will include the other comments/whitespace to help break up the SPIRV

Add richer comments to SPIR-V assembly output

---

lib/compilers/argument-parsers.ts
lib/compilers/glsl.ts

Currently when using `glslang` with `GLSL` you don't get any options
After digging around I realize the issue is
1. Going `-fsyntax-only --help` with the default arg parer produces an error in glslang
2. glslang (for many other reasons that could argue are right or wrong) returns `1` and not `0` upon calling `glslang --help`

Add Glslang Argument Parser

---

lib/base-compiler.ts
lib/compilers/spirv-tools.ts
types/compilation/compilation.interfaces.ts

So SPIR-V, unlike probably everything else, can't be "executed" by itself (for graphics) because it lacks additional information. This is why there is a "Validator" tool, it ensures statically the IR is "good so far"
The issue because currently you get a non-obvious result, this PR allows the following to occur

Add success message for validator tool

---

README.md
app.ts

Still supports comma-separated languages.
See https://github.com/compiler-explorer/compiler-explorer/discussions/7074

Support multiple --language arguments

---

lib/utils.ts

eachLine is a small util around splitLines (I am wondering if we might as well just remove it alltogether..?) that previously had `() => ResultLine | void`, but none of the callers of eachLine use its return value ever.

Remove void type from eachLine

---

lib/compilation-queue.ts

Removes an old TODO of mine :)
p-queue conditionally returns `undefined` if throwOnTimeout is not set to true. We currently operate our own timeout check, so I haven't changed that.
Setting timeout to undefined should give us the correct type without affecting behavior. https://github.com/sindresorhus/p-queue/blob/main/source/index.ts#L253

Remove unnecessary type assertion

---

lib/compilers/ylc.ts

Hi all!
I recently changed argument passing for my compiler.
From:
```
ylc -in=<in> -o=<out>
```
to:
```
ylc <in> -o=<out>
```
Which makes ygen currently unusable 😭
So i fixed it in this pr
Bye

[FIX] fixed argument passing for ygen

---

etc/config/csharp.amazon.properties
etc/config/csharp.defaults.properties
etc/config/fsharp.amazon.properties
etc/config/fsharp.defaults.properties
etc/config/il.amazon.properties
etc/config/il.defaults.properties
etc/config/vb.amazon.properties
etc/config/vb.defaults.properties
lib/compilers/_all.ts
lib/compilers/dotnet.ts

- Adding support for .NET 9.0
- Adding support for ILSpy
- Make some changes to the compiler name so that the meaning of the version is more cleared
- Adding missing compilers for existing .NET versions
cc: @mattgodbolt

Add support for .NET 9.0 and ILSpy

---

static/sharing.ts
static/styles/themes/dark-theme.scss
static/styles/themes/default-theme.scss
static/styles/themes/one-dark-theme.scss
static/styles/themes/pink-theme.scss
views/menu-other.pug

Adds intent link for sharing a Compiler Explorer link to Bluesky. Also adds a link to the [Compiler Explorer Bluesky profile](https://bsky.app/profile/compiler-explorer.com) into the `Other` menu.
<details>
<summary><b>Screenshots of the new links:</b></summary>
Shared post
</details>
I added the `via @compiler-explorer.com` to be the same as twitter, but since bsky does not fully support tagging yet, it gives the user a dropdown to select the compiler explorer user, which seems kinda janky. I left it in for now, but can remove it until bsky supports tagging automatically.

Add Bluesky to link sharing options and other menu

---

lib/compilers/dotnet.ts

The compile result of ILSpy is C# code, so use `csharp` for highlighting.

.NET: Set languageId for ILSpy

---

lib/compilers/dotnet.ts

As per https://github.com/compiler-explorer/compiler-explorer/issues/6199#issuecomment-2505980377, allowing passing `--help` to compilers so that users can know what options and switches are available (though part of them will be filtered out, but still better than having nothing).

Allow passing --help to compilers

---

app.ts
lib/handlers/api/assembly-documentation-controller.ts
lib/handlers/api/controller.interfaces.ts
lib/handlers/api/source-controller.ts
test/handlers/asm-docs-tests.ts
test/handlers/site-templates-tests.ts
test/handlers/source-tests.ts

By requiring controllers to declare their own routes, we ensure consistency between tests and the actual server

Introduce HttpController interface for http routers

---

.github/labeler.yml
etc/config/fortran.amazon.properties
lib/compilers/_all.ts
lib/compilers/lfortran.ts

Details:
LFortran is a modern open-source (BSD licensed) interactive Fortran
compiler built on top of LLVM. See, https://lfortran.org for more details.
There was an interest in the community to add the compiler into the 
Compiler Explorer: https://github.com/lfortran/lfortran/issues/623. 
So, this PR adds it.
LFortran is in alpha (the source code compiles to binary and execute. 
But, users are expected that their code can break). It can emits AST, 
ASR, LLVM, C, C++, WAT, Julia, Fortran, etc. It has multiple backend
like LLVM (default), C, C++, x86, WASM, fortran and mlir. 
For more options run `--help`.
Changes in this PR:
- Add LFortran as a new Fortran compiler.
- `-g` options is enabled by default in `optionsForFilter`. Providing an option 
to disabling it helps other compilers (that …

[feat] Add LFortran as a new fortran compiler

---

etc/config/fortran.amazon.properties
lib/compilers/lfortran.ts

Advice sought: I didn't want to plumb through a whole new compiler flag for `clang` so used a top-level one for `fortran` in the form of a `ceProp` (which doesn't cascade through all the groups etc). I think this is _ok_ but ugly and surprising (To me...) and I wonder if we should actually consider making each compiler's `ceProps` use the same logic as the logic in the discovery process with parent properties etc...or not. (cc @partouf in case I've missed something obvious!)

Add lfortran and a slightly hacky path to clang

---

lib/handlers/api/assembly-documentation-controller.ts
lib/handlers/api/source-controller.ts
lib/handlers/middleware.ts
test/handlers/middleware-tests.ts

Just add the headers you want to the handler list :)
It's basically the addStaticHeaders function again, but this time more composable. End goal is to replace that function and all its uses with this as I go with the api improvements
This technically also fixes a cors regression from earlier patches

Add re-usable middleware functions to http server

---

app.ts

This has been dangling as a TODO from @mattgodbolt since 2021. Running the following Athena query:
```sql
SELECT COUNT(*) as reqs, uri, date
from cloudfront_logs
WHERE uri LIKE '/shortener%'
GROUP BY date, uri
```
Yields about 8-20 requests per day. I think this is an insignificant enough amount of traffic to justify removing it now.

Remove old shortener path

---

app.ts
lib/handlers/middleware.ts
lib/handlers/noscript.ts
lib/handlers/route-api.ts

Stops passing these functions around and instead configures the headers by chaining express handlers

Remove addStaticHeaders and contentPolicyHeader functions

---

lib/compilers/dotnet.ts

#7143 accidentally broke the compilation for mono as it would pass an unnecessary option `--parallalism 1` to `mono`. Missed this in my local test as the result of mono was cached.
This option is only used by Crossgen2 and NativeAOT.

.NET: Fix the redundant options in some cases

---

static/main.ts
static/panes/editor.ts

When settings are set to emit-short-link upon ctrl+S, managing the logic in `Editor` is problematic since the editor may lose focus and not receive the event.
Also logically this is a cross-site event, and doesn't belong in any particular editor (there can be multiple).

Fix #3264: move emitShortLinkEvent from editor-pane to main window

---

etc/config/c++.amazonwin.properties
etc/config/c.amazonwin.properties

Adding a switch to all MSVC compilations that specifies the charset seems good enough.

Fix #3203: Apply the workaround suggested by OP

---

lib/compilers/rust.ts

Rust compilers output to fixed-named intermediate files. When running a regular compiler with `--emit-llvm` _and_ an IR view on the same source, the outputs fight.
This ensures the intermediate files for IR are named differently.
Thanks @bjorn3
Closes #7012

Separate filenames for llvm IR in rust

---

etc/config/ada.amazon.properties

The compiler was incorrectly reinstalled after I probably forgot to correct end #3701.
Fixes #7168

Readd powerpc64 GNAT 11.2 compiler

---

etc/config/c++.amazon.properties

Older g++ versions were kind of working (by chance) for the BPF target. With more recent, it's broken, so was not enabled. Having only "old" compilers available in C++, but not in C is confusing, and not really useful => hidding the existing C++ compilers.
fixes #7116

gccbpf: disable C++

---

etc/config/c++.amazonwin.properties

Fixes https://github.com/compiler-explorer/compiler-explorer/issues/7169
But may be more compiler id's are missing.
We tried to address this as best as we could when transitioning to the new infra and new msvc installations, but we probably missed more than just this one.

Add alias for long lost msvc id

---

lib/compilers/dotnet.ts

Instead of skipping the exactly the last option, skip all options after the input filename.
Otherwise, in some cases there can be options like `-Wl` and etc. being passed to the compiler and cause build failures.

Make the argument parsing more robust

---

etc/config/spirv.amazon.properties

I added SPIRV-Cross support in https://github.com/compiler-explorer/compiler-explorer/pull/7056 and with the Infra changes in https://github.com/compiler-explorer/infra/pull/1475 we can have it up online
(note, the `spirv-reflect` needed a fix to the command line args which means will have to wait until next SDK to add it here)

Add SPIR-V Cross to production

---

etc/config/odin.defaults.properties
lib/compilers/odin.ts

- support library code filter
- disable demangling, its not needed for odin
- support LLVM IR

Improve odin codegen processing

---

lib/compilers/glsl.ts

glslang outputs its message strangely (and it is not going to change, otherwise I would have made the changes there)
This will take an ouptut like
```
ERROR: <source>:4: Something bad
WARNING: <source>:5: Something less bad
```
to be
```
<source>:4: Something bad
<source>:5: warning: Something less bad
```
so it appears automatically in the UI

Fix error lines for GLSL output

---

Makefile
compiler-args-app.ts
docs/AddingASiteTemplate.md
etc/scripts/build-dist-win.ps1
etc/scripts/build-dist.sh
etc/scripts/docenizers/docenizer-java.sh
etc/scripts/docenizers/docenizer-llvm.sh
etc/scripts/generate_site_template_screenshots.ts
package-lock.json
package.json

Migrates tooling to TSX (as advised by nodejs) until we are on Node 22 where we can `--watch --experimental-strip-types`

Replace ts-node with tsx

---

lib/compilers/dotnet.ts

This allows users to inspect the disassembly other than x64.

.NET: Add cross-arch codegen support for crossgen2

---

etc/config/c++.amazonwin.properties
etc/config/c.amazonwin.properties
lib/compilers/win32.ts

Following the discussion in #7164.
@partouf I believe this would solve also linkage against windows libs built with /utf-8

Set MSVC default option to /utf-8, remove it if the user specified /source-charset or /execution-charset

---

etc/config/rust.amazon.properties

The -vV set as default for rust is really for "rustc". As there are not many alternative compilers, and as rustc is really 99.99% of the rust compiler installs, it's simpler to override the value for gccrs.
fixes #7220

fix versionFlag for gccrs

---

static/modes/glsl-mode.ts
static/modes/hlsl-mode.ts
static/modes/slang-mode.ts
static/modes/spirv-mode.ts

I realize basic things like `ctrl`+`/` and auto complete `}` for my `{` were missing from HLSL/GLSL/Slang
After digging, found that it was just a lack of setting `setLanguageConfiguration` for the monaco-editor for each of them
Confirmed the config in `node_modules/monaco-editor/esm/vs/basic-languages/cpp/cpp.js` suites the 3 languages (as they are also all derived from C based languages)

Add Monaco LangConfiguration to GPU languages

---

examples/android-java/default.java
examples/android-kotlin/default.kt
lib/compilers/dex2oat.ts
test/android-tests.ts

This change makes full oatdump output visible behind the "Directives" filter. This does the same thing as the --full-output flag, but is more-easily used. The default code snippets have been updated to include this.

Add full oatdump output behind filters

---

lib/base-compiler.ts

A warning in an old gcc (4.8.1) had a format that was accidentally caught by the -fopt-info regex. Now accounting for potential errors/warnings caught accidentally.
I don't like that `processOptOutput` is being called regardless of whether `backendOptions.produceOptInfo` is set, maybe need to address it too.

Fix #7237: account for potential warning/error matches

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

It seems that 12.2.0 used to be built with the soft float ABI, "gnueabi", but at some point was rebuilt with the hard float ABI "gnueabihf".
I see this when using GCC 12.2.0 directly:
```
COLLECT_GCC=/opt/compiler-explorer/arm/gcc-12.2.0/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc
Target: arm-unknown-linux-gnueabihf
```
This broke any C or C++ example that uses a standard include. Like, at time of writing, https://godbolt.org/z/rKsnj9Mj7.
So I've updated all the compilers that referenced this sysroot. This includes updating the target setting, but judging from the nearby comments the intention was always to produce hard float code anyway.

Fix include path for Armv7-A compilers using gcc 12.2.0 sysroot

---

etc/config/assembly.amazon.properties
etc/config/c.amazon.properties
etc/config/llvm_mir.amazon.properties

Add clang 19 for C for ARM, Mips, BPF, and RISC-V. C++ was already done a few months ago. Also add clang 19 for LLVM MIR and Assembly.
For ARM I used gcc 14.2.0 to match what was already done for C++.

Add clang 19 for more languages.

---

lib/compilers/rust.ts
test/base-compiler-tests.ts

This is mainly for `pahole`, which requires type information that is only present with `-C debuginfo=2`:
https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo
CE originally passed `-g` to `rustc` (which is an alias for `-C debuginfo=2`), but this was changed in c4411ff2a135893b13d49a65c7da613caa93d6ba to `-C debuginfo=1` to work around https://github.com/rust-lang/rust/issues/11906. However, this workaround never actually removed frame pointers, so switching back to `-C debuginfo=2` should not affect codegen for very old `rustc` versions. See also #79.

[rust] switch to `-C debuginfo=2`

---

docs/WindowsLocal.properties

Adds a missing property for the sample Windows props file. Without it, `Win32Demangler` isn't used and demangling fails:
```sh
error: Demangler output issue 5 > 1 {"0":"_num$","code":1,"execTime":24,"okToCache":true,"stderr":"","stdout":"Microsoft (R) C++ Name Undecorator\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nUsage: undname [flags] fname [fname...]\r\n   or: undname [flags] file\r\n","timedOut":false,"truncated":false}
error: Error during compilation 2:  Internal issue in demangler {"stack":"Error: Internal issue in demangler\n    at CppDemangler.processOutput (c:\\Users\\sweet\\Source\\Repos\\compiler-explorer\\lib\\demangler\\base.ts:172:19)\n    at CppDemangler.process (c:\\Users\\sweet\\Source\\Repos\\compiler-explorer\\lib\\demangler\\base.ts:223:21)\n …
```

Set demanglerType=win32 in Windows sample props

---

etc/config/llvm.amazon.properties

Add Hexagon-clang support for LLVM IR

---

etc/config/elixir.defaults.properties
lib/compilers/_all.ts
lib/compilers/elixirasm.ts

Hi, this PR adds a way to view the assembly code of Elixir code.
This continue the work from #6081 and #6104

View Elixir jitted assembly

---

lib/compilers/dex2oat.ts

The Kotlin compilation step results in an added 'final' in the D8 .smali output, which we weren't accounting for. This change updates the class name regex for .smali files to collect only the 'L<class>;' string.
This change also fixes dex2oat for Android Java in cases where 'final' is applied to classes.

Fix dex2oat on Android Kotlin

---

etc/config/c++.amazon.properties

Adds v4, v5 and v6.
related to: [compiler-explorer/infra](https://github.com/compiler-explorer/infra/pull/1490)

upgrade mimic++ header-only library

---

lib/compilers/clang.ts

Added check for clang-offload-bundler for Intel OneAPI >= 2024.0.0

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties

This change adds recent ART mainline releases (version 35) and R8 versions (8.6, 8.7).

Update Android compilers

---

etc/nsjail/user-execution.cfg

Currently only maps in the stdbuf and the lib it needs. Tested locally and paths confirmed to exist on prod boxes.
See #7239

Let user execution `stdbuf`

---

lib/parsers/asm-parser.ts
test/filters-cases/bug-1799.asm
test/filters-cases/bug-1799.asm.binary.directives.labels.comments.json
test/filters-cases/bug-1799.asm.directives.comments.json
test/filters-cases/bug-1799.asm.directives.json
test/filters-cases/bug-1799.asm.directives.labels.comments.json
test/filters-cases/bug-1799.asm.directives.labels.comments.library.dontMaskFilenames.json
test/filters-cases/bug-1799.asm.directives.labels.comments.library.json
test/filters-cases/bug-1799.asm.directives.labels.json
test/filters-cases/bug-1799.asm.directives.library.json
test/filters-cases/bug-1799.asm.none.json

Treats `.set` as an "alias" for the set of labels referred to, and doesn't filter alias-creating `.set` in used paths even if directive filtering is on. Only works for `.set <something>, .` with an optional `+ 0`.
Also changes a silly loop that was looping N times doing the same thing if `inFunction && isDataDefinition`, though quite possibly that's broken in a different way. No tests changed, anyway.
Adds a new test for the new behaviour.
Closes #1799

Handle ARM's .set usage

---

lib/compilers/dex2oat.ts
test/android-tests.ts
test/android/parse-data/ClassWithL.smali
test/android/parse-data/InnerClassCases.smali

This fixes the case where compilations of classes including a 'L'
character would fail. A test case has been added for this, and for inner
classes.

Fix .smali class regex in Dex2OatCompiler 

---

app.ts
lib/compiler-finder.ts
test/compiler-finder-tests.ts

Nothing was using it, we're using other methods these days to discover remote compilers (and have been for years), and it was broken (see #1790).
Also cleans up some config (moving it from aws to ceProps; though it was unused, default used only), and also some workarounds for remote compilers that refer back to the MS compiler era (#1768).
This leaves the ability in `aws.ts` to fetch instances in case we ever need the functionality, as this is tested and still works.
Closes #1790

Decommision the "AWS" magic compiler name

---

lib/parsers/asm-parser.ts

- use `Set` and `Map`
- reflow comments
- remove redundant `!!`
- rephrase iterative "follow the chain of weak symbols" to be recursive, removing artificial limit.

Some tidying up of the asm parser code

---

lib/compilers/odin.ts
test/odin-tests.ts
test/odin/add_require.odin.expected

In optimized build, odin inlines the world and even ends up inlining the user visible `main` function into the entry point main. The result is empty asm output which is confusing. Thus, @require main so that the compiler doesn't inline user visible main function
#7210

odin: require main function

---

static/ansi-to-html.ts
static/panes/output.ts
test/ansi-to-html-tests.ts

Some compilers (such as `gcc` and `rustc`) support emitting hyperlinks
to the documentation for error messages and/or warnings. This PR adds a
parser for the respective `OSC 8` ANSI escape sequence (see
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) and
makes them clickable in the output window.
For example: https://godbolt.org/z/o1v7WzPc6
For GCC, this would make `-Wreturn-type` a clickable link to https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-return-type.
For Rust, this would make `E0425` a clickable link to https://doc.rust-lang.org/error_codes/E0425.html.
Note that this also applies to execution output. A malicious program could (when executed) produce output that contains clickable links to anything.
Related feature requests:
* …

Parse terminal hyperlinks in command output

---

lib/parsers/llvm-pass-dump-parser.ts

Function in LLVM IR can also contain `-` characters without being enquoted.

Fix function define regex in pass dump parser

---

etc/config/c++.amazon.properties

The default objdump version for RISC-V clang is 10.2.0. This doesn't support newer RISC-V extensions.

Update objdump version to 14.2.0 for RISC-V clang trunk.

---

lib/compilers/nim.ts

Stops sentry errors, gives a slightly less awful error to the user. Closes #1814
Tested locally.

Prevent exception if compiler didn't generate

---

lib/utils.ts
test/utils-tests.ts

When passing `-fdiagnostics-urls=always`/`-Z terminal-urls=yes`, the hyperlink escape sequence was not stripped from the mouse hover widget in the editor pane.
Link: https://godbolt.org/z/3cP8jj8jc
Hover over the empty braces in the C++ editor or the `i32` in the Rust editor:
Before:
```
warning: no return statement in function returning non-void []8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-return-type-Wreturn-type]8;;]x86-64 gcc 14.2 #1
error[]8;;https://doc.rust-lang.org/error_codes/E0308.htmlE0308]8;;]: mismatched typesrustc nightly #2
```
Now:
```
warning: no return statement in function returning non-void [-Wreturn-type]x86-64 gcc 14.2 #1
error[E0308]: mismatched typesrustc nightly #2
```

Strip hyperlink escape sequences from editor pane diagnostics hover widget

---

lib/utils.ts
test/utils-tests.ts

Rust error message locations (` --> <source>:<line>:<col>`) can have more than one leading space, e. g. when the source code snippet that is shown has line numbers greater than ten.
In this example (https://godbolt.org/z/9W8xPv36c), the error message is not be recognised as an error and there are no red squigglies in the editor pane.

Parse Rust error message locations with multiple leading spaces

---

static/widgets/history-widget.ts
views/popups/history.pug

Single tab, no diffs - single source display, no list bullets, added spacing, added syntax highlighting.
That's it, I think.

Overhaul 'history' look

---

lib/utils.ts
test/utils-tests.ts

The Rust compiler emits error messages that are (in some cases) detailed enough that they can be parsed to generate quickfixes, e. g. when missing an import or a nightly feature flag.
Example: https://godbolt.org/z/jh3bY19P4 With this PR, hitting `Ctrl-.` with the cursor above any of the two errors in the editor will open a quickfix popup that can fix the respective error:
=>
This feature could also be implemented (more robustly) by using `rustc`’s JSON output. However, `rustc` can’t output *both* human-readable and structured diagnostics, so it would be necessary to invoke the compiler twice to do this. Considering that the Rust Playground also parses the normal human-readable error format, I’d argue that the regex-based approach is good enough.
---
Requested in #5284.

[rust] Add quickfixes for missing imports and feature flags

---

etc/nsjail/user-execution.cfg

Mounts some newer `/dev` and `/sys` directories needed by the newer NVidia drivers into the sandbox. Also make `/proc` read-write which is needed as the driver writes to `/proc/self/task/tid/comm` to try and change its name.
CC @rwarmstr
I don't believe there's a security risk in making `/proc` writeable, though it's annoying that the NVidia process actually errors on the inability to rename its own process name.

Changes for newer NVidia drivers

---

.github/workflows/test-and-deploy.yml
.github/workflows/test-win.yml
package.json

There's nothing special with these anymore. They are the same both locally and in CI now, because our Vitest and Biome setups don't behave differently there

Deduplicate npm scripts used for CI

---

etc/config/rust.amazon.properties

Rust 1.83+ changed the location of `libstd-*.so` so that it is no longer in the default `LD_LIBRARY_PATH` that CE sets:
```console
$ fd --glob 'libstd-*.so' /opt/compiler-explorer
/opt/compiler-explorer/rust-1.82.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-22be60875a4ac8d7.so
/opt/compiler-explorer/rust-1.82.0/lib/libstd-22be60875a4ac8d7.so
/opt/compiler-explorer/rust-1.83.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-ca74a2d9c5166d9f.so
```
This broke execution: https://godbolt.org/z/7fc11afKa

Fix execution for Rust 1.83+ with dynamically linked standard library

---

etc/config/zig.defaults.properties
lib/compilers/zig.ts

- Make it easy/possible to run compiler-explorer-zig locally (see first commit)
- Dont strip debug info, add explicit flag for this (second commit)
- Allow filtering library functions. (it doesn't work super great atm, but at least some of the hundreds of thousands of lines get filtered out).

Zig improvements

---

biome.json
types/cache.interfaces.ts

Function is usually frowned upon in TS because it gives no description of what type of function.

Re-enable noBannedTypes Biome rule

---

biome.json
static/graph-layout-core.ts

Disabled the lint for the only match as the code is mostly ported from cutter's graph engine.

Re-enable useLiteralEnumMembers Biome rule

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

I tested `gcc-snapshot`s `c++filt` and it still doesn't handle `require` well. llvm does.

Fix #7359: use llvm-cxxfilt by default for all compilers

---

etc/config/android-java.amazon.properties
etc/config/android-kotlin.amazon.properties
lib/compilers/d8.ts

This change updates the Java version used for R8/D8/dex2oat latest to the most recent Java version available to help investigate newer Java features.

Use Java 22 for latest Android compilers

---

etc/config/carbon.amazon.properties
etc/config/carbon.defaults.properties
examples/carbon/default.carbon
lib/compilers/_all.ts
lib/compilers/carbon.ts

- Renames existing carbon stuff to carbon-explorer. Will need a quick infra install and will temporarily (like, for 2m) break things during deploy.
- Adds carbon binary support
- Supports binary, execute, and binary objects
- Updates the default carbon file as best I can
Closes #5402

Add carbon native compiler

---

static/styles/colours.scss

Sass `transparentize` is deprecated: https://sass-lang.com/documentation/breaking-changes/color-functions/

Fix depracation warnings

---

CONTRIBUTORS.md
compiler-args-app.ts
lib/base-compiler.ts
lib/compilers/argument-parsers.ts
lib/compilers/zig.ts
types/compiler.interfaces.ts

This makes it so the Zig compiler can now use the compiler flag following `-target ` to query the correct ISA for assembly docs!
Not sure if it still defaults to amd64 on an aarch64 computer when `-target ` is not present. But I will leave that problem for another day.

[Zig] Fix target/arch parsing so assembly docs query the correct ISA

---

etc/nsjail/compilers-and-tools.cfg
lib/exec.ts
lib/handlers/compile.ts
package-lock.json
package.json

- Wrap the executable in `stdbuf` higher up than in `executeDirect` which means we run `stdbuf` _inside_ the jail instead of outside it when running. This fixes jail/stdbuf interactions.
- Install `which` types to avoid a `no-ts`
- Ensure `stdbuf` et al is mapped in compilers-and-tools
- As a fly-by also unify the configuration of NVidia devices between execution and compilation.

Misc fixes for unbuffering

---

lib/compilers/orca.ts

ORCA/C uses its own asm format, and the external parser is not appropriate for it.

Disable external parser for ORCA/C

---

lib/compilers/d8.ts

This fixes the version info button in the compiler window for R8/D8. Version info is pulled from the version properties file for latest, and from the filename for named releases.

Add version info for R8/D8

---

.github/workflows/test-and-deploy.yml
etc/scripts/test_numba_wrapper.py
etc/scripts/util/propscheck.py
etc/scripts/util/propschecktest.py

- Resolve comments from #5592:
- Replace a silly indirect import https://github.com/compiler-explorer/compiler-explorer/pull/5592#discussion_r1962004963
- Run `test_numba_wrapper` in `.github/workflows/test-and-deploy.yml`. https://github.com/compiler-explorer/compiler-explorer/pull/5592#discussion_r1962004131
- Patch minor errors in `etc/scripts/util/propschecktest.py` and also test it.

Test the numba wrapper in test-and-deploy

---

lib/compilers/sway.ts

I'll update `processAsm` to actually have a proper type and that will catch this in future.

Fix format of processAsm

---

etc/config/swift.amazon.properties

- add a new compiler group for swift aarch64 cross-compilation
- add a new entry for the 6.0.3 swift compiler to this new group that uses the existing x86 toolchain
- add additional compilation options to the new compiler which will cross compile to arm via the static musl SDK added in https://github.com/compiler-explorer/infra/pull/1524
- [tangential cleanup]: fixes a typo in the swift 5.10 alias
note: this is my first attempt to add a new compiler group, so i'd appreciate any feedback as to whether i've overlooked or mis-configured any of the fields.

[swift]: add 6.0.3 compiler configuration that will cross-compile to aarch64

---

lib/base-compiler.ts
types/compilation/compilation.interfaces.ts

This is a super conservative tweak towards trying to use types for processAsm, objdump, afterCompilation et al.

Tiniest possible step towards type safety for CompilationResult.asm

---

lib/artifact-utils.ts
lib/compilation-env.ts
lib/compiler-arguments.ts
lib/compilers/argument-parsers.ts
lib/compilers/beebasm.ts
lib/compilers/carbon.ts
lib/compilers/cc65.ts
lib/compilers/dex2oat.ts
lib/compilers/ispc.ts
lib/compilers/java.ts
lib/compilers/ldc.ts
lib/compilers/madpascal.ts
lib/compilers/pascal-win.ts
lib/compilers/pascal.ts
lib/compilers/racket.ts
lib/compilers/rga.ts
lib/compilers/solidity.ts
lib/execution/base-execution-env.ts
lib/handlers/compile.ts
lib/tooling/clang-format-tool.ts
lib/tooling/clang-query-tool.ts
lib/tooling/clang-tidy-tool.ts
lib/tooling/llvm-mca-tool.ts
lib/tooling/osaca-tool.ts
lib/tooling/pvs-studio-tool.ts
lib/utils.ts

- Updates a number of uses of `fs-extra` which were only for the promisified fs calls.
- Makes a few sync calls async.
- Makes a few `read` calls that didn't specify a text mode, but then parsed as a string...into the equivalent `readFile` call.

Use node:fs/promises where possible

---

static/panes/gccdump-view.ts

Fix #7296: `clearOptions` instead of `clear` for gcc pass selector

---

lib/base-compiler.ts
lib/execution/base-execution-env.ts
lib/handlers/compile.ts
lib/temp.ts
package-lock.json
package.json
test/temp-tests.ts
test/utils.ts

Replaces aging `temp` with a simple, bespoke solution. Reduces the number of deprecated/out-of-date dependencies we pick up.
Closes #7445.

New temp directory tracker

---

static/panes/gccdump-view.ts

Fix #7464: need both clear and clearOptions on gccdump's TomSelect

---

static/styles/explorer.scss

Fixes a z-index fight among goldenlayout's dropdowns and the editor's minimap, which both had a z-index of 5 - Let goldenlayout's win by 1 now
Closes https://github.com/compiler-explorer/compiler-explorer/issues/7473

Fix goldenlayout dropdowns z-index fight with Monaco's minimaps

---

etc/config/assembly.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/cuda.amazon.properties
etc/config/llvm.amazon.properties
etc/config/llvm_mir.amazon.properties
etc/config/tablegen.amazon.properties

Should take care of the LLVM stuff mostly everywhere.
- Didn't touch cppx or cpp_for_opencl, these haven't been updated the last few times either
- MLIR untouched, because it's a different install. I can look into that later

Install Clang/LLVM 20

---

etc/config/c++.amazon.properties

Added new versions (and one old one) of the Intel OneAPI C++ compiler:
- 2024.2.1
- 2025.0.1
- 2025.0.3
- 2025.0.4
Refers to [this PR](https://github.com/compiler-explorer/infra/pull/1541).

Added new versions of Intel OneAPI C++ compiler

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/zig.amazon.properties

zig `0.14.0` released on 2025-03-05.
Corresponding infra PR: https://github.com/compiler-explorer/infra/pull/1544

Add zig 0.14.0 and make it the default zig compiler

---

CONTRIBUTORS.md
etc/config/carbon.defaults.properties

This allows using the carbon toolchain as the default Carbon compiler when working in a local development environment.

Put the carbon toolchain in the `carbon.defaults` properties

---

etc/config/rust.amazon.properties
etc/config/rust.defaults.properties
lib/tooling/_all.ts
lib/tooling/base-tool.ts
lib/tooling/clippy-tool.ts

This adds the [Clippy](https://github.com/rust-lang/rust-clippy) linter for all Rust compilers >= v1.29.
~~Clippy is already installed by default for recent-ish Rust versions, but I have not checked if it’s also installed for *really* old versions.~~
Resolves #2562.

Add clippy for Rust

---

lib/tooling/base-tool.ts
lib/tooling/clippy-tool.ts

See https://github.com/compiler-explorer/compiler-explorer/pull/7477#issuecomment-2721773116

[rust] don’t use a separate tempdir for clippy

---

lib/compilers/d8.ts

R8 will not produce a .dex file if there are no entry points into the .class file code. This change updates R8/D8 so that a missing .dex file returns a message to the user in the compiler output window, instead of logging a warning/error.

Correctly handle missing .dex file for R8

---

lib/base-compiler.ts

Causes unwanted cache invalidation (of `client-options.js`) when libraries are selected by the user on GPU instances.

Dont change original library versioninfo object

---

etc/config/slang.amazon.properties
etc/config/spirv.amazon.properties

Update the online version for SPIR-V and Slang compilers for the Vulkan 309 SDK to correspond with https://github.com/compiler-explorer/infra/pull/1550

Update SPIR-V and Slang verisons

---

etc/config/c.amazon.properties
lib/compilers/_all.ts
lib/compilers/argument-parsers.ts
lib/compilers/c2rust.ts

Adds new compiler base for c2rust, a transpiler that converts C code to Rust.
There's one outstanding TODO in the code about incorrect default filters for the c2rust output. I wasn't sure how to address it, so help would be appreciated.
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/6888 and https://github.com/compiler-explorer/compiler-explorer/issues/5900 (there are duplicate feature requests).

Initial support for c2rust

---

etc/config/algol68.amazon.properties
etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/gimple.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/objc++.amazon.properties
etc/config/objc.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/spice.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties
lib/tooling/osaca-tool.ts

Updated OSACA to version 0.7.0 that finally includes support for Intel syntax assembly.
Therefore, I increased the version numbers in the `*.amazon.properties` files and removed the check and error message for Intel syntax in `osaca-tool.ts`.
Successfully tested with `make check` and manually with a local instance

use OSACA v0.7.0 as tool

---

biome.json
lib/compilers/argument-parsers.ts

Fixes regression noticed by @DavidSpickett in #7033
This is a temporary workaround until we consider rewriting these to be regular classes.

Revert noThisInStatic Biome rule for argument-parsers.ts

---

etc/config/c++.amazon.properties

Update c++.amazon.properties: update repo URL after org renaming: https://github.com/bemanproject/
The URL was updated in https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L1140-L1163.
I know GitHub redirects for old links, but I would like to fix this leftover.
Note: we don't need to re-deploy for this issue.

Update c++.amazon.properties: update repo URL after org renaming

---

etc/config/swift.amazon.properties

infra change: https://github.com/compiler-explorer/infra/pull/1564. something may have changed with the Musl SDK used for cross compiling, so going to defer updating the UI to add that until someone can figure out what's going on there.

[swift]: add 6.1 x86 release compiler

---

etc/config/sway.amazon.properties

Add `build` command to Sway compiler options to ensure Compiler Explorer correctly executes `forc build --offline` when running Sway code.
This should resolve the error that was reported by @partouf [here](https://github.com/compiler-explorer/compiler-explorer/pull/7456#issuecomment-2721747677).

fix: add build to sway options

---

etc/config/assembly.amazon.properties

Relates to https://github.com/compiler-explorer/compiler-explorer/issues/7528.
I am not updating Arm and AArch64 because they are still using 2.38 in their GCC 14.2.0 builds.

Add Bintuils 2.42 assemblers for x86, riscv32 and riscv64

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
lib/compilers/_all.ts
lib/compilers/clang.ts
lib/instructionsets.ts
types/instructionsets.ts

These clang + LLVM backends are not upstreamed but [a community effort](https://github.com/CE-Programming/llvm-project/), so it's a bit customized.
This requires https://github.com/compiler-explorer/infra/pull/1566
_Edit: tested locally, works fine._

Add (e)z80-clang compilers.

---

package.json

Corepack (https://github.com/nodejs/corepack) is a shim for pnpm/yarn/npm that allows you to automatically use the right package manager for a project as long as it declares which packageManager it wants to use.
This patch adds registers npm 11.2.0 (latest) as the preferred version for corepack.
This has no effect on any project infrastructure as CE infra itself does not use corepack at the moment.

Configure packageManager field to enable corepack compatability

---

etc/config/c++.amazon.properties

I'm so sorry for the follow-up PR. In #7532 I had just changed all files that refer to spdlog according to a [search](https://github.com/search?q=repo%3Acompiler-explorer%2Fcompiler-explorer%20spdlog&type=code), but it seems that doesn't return c++.amazon.properties. Weird... (GitHub probably only indexes the first 2000 lines or so).
In any case, this PR adds the same lines as in #7532 to `etc/config/c++.amazon.properties` as well. Again, apologies this didn't get included in a single PR.

Add spdlog also to c++

---

examples/rust/default.rs

`no_mangle` is an `unsafe` attribute in the 2024 edition. All other editions still accept the old form without `unsafe`, but also optionally allow `#[unsafe(no_mangle)]`.
The new form was stabilised in Rust 1.82 (released 2024-10-17), so the default code is now incompatible with Rust <= 1.81.
Unsafe attributes RFC: https://rust-lang.github.io/rfcs/3325-unsafe-attributes.html
Example: https://godbolt.org/z/d3rE9r7ae

Make default Rust code compatible with 2024 edition

---

etc/config/c++.amazon.properties

Qt 6.9.0 release in c++.amazon.properties
infra PR here: https://github.com/compiler-explorer/infra/pull/1581

Update Qt 6.9.0

---

lib/binaries/binary-utils.ts
lib/execution/execution-query.ts
static/panes/output.ts

* Fixes bug where executables were always run on Windows even if aarch64 
* Fixes bug in output pane where error was not shown as to why execution did not work
(Windows still not properly fixed, will need to find `file` equivalent for Windows)

Execution fixes (when using architectures that cant run)

---

etc/config/swift.amazon.properties

adds a config entry for cross compiling to arm for the 6.1 release compiler. necessary infra changes added in https://github.com/compiler-explorer/infra/pull/1564. tested that the new config should work by manually adding the flags here: https://swift.godbolt.org/z/EPrsbKPf4.

[swift]: add 6.1 arm release compiler

---

lib/compilers/c2rust.ts

To pass arguments to `clang` (such as `-std=...`), `--` must be used to separate these arguments from the arguments to `c2rust`:
```console
$ ./c2rust-transpile --help
transpile 0.20.0
[...]
USAGE:
c2rust-transpile [OPTIONS] [COMPILE_COMMANDS]... [-- <EXTRA_CLANG_ARGS>...]
```
However, when doing this, the input file must be passed *before* the `--`. Also, when libraries are enabled, the include and link flags must be passed to `clang` (but duplicate `--` are not allowed).
Example for passing command line arguments: https://godbolt.org/z/eqfa3T7WY
Example for activating a library: https://godbolt.org/z/srh55Y1hY

[c2rust]: allow passing arguments to `clang`

---

lib/handlers/api.ts

Google AI suggested too (independently, I did this first then searched and got:
---
1. Using Middleware
A middleware function can intercept OPTIONS requests and set the appropriate CORS headers.
```js
app.use(function(req, res, next) {
res.header("Access-Control-Allow-Origin", "*");
res.header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS");
res.header("Access-Control-Allow-Headers", "Content-Type, Authorization");
if (req.method === 'OPTIONS') {
res.sendStatus(200);
} else {
next();
}
});
```
---
Tested locally with curl on GET, OPTIONS, and POST and correctly lets OPTIONS return an empty CORS block, etc. And the site works too :)

Specifically allow OPTIONS for browser preflight CORS checks.

---

etc/config/c++.amazon.properties

Add beman.exemplar library trunk version - https://github.com/compiler-explorer/compiler-explorer/issues/7624
Infra PR - https://github.com/compiler-explorer/infra/pull/1594
Beman Issue - https://github.com/bemanproject/exemplar/issues/155
Tested these changes on my laptop running Ubuntu 22.04

Add beman.exemplar library trunk version

---

static/styles/explorer.scss
views/popups/load-save.pug

Not quite sure what happened here: the display: none came from change ef7db1af1d0ba3dce03dc9df33db346bb309d39f and we can't quite work out how it was working then.
Fixes #7641

Reinstate and restyle load/save button

---

etc/config/c.amazon.properties

Add `-march=native` warning for x86 GCC and clang for C

---

.github/labeler.yml
etc/config/solidity.amazon.properties
etc/config/solidity.defaults.properties
lib/compilers/_all.ts
lib/compilers/argument-parsers.ts
lib/compilers/solx.ts

Related PR in infra: https://github.com/compiler-explorer/infra/pull/1602

Add solx, new Solidity LLVM-based compiler

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Fixes #7635
Prior to this change the C++ compilers set objdumper on the Armv7/v8 category as a whole, pointing to some objdump from a gcc cross compiler. This works because that tool expects Arm objects, and you could use the "compile to binary object" option successfully.
For C, we only set objdumper for specific compilers. Those being the trunk and "all features" versions. So when "compile to binary object" was enabled it worked for trunk but never for any version before that.
The other versions were using the settings file's global objdumper which pointed to an objdump that only expects x86 object files.
/opt/compiler-explorer/gcc-14.2.0/bin/objdump: can't disassemble for architecture UNKNOWN!
/tmp/compiler-explorer-compiler4xFvjY/output.s:     file format elf64-little
To fix this I …

Arm: add missing objdumper settings and update to GNU objdump 15.1.0

---

lib/base-compiler.ts

Resolves #7669.
`processAsm` didn’t recognise that `opt` generates LLVM IR, so it invoked the generic `AsmParser` instead.

Treat `opt` output as LLVM IR

---

app.ts
lib/app.interfaces.ts
lib/compiler-finder.ts
lib/handlers/handler.interfaces.ts
lib/handlers/noscript.ts
lib/handlers/route-api.ts
lib/options-handler.ts
test/handlers/route-api-test.ts
test/options-handler.ts

- prevents anything importing from `app.js`
- generally tidies up and removes unused stuff
- makes typing a bit more correct

Simplify and extract types

---

etc/config/android-kotlin.amazon.properties

This covers library versions 1.10.2, 1.9.0, 1.8.1, 1.7.3, and 1.6.4, which are the latest releases for each major version. dex2oat uses Kotlin 1.9.20 under the hood, so 1.9.0 is the latest kotlinx.coroutines release supported. (1.10.2 can still be used for kotlinc).

Add kotlinx.coroutines to Android Kotlin

---

etc/config/c++.amazon.properties

Add beman.scope library trunk version -  #7663 
Infra PR - https://github.com/compiler-explorer/infra/pull/1610
Beman Issue - https://github.com/bemanproject/scope/issues/22
Tested these changes on my laptop running Ubuntu 22.04

Add beman.scope library trunk version

---

etc/config/c++.amazon.properties

Adds latest Intel OneAPI C++ compiler version: 2025.1.1. Also changes the latest version to point to it.
A PR on `compiler-explorer/infra` will soon follow.
Edit: [here](https://github.com/compiler-explorer/infra/pull/1606) it is.

Added Intel OneAPI 2025.1.1

---

static/widgets/timing-info-widget.ts

Closes https://github.com/compiler-explorer/compiler-explorer/issues/7647
Fixed timing widget for light system:
Also made the pink theme use the default chart.js colours, as I think they have more contrast than white-on-pink

Fix system light theme timing widget visibility

---

static/styles/explorer.scss
static/styles/themes/pink-theme.scss
views/templates/widgets/compiler-selector.pug

Closes https://github.com/compiler-explorer/compiler-explorer/issues/7648
In Boostrap 5, `disabled` buttons now have `pointer-events: none` ([Changelog here](https://getbootstrap.com/docs/5.0/migration/#buttons)) which disables the `title` contents popping up.
This PR fixes it by making it a default `badge`, which keeps the same layout as buttons, but is not clickable by default, much better than having a `disabled` button never meant to be clicked.
It also slightly changes the padding of the buttons to give them some breathing space, and fixes a dark background on the pink theme (Found while testing that all themes worked properly with the `badge`)

Fix conformance compiler output title not showing

---

lib/compilers/argument-parsers.ts
test/compilers/argument-parsers-tests.ts

* For `nightly` Rust (and 1.88+), the output format of `--help` was changed in https://github.com/rust-lang/rust/pull/140152.
This PR changes the parser to parse the new format, so that edition overrides are selectable for `nightly` Rust. Note the `<>`:
```
--edition <2015|2018|2021|2024|future>
Specify which edition of the compiler to use when
compiling code. The default is 2015 and the latest
stable edition is 2024.
```
* Rust <= 1.34 (and >= 1.31) support the 2018 edition, but the help message only includes `--edition` in verbose mode.

Fix Rust edition argument parser

---

static/panes/stack-usage-view.ts

The stack usage view does not show the source code, only the stack usage lines:
With this PR, the code is shown:

Show source in stack usage view

---

etc/config/spirv.amazon.properties

Update the online version for SPIR-V and Slang compilers for the Vulkan 309 SDK to correspond with https://github.com/compiler-explorer/infra/pull/1611

Update SPIR-V and Slang version

---

etc/config/assembly.amazon.properties

Follow up to https://github.com/compiler-explorer/compiler-explorer/pull/7540.
Fixes #7528
Last time I tried this, the 14.2.0 GCC builds were still using 2.38 for Arm and AArch64, now there are 15.1.0 builds and those both use 2.44.
Which I have confirmed locally:
$ /opt/compiler-explorer/arm64/gcc-15.1.0/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-as --version
GNU assembler (GNU Binutils) 2.44
$ /opt/compiler-explorer/arm/gcc-15.1.0/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-as --version
GNU assembler (GNU Binutils) 2.44
While I'm here, I added 2.38 to Arm since it was missing. From the GCC 13.2.0 build:
$ /opt/compiler-explorer/arm/gcc-13.2.0/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-as --version
GNU assembler (GNU Binutils) 2.38

Assembly: Add new GNU AS versions for Arm and AArch64

---

lib/compilers/rust.ts

Make 2024 the default edition for Rust >= 1.85

---

static/main.ts

Fixes issues with missing components (e.g. from beta, 'explain')
The issue was that the exceptions are thrown in `initLayout`, not in the constructor.

Refactor startup to catch exceptions where they're thrown. 

---

etc/config/rust.amazon.properties

This PR adds the Rust crate **ahash** version 0.8.12 to Compiler Explorer.
Related PR: https://github.com/compiler-explorer/infra/pull/1633

Add Rust crate ahash v0.8.12

---

static/motd.ts

Fixes a subtle breakage from the bootstrap migration: The motd close button works for update/motds but not community ads. This PR cleans up the duplicate code and subsequent deviation.

Fix motd close button for community ads

---

etc/config/rust.amazon.properties

Needs https://github.com/compiler-explorer/tools/pull/14.
See https://github.com/compiler-explorer/compiler-explorer/issues/7772. This PR does not quite resolve that issue because C++ is also affected.

Switch back to `rustfilt` for Rust demangling

---

lib/compilers/pascal-utils.ts
lib/compilers/pascal-win.ts
lib/compilers/pascal.ts
test/pascal-tests.ts

The class doesn't hold any state, and it's only ever instantiated to call these functions. We might as well export them as regular functions
Unfortunately the git diff looks pretty horrible, but it's simply replacing each method with `export function` and deleting the class.

Replace PascalUtils class with top-level functions (NFC)

---

etc/config/raku.amazon.properties

by adding a (strictly speaking wrong) isSemVer=true and setting a SemVer prop based on the year.month.patch versioning that the releases have.
The decision to keep the "name" property instead of relying on baseName + SemVer is to keep the naming scheme as
Rakudo $version $backend instead of having the backend in the middle.

Sort rakudo versions newest-first

---

etc/config/rust.defaults.properties

The `clippy` configured in `rust.defaults.properties` is currently broken since `clippy-tool.ts` requires a `postcompilation` tool (https://github.com/compiler-explorer/compiler-explorer/commit/61715be49a88c5fb3d2bb25e05974049fe26c441).

Set correct tool type for local `clippy`

---

static/formatter-registry.ts
static/modes/rust-mode.ts

#7766 changed the Monaco language identifier for Rust, but missed a spot in `formatter-registry.ts`, so now Monaco can’t autoformat (right click → “Format Document”) Rust code any more.

Re-enable Monaco autoformatting for Rust

---

lib/compilers/lfortran.ts

More recent versions of LFortran use `LFORTRAN_LINKER` env var for linking, rather than `LFORTRAN_CC`.
Tested locally with 0.42 and 0.51

Add more recent LFortran linker flag

---

etc/config/c.amazon.properties
etc/config/execution.aarch64prod.properties
etc/config/execution.aarch64staging.properties

- removes config for firejail (unused, and doesn't exist on aarch64)
- copies execution config to aarch64prod, aarch64staging (as that's the path that is looked for by the environment)
- unifies c and c++ aarch64 config to "supportBinary" for aarch64 compilers

Aarch64 config fixes

---

static/panes/tool.ts
static/styles/explorer.scss
views/index.pug

Before #7797, elements such as “Toggle full version output” in the compiler version popup or the share buttons (“Short Link” etc.) would change the cursor to a pointer on hover (like normal links do), but this was lost when they were switched to use `link-primary`.
This PR restores the previous behaviour.

Add `cursor: pointer` to some clickable texts

---

test/compilers/argument-parsers-tests.ts

Add missing `await`s in Rust argument parser tests

---

static/hub.ts

I have no clue how Golden Layout ever picked this one up since the call to `registerComponent` passes a function that returns void...

Return the editor instance from codeEditorFactory

---

static/components.interfaces.ts
static/hub.ts

Removes all `any` return types from the factories, and infers the state type from the pane itself (except for tree which isn't a traditional pane)

Infer pane state from pane constructor

---

static/widgets/libs-widget.ts

Updated helper methods to return jQuery<HTMLElement> collections, eliminating unnecessary type casts.
Modified the favorites list creation to use the updated helper methods, ensuring consistent typing.
Revised the selected libraries display to insert library divs without type casts, aligning with the new typing approach.
Adjusted search result generation to utilize HTMLElement typing, streamlining the insertion of "no libraries" messages and library cards.
Ensured that the helper for inserting example links now expects jQuery<HTMLElement>, maintaining type consistency.
Tested with:
npm run ts-check
npm test
make check

Refactor Enhance Type Saftey in Library Elements

---

lib/parsers/asm-parser.ts
test/asm-parser-tests.ts

Ensured labels are not mistaken for comments by skipping comment filtering when the line matches a label definition
Added a regression test verifying that labels starting with “@” remain visible even when comment filtering is enabled
Fixes #7889 
Tested with 
npm run lint
npm run ts-check
npm run test-min
npm run check-frontend-imports
make check

Fix to ensure labels are not mistaken for comments

---

etc/config/hlsl.amazon.properties

This change adds the new DXC 1.8.2405 releases. This PR depends on the infra PR below being merged and compilers built:
https://github.com/compiler-explorer/infra/pull/1713

[HLSL] Add DXC 1.8.2505 releases

---

etc/config/fortran.amazon.properties

This PR adds the Fortran library **roots_fortran** version 1.5.0 to Compiler Explorer.
- GitHub URL: https://github.com/jacobwilliams/roots-fortran
- Package Manager: FPM (Fortran Package Manager)
Related PR: https://github.com/compiler-explorer/infra/pull/1688
---
_PR created with [ce-lib-wizard](https://github.com/compiler-explorer/ce-library-wizard)_

Add Fortran library roots_fortran v1.5.0

---

etc/scripts/docenizers/docenizer-avr.py
lib/asm-docs/generated/asm-docs-avr.ts
test/handlers/asm-docs-tests.ts

AVR instruction documentation has been broken since Microchip updated their manual URLs and PDF format. The docenizer would pull from outdated documentation circa 2021.
Changes:
Updated PDF URL to current 2024 manual location (aemDocuments path)
Fixed page number regex to match new footer format (DS40002198C - XX)
Added proper Unicode cleanup and quote escaping for generated TypeScript
Corrected import path in generated file
Updated test expectations for new URL format
All 116 AVR instructions now have working documentation links pointing to the correct pages in the 2024 manual. Generated TypeScript compiles without errors and all tests pass.
Verified that:
Documentation links work correctly
Generated code has no TypeScript errors
All existing tests pass with updated expectations
Manual …

Update AVR instruction documentation for 2024 manual

---

lib/compilers/nim.ts
test/nim-tests.ts

This PR addresses a crash caused by fs.rename() failing when moving output files across filesystems (or due to permissions), which previously led to an unhandled ENOENT error #7179 
Cause:
The NIM compiler writes intermediate files to a cache directory.
fs.rename() was used to move these files to the final output path.
fs.rename() fails across device boundaries or on permission errors.
The failure wasn’t handled, causing the process to crash.
Therefore a fallback mechanism was added to the file move process to prevent unhandled ENOENT crashes.
All NIM tests pass
ESLint passes
Additional test coverage to address this issue was added

Fix NIM compiler ENOENT error when moving cache files

---

lib/parsers/asm-parser-ptx.ts
test/asm-parser-tests.ts
test/filters-cases/ptx-example-more-complicated.asm.binary.directives.labels.comments.json
test/filters-cases/ptx-example-more-complicated.asm.directives.comments.json
test/filters-cases/ptx-example-more-complicated.asm.directives.json
test/filters-cases/ptx-example-more-complicated.asm.directives.labels.comments.json
test/filters-cases/ptx-example-more-complicated.asm.directives.labels.comments.library.dontMaskFilenames.json
test/filters-cases/ptx-example-more-complicated.asm.directives.labels.comments.library.json
test/filters-cases/ptx-example-more-complicated.asm.directives.labels.json
test/filters-cases/ptx-example-more-complicated.asm.directives.library.json
test/filters-cases/ptx-example-more-complicated.asm.none.json

Recogonize lines with predicate (e.g., `@%p1`, `@!%p1`) as instructions:
- `@%p1 ld.global.v4.b32 { %r9, %r10, %r11, %r12 }, [ %rd3 + 0 ];`
- `@%p2 bra $L__BB0_28;`
- `@!%p2 bra $L__BB0_28;`
| Before | After | 
| --- | --- |
| <img width="580" height="320" alt="image" src="https://github.com/user-attachments/assets/c3913b09-ce04-44c5-a4c0-fa69805cf1d7" /> | <img width="566" height="323" alt="image" src="https://github.com/user-attachments/assets/08308b3d-df00-4cf1-8321-203c374c27c3" /> |
From https://docs.nvidia.com/cuda/parallel-thread-execution/#instruction-statements: 
> Instructions have an optional guard predicate which controls conditional execution. The guard predicate follows the optional label and precedes the opcode, and is written as @p, where p is a predicate register. The …

Fix PTX parsing with predicate

---

etc/scripts/triton_wrapper.py

Fix issue with AMD by removing the dependency on lld (tested locally by moving `/usr/bin/ld.lld` and `/opt/rocm/llvm/bin/ld.lld`)
```
File "/opt/compiler-explorer/triton/v3.3.1/lib/python3.12/site-packages/triton/runtime/jit.py", line 347, in <lambda>
return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/compiler-explorer/triton/v3.3.1/lib/python3.12/site-packages/triton/runtime/jit.py", line 569, in run
kernel = self.compile(src, target=target, options=options.__dict__)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/compiler-explorer/triton/v3.3.1/lib/python3.12/site-packages/triton/compiler/compiler.py", line 230, in compile
key = …
```

[Triton] Fix AMD lld issue

---

etc/scripts/docenizers/docenizer-ptx-sass.py
lib/asm-docs/generated/asm-docs-sass.ts

In PR https://github.com/compiler-explorer/compiler-explorer/pull/7976, I forgot to handle the case where same instructions have different descriptions. This PR fixes the script and removes the duplicates from the generated file. 
The SASS docs are extracted from multiple tables from https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#instruction-set-reference. For example, 
- Table 4. Maxwell and Pascal Instruction Set
- ...
- Table 8. Hopper Instruction Set
- Table 8. Blackwell Instruction Set (wait...what? both tables are table 8? whatever...)
Previously, only the duplications for the (opcode, descriptions) pair were removed. In this PR, we only check the duplications based on the opcode and only keep the last one (based on the assumption that the newer ones are better). 
I …

Remove duplicates in SASS docs

---

lib/base-compiler.ts
static/panes/compiler.ts
static/panes/gccdump-view.interfaces.ts
static/panes/gccdump-view.ts
types/compilation/compilation.interfaces.ts
views/templates/panes/gccdump.pug

This option is undocumented, but has been around since 2010 for GCC 4.6.0

Add alias option for gcc tree/rtl viewer (#7985)

---

cypress/e2e/claude-explain.cy.ts
cypress/support/utils.ts

Address Copilot feedback by replacing `any` types with proper TypeScript types in Cypress test files.
**cypress/support/utils.ts:**
- `win: any` → `win: Cypress.AUTWindow`
- `$element: any` → `$element: JQuery<HTMLTextAreaElement>`
- `$body: any` → `$body: JQuery<HTMLElement>`
**cypress/e2e/claude-explain.cy.ts:**
- `req: any` → `req: Cypress.Interception` (3 instances)
- `url: any` → `url: string`
- Improves type safety and catches potential runtime errors at compile time
- Follows TypeScript best practices
- Addresses all Copilot suggestions for better code quality
- No functional changes, purely type improvements
All TypeScript checks pass and no functionality is affected.

Improve TypeScript type safety in Cypress tests

---

etc/config/assembly.amazon.properties

Bump Binutils version into 2.45 when using GCC 15.1.
The change form 2.44 into 2.45 includes some new assembler features, the details please check 
https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gas/NEWS;h=2e9538bd2736b4108cc5a383802c75f5feacfbc4;hb=2bc7af1ff7732451b6a7b09462a815c3284f9613

Bump Binutils version into 2.45 when using GCC 15.1.

---

etc/nsjail/compilers-and-tools.cfg
etc/nsjail/user-execution.cfg

This _maybe_ shows an issue - users could find _anything_ in cefs so we need to make sure we don't ever put privileged stuff in cefs.

Mount cefs into the jails

---

static/panes/editor.ts

Trying to solve the root cause:
`Editor.maybeEmitChange` calls `this.eventHub.emit('editorChange')`, and then `Compiler.onEditorChange` calls `this.compile()` .
So the idiom
```ts
this.maybeEmitChange();
this.requestCompilation();
```
repeated a few times in editor.ts, causes two rapid (and redundant) invocations of `compile`, which in turn cause the race.  This PR removes all calls to `Editor.requestCompilation` and in fact removes the function entirely.
@jeremy-rifkin  I'm guessing this is *not* the race you encountered mentioned in the source? (but might be wrong of course).
I'm guessing `maybeEmitChange` is a late addition to solve some other problems, and this race was an unintended side effect, but please correct me if you have better understanding of the code and its history.

Fix #8037: avoid duplicate `compile` call

---

static/panes/editor.ts

This fixes #8064 - hitting ctrl-enter worked _if compile on demand was set_. Otherwise the compiler ignored the editor change.
We still need to emit the change (else the compiler window and tools may not notice any changed text), but then if compile on demand is not on, we manually trigger a request.

Send a "request compile" if compile on demand isn't set

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/zig.amazon.properties

zig `0.15.1` released on 2025-08-19.
The corresponding infra PR: https://github.com/compiler-explorer/infra/pull/1785

Add zig 0.15.1 and make it the default zig compiler

---

etc/config/c++.amazon.properties

Hello. I would like to add new C++ library to CE. Meta-Encoder/Decoder (med) is a header only library with no dependencies and MIT license. Only requirement is compiler with C++ 20 support. https://github.com/cppden/med
Infra pull request: https://github.com/compiler-explorer/infra/pull/1808
I run "make", "make check" and tested the changes locally and it seems that everything is fine. By locally i mean using `c++.local.properties`. Screenshot as a proof:
I'm new to contributing, so please tell me if i did something wrong. Thank you for the CE!

Add new C++ library med

---

etc/config/spice.amazon.properties

Infra PR: https://github.com/compiler-explorer/infra/pull/1823
- Add Spice compiler version 0.22.4
- Use GCC 15.2.0 for demangling
- Use Clang 21.1.0 for linking

[Spice] Add version 0.22.4

---

etc/config/cuda.amazon.properties

Added nvcc and nvrtc for CUDA 13.0.0. Also fixed host compiler to gcc 14.1.0 on newest nvcc.
Depends on https://github.com/compiler-explorer/infra/pull/1797

Added nvcc 13.0.0 and nvrtc 13.0.0

---

etc/config/swift.amazon.properties

- adds support for the Swift 6.2 release compilers (x86 & cross-compiled arm)
- bumps the default Swift compiler to 6.2
depends on infra change: https://github.com/compiler-explorer/infra/pull/1834

[swift]: add 6.2 release compilers

---

etc/config/swift.amazon.properties

seems marginally easier to update with new versions this way

[swift][refactor]: sort compilers config entry in descending order

---

static/panes/opt-view.ts

Resolves #8109.
Using `.bind` creates a function that forwards all arguments, which means that the old `filters` state was passed as the `width` parameter to `showOptRemarks`, but `undefined` was expected.

Fix view zones after toggling opt-remark filters

---

etc/config/solidity.amazon.properties
etc/config/solidity.defaults.properties

Update Solidity compilers:
Related PR in infra: https://github.com/compiler-explorer/infra/pull/1837

Update Solidity solc and solx compiler versions
