- lib/csp.ts
> Port csp.js to ts, remove _ dep

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/902
> Rust 1.66.0

- lib/compilation-queue.ts
> Moving compilation queue to ts

- static/styles/themes/dark-theme.scss
- static/styles/themes/default-theme.scss
This was not present for some reason.
(Top is selected, bottom is active)
> Add select colours to ts-dropdown

- app.js
- lib/logger.ts
- test/utils-tests.js
Also redoes some pretty nasty morgan workarounds in favour of an actual real stream.
> TS-ify logger

- etc/config/c++.amazon.properties
https://github.com/josuttis/belleviews/tree/main/sources
> Add Josuttis' Belle Views to C++ compiler

- lib/parsers/asm-parser.ts
They were getting filtered out
Closes #4434
> Add .hword and .octa to datadef regex

- .eslintrc.yml
- lib/base-compiler.ts
- lib/options-handler.ts
- lib/tooling/base-tool.ts
- package-lock.json
- package.json
> Add lint rule for unused imports, and fix

- etc/config/c++.amazon.properties
> Add rollbear/strong_type library

- static/panes/cfg-view.ts
> Prevent default for zoom event in cfg

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Should also be added to C when it works
> add sqlite to cpp

- docs/API.md
> Add note about API not supporting external files

- package-lock.json
- package.json
> Bump to latest webpack because why not

- package-lock.json
- package.json
Tested locally, includes `npm update` for minor revisions.
> Hopefully uncontroversial bumpings

- docs/Roadmap.md
Comments welcomed. This is my thoughts on the priorities to 2023, what we did in 2021 and 2022.
> 2023 Roadmap

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Add new ACB 4.11.0 version.
fixes #4506
> Add new version of Kalray' KVX compiler

- lib/buildenvsetup/ceconan.ts
- adds error handlers for all streams
- catches exceptions raised in the non-trivial `entry` handler
- rejects in all cases
Partially addresses #4512
> Catch exceptions in tar handling

- lib/buildenvsetup/ceconan.ts
> Handle non-200s from conan

- examples/jakt/default.jakt
And make sure to cast the i32 to a c_int from the example function.
> jakt: Fix signature of default example's main

- lib/buildenvsetup/ceconan.ts
https://sentry.io/organizations/compiler-explorer/issues/3853263939/?project=102028&query=is%3Aunresolved&referrer=issue-stream
produced an uncaught exception
untested
> response undefined fix

- etc/config/c++.amazon.properties
> Add v8 of strong_type C++ lib

- etc/scripts/docenizers/docenizer-6502.py
- etc/scripts/util/contributorer.py
- etc/scripts/util/formatcheck.py
- etc/scripts/util/propscheck.py
credit to https://sourcery.ai/
> update some py scripts

- etc/config/crystal.amazon.properties
https://github.com/compiler-explorer/infra/pull/924
> Add Crystal 1.7.0

- lib/handlers/compile.ts
> Fix the cuda and microsoft compilation from /noscript

- static/panes/cfg-view.ts
- static/settings.ts
- static/widgets/site-templates-widget.ts
> Quick fixes for bugs noticed while testing

- static/panes/cfg-view.ts
> Fix size computation under display:none

- static/settings.ts
> Patch highlighting color scheme setting bug

- lib/handlers/health-check.ts
> Tsify lib/handlers/health-check

- lib/aws.ts
> Tsify lib/aws

- lib/base-compiler.ts
I want to log some timing info for compile requests to see how many fast compiles we get vs long 20s compiles. I'm concerned prometheus may introduce an averaging effect on the data so logging seems like a decent temporary solution.
> Collect timing metrics for compile requests

- docs/Privacy.md
- etc/scripts/parsed_pug_file.js
- static/generated/privacy.pug
> Update and fix link to MS privacy policy

- static/panes/gccdump-view.ts
- static/panes/pane.ts
> automatically fix old gccdump states

- .eslintrc.yml
- lib/base-compiler.ts
- lib/compilation-env.ts
- lib/compilation-queue.ts
- lib/compilers/dosbox-compiler.ts
- lib/handlers/compile.ts
While I was looking at this file I went ahead and tsified it
> Tsify compilation-env

- static/settings.ts
> Fix some value handling in settings

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/936
> Rust 1.67.0

- lib/parsers/asm-raw.ts
- lib/parsers/asmregex.ts
> Convert asm-raw to typescript

- lib/base-compiler.ts
Made up some buckets. We will have to keep an eye on how many metrics it makes
Tested locally with `--metricsPort`
> Use prometheus to record execution time and compile histograms

- lib/formatters/base.interfaces.ts
- lib/formatters/index.ts
- lib/handlers/formatting.ts
- static/styles/themes/dark-theme.scss
TypeScript code for handling formatter requests
> Tsify lib/handlers/formatting.js

- lib/compilers/hook.ts
- test/compilers/hook-tests.js
- add the `HOOK_HOME` to all interpreting.
cc @fabiosvm
> Fix up hoom_home for interpreting

- lib/parsers/asm-parser-beebasm.ts
- lib/parsers/asm-parser.ts
> tsify asm-parser-beebasm

- lib/parsers/asm-parser-dart.ts
- lib/parsers/asm-parser.ts
- types/features/filters.interfaces.ts
> Ts-ify dart

- lib/parsers/asm-parser-sass.ts
- test/utils.ts
> TSify sass

- lib/handlers/source.ts
> Fix the load/save button

- etc/config/c++.amazon.properties
> Bump rollbear/strong_type to v9 and v10

- lib/parsers/asm-parser-z88dk.ts
Will merge this once the tests pass, review for "fyi" :)
> TSify the z88dk parser

- lib/tooling/clang-format-tool.ts
> tsify clang-format-tool

- lib/tooling/clang-query-tool.ts
> tsify clang-query-tool

- lib/handlers/noscript.ts
> Tsify lib/handlers/noscript

- test/java-tests.ts
Kind of silly hack on the CompilerInfo but otherwise we have to add the remaining 50 fields..
> Tsify java-tests.js

- etc/scripts/docenizers/docenizer-java.sh
- etc/scripts/docenizers/docenizer-java.ts
- etc/scripts/docenizers/docenizer-llvm.sh
- etc/scripts/docenizers/tsconfig.json
> Tsify the java docenizer

- static/components.interfaces.ts
- static/components.ts
- static/panes/compiler.ts
> Fix tool conversion bugs

- lib/buildenvsetup/ceconan-rust.ts
For this issue: https://github.com/compiler-explorer/compiler-explorer/issues/4456
> Add check for triple

- etc/config/c++.defaults.properties
- etc/config/c.defaults.properties
(and clang-query default to c.defaults.properties)
> Add clang-tidy default tool to c/c++.defaults.properties

- lib/compilers/dmd.ts
- lib/compilers/ldc.ts
> fix: support for binaryObject for ldc and dmd

- tsconfig.backend.json
- typings/node-targz.d.ts
Addresses a tiny issue found in #4753
> fix: move typings to actually be registered

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
> Updated version of some jfalcou libraries

- static/panes/device-view.ts
> fix for device selection not saved in shared link

- lib/handlers/route-api.ts
- lib/properties.ts
- test/properties-test.ts
- test/sponsors-test.ts
- test/statenormalisation-tests.ts
- test/unfurl-tests.ts
- test/utils-tests.ts
- test/win-path-tests.ts
> Tsify a small handful of tests

- lib/parsers/llvm-pass-dump-parser.ts
> Handle another LLVM pass dump case

- .github/workflows/deploy-win.yml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-win.yml
- CONTRIBUTING.md
- README.md
- etc/scripts/find-node
Still assume node 16 compatibility for now.
> Bump used node version to 18

- lib/parsers/asm-parser-vc.ts
Resolves #4781. Remove the assertion, just allow the bad behavior silently. Same behavior as before the tsification.
> Remove an assertion now that we know the case can happen

- lib/base-compiler.ts
- lib/compilation-env.ts
Collecting raw data points for job time and queue time for a few days. Briefly discussed with Matt, will be reverting in a few days.
> Temporarily collect metrics on job time and queue time

- etc/config/c++.amazon.properties
This PR addresses the request made in #4777 .
* Ran `make check`, tests and linter pass the checks
* Added cereal library locally and tested with simple example
> added cereal serialization library

- examples/fortran/default.f90
integer reflects a more accurate example compared to other languages in the code
> Update default fortran example

- etc/config/d.amazon.properties
Infra https://github.com/compiler-explorer/infra/pull/952
> Add LDC 1.31.0 and make it the default D compiler

- lib/llvm-opt-transformer.ts
- package-lock.json
- package.json
- test/llvm-opt-transformer-test.ts
> Update to yaml and drop some unneeded deps

- views/menu-other.pug
Added Stats page to the "other" dropdown menu on the homepage. This closes #4812.
> added Grafana Stats page to other-menu

- etc/config/crystal.amazon.properties
> Update Crystal 1.7.0 -> 1.7.3

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/961.
> Rust 1.68.0

- etc/config/vb.amazon.properties
- etc/config/vb.defaults.properties
vb only supports latest, preview is invalid
> fix vb langversion

- package-lock.json
- package.json
- static/panes/compiler.ts
- static/panes/executor.ts
Tested locally; read release notes, all seems good.
> Bump to latest LRU library and use new clear() method

- static/main.ts
- static/panes/compiler.ts
- static/panes/tree.ts
- static/styles/explorer.scss
- static/styles/themes/dark-theme.scss
- static/styles/themes/default-theme.scss
- static/widgets/alert.ts
- static/widgets/load-save.ts
> Update error alert styling

- static/url.ts
Fixes #4555. Might also address #4817.
> Address lzstring decompress failure

- lib/handlers/route-api.ts
> Fix /clientstate/ 404 bug

- package-lock.json
- package.json
Checked notes and tested locally.
> Bump scroll into view

- package-lock.json
- package.json
Nothing scary in the release notes; did a quick spot check of the timings page.
> Bump to the latest chart.js

- .eslintrc.yml
> Re-enable import/no-cycle

- static/panes/compiler.ts
> Add a boundary check for the compiler context menu handler

- static/panes/editor.ts
Trying to figure out #4868, unless anyone has an idea how to repro locally
> Capture info to help triage an issue #4868

- etc/config/cuda.amazon.properties
Adds support for the NVIDIA CUDA 12.1 release
> Add CUDA 12.1

- etc/config/c++.amazon.properties
> add simdjson

- etc/config/c++.amazonwin.properties
- etc/config/c.amazonwin.properties
> Add 'mingw' to mingw compilerCategories

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Ref https://github.com/compiler-explorer/compiler-explorer/issues/4880
> Add new version of Kalray KVX compiler 4.12.0

- static/components.interfaces.ts
- static/components.ts
- static/main.ts
- static/panes/editor.ts
- static/panes/tree.ts
> Ensure a default language is provided for new editor panes

- etc/cewrapper/compilers-and-tools.json
- etc/cewrapper/user-execution.json
- etc/config/c++.amazonwin.properties
- etc/config/c.amazonwin.properties
- lib/compilers/win32-mingw-clang.ts
- lib/compilers/win32-mingw-gcc.ts
* Copied the limits from nsjail config
* Filters users options -lsomelib and puts them at the end of the options (too many libraries to fix with autodetect)
> Limits + windows linking

- etc/config/mlir.amazon.properties
- examples/mlir/default.mlir
Untested
https://github.com/compiler-explorer/infra/pull/976
> Add MLIR 16.0.0

- static/aprilfools2023.ts
- static/styles/explorer.scss
- views/index.pug
> Add a close button for the "Now in pink" banner

- static/colours.scss
- static/styles/themes/pink-theme.scss
- static/themes.ts
Fix selection, set a pink selection color, fix executor stdout, and fix the cursor position indicator.
Resolves #4926, resolves #4933
> A few pink mode fixes

- static/panes/compiler.ts
hotfix for https://github.com/compiler-explorer/compiler-explorer/issues/4936
> fix url includes for files used in tree

- README.md
I attempted to set up a multi-compiler CE instance in an offline environment. As a result, I added the steps for setting it up to the CE documentation.
> [doc] Add suggestions for deploying multiple compilers locally.

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- Adds latest release
- Add missing configuration to C compilers
> Updates configuration for xtensa compilers.

- lib/tooling/sonar-tool.ts
Forgot there were some hard-coded parts about the language in the URLs...
> Fix Sonar rule URLs for C

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
https://github.com/rollbear/trompeloeil/
> Added the latest versions of the Trompeloeil mocking fw

- static/panes/compiler.ts
- static/panes/executor.ts
> defer compilation by when still loading panes

- lib/tooling/sonar-tool.ts
> Sonar analysis: fix library usage

- static/panes/diff.interfaces.ts
- static/panes/diff.ts
To be able to diff device asm
Currently crippled by https://github.com/compiler-explorer/compiler-explorer/issues/4972 because the devices have to be dynamically loaded based on what the compilation results are.
> Device view diff

- etc/config/crystal.amazon.properties
> Add Crystal 1.8.1

- etc/config/typescript.amazon.properties
- etc/config/typescript.defaults.properties
Added TypeScript Native 0.0.26 alpha
> Added TypeScript Native 0.0.26 alpha

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/994.
> Rust 1.69.0

- etc/config/go.amazon.properties
Just like https://github.com/compiler-explorer/compiler-explorer/pull/3945 but for Go 1.20. Depends on https://github.com/compiler-explorer/infra/pull/991
> Add Go 1.20

- lib/tooling/clang-format-tool.ts
> Fix clang stdin bug

- static/panes/editor.ts
Fixes #4988, haven't tested locally as I don't have >50 languages installed locally
> Set maxOptions for the language select

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1004
> Add LDC 1.32.1 and make it the default D compiler

- etc/config/c++.amazon.properties
> Add Boost 1.82.0

- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
All reported by compiler discovery.
fixes #5004
> Fix wrong compiler exec

- etc/config/c++.amazon.properties
- etc/config/objc++.amazon.properties
> Add strong_type v11

- CONTRIBUTORS.md
- static/modes/cppfront-mode.ts
The test case: <https://highlight-cpp2.godbolt.org/z/9rnxdYzYW>.
> lang(cpp2): improve highlighting

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
ppc64, bpf and mips
needed for https://github.com/compiler-explorer/compiler-explorer/pull/5001
> fix categories for some clang compilers

- etc/config/circle.amazon.properties
- lib/buildenvsetup/_all.ts
- lib/buildenvsetup/base.ts
- lib/buildenvsetup/ceconan-circle.ts
Not glorious but seems to work locally.
CC @seanbaxter
> A somewhat hacky way of making circle link against clang trunk's libs

- etc/config/typescript.amazon.properties
- etc/config/typescript.defaults.properties
Added TypeScript compiler for Ubuntu 20.04 ver 0.0.27-alpha
> Added TypeScript Native 0.0.27 alpha

- static/compiler-service.ts
> Fix warning detection for wine msvc

- static/styles/explorer.scss
> Make compiler full version tooltips scrollable

- static/panes/editor.ts
> Better tab width handling

- static/styles/explorer.scss
only tested manually in chrome, not by running CE
> min width spon thing

- static/modes/cppfront-mode.ts
- static/themes.ts
This is the follow-up to #5027.
The test cases: <https://highlight-cpp2.godbolt.org/z/qrqYPvaWE>.
<details><summary>Preview</summary>
</details>
> feat: parse Cpp2 to highlight it

- static/main.ts
- static/styles/explorer.scss
> Egregiously overengineered fix for a niche UI bug

- lib/base-compiler.ts
- lib/compilers/argument-parsers.ts
- lib/compilers/clang.ts
> add support to query and parse c standard versions

- etc/config/mlir.amazon.properties
> add mlir-trunk

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1025
> Rust 1.70.0

- etc/config/cobol.amazon.properties
- etc/config/cobol.defaults.properties
- lib/compilers/gnucobol.ts
> fix intel notation for cobol

- lib/options-handler.ts
> no warning about paths if library version is autodetect

- etc/config/cobol.amazon.properties
- etc/config/cobol.defaults.properties
- lib/compilers/gnucobol.ts
> Fix cobol binary modes and objdump

- lib/compilers/assembly.ts
> bugfix asm arg overrides can be undefined

- lib/base-compiler.ts
> bugfix c vs c++ argparsing

- etc/config/c++.amazon.properties
Companion PR for https://github.com/compiler-explorer/infra/pull/1015.
> Add Kokkos C++ library

- lib/base-compiler.ts
> Keep track of compiler and exec queue time

- lib/compilers/mlir.ts
Fix for 
https://github.com/compiler-explorer/compiler-explorer/issues/5092
> Update mlir.ts for issue #5902

- docs/SupportedEmulators.md
- lib/asm-docs/arm.ts
- package-lock.json
- static/styles/explorer.scss
- static/styles/themes/dark-theme.scss
- static/styles/themes/default-theme.scss
- static/styles/themes/pink-theme.scss
- webpack.config.esm.ts
- npm update
- bump the webpack version as usually that needs it
- re-run eslint
- re-run format
> Bump all deps

- static/panes/conformance-view.ts
Fixes #5119 where a type error happens during page load
> Fix conformance view state bug

- static/panes/compiler.ts
> add floating point representation for numeric tooltip

- static/panes/editor.ts
> Check for clipboard support better

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> `fmt/10.0.0` added + circle revisions synced with the rest

- etc/config/c.amazon.properties
> Fix C arduino arguments

- lib/handlers/compile.interfaces.ts
- lib/handlers/compile.ts
- views/noscript/compiler.pug
> Filter ansi escape codes in noscript

- static/panes/editor.ts
- static/panes/executor.ts
Fixes #4868
This took so long to track down. I am convinced `@ts-expect-error` is *always an error*.
> Fix longstanding issue TypeError: e.map is not a function

- static/styles/explorer.scss
- views/_layout.pug
> Fix color scheme flash on page load for pink theme

- static/panes/editor.ts
> Fix word wrapping bug

- lib/asm-docs/amd64.ts
> Fix movabs asm docs bug

- etc/config/csharp.amazon.properties
- etc/config/csharp.defaults.properties
- etc/config/fsharp.amazon.properties
- etc/config/fsharp.defaults.properties
- etc/config/vb.amazon.properties
- etc/config/vb.defaults.properties
related to https://github.com/compiler-explorer/infra/pull/1033
> dotnet 6.0.18 and 7.0.7

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
Depends on installing new compilers: https://github.com/compiler-explorer/infra/pull/1038
> add oneapi 2023.0.0 & 2023.1.0

- lib/base-compiler.ts
> Don't try to build and execute if the initial build failed

- static/tests/motd.ts
- views/_layout.pug
> Fix CE not working without internet

- lib/base-compiler.ts
- lib/exec.ts
- lib/llvm-opt-transformer.ts
- test/exec-tests.ts
- types/execution/execution.interfaces.ts
> Fix handling when the opt output is truncated

- lib/base-compiler.ts
- static/panes/ast-view.ts
- static/panes/cfg-view.ts
- static/panes/device-view.ts
- static/panes/diff.ts
- static/panes/flags-view.ts
- static/panes/gccdump-view.ts
- static/panes/gnatdebug-view.ts
- static/panes/gnatdebugtree-view.ts
- static/panes/haskellcmm-view.ts
- static/panes/haskellcore-view.ts
- static/panes/haskellstg-view.ts
- static/panes/ir-view.ts
- static/panes/llvm-opt-pipeline.ts
- static/panes/opt-view.ts
- static/panes/output.ts
- static/panes/pane.interfaces.ts
- static/panes/pane.ts
- static/panes/pp-view.ts
- static/panes/rusthir-view.ts
- static/panes/rustmacroexp-view.ts
- static/panes/rustmir-view.ts
- static/panes/stack-usage-view.ts
- static/panes/tool-input-view.ts
- static/panes/tool.ts
- types/compilation/compilation.interfaces.ts
> Improve pane typing

- lib/compilers/nvcc.ts
> resolve #5014

- etc/config/c.amazon.properties
- lib/base-compiler.ts
- lib/compilers/_all.ts
- lib/compilers/movfuscator.ts
Resolves #985
Builder: https://github.com/compiler-explorer/misc-builder/pull/65
Infra: https://github.com/compiler-explorer/infra/pull/1041
> Add the movfuscator

- lib/exec.ts
> resolve #4330

- etc/config/c++.amazon.properties
- fix a typo and use correct kokkos version
- drop `trunk` as it is not used in `infra`
> Use correct kokkos version and `packagedheaders=true`

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
> gcc: add native gcc 10.5.0

- etc/scripts/util/propscheck.py
> propcheck: skip local properties

- CONTRIBUTORS.md
- lib/exec.ts
- test/exec-tests.ts
A fix for https://github.com/compiler-explorer/compiler-explorer/issues/5233
> Add a line break before kill

- static/main.ts
- static/styles/explorer.scss
* Disable custom color and just use regular theme colors
* Disable inline text for now, doesn't look right with MOTD
> Fix link datetime layout

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1054.
> Rust 1.71.0

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1053.
> kokkos 4.1.00

- etc/config/crystal.amazon.properties
> Add Crystal 1.9.2 / 1.8.2

- docs/WhatIsCompilerExplorer.md
I like the new "what is compiler explorer" very much. Thank you for doing it. I did a little bit of wordsmithing as I thought the intro needed some ironing out.
> Wordsmithing "What is compiler explorer?"

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
For 22 targets that already have 13.1.
fixes #5283
> Add cross gcc 13.2

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1064
> Add LDC 1.33.0 and make it the new default d compiler

- etc/config/c++.amazon.properties
- lib/compilers/_all.ts
- lib/compilers/nvcpp.ts
Fixes #5217
[Local testlink](http://127.0.0.1:10240/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAAzBqkAA6oCoRODB7evnrJqY4CQSHhLFEx8baY9vkMQgRMxASZPn5cFVXptfUEhWGR0XEJCnUNTdmtQ109xaUDAJS2qF7EyOwc5rHByN5YANQmsW5iwCSECCz72CYaAILrm9uYeweYqpjIXtUXV7dmGwxbXl2%2BzcADc3kRiF8bnd/g8nm5kAhiAJUFCfn8AUCDsRDMBMAo0TDMY9gU4hsRMKxCTcvKkjDstgBrAD6BCeABEdkN0CAUEiUbyhpT0ABPZlbVDIRn7Kw0unAHboJasjlcgg8vnIhioXlKnGfA7oRYRehfWKy67MNgKRJMFZqrGc7m8l5vD7pGXfK342327kg1XOkAgvCYADuBPN32%2BwTZLCYwQgsz2AHYLTsMztYztQqquGAOBoiwWixpPTdMw7eWCHCRSYILjtVBBQvMdiKW7Ny9dK9mmKqzN3K0GaLRaMyGBBuewQLbiMyvAwlABHUhNgB06CYdSTa9Ca64XajFczI7o48n095c4XS8wq/bm%2B3TF3OYPR/TmaYH1Qaq6qqZVleW1MMkyHU91V5fh50pREJyndUZxvRcVzXf1eScHc …
> Nvc++ deviceview support

- CONTRIBUTORS.md
- etc/config/cobol.amazon.properties
infra PR at https://github.com/compiler-explorer/infra/pull/1071
> cobol: GnuCOBOL 3.2

- etc/config/c++.amazon.properties
More context in https://github.com/compiler-explorer/infra/issues/1070
> ClangIR enabled clang support

- etc/config/go.amazon.properties
Just like #4970 but for Go 1.21. Depends on compiler-explorer/infra#1067
> Add Go 1.21

- etc/config/cobol.amazon.properties
> fixed missing adjustment of GnuCOBOL default

- etc/config/analysis.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/clean.amazon.properties
- etc/config/cppx.amazon.properties
- etc/config/cppx_blue.amazon.properties
- etc/config/cppx_gold.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/haskell.amazon.properties
- etc/config/ispc.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- etc/config/swift.amazon.properties
- etc/config/zig.amazon.properties
Updated OSACA from v0.5.0 to v0.5.2
> updated OSACA version to v0.5.2

- etc/config/ispc.amazon.properties
ISPC v1.21.0 has been released. Related change: https://github.com/compiler-explorer/infra/pull/1075
> Add ISPC v1.21.0

- lib/compilers/dotnet.ts
limitations:
* linux-x64 only
* no execution support
all of which can be added later after this initial support
> add dotnet aot support for linux-x64

- etc/config/c.amazon.properties
Adding compiler hosted here: https://github.com/xavierrouth/C-LC3-Compiler for educational use.
> Add LC3 C compiler.

- etc/cewrapper/compilers-and-tools.json
> [win] enable appcontainer for compilers

- etc/config/c++.amazon.properties
> Add Boost 1.83.0

- etc/config/c++.amazon.properties
Close https://github.com/compiler-explorer/compiler-explorer/issues/5380
The infra part was introduced in
https://github.com/compiler-explorer/infra/pull/1072
> [Library Request] Add async_simple library

- etc/config/c++.amazon.properties
.so needed by QT, but also useful for other things I suppose
> Add lib pcre2

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1092
> Add LDC 1.34.0 and make it the new default

- etc/config/java.amazon.properties
https://jdk.java.net/21
For https://github.com/compiler-explorer/infra/pull/1094.
> Add JDK 21

- etc/config/c++.amazon.properties
On top of https://github.com/compiler-explorer/compiler-explorer/pull/5500.
> LLVM 17 Clang Assertions

- etc/config/rust.amazon.properties
Followed instructions in https://github.com/compiler-explorer/infra/blob/main/docs/adding_rust_crates.md.
This is the partner PR to https://github.com/compiler-explorer/infra/pull/1019
> add_rust_dashmap_crate Added dashmap crate version 5.4.0.

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> mp-units 2.0 and fmt 10.1.1 added

- CONTRIBUTORS.md
- docs/API.md
ForCompile - A Fortran library to access the API.
by gha3mi.
> Add ForCompile project to API.md. (#5516)

- .github/workflows/deploy-win.yml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-win.yml
- CONTRIBUTING.md
- Makefile
- README.md
- compiler-args-app.ts
- docs/AddingASiteTemplate.md
- etc/scripts/build-dist-win.ps1
- etc/scripts/build-dist.sh
- etc/scripts/docenizers/docenizer-java.sh
- etc/scripts/docenizers/docenizer-llvm.sh
- etc/scripts/find-node
- package.json
- works both v18 and v20
- see https://github.com/TypeStrong/ts-node/issues/1997
> Replace ts-node-esm with direct calls to node to support node 20

- etc/config/c++.amazon.properties
> cxx-variadic-friends: add ce changes for experimental branch

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1109
> Rust 1.73.0

- CONTRIBUTING.md
- docs/API.md
- lib/parsers/asm-parser.ts
- package-lock.json
- webpack.config.esm.ts
also run the lint and format nonsense
> Bump all the things forward

- etc/config/c++.amazon.properties
https://github.com/compiler-explorer/infra/pull/1110
> Add cpptrace

- etc/config/c++.amazon.properties
> Add NVIDIA HPC SDK 23.9 to etc/config/c++.amazon.properties

- etc/config/julia.amazon.properties
Companion to https://github.com/compiler-explorer/infra/pull/1118.  I tried to look to other similar PRs to update other toolchains, I hope I'm doing it right.
> Add Julia v1.9.3

- etc/config/crystal.amazon.properties
> Add Crystal 1.10.1

- lib/parsers/llvm-pass-dump-parser.ts
- test/llvm-pass-dump-parser-tests.ts
> support new IR Dump header

- lib/compilers/crystal.ts
Crystal 1.9+ has made the `.s` and `.ll` files follow the base name of the output rather than the input (I think this is due to crystal-lang/crystal#13370), this PR matches the Crystal compiler's behavior
> Fix Crystal assembly and LLVM IR output on 1.9+

- etc/config/hylo.amazon.properties
- lib/base-compiler.ts
- lib/compiler-finder.ts
- lib/compilers/hylo.ts
- types/compiler.interfaces.ts
> Hylo fixes; specify PATH, and fix name

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
* Add spdlog 1.9.2, 1.10.0, 1.11.0, 1.12.0
> Support latest versions of spdlog

- lib/compilers/hlsl.ts
Since DXC is a fork of Clang from LLVM 3.7, the AST can be generated and parsed in a manner similar to the Clang AST.
> Add AST viewer support for HLSL/DXC

- etc/config/solidity.amazon.properties
Ref https://github.com/compiler-explorer/infra/pull/1130
> Add Solidity 0.8.21

- lib/exec.ts
Addresses issue in https://github.com/compiler-explorer/compiler-explorer/issues/5655
> Execution hotfix

- lib/compilers/dotnet.ts
> Fix crossgen2 compilation

- lib/compilers/dotnet.ts
Always get the version string for dotnet so that the version string won't be cached per godbolt server instance.
/cc: @mattgodbolt This can fix the version issue we discussed on discord.
> Always get version string for dotnet

- lib/base-compiler.ts
- lib/compilers/clean.ts
> store exec+sandbox types

- etc/config/nim.amazon.properties
Related https://github.com/compiler-explorer/infra/pull/1138
> Add Nim version 1.6.16 and 2.0.0, use newer gcc

- etc/config/c++.amazon.properties
This adds a prototype implementation of https://open-std.org/JTC1/SC22/WG21/docs/papers/2023/p2961r0.pdf
>  Add contracts-nonattr

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> Added Trompeloeil v46

- static/panes/editor.ts
- static/panes/executor.ts
- test/cfg-cases/cfg-llvmir.invoke.json
- test/cfg-cases/cfg-llvmir.loop.json
> Fix shared state close issue

- etc/config/swift.amazon.properties
See also: https://github.com/compiler-explorer/infra/pull/1143
> Add Swift 5.9 release and Swift 5.10 nightly

- package-lock.json
- package.json
- webpack.config.esm.ts
- npm upgrade
- npm install latest sonarjs (which was "breaking" semantically but didn't seem to be)
- bump the js webpack version out of paranoia
- test
- run lint and format
> Upgrade all the things

- lib/compilers/snowball.ts
> Fixed CLI args for snowball

- package-lock.json
- package.json
- static/panes/diff.ts
- static/panes/llvm-opt-pipeline.ts
- static/widgets/compiler-picker.ts
Worked just fine in local testing!
> Bump to latest tom-select. Thanks @oyejorge

- etc/config/ispc.amazon.properties
ISPC v1.22.0 has been released. Related change: https://github.com/compiler-explorer/infra/pull/1154
> Add ISPC v1.22.0

- etc/config/c++.amazon.properties
- etc/config/cuda.amazon.properties
Add HPC SDK 23.11 to etc/config/c++.amazon.properties
Add CUDA 12.3 to etc/config/cuda.amazon.properties
> Changes for NVIDIA HPC SDK 23.11

- lib/compilers/dotnet.ts
- lib/handlers/formatting.ts
- package-lock.json
- static/panes/editor.ts
- static/rison.ts
> Bump remaining deps

- lib/compilers/snowball.ts
> Changed exec to exe for snowball

- etc/config/c3.amazon.properties
- lib/compilers/c3c.ts
c3c compiler version 0.5 (alpha) added.
> New C3 compiler added

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1160.
> kokkos `4.2.00`

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
Adds [taskflow](https://github.com/taskflow/taskflow) as a C++ library.
Related PR: https://github.com/compiler-explorer/infra/pull/1164
Note:
taskflow is a General-purpose Parallel and Heterogeneous Task Programming System.
taskflow helps users quickly write parallel and heterogeneous task programs in modern C++.
taskflow has been widely used in many companies and academic institutes, like Cruise, Nvidia, AMD, NSF, etc.
taskflow has appeared in various C++ conferences, including [CppCon'20](https://www.youtube.com/watch?v=MX15huP5DsM) and [MUC++](https://www.youtube.com/watch?v=u8Mc_WgGwVY)
> Add taskflow

- lib/aws.ts
- lib/s3-handler.ts
- lib/storage/s3.ts
- package-lock.json
- package.json
- test/_setup-fake-aws.ts
Also errors early if we can't get them at all, and configures retries and timeouts
Mitigation for #5813
> Cache AWS creds at startup and reuse

- etc/config/c++.amazon.properties
- etc/config/objc++.amazon.properties
> Add strong_type v13

- lib/compilers/ldc.ts
> fix ldc llvmir

- etc/config/c++.amazon.properties
> Add EDG experimental reflection entry

- etc/config/dart.amazon.properties
Follow-up to https://github.com/compiler-explorer/infra/pull/1179
> Surface Dart 3.2 release

- etc/config/c++.amazon.properties
`make check` passes; tested the new library with `./ce_install` and `make dev`.
Corresponding infra PR: https://github.com/compiler-explorer/infra/pull/1180
> Add dsharlet/array library

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1184
> Update LDC to 1.35.0

- etc/config/c++.amazon.properties
Relates to [this](https://github.com/compiler-explorer/infra/pull/1176)
> Update entt to latest minor and patch versions

- etc/config/c++.amazon.properties
> Change the compiler label for EDG Default 6.5

- app.ts
- lib/compilers/d8.ts
- lib/global.ts
> Add the HandlerConfig type to the global handler config

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-frontend.yml
> Move runners to 22.04. Partially subsumes #4950

- etc/config/c++.amazon.properties
> Update c++.amazon.properties for EDG 6.6

- etc/config/c++.amazon.properties
Add [Glaze](https://github.com/stephenberry/glaze) JSON library
> Add Glaze library

- etc/config/compiler-explorer.amazonwin.properties
depends on https://github.com/compiler-explorer/infra/pull/1198
> move cmake to local disk

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1200
> Rust 1.75.0

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> Added Trompeloeil v47

- etc/config/julia.amazon.properties
Companion PR to https://github.com/compiler-explorer/infra/pull/1201.
> Add Julia v1.10.0

- etc/config/c++.amazon.properties
> Add Boost 1.84.0

- lib/compilers/pony.ts
Following the discussion in #3864.
@RossSmyth  FYI
> Stop forcing debug builds in `pony`

- etc/config/crystal.amazon.properties
> Add Crystal 1.11.1

- etc/config/c++.amazon.properties
More context in https://github.com/compiler-explorer/infra/pull/1209
> Add vast-trunk compiler

- static/multifile-service.ts
> Fix bug when loading zip file

- lib/compilers/dex2oat.ts
Most importantly sets the current working directory to the temp dir for the users' code so the needed files can be written to disk.
> Dex2oat error handling and fixes

- etc/config/c.amazon.properties
close compiler-explorer/compiler-explorer#4561
> Add SDCC 4.2.0 and SDCC 4.3.0

- app.ts
- lib/base-compiler.ts
- lib/compilers/d8.ts
- lib/compilers/dex2oat.ts
- lib/compilers/java.ts
- lib/compilers/kotlin.ts
- lib/handlers/route-api.ts
This PR populates types in the HandlerConfig
> Improve typings for the now-global HandlerConfig

- etc/config/c++.amazon.properties
Forgot some config in f3277b8aed2ca12ce961d08ef792c4061a3331ac.
fixes #5943
> icc: workaround bug in libstdc++ (#5984) (cont)

- static/colour.ts
- static/panes/ast-view.ts
- static/panes/compiler.ts
- static/panes/device-view.ts
- static/panes/editor.ts
- static/panes/ir-view.ts
- static/panes/opt-view.ts
- static/panes/stack-usage-view.ts
…in favor of createDecorationsCollection.
Minor drive-by cleanups.
> Remove usage of the depracated monaco.IEditor deltaDecorations

- lib/compilers/dex2oat.ts
> Override getVersion() for dex2oat

- static/panes/diff.ts
- static/panes/flags-view.ts
Fixes #6088 
Changes the createEditor implementations that were missed in https://github.com/compiler-explorer/compiler-explorer/pull/6078
> fix missing createEditor changes

- etc/config/c++.amazon.properties
Fixed issues in first PR
Add HPC SDK 24.1 to  etc/config/c++.amazon.properties
> Changes for NVIDIA HPC SDK 24.1 #2

- lib/compilers/dex2oat.ts
> Update dex2oat version string

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1230.
> Rust 1.76.0

- .github/labeler.yml
Now it will work, I am pretty sure ;)
> Fix labeler config - part 2

- package-lock.json
- package.json
https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0460
> Bump forward to new monaco, which is exclusively bug fixes

- etc/config/spice.amazon.properties
Add Spice version 0.19.3
Infra PR: https://github.com/compiler-explorer/infra/pull/1240
> [Spice] Add version 0.19.3

- etc/config/ispc.amazon.properties
ISPC v1.23.0 has been released. Related change: https://github.com/compiler-explorer/infra/pull/1238
> Add ISPC v1.23.0

- lib/compilers/spice.ts
This should speed up the compilation of Spice code. Before, the whole compilation (including linking) was done, even if only the IR dump was requested. Now there is the `--abort-after-dump` option, that will avoid that.
Furthermore I noticed that the IR dump was also active when (if I understand it correctly) we only want to dump assembly.
> [Spice] Abort compilation after dump

- docs/AddingACompiler.md
Addresses https://github.com/compiler-explorer/compiler-explorer/issues/3680
> Doc update

- static/panes/ast-view.ts
- static/panes/ir-view.ts
> type might not be what it says

- lib/compilers/pythran.ts
> fix pythran wrt ldpath

- static/panes/compiler.ts
And change 'toggle' to 'hide' to better express the intention.
Fixes #6225.
> Fix an element on('dragstart') applies to

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
I really need to think about how to improve this...
> Add the missing clang 18s

- etc/scripts/docenizers/docenizer-riscv64.py
- lib/parsers/dex2oat-pass-dump-parser.ts
> chore: remove repetitive words

- etc/config/c++.amazon.properties
Add HPC SDK 24.3 to etc/config/c++.amazon.properties
> Changes for NVIDIA HPC SDK 24.3

- static/monaco-config.ts
Should disable "sticky scroll" until we have a setting for it:
https://microsoft.github.io/monaco-editor/docs.html#variables/editor.EditorOptions.html
https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IEditorStickyScrollOptions.html
> Attempt to disable sticky scroll

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1256.
> Rust 1.77.0

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Solve the issue mentioned here: https://github.com/compiler-explorer/compiler-explorer/pull/6228#issuecomment-2005622875
@partouf
> Explicitly specify c++filt as demangler for clang bpf

- lib/tooling/llvm-mca-tool.ts
> Refuse to run llvm-mca with "Compile to binary object"

- .github/ISSUE_TEMPLATE/compiler_request.yml
- .github/ISSUE_TEMPLATE/language_request.yml
- .github/ISSUE_TEMPLATE/library_request.yml
Replaces an earlier PR about this - I made some local git mess and had to redo it.
> Nudge towards contributions in the templates for language/compiler/library requests 

- etc/config/c++.amazon.properties
- etc/config/objc++.amazon.properties
> Add strong_type v14

- etc/config/spice.amazon.properties
Add Spice version 0.19.5.
Infra PR: https://github.com/compiler-explorer/infra/pull/1257
> [Spice] Add version 0.19.5

- etc/config/julia.amazon.properties
Should fix https://github.com/compiler-explorer/infra/issues/1260.  Corresponding PR in infra at https://github.com/compiler-explorer/infra/pull/1261 by @partouf.
> Add julia nightly compiler

- lib/base-compiler.ts
> Filter linker switches to avoid bogus warnings

- etc/config/go.amazon.properties
Just like #5374 but for Go 1.22.1.
Depends on compiler-explorer/infra#1263
> Add Go 1.22

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1265
> Add LDC 1.37.0 and make it the default D compiler

- static/styles/themes/custom-golden-layout-themes/one-dark.scss
- static/styles/themes/one-dark-theme.scss
Fixed:
- Dropdown menu disabled color
- Dropdown menu active color
- General panel background color
- Separator line for minimap
- Output text-count color
- Remove pure white across theme
- Fix custom-select in popout
> Correct several colors in one dark

- etc/scripts/build-dist.sh
Adds support without having to npm i on an arm runner
> Start aarch64 support

- lib/parsers/asm-parser.ts
- test/android-tests.ts
- test/base-compiler-tests.ts
- test/compilers/hook-tests.ts
- test/demangler-tests.ts
- test/exec-tests.ts
- test/filter-tests.ts
- test/filters-cases/bug-1229.asm.directives.labels.comments.library.dontMaskFilenames.approved.txt
- test/handlers/api-tests.ts
- test/library-tests.ts
- test/tool-tests.ts
> fix part of the windows tests

- test/asm-parser-tests.ts
- test/filter-tests.ts
> attempt to disable filter-tests for windows

- etc/config/swift.amazon.properties
https://github.com/compiler-explorer/infra/pull/1278
> Make Swift 5.10 not nightly

- etc/config/hlsl.amazon.properties
Took a few dot releases to stabilize, but now that it is stable we should default to the newest release.
> Update the default DXC to the latest release.

- lib/compilers/d8.ts
Allows for compilation errors in the source code to be inspected when using D8 or dex2oat.
> Propagate java/kotlin errors to D8

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1275.
> Kokkos `4.3.0`

- lib/stats.ts
- package-lock.json
- package.json
- enhanced-ms and fix
- css-loader
- vitest
> Major bumps

- etc/config/hlsl.amazon.properties
Reguires https://github.com/compiler-explorer/infra/pull/1277
> Add RGA 2.9

- lib/llvm-opt-transformer.ts
- static/panes/opt-view.interfaces.ts
- static/panes/opt-view.ts
- static/styles/themes/dark-theme.scss
- static/styles/themes/default-theme.scss
- static/styles/themes/one-dark-theme.scss
- static/styles/themes/pink-theme.scss
> Opt remarks: replace hover-over-sidebar display with inline text

- lib/stats.ts
- test/stats-test.ts
Should fix https://github.com/compiler-explorer/infra/issues/1284
> Fix duplicated filters in logging

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1288
> [Spice] Add version 0.19.6

- package-lock.json
- package.json
> Update to Monaco 0.48

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1290.
> Rust 1.78.0

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/modula2.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
- etc/config/rust.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6446
> Add GCC 14.1 for native (intel)

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
For 8 different languages.
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6406
> Add 21 cross compilers for GCC 14.1

- lib/compilers/dex2oat.ts
profman was previously running from the wrong place, leading artifacts to not be written/read correctly. This change also replaces usages of 'tmpDir' with 'd8DirPath' for specificity.
> Update customCwd for profman in dex2oat

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
see https://github.com/compiler-explorer/gcc-cross-builder/pull/68
> add GCC arm64 4.9.4 and 5.5.0

- .github/workflows/test-frontend.yml
Seems like a decent thing to do. cypress should already be using node 20 though
> Bump to v6 cypress run config

- static/panes/opt-view.interfaces.ts
- static/panes/opt-view.ts
- views/templates/panes/opt-view.pug
I thought I already added it but seems I didn't.
> Add 'wrap lines' button to opt-view

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6229
> Add latest Kalray compiler: ACB 5.0.0

- etc/config/ada.amazon.properties
- etc/config/d.amazon.properties
- etc/config/objc++.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6456
> Loongarch64: add support for Ada, D and Objective-C++

- etc/config/c++.amazon.properties
> fix: path for tools for arm-unknown 13.2 we wrong

- etc/config/c++.amazon.properties
[jwt-cpp](https://github.com/Thalhammer/jwt-cpp) is a C++11 header only library for parsing, validating and signing json web tokens. It supports a wide range of different cryptography and json libraries and implements all currently standardised signing algorithms.
> Add jwt-cpp C++ library

- etc/config/c++.amazon.properties
> Add @hanickadot's p3068 constexpr exceptions branch

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1306
> Add LDC 1.38.0 and make it the default D compiler

- etc/config/c++.amazon.properties
Fix missing `v` prefix in include paths.
> Fix jwt-cpp include paths

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/modula2.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
> Add GCC 13.3.0 native

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
> Add 23 cross GCC 13.3

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/objc.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6406
> Add GCC 14.1 for sparc-leon

- lib/base-compiler.ts
- static/event-map.ts
- static/panes/compiler.ts
> Remove unused events `filtersChange`, `requestFilters`, some added types to `BaseCompiler.compile`

- etc/config/ispc.amazon.properties
ISPC v1.24.0 has been released. Related change: https://github.com/compiler-explorer/infra/pull/1316
> Add ISPC v1.24.0

- lib/cfg/cfg-parsers/llvm-ir.ts
> Fix llvm-ir-cfg: `callbr` might be multiline, AND might start with `%1 =`

- etc/config/spice.amazon.properties
Add version 0.20.0 of the Spice compiler
Infra PR: https://github.com/compiler-explorer/infra/pull/1313
> [Spice] Add version 0.20.0

- etc/config/cuda.amazon.properties
> Update cuda.amazon.properties for CUDA 12.4u1

- lib/compilers/java.ts
- lib/compilers/kotlin.ts
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/6547
> fix kotlin execution result when compilation fails

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1320
> [Spice] Add version 0.20.1

- static/styles/themes/ansi-dark.scss
- static/styles/themes/dark-theme.scss
- static/styles/themes/one-dark-theme.scss
> Use improved ansi colors for one dark pro

- .github/renovate.json
> Tell renovate to back off a bit

- static/panes/executor.ts
- static/styles/explorer.scss
> Horizontal scroll the entire execution pane

- static/panes/compiler.ts
This is a proposed fix for #6516
> Remember scroll position on recompile

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1328
> [Spice] Add version 0.20.2

- etc/config/c++.amazonwin.properties
- etc/config/c.amazonwin.properties
> Add aliases for 19_38

- etc/config/c++.amazonwin.properties
- etc/config/c.amazonwin.properties
> Fix alias...again

- etc/config/c++.amazon.properties
- etc/config/cuda.amazon.properties
> Add clang-rocm 6.0.2 and 6.1.2 for C++

- etc/config/c++.amazon.properties
Companion PR:
* https://github.com/compiler-explorer/infra/pull/1343
> Add CLI11 version 2.4.2

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
12.4 config for native and 20 cross GCC.
For https://github.com/compiler-explorer/compiler-explorer/issues/659
> Add GCC 12.4 for native and cross

- lib/compilers/rustc-cg-gcc.ts
Fix lib path.
refs https://github.com/compiler-explorer/compiler-explorer/issues/5342
> Unbreak rustc_cg_gcc

- etc/config/c++.amazonwin.properties
> Set instruction sets for msvc compilers

- etc/config/c++.amazon.properties
> Fix objdumper for clang arm64

- etc/config/c++.amazon.properties
> Add @je4d's p1974 clang

- etc/config/c++.amazon.properties
Specific versions added:
- 2024.1.0.468
- 2024.2.0.495
Needs [this PR](https://github.com/compiler-explorer/infra/pull/1349) to be merged.
> Added Intel OneAPI 2024.1 and 2024.2

- etc/config/wasm.amazon.properties
- etc/config/wasm.defaults.properties
👋 Hey,
This PR adds the two latest major versions for wasmtime.
Related infra PR: https://github.com/compiler-explorer/infra/pull/1350
> Add wasmtime versions 21.0.1 and 22.0.0

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> mp-units 2.2.0 + fmt 11.0.0

- etc/config/d.amazon.properties
infra: https://github.com/compiler-explorer/infra/pull/1356
> Add LDC 1.39.0 and make it the default D compiler

- static/settings.ts
> Increase defaultDelayAfterChange to 2s

- static/widgets/fontscale.ts
> Make scroll-up increase the font size and scroll-down decrease it

- static/settings.ts
> After a 10 day experiment, decrease defaultDelayAfterChange back

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> Add strong_type v15 and Trompeloeil v48

- etc/config/c++.amazon.properties
Follows up on changes in https://github.com/compiler-explorer/infra/commit/45858d90667bb166e90c78bbf339fe2dc49291e2
> replace mfem trunk with 4.7

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1370.
> Rust 1.80.0

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1371
> [Spice] Add version 0.20.3

- etc/config/c++.amazon.properties
> Add p3367 (constexpr coroutines)

- lib/tooling/llvm-mca-tool.ts
This patch fixes a few issues with argument passthrough that have been
discovered since #6682 was landed.
* X86 didn't work if -march=CPU was supplied.
* It wasn't possible to override flags on MCA, because the auto-detected
flags came before user flags.
* Since compiler-explorer runs on x86 native hardware, if targetting
aarch64, it would result in an error about the default requested
native CPU not being available for the architecture.
X86 clang uses -march to specify the CPU, and it's invalid to supply
-march=<cpu> to LLVM-MCA. Meanwhile, LLVM-MCA requires an -mcpu
argument.
Therefore, to handle x86 it's necessary to rewrite -march to -mcpu so
long as the march flag is used to supply a CPU value (i.e. not an
architecture level beginning with `x86-64`).
Per …
> Improve passthrough of -march and -mcpu from compiler to llvm-mca

- lib/base-compiler.ts
- lib/llvm-opt-transformer.ts
- static/styles/themes/dark-theme.scss
- static/styles/themes/one-dark-theme.scss
- static/styles/themes/pink-theme.scss
- test/llvm-opt-transformer-test.ts
> Fix opt-remarks / stack-usage font size in all themes - not just default

- etc/config/c++.amazon.properties
> Add simdjson 3.10.0

- etc/config/c++.amazon.properties
- etc/config/cuda.amazon.properties
Add HPC SDK 24.7 to etc/config/c++.amazon.properties
Add CUDA 12.5 to etc/config/cuda.amazon.properties
> Changes for NVIDIA HPC SDK 24.7

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/modula2.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
- etc/config/rust.amazon.properties
refs https://github.com/compiler-explorer/compiler-explorer/issues/6741
> Add GCC 14.2 native intel

- etc/config/c++.amazon.properties
> Add p3372 (constexpr containers and adaptors)

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1390
> [Spice] Add version 0.20.4

- etc/config/c++.amazon.properties
New version 0.4.0
Infra PR: https://github.com/compiler-explorer/infra/pull/1393
> Update Flux library

- lib/compilers/solidity.ts
> Robustify SolidityCompiler

- static/multifile-service.ts
- static/panes/tree.ts
Some major-ish fixes to tree and minor fixes in multifile-service.
This hopefully fixes #6770, #5734, and maybe others.
> Final (?) pane-renaming fix

- etc/config/c++.amazon.properties
Add Qt 6.7.0. This is counterpart to https://github.com/compiler-explorer/infra/pull/1398
> Add Qt 6.7.0

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- lib/tooling/bloaty-tool.ts
Added `bloaty` tool configuration for C, C++, D, Rust and Pascal. 
resolve #6240
> Add `bloaty` tool for C, C++, D, Rust and Pascal

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1402.
> Add Kokkos 4.3.01 and 4.4.00

- etc/config/gimple.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/6759
> Add missing cross GCC for GIMPLE

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1406
> Rust 1.81.0

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1408
> add quill 7.0.0

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1404
> [Spice] Add version 0.20.5

- etc/config/c++.amazon.properties
Depends on
- https://github.com/compiler-explorer/clang-builder/pull/73
- https://github.com/compiler-explorer/infra/pull/1411
This is experimental work on an implementation for [P2688](https://wg21.link/p2688).
It implements most of the parsing and constant evaluation logic.
The following is a sample of its current capabilities:
```rust
enum Color { Red, Blue };
struct S {
Color color;
int xs[2];
};
struct Result {
Color color;
int i;
constexpr bool operator==(const Result&) const noexcept = default;
};
constexpr auto test_nested_decomposition_pattern(const S& s) {
return s match -> Result {
[let c, [0, 0]] => {c, -1};
[let c, [let x, 0]] => {c, x * 2};
[let c, [0, let y]] => {c, y * 4};
let [c, [x, y]] => {c, x * y};
};
}
static_assert(test_nested_decomposition_pattern({Red, {0, 0}}) == …
```
> Update Pattern Matching to P2688.

- docs/AddingALanguage.md
> docs: update variable name for fs.remove arg

- docs/AddingALanguage.md
> docs: include the type entry required for language-key

- package-lock.json
- package.json
Tested locally, vi mode and all. Checked the release notes, nothing significant either. So, just maintenance stuff.
> Bump monaco

- package-lock.json
- package.json
According to https://github.com/hipstersmoothie/eslint-formatter-github/issues/111 it's not needed, and it brings in a bunch of extra deps we don't care about.
> Drop eslint-formatter-github

- etc/config/c++.amazon.properties
Should fix https://github.com/compiler-explorer/compiler-explorer/issues/6899
> update gcc versions for clang 19

- etc/config/fortran.amazon.properties
> Add Fortran Package Manager (library)

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1417
> Add quill v7.2.1

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> mp-units 2.3.0 support added

- static/modes/cppfront-mode.ts
This is an update to #5727.
The test cases: <https://highlight-cpp2.godbolt.org/z/P8zdfe7cW>.
<details><summary>Preview</summary>
</details>
> feat: update grammar of Cpp2

- etc/config/c++.amazonwin.properties
Accompanied by https://github.com/compiler-explorer/infra/pull/1380
> Add clang-cl to Windows compilers

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1421
> Add quill v7.3.0

- examples/il/default.il
- lib/compilers/dotnet.ts
Adding include path to ilasm.
Fixes https://github.com/compiler-explorer/compiler-explorer/pull/6856#issuecomment-2384005092
@partouf
> IL: Fixes include path for Linux

- etc/config/dart.amazon.properties
Dependent on https://github.com/compiler-explorer/infra/pull/1422. Thank you!
> Surface Dart 3.2 to 3.5 releases

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/objc++.amazon.properties
> Add trompeloeil v49

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1425
> [Spice] Add version 0.20.6

- etc/scripts/docenizers/Makefile
- etc/scripts/docenizers/docenizer-python.py
- package.json
> Small build/docz fixes

- etc/config/c++.amazon.properties
Add Qt 6.8.0 release. This is counterpart to https://github.com/compiler-explorer/infra/pull/1433
> Add QT 6.8.0

- etc/config/c++.amazon.properties
I ran make check and it replied:
Unable to find a node
etc/scripts/find-node: 29: --version: not found
make: *** [Makefile:18: .node-bin] Error 127
I have no clue what this means.
> Added p3412 lines to a configuration file.

- etc/config/compiler-explorer.defaults.properties
- lib/options-handler.ts
Remove the unused googleShortLinkRewrite and gapiKey
> Small options cleanup

- etc/config/rust.amazon.properties
A big one!
Infra: https://github.com/compiler-explorer/infra/pull/1436
> Rust 1.82.0

- etc/config/python.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1428
> Add Python 3.13 and make it the default

- etc/config/crystal.amazon.properties
> Add Crystal 1.14.0 and 1.13.3

- lib/clientstate-normalizer.ts
- lib/clientstate.ts
- lib/handlers/route-api.ts
Add typing, some refactoring to switch-case.  Mark unused functions - but not deleting yet, out of suspicion it has something to do with #6980.
> Tsify most of clientstate

- static/panes/compiler.ts
- static/panes/executor.ts
- static/widgets/compiler-version-info.ts
> Add display for internal compiler id

- lib/clientstate-normalizer.ts
> Fix compilers to executors

- lib/base-compiler.ts
- lib/buildenvsetup/buildenv.interfaces.ts
- lib/buildenvsetup/ceconan.ts
- lib/compilers/assembly.ts
- lib/compilers/rga.ts
- lib/exec.ts
- lib/execution/base-execution-env.ts
- lib/parsers/asm-parser-beebasm.ts
- lib/parsers/asm-parser-cpp.ts
- lib/parsers/asm-parser-dart.ts
- lib/parsers/asm-parser-dotnet.ts
- lib/parsers/asm-parser-mads.ts
- lib/parsers/asm-parser-spirv.ts
- lib/parsers/asm-parser-z88dk.ts
- lib/parsers/asm-parser.ts
- lib/utils.ts
- test/asm-tests.ts
- types/asmresult/asmresult.interfaces.ts
- types/compilation/compilation.interfaces.ts
- types/execution/execution.interfaces.ts
> Store times in `number`s only

- docs/API.md
> Unhide secret words

- static/panes/executor.ts
- types/compilation/compilation.interfaces.ts
> Extra safety around executeParameters.args

- static/panes/diff.ts
> In diff view, protect against undefined asm (case of a failed build)

- etc/config/go.amazon.properties
Just like #6296 but for Go 1.23.2.
Depends on compiler-explorer/infra#1443
> Add Go 1.23.2

- etc/config/c++.amazon.properties
Refers to [this PR](https://github.com/compiler-explorer/infra/pull/1448).
> Added Intel OneAPI 2025.0.0.740

- static/panes/tree.ts
> Bugfix Unknown file

- etc/config/ispc.amazon.properties
Corresponding infra PR: https://github.com/compiler-explorer/infra/pull/1452
> Add ISPC v1.25.3 and remove ispc-templates_new

- etc/config/cuda.amazon.properties
> update CUDA compilation w/ clang

- static/modes/cpp-for-opencl-mode.ts
- static/modes/cppcircle-mode.ts
- static/modes/cppp-mode.ts
- static/modes/cuda-mode.ts
- static/modes/glsl-mode.ts
- static/modes/hlsl-mode.ts
- static/modes/openclc-mode.ts
- static/panes/clangir-view.ts
- static/panes/compiler.ts
> Some minor additions to frontend typing

- static/sentry.ts
> Silence some frontend sentry noise (monaco internal benign errors)

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1455
> add quill v7.5.0

- lib/compilers/d8.ts
- lib/compilers/r8.ts
This change supports JVM system property input by reordering user-input compiler options that begin with '-D' or '-J'. The latter is an R8/D8 convention; the 'J' is stripped before being used.
Other compiler options are assumed to still apply to R8/D8.
> Support system properties in the R8/D8 invocation

- etc/config/android-java.amazon.properties
- etc/config/android-kotlin.amazon.properties
> Add support for the androidx.annotation library

- lib/base-compiler.ts
Hotfix to reduce memory footprint
> Don't keep possibleArguments to reduce memory footprint

- app.ts
- lib/handlers/api.ts
- lib/handlers/api/site-template-controller.ts
- test/handlers/api-tests.ts
- test/handlers/site-templates-tests.ts
Equivalent of #7130 for site templates
> Add controller for site templates

- app.ts
- lib/handlers/health-check.ts
Removes the any types and properly types the option
> Add correct types to healthcheck endpoints

- lib/handlers/api/site-template-controller.ts
- lib/site-templates.ts
- test/handlers/site-templates-tests.ts
File doesn't have anything to do with the http server anymore
> Move site-templates loader file

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1468.
> Rust 1.83.0

- lib/compilers/dotnet.ts
Follow up to #7141
As per https://github.com/compiler-explorer/compiler-explorer/pull/7141#issuecomment-2506116434, remove the restrictions on compiler options.
cc: @junlarsen
> Remove the restrictions on compiler options

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1454
> Add library `option`

- app.ts
> Hoist healthcheck router above logging middleware

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/compiler-explorer.defaults.properties
- etc/config/cuda.amazon.properties
- etc/config/solidity.amazon.properties
Some janitorial work. Unclear what is the status of TOIT
> Fix #5052: cleanup ghost compilers

- etc/config/julia.amazon.properties
Companion PR to https://github.com/compiler-explorer/infra/pull/1471
> Add julia v1.11.2

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
See:
* https://github.com/compiler-explorer/clang-builder/pull/77
* https://github.com/compiler-explorer/compiler-workflows/pull/30
* https://github.com/compiler-explorer/infra/pull/1472
> Added p2998

- lib/handlers/middleware.ts
> Hotfix static max age header

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1473.
> Add Kokkos 4.4.01 and 4.5.00

- package-lock.json
- package.json
Manual application of #7187 in order to get secrets or something? deploy failed anyways
> Bump path-to-regexp and express

- views/popups/library-selection.pug
> Add a warning about lack of Windows support.

- static/modes/slang-mode.ts
closes https://github.com/compiler-explorer/compiler-explorer/issues/7180
Worked with Slang developers on discord and put together a list of keywords that should be good and when I update the Slang version in the future can find a change list to include anything that changes then
> Add remaining Slang keywords

- Makefile
- package-lock.json
- package.json
Works just like before with reloading of properties. See demo GIF
> Replace supervisor with tsx --watch

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/modula2.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
- etc/config/rust.amazon.properties
refs https://github.com/compiler-explorer/compiler-explorer/issues/7115
> Add native x86 GCC build with assertion

- etc/config/c++.amazon.properties
"Sibling" PR to https://github.com/compiler-explorer/infra/pull/1482 
Thanks for the wonderful website!
> Add Mdspan Reference Implementation

- etc/config/c++.amazon.properties
- etc/nsjail/compilers-and-tools.cfg
- lib/compilers/_all.ts
- lib/compilers/qnx.ts
> Add support for QNX

- lib/base-compiler.ts
- lib/compilers/argument-parsers.ts
- static/panes/opt-view.interfaces.ts
- static/panes/pp-view.interfaces.ts
- test/base-compiler-tests.ts
> Opt-remarks for gcc

- lib/sponsors.ts
- test/sponsors-test.ts
I really don't like the solution but it works for this case and lets us add a few more sponsors before it all breaks.
> Handle sponsor cases with items that need to be shown every time better

- .gitignore
- docs/WindowsLocal.properties
- docs/WindowsNative.md
- docs/WindowsSubsystemForLinux.md
- lib/compilers/win32.ts
> Fix MSVC's handling of `/link` options, fix and modernize some docs

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/circle.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
> Add recent Pythons as libraries for C-like languages

- etc/config/scala.amazon.properties
https://github.com/compiler-explorer/infra/pull/1493
Tested locally
> Update scala with new compilers and jdk 21

- lib/parsers/asm-parser.ts
- test/filters-cases/bug-7280.asm
- test/filters-cases/bug-7280.asm.binary.directives.labels.comments.json
- test/filters-cases/bug-7280.asm.directives.comments.json
- test/filters-cases/bug-7280.asm.directives.json
- test/filters-cases/bug-7280.asm.directives.labels.comments.json
- test/filters-cases/bug-7280.asm.directives.labels.comments.library.dontMaskFilenames.json
- test/filters-cases/bug-7280.asm.directives.labels.comments.library.json
- test/filters-cases/bug-7280.asm.directives.labels.json
- test/filters-cases/bug-7280.asm.directives.library.json
- test/filters-cases/bug-7280.asm.none.json
Fixes #7280
@partouf I expect this will need a fix in the C++ code too, right?
> Support `.base64` as a data indicator.

- examples/ispc/default.ispc
After #7273, ISPC code can be executed, so modify the default example to demonstrate how to do it.
> Update default ISPC example

- etc/config/odin.amazon.properties
companion of pr https://github.com/compiler-explorer/infra/pull/1502
> Use odin 2025-01

- etc/config/rust.amazon.properties
This adds the tools requested in #6796.
> Add some tools for rust

- etc/config/slang.amazon.properties
Adds new slang from https://github.com/compiler-explorer/infra/pull/1499
> Add Slang 2025.2.2

- etc/config/spirv.amazon.properties
Adds new SPIR-V tools from new Vulkan SDK (https://github.com/compiler-explorer/infra/pull/1498)
> Update SPIR-V with newest Vulkan SDK

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
Changes for HPC SDK 25.1
Add nvc 25.1 to etc/config/c.amazon.properties
Add nvc++ 25.1 to etc/config/c++.amazon.properties
Add nvfortran 25.1 to etc/config/fortran.amazon.properties
> Changes for NVIDIA HPC SDK 25.1

- etc/config/c++.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1509
> Add quill v8.1.0

- etc/config/c.amazon.properties
> Update SDCC to 4.5.0

- etc/config/c++.amazon.properties
> Update to add Boost 1.87 support

- etc/config/c++.amazon.properties
Rename beman.optional26 to beman.optional as per https://github.com/bemanproject/beman/issues/85
> Rename beman.optional26 to beman.optional

- etc/config/crystal.amazon.properties
> Add Crystal 1.15.0 and 1.14.1

- etc/config/c++.amazon.properties
> Add EDG 6.7 release files

- .github/labeler.yml
- etc/config/algol68.amazon.properties
- etc/config/algol68.defaults.properties
- examples/algol68/default.a68
- lib/compilers/ga68.ts
- lib/languages.ts
- types/languages.interfaces.ts
refs https://github.com/compiler-explorer/compiler-explorer/issues/7258
> Add new language: Algol68 and corresponding GCC frontend

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
refs https://github.com/compiler-explorer/compiler-explorer/issues/6321
> Add GCC cross for Tricore

- etc/config/odin.defaults.properties
#7210
After this PR the linked issue can be closed as almost everything mentioned in the issue is addressed
> Odin: Filter some more labels from objdump output

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1520
> [Spice] Add version 0.21.1

- lib/clientstate-normalizer.ts
- lib/handlers/route-api.ts
Should fix https://github.com/compiler-explorer/compiler-explorer/issues/7370
> Missing tree filenames short link fix

- package-lock.json
- package.json
I must've missed this in the biome PR somehow :)
> Remove dependency on prettier

- etc/config/csharp.amazon.properties
- etc/config/csharp.defaults.properties
- etc/config/fsharp.amazon.properties
- etc/config/fsharp.defaults.properties
- etc/config/il.amazon.properties
- etc/config/il.defaults.properties
- etc/config/vb.amazon.properties
- etc/config/vb.defaults.properties
Depends on https://github.com/compiler-explorer/infra/pull/1525
> New dotnet versions

- etc/config/ispc.amazon.properties
ISPC v1.26.0 has been released.
Related PR: https://github.com/compiler-explorer/infra/pull/1528
> Add ISPC v1.26.0

- etc/config/python.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1526
> Add PyPy 3.11

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
References:
- Infra PR: https://github.com/compiler-explorer/infra/pull/1527
- https://github.com/compiler-explorer/misc-builder/pull/103
> update clad to v1.9 with clang v19.1.0

- static/modes/spice-mode.ts
Add `cast` keyword to Spice mode
> [Spice] Add cast keyword

- etc/config/rust.amazon.properties
Add newly released rustc 1.85.0
> Rust 1.85.0

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1536
> [Spice] Add version 0.22.0

- etc/config/c++.amazon.properties
Add library Proxy since version 3.0.0.
https://github.com/compiler-explorer/infra/pull/1534
> Add C++ library `Proxy`

- test/android-tests.ts
- test/base-compiler-tests.ts
- test/cache-tests.ts
- test/cfg-tests.ts
- test/checks.ts
- test/demangler-tests.ts
- test/filter-tests.ts
- test/golang-tests.ts
- test/java-tests.ts
- test/lang-tests.ts
- test/library-tests.ts
- test/llvm-ast-parser-tests.ts
- test/odin-tests.ts
- test/packager-tests.ts
- test/pascal-tests.ts
- test/statenormalisation-tests.ts
- test/tool-tests.ts
- test/unfurl-tests.ts
- test/utils-tests.ts
- test/utils.ts
Also don't re-export fs and path through utils
> Update tests to use node fs

- static/panes/compiler.ts
> Fix #7425: Fix an edge case in asm jump-to-label

- lib/binaries/win-utils.ts
- lib/buildenvsetup/ceconan.ts
- lib/compiler-finder.ts
- lib/execution/execution-triple.ts
- lib/languages.ts
- lib/options-handler.ts
- lib/toolchain-utils.ts
- use node libraries instead of fs-extra
> More relatively uncontentious fs changes

- lib/compilers/clang.ts
- lib/compilers/clean.ts
- lib/compilers/d8.ts
- lib/compilers/dosbox-compiler.ts
- lib/compilers/dotnet.ts
- lib/compilers/nim.ts
- lib/compilers/r8.ts
- lib/compilers/sway.ts
- use utils functions where necessary
- introduce a few asyncs where needed.
Some local testing done (e.g. with sway and clang). Will need testing in staging for the best outcome.
> Port compilers over to using node:fs et al

- etc/config/execution.amazonwin.properties
- etc/config/execution.defaults.properties
> Disable unbufferStdoutExe config, due to clash with asan

- etc/config/c++.amazon.properties
Added 4 example to demonstrate the basic usage.
> Add examples for Proxy

- views/resources/logos/c.svg
Hi! This is a change of the C logo to graphic officially endorsed by the C committee.
> Correct C logo

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1549
> [Spice] Add version 0.22.1

- etc/config/c++.amazon.properties
Related infra PR [here](https://github.com/compiler-explorer/infra/pull/1552).
> Added Intel OneAPI 2025.1.0

- etc/config/c++.amazon.properties
Adds [glaze](https://github.com/stephenberry/glaze) 5.0.0. I tried to follow what was already there so apologies if I didn't do this right.
> Add glaze 5.0.0

- lib/compilers/dotnet.ts
Depends on https://github.com/compiler-explorer/dotnet-builder/pull/25
> .NET: Add multiple architectures support for NativeAOT

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1560.
> Rust 1.86.0

- etc/config/android-java.amazon.properties
- etc/config/android-kotlin.amazon.properties
> Update dex2oat latest name

- etc/config/crystal.amazon.properties
> Add Crystal 1.16.0

- etc/config/c++.amazon.properties
Infra PR
https://github.com/compiler-explorer/infra/pull/1562
> Add quill v9.0.0

- etc/config/c++.amazon.properties
- etc/config/cuda.amazon.properties
> add hipclang for rocm 6.2.4 and 6.3.3

- static/panes/gccdump-view.ts
> Fix #7464: resolve TomSelect glitch by delaying active option setting

- lib/base-compiler.ts
- lib/compilers/rust.ts
> Support opt remarks for rustc-nightly

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1570.
> Add Kokkos 4.5.01 and 4.6.00

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/cuda.amazon.properties
- etc/config/fortran.amazon.properties
Add nvc 25.3 to etc/config/c.amazon.properties
Add nvc++ 25.3 to etc/config/c++.amazon.properties
Add nvfortran 25.3 to etc/config/fortran.amazon.properties
Add CUDA 12.8.1 to etc/config/cuda.amazon.properties
> Changes for NVIDIA HPC SDK 25.3

- etc/config/d.amazon.properties
infra: https://github.com/compiler-explorer/infra/pull/1580
> Add LDC 1.40.1 and make it the default D compiler

- etc/config/c++.amazon.properties
> add clang -fimplicit-constexpr branch

- etc/config/assembly.amazon.properties
- etc/config/cuda.amazon.properties
> [CUDA] update ptxas and clang compilers with recent CUDA SDK versions.

- docs/TestingTheUi.md
- static/main.ts
- static/sharing.ts
- static/widgets/compiler-version-info.ts
Checked locally. Have no idea how the heck the quotes got changed....
> Handle items that don't exist in embedded mode; fix iframe generation

- docs/Bootstrap5Migration.md
- static/bootstrap-utils.ts
- static/sharing.ts
- static/widgets/alert.ts
Remove some unnecessary functions and clarify docs.
> Cleanup post bootstrap 5

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/cobol.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/go.amazon.properties
- etc/config/modula2.amazon.properties
- etc/config/objc++.amazon.properties
- etc/config/objc.amazon.properties
- etc/config/rust.amazon.properties
refs https://github.com/compiler-explorer/compiler-explorer/issues/7549
> Add native x86_64 GCC 15.1.0

- docs/AboutLibraryPaths.md
- docs/AddingACompiler.md
- docs/AddingAFormatter.md
- docs/AddingALanguage.md
- docs/AddingALibrary.md
- docs/AddingATool.md
- docs/AddingCustomCompilersOverview.md
- docs/Cerberus.md
- docs/Configuration.md
- docs/EWARM.md
- docs/EWAVR.md
- docs/TiC2000.md
- docs/TurboC.md
- docs/WindowsNative.md
- docs/WindowsSubsystemForLinux.md
This PR adds a detailed Configuration.md document that comprehensively explains the Compiler Explorer configuration system. It covers:
- Configuration file structure and hierarchical loading
- Property types and automatic conversions
- List separators and specialized formats
- Group inheritance and compiler configuration
- Variable substitution mechanisms
- Advanced features like remote compilers and property debugging
Additionally, it updates all related documentation to reference this central document for configuration details, reducing duplication and ensuring consistency.
This document will serve as the foundation for future configuration system improvements by providing clear documentation of the current implementation.
> Add comprehensive Configuration.md documentation

- etc/config/c++.amazon.properties
Add beman.net library trunk version - #7622 
Infra PR - https://github.com/compiler-explorer/infra/pull/1592
Beman Issue - https://github.com/bemanproject/net/issues/23
Tested these changes on my laptop running Ubuntu 22.04
> Add beman.net library trunk version

- etc/config/c++.amazon.properties
References: https://github.com/compiler-explorer/misc-builder/pull/109 and https://github.com/compiler-explorer/infra/pull/1595
> update clad to v1.10 with clang v20.1.0

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/gimple.amazon.properties
- etc/config/objc.amazon.properties
fixes https://github.com/compiler-explorer/compiler-explorer/issues/7563
> Add GCC 12.4.0 for VAX NetBSD

- CLAUDE.md
- app.ts
- lib/assert.ts
- lib/global.ts
- test/assert-tests.ts
Wasn't sure how to test this so ... @jeremy-rifkin can you take a look please? :)
> Remove top-level global for base directory

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1604.
> Add Kokkos 4.6.01

- etc/scripts/julia_wrapper.jl
This is needed for https://github.com/JuliaLang/julia/issues/58286.
CC @vchuravy.
> Adapt Julia wrapper to v1.12

- Makefile
> Update Makefile --webpack-content to --static

- etc/config/kotlin.amazon.properties
Waiting for
- compiler-explorer/infra#1619
> Install recent Kotlin

- cypress/e2e/remote-id.cy.ts
- lib/options-handler.ts
- shared/remote-utils.ts
- shared/url-testcases.ts
- static/lib-utils.ts
- static/tests/remote-id.ts
- test/options-handler.ts
Fixes #7590
Ugly code duplication was a bit annoying
> fix remote libraries listing backend and frontend

- static/panes/opt-view.ts
Resolves #7662.
[View zones](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IViewZone.html) are rendered in the editor widget but don’t count as lines themselves. Monaco doesn’t automatically grow them to fit their content (and doesn’t extend the scroll area to fit them when the text is rendered without line breaks), so the height must be calculated manually.
Additionally, this changes the remarks to be *above* the line they are attached to. This is more intuitive in my opinion, but can be reverted again if you prefer.
Comparison:
before:
after:
> Show opt remarks in a view zone instead of as editor content

- etc/config/rust.amazon.properties
Ten years!
Infra: https://github.com/compiler-explorer/infra/pull/1624
> Rust 1.87.0

- etc/config/ispc.amazon.properties
Adding ISPC v1.27.0. Related change https://github.com/compiler-explorer/infra/pull/1622
> Add ISPC v1.27.0

- lib/app/controllers.ts
- lib/app/main.ts
- lib/app/server-config.ts
- lib/app/server.interfaces.ts
- lib/app/server.ts
- test/app/rendering-tests.ts
- test/app/server-tests.ts
- healthcheck got accidentally unwired
- CSP was accidentially "done" (was a TODO)
> Fix issues introduced in #7681

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/cuda.amazon.properties
- etc/config/fortran.amazon.properties
Add nvc 25.5 to etc/config/c.amazon.properties
Add nvc++ 25.5 to etc/config/c++.amazon.properties
Add nvfortran 25.5 to etc/config/fortran.amazon.properties
Add CUDA 12.9 to etc/config/cuda.amazon.properties
> Changes for NVIDIA HPC SDK 25.5

- etc/config/crystal.amazon.properties
> Update Crystal to 1.16.3

- .claude/commands/fix-sentry-issue.md
- .claude/commands/hunt-sentry-issues.md
FAO @partouf adds two new `/` commands in claude, seems to work quite well. Needs the sentry MCP which is pretty easy to install. Will do a github one too
> Add sentry hunting commands

- lib/compilers/c3c.ts
> Fix C3 0.6.8

- etc/config/c++.amazon.properties
> Only include tip-of-tree main version for Bronto library.

- static/graph-layout-core.ts
> Refactor graph layout system

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/1678.
> Rust 1.88.0

- lib/cfg/cfg-parsers/_all.ts
- lib/cfg/cfg-parsers/base.ts
- lib/cfg/cfg-parsers/clang.ts
- lib/cfg/cfg-parsers/gcc.ts
- lib/cfg/cfg-parsers/oat.ts
- lib/cfg/cfg-parsers/python.ts
- lib/cfg/instruction-sets/_all.ts
- lib/cfg/instruction-sets/python.ts
- test/cfg-cases/cfg-python.basic.json
- test/cfg-cases/cfg-python.basic2.json
- test/cfg-tests.ts
Still WIP, but already a step forward
> CFG for Python

- etc/config/c++.amazon.properties
infra PR: 
https://github.com/compiler-explorer/infra/pull/1680
> add quill v10.0.1

- lib/base-compiler.ts
- lib/cfg/cfg-parsers/base.ts
- lib/cfg/cfg-parsers/python.ts
- lib/cfg/cfg.ts
- test/cfg-tests.ts
Along with improved function names.
> Adapt python cfg to python 3.13

- etc/config/c++.amazon.properties
Parent PR at https://github.com/compiler-explorer/clang-builder/pull/92
> Add P3385 experimental clang compiler

- lib/cfg/instruction-sets/xtensa.ts
- test/cfg-cases/cfg-xtensa.loop.json
- test/cfg-tests.ts
Source taken from the link in #6886
> Fix #6886: Add cfg support for Xtensa ISA

- etc/config/crystal.amazon.properties
> Add Crystal 1.17.0

- lib/tooling/llvm-mca-tool.ts
Would appreciate a review on this, hope my understanding is correct.
You can see the targets recognized by llvm-mca:
```
/opt/compiler-explorer/clang-trunk/bin $ ./llvm-mca --version
LLVM (http://llvm.org/):
LLVM version 21.0.0git
Optimized build.
Default target: x86_64-unknown-linux-gnu
Host CPU: raptorlake
Registered Targets:
aarch64     - AArch64 (little endian)
aarch64_32  - AArch64 (little endian ILP32)
aarch64_be  - AArch64 (big endian)
amdgcn      - AMD GCN GPUs
arm         - ARM
arm64       - ARM64 (little endian)
arm64_32    - ARM64 (little endian ILP32)
armeb       - ARM (big endian)
avr         - Atmel AVR Microcontroller
bpf         - BPF (host endian)
bpfeb       - BPF (big endian)
bpfel       - BPF (little endian)
dxil        - DirectX Intermediate Language
hexagon     - …
```
> Fix #7539: llvm-mca falls back to autodetected arch if fails to use compilation switches

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
Add nvc 25.7 to etc/config/c.amazon.properties
Add nvc++ 25.7 to etc/config/c++.amazon.properties
Add nvfortran 25.7 to etc/config/fortran.amazon.properties
> Changes for NVIDIA HPC SDK 25.7

- etc/config/c++.amazon.properties
Related to https://github.com/compiler-explorer/infra/pull/1721.
> Add Kokkos 4.6.02

- etc/config/spice.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/1729
> [Spice] Add version 0.22.3

- etc/config/python.amazon.properties
- lib/compilers/_all.ts
- lib/compilers/codon.ts
> Add Codon Python compiler

- lib/parsers/asm-parser.ts
- test/demangle-cases/bug-713.asm.json
- test/filters-cases/eigen-test.asm.directives.comments.json
- test/filters-cases/eigen-test.asm.directives.json
- test/filters-cases/eigen-test.asm.directives.labels.comments.json
- test/filters-cases/eigen-test.asm.directives.labels.comments.library.dontMaskFilenames.json
- test/filters-cases/eigen-test.asm.directives.labels.comments.library.json
- test/filters-cases/eigen-test.asm.directives.labels.json
- test/filters-cases/eigen-test.asm.directives.library.json
- test/filters-cases/set-directive-rust.asm
- test/filters-cases/set-directive-rust.asm.binary.directives.labels.comments.json
- test/filters-cases/set-directive-rust.asm.directives.comments.json
- test/filters-cases/set-directive-rust.asm.directives.json
- test/filters-cases/set-directive-rust.asm.directives.labels.comments.json
- test/filters-cases/set-directive-rust.asm.directives.labels.comments.library.dontMaskFilenames.json
- test/filters-cases/set-directive-rust.asm.directives.labels.comments.library.json
- test/filters-cases/set-directive-rust.asm.directives.labels.json
- test/filters-cases/set-directive-rust.asm.directives.library.json
- test/filters-cases/set-directive-rust.asm.none.json
> Don’t filter `.set` directives that declare merged functions

- etc/config/ispc.amazon.properties
ISPC v1.28.0 has been released. Related infra change: https://github.com/compiler-explorer/infra/pull/1762
> Add ISPC v1.28.0

- etc/config/c++.amazon.properties
> Add p2034_lambda GCC

- etc/config/ispc.amazon.properties
ISPC v1.28.1 has been released. Related infra change: https://github.com/compiler-explorer/infra/pull/1781
> Add ISPC v1.28.1

- etc/config/c++.amazon.properties
Sister PR [here](https://github.com/compiler-explorer/infra/pull/1777).
> Add Intel OneAPI 2025.2.1

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
Add nvc 25.9 to etc/config/c.amazon.properties
Add nvc++ 25.9 to etc/config/c++.amazon.properties
Add nvfortran 25.9 to etc/config/fortran.amazon.properties
> Changes for NVIDIA HPC SDK 25.9

- lib/parsers/asm-parser-vc.ts
I couldn't verify locally (I failed to install VC 19.30, and the issue doesn't reproduce in later versions).   
But I'm confident enough the included changes are an improvement anyway, so I feel it's ok to push - I'll keep #5524 open until the fix can be verified in the live site.
> Fix #5524: Improve VC assembly filtering

- etc/config/c++.amazon.properties
- etc/config/c++.amazonwin.properties
Linux building: https://github.com/compiler-explorer/infra/actions/runs/18198444653/job/51835248850
Windows: https://github.com/compiler-explorer/infra/actions/runs/18206096921 (hopefully)
> Add boost 1.88 and 1.89 for linux and windows

- .github/workflows/test-and-deploy.yml
- etc/scripts/gh_tool/.gitignore
- etc/scripts/gh_tool/README.md
- etc/scripts/gh_tool/docs/PHASE1-FINDINGS.md
- etc/scripts/gh_tool/docs/TRIAGE-CRITERIA.md
- etc/scripts/gh_tool/pyproject.toml
- etc/scripts/gh_tool/src/gh_tool/__init__.py
- etc/scripts/gh_tool/src/gh_tool/cli.py
- etc/scripts/gh_tool/src/gh_tool/duplicate_finder.py
- etc/scripts/gh_tool/test_duplicate_finder.py
- etc/scripts/gh_tool/tests/test_duplicate_finder.py
This PR adds a new Python CLI tool for automating GitHub repository management tasks.
The initial implementation provides duplicate issue detection using text similarity analysis. This is the first step toward automating repository triage tasks.
- **Click-based CLI** with subcommands for future extensibility
- **find-duplicates command** for detecting duplicate issues using text similarity
- Uses **gh CLI** for GitHub API access (no token management needed)
- Text similarity using `difflib.SequenceMatcher` (ratio-based algorithm)
- Configurable similarity threshold (default: 0.6)
- Progress bar for long-running comparisons
- Age filtering support (`--min-age` parameter)
- Standard Python src-layout with **uv** for dependency management
- **Comprehensive test suite** with pytest …
> Add gh_tool CLI for GitHub repository automation

- etc/config/ispc.amazon.properties
- examples/ispc/default.ispc
This PR adds support of recently released ISPC 1.28.2 and updates a default snippet for it.
Related infra change: https://github.com/compiler-explorer/infra/pull/1857
> Add ISPC v1.28.2
