static/urlshorten-google.js

This can happen when sharing has been disabled.
Fixes #61.

Handle the case where no gapi object exists.

---

app.js
package.json

memwatch doesn't work with node 0.12, so switch it out for memwatch-next

Switch to memwatch-next

---

lib/sources/builtin.js

Compare function should return negative, 0, or a positive integer.
Not true or false.
Signed-off-by: Ola Jeppsson <ola@adapteva.com>

Fix sorting of examples

---

app.js
lib/compile.js

I found this useful as I have many cross-compilers, and not all have ``-fexceptions`` on by default.
Also, I'm providing a choice for both 32bit and 64bit, but using the same compiler.
```
compilers=gdc32:gdc64
compiler.gdc32.exe=/srv/compilers/bin/gdc-5
compiler.gdc32.options=-m32
compiler.gdc64.exe=/srv/compilers/bin/gdc-5
compiler.gdc64.options=-m64
```
(Running site here: http://explore.dgnu.org )

Add ability to set per-compiler options

---

static/index.html

so it looks better on high-DPI displays.
From https://ar.al/scribbles/fork-me-on-github-retina-ribbons/.
Comparison:

Use higher-resolution "Fork me on GitHub" ribbon

---

app.js

For instance, if there is a proxy to the outside world on a secondary interface.  E.g:
```
./app.js --host=192.168.1.5 --port=12345 # ...
```

Add host option to allow server to run on non-default interface

---

c-preload/Makefile

As per: http://lists.freebsd.org/pipermail/freebsd-questions/2008-March/172079.html
> The dlopen/dlsym functions are built into libc on FreeBSD, so there's no need for a libdl

Don't try to link in dl library on FreeBSD.

---

lib/compile.js

* fixes an issue where the user cannot specify any compiler options if the optionsBlacklistRe config option isn't specified (i assume that this is not the intended behavior)
* this is due to the fact that if the black list regex isn't specified, gccProps returns 'undefined'; in JS "new RegExp(undefined)" evaluates to /(?:)/ which matches any string with a non-null result of empty string
* as a result, any option is considered as blacklisted
* this commit sets the option default to /(?!)/ which truly doesn't match anything (i.e. the match is null for any string)

Fixes rejection of any user provided compiler option optionsBlacklistRe isn't set

---

static/compiler.js

Related to this ticket: https://github.com/codemirror/CodeMirror/issues/4066

fix typing '#' in triggering emacs keybind

---

examples/c++/max_array_opt.cpp

A more compatible and concise hint for memory alignment in the "max array opt" example.

Better alignment hint for "max array opt"

---

static/compiler.js

The status button (the button with the exclamation mark and triangle), does not work properly in Mozilla Firefox, the title does not show up, because it is an attribute on the `span`-element, and not the button itself, and similarly the events, that allows creating an output area, also don't work as they are attached to the `span`-element.
This diff modifies `static/compiler.js` slightly, so the `title`-attribute and the events are applied to the parent `button`-element which fixes it on Mozilla Firefox, and also makes the whole button work, as opposed to only the part that has the status icon on it.
I have played around with this change, and have not found any bugs with it, and have tested in both Mozilla Firefox, and Google Chrome, where it seems to work as it should.

Fixes the status button so it works on Mozilla Firefox

---

etc/config/d.amazon.properties

This should add LDC to the list of available compilers on d.godbolt.org.

Add LDC to Amazon config

---

Makefile
app.js
d/Makefile
d/demangle.d
etc/config/d.amazon.properties
lib/compile.js

This change makes the assembly-output and output-filename flags configurable, and sets them correctly for LDC.
Also includes:
- make the Makefile work with DMD environment variable pointing to a DMD-compatible D compiler
- fix demangling of D symbols on OS X
With these changes, LDC works correctly locally (except that the output is not colorized)

Add support for the LDC compiler

---

lib/asm.js

I did a quick check and I think all languages use "example" in the source filename.

Fix file match for colorizing

---

lib/compile.js

I don't fully understand, but this fix is needed to make the C compilers work locally on my machine again. `compilerInfo.asmFlag` and `compilerInfo.outputFlag` may be undefined (although I thought I had set a default value for them)

Fix undefined compiler flag issue

---

etc/config/d.amazon.properties

This reduces the length of the compiler name to a manageable size.

LDC: remove the dlang version number

---

lib/compile.js

By passing -g at the beginning of the CLI args, debug info noise
can be turned off by passing -g0 in the args.
It's also possible to pass -gline-tables-only if line colouring is
desired and we want to avoid most debug info noise.
Check the difference between `-g0 -emit-llvm` and `-emit-llvm` on clang.
Also check the difference between the default (`-g`) `-g0` and
`-gline-tables-only` on any gcc/clang asm (with line colouring on).

[debug info] Pass -g at the start of the command line.

---

etc/config/d.amazon.properties

Fits together with gcc-explorer-image PR #9, https://github.com/mattgodbolt/gcc-explorer-image/pull/9.

LDC beta: don't explicitly mention version number

---

etc/config/d.defaults.properties

Tested this locally only somewhat. Getting this to work on OS X is a bit of a pain.

Enable binary output for D compilers

---

lib/base-compiler.js

To potentially make the intent clearer for future inquiring minds, add a comment to checkSource function explaining that it's not meant to prevent arbitrary file inclusion, only to diagnose unsophisticated attempts.

base-compiler.js: acknowledge checkSource weakness

---

lib/compilers/ldc.js

I'm having trouble building the project, but it seems like there shouldn't be any extra changes required. (LLVM's `-x86-asm-syntax=intel` mode is already being used for Rust.)

d/ldc: Enable Intel syntax (?)

---

static/compiler.js
static/editor.js

We're now able to mark the asm linked to a line of code on multiple compiler windows
Also, leftover property from a previous iteration has been removed
Closes #315

Improvements to double linked edtiros

---

static/compiler.js
static/editor.js

I open this PR so I can get some opinions on the code for this one. I have annottated few fragments that I will polish Soon™ once I get some feedback/help
Note that the tooltip api is nowhere to be found on the Monaco Editor, but decorations are able to access them, so we just create a decoration on the mouse position that opens a tooltip with the converted value. In order to do this and **not** lose the linking code decorations, we now have to store the decoration arrays separatedly, and emply the first one of this array for the tooltip. I think it's a good solution but I'm open to suggestions.
I'm quite sure binary numerals will get parsed as decimals by javascript, so there's that
Closes #27 #107

Adds a numerical constants tooltip conversion

---

static/compiler.js

I did not test it when I submitted it because the changes were minimal, yet I screwed it up!
Sorry about that 😞 
The issue came to be because I c&p the code from a previous iteration that instead of checking if we could do it and did it in case we could, it checked if we could **not** do it and returned in that case.
Again, sorry

Fixed typo that prevented code highlighting

---

.gitignore
lib/base-compiler.js
package.json
static/compiler.js
static/components.js
static/explorer.css
static/hub.js
static/main.js
static/opt-view.js
views/templates.pug

WIP: But the code structure should largely be unchanged.
This closes out #332 
- this actually turned out to be unrelated. It looks like im getting 2 on compileResults on load
This should hopefully work now, if there are any problems let me know.
I usually use code from to test it out. 
https://github.com/llvm-mirror/test-suite/tree/master/SingleSource/Benchmarks

First pass at adding a opt view mode for compiler explorer

---

static/opt-view.js

I can't really display it, so for now we just ignore them.
this fixes https://github.com/mattgodbolt/compiler-explorer/issues/409

For now lets just rip out anything that doesn't have a debugloc

---

d/demangle.d

`demangle` is misinterpreted as the module name...

Fix compilation of demangle.d with newer DMD versions.

---

static/compiler.js

Added new lines before the string that gets appended to the hover message of asm docs to make it more explicit and to separate it from the doc message itself.

Improved the hover message

---

README.md

I have a few doubts about the JSON output.
* Why are the values of the `stdout` and `stderr` properties, JSON arrays ? Does that mean that 2 or more objects of the form present in the array would be present ?
* Does the **(as above)** in the `stderr` property meant to point to the format of the `stdout` property ?

Formatted the JSON to make it more readable

---

etc/config/builtin.ispc.properties
etc/config/ispc.defaults.properties
examples/ispc/max_array.ispc
examples/ispc/sum_array.ispc
lib/compilers/ispc.js

[Intel ISPC](https://ispc.github.io) is a C derivative with SPMD semantics baked into the language, which often allows for more effective auto-vectorization than is possible in standard C/C++. This patch integrates the ISPC compiler, and adds idiomatic ports of Compiler Explorer's `max_array` and `sum_array` examples.
The compiler is BSD licensed and Linux binaries are provided by the project, so it should be pretty straightforward to integrate into the server image.
Caveats:
ISPC doesn't support Intel assembly syntax, so that's disabled (ironic considering it's an Intel project)
Binary disassemble mode is disabled for now because I'm dumb and couldn't convince it to work.

Add support for Intels ISPC compiler

---

examples/ispc/max_array.ispc

Oops, `foreach(begin...end)` only iterates up to `end-1` so the end bound should be 65536.

Fix upper bound in ISPC max_array

---

lib/base-compiler.js
lib/compile-handler.js
static/ast-view.js
static/compiler.js
static/components.js
static/hub.js
views/templates.pug

Opened this pull request to track support for viewing the Clang AST. I still need to ensure that the functionality is enabled/disabled as required and clean up the code. Please let me know if you'd like me to change the approach of anything.

Support displaying the Clang AST

---

examples/ispc/max_array.ispc

This flag is often vital for getting good codegen, so we should probably direct new users towards it.

Mention force-aligned-memory in ISPC example

---

static/editor.js
static/ispc-mode.js

...or rather, clone Monaco's C++ syntax and hack in the ISPC keywords. Close enough 😛

Add syntax highlighting for ISPC

---

lib/base-compiler.js

Currently AST declarations are filtered out if an implicit declaration (e.g. operator new) occurs between two explicit declarations.
Example:
```
struct foo {
virtual ~foo() = default;
};
int a;
```
Current output:
```
TranslationUnitDecl
|-CXXRecordDecl <line:1:1, line:3:1> line:1:8 struct foo definition
| |-CXXRecordDecl <col:1, col:8> col:8 implicit referenced struct foo
| |-CXXDestructorDecl <line:2:5, col:28> col:13 ~foo 'void (void) noexcept' virtual default
| `-CXXMethodDecl <line:1:8, col:8 implicit operator= 'struct foo &(const struct foo &)' inline default noexcept-unevaluated 0x526f328
|   `-ParmVarDecl <col:8> col:8 'const struct foo &'
```
Fixed output:
```
TranslationUnitDecl
|-CXXRecordDecl <line:1:1, line:3:1> line:1:8 struct foo definition
| |-CXXRecordDecl <col:1, col:8> …
```

Don't filter out AST declarations after an implicit declaration

---

lib/base-compiler.js
static/ast-view.js
static/compiler.js

This fixes the issue mentioned by Björn Fahller on Slack with the AST view not playing nicely with multiple compilers.

Make AST view play nicely with other compilers

---

lib/compilers/ispc.js

ISPC uses the host's CPU to determine the default instruction set if no `--target` option is passed, so the live site is currently defaulting to `avx1.1-i32x8` or `avx2-i32x8` at random depending on which Amazon node happens to serve the request.
Users probably won't appreciate the compiler options changing erratically as they type, so I've added a hard-coded target that will serve as the default unless the user overrides it with their own `--target` setting. `sse2-i32x4` is used for consistency with most other x86-64 compiler's default behavior.

Make ISPC default to SSE2 if no target is specified

---

etc/config/builtin.haskell.properties
etc/config/haskell.defaults.properties
examples/haskell/sumOverArray.hs
lib/compilation-env.js
lib/compilers/haskell.js
views/example.hs
views/head.pug
views/index.pug

Adds support for Haskell using GHC.
Fixes #444

Add Haskell support

---

lib/base-compiler.js

`backendOptions` in `base-compiler.js` is apparently not defined sometimes (may be due to caching). This fix ensures that it's defined before attempting to read from it.

Ensure that backendOptions is defined

---

app.js
etc/config/compiler-explorer.defaults.properties
static/compiler.js
static/components.js
static/conformance-view.js
static/editor.js
static/explorer.css
static/hub.js
views/templates.pug

What
---
A view that allows compiling with multiple compilers at once and informs on the results of each one. It is able to display warnings/compilation errors *but not the produced asm*
Why
---
I liked @adishavit's (Slack) request for something like this (It also gave me few ideas for the formatting tool #346 #111 )
Limitations
---
Some limitations are in place but none are necessary, so tell me if you don't feel the need for some to be there
- Produced asm is descarted (We only care about the compilation status, but maybe having a "Show me asm" button would be cool?)
- 6 compilers per view
- 1 view per editor
The last two are there so we don't ddos ourselves. Maybe they are a bit too harsh? Maybe more than 6 compilers per view is ok?
TODO
---
Notes
---
- This PR changes the signature of …

Conformance viewer

---

Makefile
rust/Cargo.lock
rust/Cargo.toml
rust/src/main.rs

I added `RUSTFLAGS` and `simd-accel` in case you agree to use `nightly`(`rust-toolchain` from `rustup 1.5.0` could be used here to lock to a specific nightly) in order to accelerate the regex with SIMD.

Update Rust dependencies

---

static/compiler-service.js

- Or at least I hope so. I've only tested on Ubuntu and this is a
CL-specific bug.
- However, it WOMM! (GCC 4.9.3 & Clang 3.8.0)

fixes #472

---

etc/config/c++.amazon.properties

It's easy to confuse and relate the word 'snapshot' with other things
and it doesn't seem quite communicative. Moreover, we already identify
the compiler built from clang's source as 'trunk'.
So, in order to use clear wordings and to be consistent, use the word
'trunk' (at least in the user interface) to identify the compiler built
from gcc's "trunk" ;-)

Use 'trunk' instead of 'snapshot' to indicate gcc built from source

---

haskell/Makefile

Arch Linux does not install static ghc libraries by default. Running "make run"
without this commit leads to linker errors during the compilation of
haskell/demangle. Compiling demangle with -dynamic fixes this issue.
```
$ make run
make -C haskell
make[1]: Entering directory '/home/racko/gcc-explorer/haskell'
ghc -package ghc demangle.hs
Linking demangle ...
/usr/bin/ld.gold: error: cannot find -lHSghc-8.2.1
/usr/bin/ld.gold: error: cannot find -lHSterminfo-0.4.1.0
/usr/bin/ld.gold: error: cannot find -lHShoopl-3.10.2.2
/usr/bin/ld.gold: error: cannot find -lHSghci-8.2.1
/usr/bin/ld.gold: error: cannot find -lHSghc-boot-8.2.1
/usr/bin/ld.gold: error: cannot find -lHStransformers-0.5.2.0
/usr/bin/ld.gold: error: cannot find -lHShpc-0.6.0.3
/usr/bin/ld.gold: error: cannot find …
```

Fixed haskell/demangle linker errors on systems without static ghc libs

---

etc/config/d.amazon.properties

...because it supports a much newer dlang version (2.074) compared to GDC 5.2.0 (dlang 2.066).

Use LDC 1.4.0 as default D compiler

---

static/cfg-view.js

While working on a custom RTL view pane for GCC, I was mislead by this typo :)
cfg-view.js: add missing 't' in defaultCfgOu*T*put.

Trivial typo fix

---

app.js

The WSL support is beta at best, and is waiting on WSL features/fixes from @benhillis such as exposing Windows environment variables to WSL. But it seemed harmless to integrate, so we did. 
I didn't consider that people would want to run the Compiler Explorer under WSL *without* trying to set up MSVC to run on Windows. My changes broke that scenario, as pointed out in #468. This PR adds an option to explicitly specify that you want to run under WSL.
If you want to run under WSL with Windows support, with this change you will need to invoke as `make EXTRA_ARGS="--wsl"` in order to allow MSVC to find its temporary files. If you do not pass this argument, WSL will work with any non-MSVC compilers as per usual.

Add explicit WSL option to resolve issue #468

---

lib/asm.js
test/cases/kalray-hellow.asm
test/cases/kalray-hellow.asm.directives
test/cases/kalray-hellow.asm.directives.labels

Some assembly syntax can use '='. Refine asm filtering to only
consider as assignements statements of the form:
Some_Name = Some Thing Else
ie. Checks that LHS has exactly 1 element.
Include a new test using such assembly.
fix #620

Better handling of assignments in assembly

---

lib/base-compiler.js

Some passes can produce empty file. Avoid user confusion by making
this emptyness explicit to the user.
This was suggested by @honggyukim

gccdump: display message for empty dump files

---

lib/compilers/fpc.js

This change is not the prettiest, but this way the FPC compiler supports both it's original ASM output and the objdump output

support both asm output and objdumb output

---

lib/base-compiler.js
static/gccdump-rtl-gimple-mode.js
static/gccdump-view.js

Based on 'mylang' example that mostly works correctly for gimple.
Added all RTL classes and ';' prefixed comment.
Still a lot could be done, but it's better than without any color
highlighting.
I don't have the IDE installed here, so I'm note sure the coding style is correct. If needed, I can recheck that later.

gccdump: add basic syntax highlighting

---

Makefile

Currently Makefile only checks if the node is v8, otherwise it just
shows a warning then stops.
This patch is to fix Makefile to understand the node version higher than
v8 as well.

build: Fix node version check to v8 or higher

---

Makefile

It'd be better to add an warning message if node version is higher than
the tested version.
Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

build: Add an warning when node version is higher than tested version

---

README.md

It'd be better to have color in JavsScript code in README.

doc: Add syntax highlighting for javascript in README

---

static/d-mode.js

- Support `` `wysiwyg` `` strings.
- Fix `/+ nesting /+ block +/ comments +/` highlighting
- Add language configuration for D, so that the editor auto-indents and adds closing braces as you type (you may also want to do this for other third party languages such as rust or swift).

Add improvements to D language support in editor

---

README.md

easy to find regardless, but still

slack channelname fix

---

static/output.js

Make information more compact to allow for more program output. 
Do not print compiler return code on successful execution
Print console output with monospaced font
Print console stderr with red colour

Improve compiler/execution/program output

---

lib/base-compiler.js
lib/compilers/argument-parsers.js
static/compiler.js
static/gccdump-view.js
views/templates.pug

Try to disable view's UI when an invalid compiler (ie. non-GCC) is
selected after the view is opened.
Also changed the hover tip for gccdump to be more homogeneous with
other buttons.
fix #638 
I've decided to follow the «quick and not so clean» path, instead of trying to refactor the compiler type system (could be a good exercise, but ti would take weeks before I could come up with something...)

gccdump: disable view when invalid compiler selected

---

README.md

it was userOptions instead of userArguments.

Fix & indent the JSON example in README.md

---

Makefile

I discovered an issue with commit 43c16a on WSL. Changes to the makefile used $(PATH). This doesn't do well on filesystems that allow spaces or parentheses (like Windows...)
This should be equivalent and additionally should improve the state of the world on Linux in case anyone is foolish enough to use a path with spaces in it.

Generalize PATH for spaces in PATH

---

lib/asm.js
test/cases/bug-577_clang.asm
test/cases/bug-577_clang.asm.directives
test/cases/bug-577_clang.asm.directives.labels
test/cases/bug-577_gcc.asm
test/cases/bug-577_gcc.asm.directives
test/cases/bug-577_gcc.asm.directives.labels
test/cases/bug-577_icc.asm
test/cases/bug-577_icc.asm.directives
test/cases/bug-577_icc.asm.directives.labels

Fixes label indentation and recognition for GCC and ICC. This will enable tracking and correctly handle hiding showing unused labels that were defined in inline assembly.
Included Clang output testcase for reference from example in #577 
Current situation where labels are shown incorrectly in GCC and ICC: https://godbolt.org/g/v5uvQL

Label indentation fixes when using inline assembly

---

lib/compilers/pascal.js
test/pascal-tests.js

Tried to make it flexible but ran into trouble in pascal-support.js so I just force compileFilename back to being output.pas

Pascal: Always use output.pas as filename, otherwise things will break.

---

c-preload/compiler-wrapper
etc/config/c++.amazon.properties
lib/cl-support.js
lib/compilers/WSL-CL.js
lib/compilers/Wine-CL.js
test/win-path-tests.js

Not too happy about this code, but it does work.
Is WSL-CL in use? Should probably change it for that one as well..
(As to setting undname as the demangler in the properties files, before that happens I should probably find out what .dll's undname needs and which ones should switch to native windows dll's instead of the Wine dll's)

Demangling for MSVC CL when using undname.exe

---

static/compiler.js
static/diff.js
static/editor.js

Currently the font of the editor is set to a specific monospace font without explicitly being marked as `monospace`. In the case where user use their own font settings to show the webpage based on whether a fontFamily is monospace or not, not explictly marking the fontFamily to be monospace would result in the content being rendered by a non-monospace font in user's settings. This patch is intended to fix this problem.

explicitly specify editor's font to be monospace

---

static/editor.js

To reproduce: 
Run as a single language eg `make EXTRA_ARGS="--language=pascal"`
Open CE in a browser
Stop CE and run it with a different language eg `make EXTRA_ARGS="--language=c++"`
Reload CE in the browser and it attempt to read the now missing pascal language info to create the editor.

Don't attempt to use the default language from the client's local storage if it no longer exists

---

static/compiler.js

supportsBinary on the clientside is an object with the languages, not a boolean like supportsExecute

Fix for supportsBinary

---

app.js
lib/handlers/api.js
test/handlers/api-tests.js

I noticed the described API functions in the Readme didn't actually exist, so this adds /api/languages and /api/compilers/:language
But you could also delete them from the Readme

Make API match the documentation

---

app.js

The !! returned true even if all the properties were false
Fixes #722

Hide execute button when execute is disabled on all compilers

---

lib/compilers/WSL-CL.js
lib/compilers/Wine-CL.js
lib/compilers/pascal.js

At least not on compilers we're certain to not have anything useful.
Wine compilers take forever with the default gcc argument parser

Don't always use argumentparser

---

static/cfg-view.js
views/templates.pug

It looks like vis.js hierarchical layout doesn't work too well on graphs with loops. Added better layer assignment logic and button for disabling/enabling physics.
Example with old version on the left, new one on the right.

Improve cfg layout.

---

app.js

Closes #828
As mentioned in the issue, this is a minimal change to prevent this specific crash; I suspect more code is relying on the assumption that `compilerPropsL` and/or other functions always return a `string`.

Fix crash on startup when a library's `listedVersions` is a single number

---

etc/config/c++.amazon.properties
etc/config/c++.amazon.win32.properties
etc/config/c++.danger.properties
etc/config/c++.defaults.properties
etc/config/c++.lud-mgodbolt01.properties
static/compiler.js

When using libraries with compiler explorer, numerous warnings are often raised in library headers. For example, this snippet, when compiled with clang `-Weverything`
```c++
#include <boost/locale.hpp>
template std::string boost::locale::conv::utf_to_utf(const char[], method_type);
```
[raises over 11000 warnings, all within Boost header files, before the process is killed.](https://godbolt.org/g/gtq1ih)
This is a semi-contrived example but not unusual.
Except for certain niche use cases (e.g. auditing the library for quality) raising warnings inside the library headers is unlikely to be desirable behavior for users.
Fortunately, there is a simple solution, setting search paths for library headers with the [`-isystem`](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html) flag …

Quiet warnings in library headers by setting include paths with -isystem on compilers that support it

---

etc/config/llvm.amazon.properties
etc/config/llvm.default.properties
examples/llvm/default.ll
lib/compilers/llc.js
lib/compilers/opt.js
lib/handlers/compile.js
lib/languages.js
test/llvm-ir-tests.js

Only basic support. `opt` compiles to LLVM IR instead of assembly, Monaco uses the `asm` highlighter and execute doesn't work for `llc` and `opt`, but `clang -x ir` works well enough, that I don't care enough to fix the others.
The properties I used are the following:
```properties
compilers=&clang:&llc:&opt
group.clang.compilers=irclang600
group.clang.intelAsm=-masm=intel
group.llc.compilers=llc600
group.llc.compilerType=llc
group.llc.supportsExecute=false
group.opt.compilers=opt600
group.opt.compilerType=opt
group.opt.intelAsm=
group.opt.supportsBinary=false
group.opt.supportsExecute=false
compiler.llc600.exe=/usr/local/bin/llc
compiler.llc600.name=llc 6.0.0
compiler.opt600.exe=/usr/local/bin/opt
compiler.opt600.name=opt 6.0.0
compiler.irclang600.exe=/usr/local/bin/clang …
```

Added basic support for LLVM IR

---

lib/compilers/pascal.js
lib/utils.js
test/pascal-tests.js
test/utils-tests.js

So that errors get highlighted for pascal just like for other compilers,
also removes the sourcecode temp folder from the output filenames

Pascal error output

---

app.js
docs/SystemdSocketActivation.md
package.json

I made a small modification to `app.js` to allow starting compiler explorer by accessing it's socket, using [Systemd socket activation](http://0pointer.de/blog/projects/socket-activation.html). A rather crude time-out system (disabled when set to `0` seconds by environment variable) is set to a default of 5 minutes.
There is a document with templates for the required Systemd socket and service files.

Add Systemd socket activation support

---

package.json
yarn.lock

I think this is needed, because there's no make on Windows, and this actually makes the website all fancy and ready.
This way you can do "yarn webpack" before doing node app.js and things will work

yarn dev for easier running without needing make

---

lib/base-compiler.js

I may have submitted this in the past, but cannot find the PR.
I believe the objection in the past is that this option should be a parameter/configuration option in the compiler properties. I hope that until then, this small addition is acceptable to enable CFG for more compilers.
(btw, my hunch is that `rustc` will also just work)

Enable CFG (Graph Output) for LDC and GDC compilers.

---

README.md
app.js
etc/config/compiler-explorer.amazon.properties
etc/config/compiler-explorer.beta.properties
etc/config/compiler-explorer.defaults.properties
static/sharing.js
static/urlshorten-google.js
static/urlshorten-none.js
views/templates.pug

These small changes make it easy to drop in an alternate url shortening service by simply dropping in a file like `static/urlshorten-homegrown.js` and setting `urlShortenService=homegrown` in an appropiate `.properties` file.
This should improve the situation for running internal compiler-explorer instances without risking leaking any code.

Switchable urlshorten

---

lib/compilers/ldc.js
test/d-tests.js

This is a proof-of-concept implementation that works locally :-)
LDC outputs an extra file when the `-vcg-ast` option is passed. The extra file is `<inputfile>.cg`, i.e. `.cg` is appended to the full inputfile path. This PR loads that file (using `cat` as is done for the asm output), which can then be output to screen without any parsing (for example, demangling is not needed).
Notes:
- this uses the "Clang AST output" view button. Perhaps rename the button to "AST output" ? 
- syntax highlighting (D syntax) could be applied to the AST view.

Add AST output to LDC.

---

lib/compilers/golang.js
test/golang-tests.js
test/golang/bug-901.asm
test/golang/bug-901.output.asm

Fixes unknown line number causing asm cut-offs from Go 1.10 output (issued raised in #901)

Go Fix <unknown line number> lines

---

etc/config/analysis.amazon.properties
etc/config/analysis.defaults.properties
examples/analysis/default.asm
lib/base-compiler.js
lib/compilers/analysis.js
lib/languages.js
static/compiler.js
test/analysis-tests.js

Fixes https://github.com/mattgodbolt/compiler-explorer/issues/861
This is a first pass, and I basically had to poke at the UI to make it "work" well enough. For now I'm filtering the "cosmetic" types of filters so they don't run on analysis tools.
Is there a way to pre-populate the "compiler options" field, so I can add something like -mcpu=btver2? Otherwise the default might not output anything.
I tried to add as little code as possible, but do ask for changes if you'd prefer to have this done some other way. (For example, I couldn't make the buttons "inactive" easily, so I just filter the options out in getEffectiveFilters)
Thanks a lot for gcc-explorer!
Filipe

Add "Analysis" class and llvm-mca as its first client

---

lib/base-compiler.js

Even if the compiler crashes, the gcc dump files can be useful (to say
the least). Try to attach the dumps inconditionnaly of the error
state.
fixes #913

Always try to attach gccdump info

---

lib/properties.js
test/example-config/cases.test.properties
test/properties-test.js

It might break 3rd party configs in some obscure way, but after looking
at how it might happen, I can't see obvious reasons not to implement it
This is a PR as opposed to a direct commit so I get the opportunity to get called out if I'm breaking something unintended
Fixes expected-lite (#935) not working properly

Avoid 0X.. property values to be parsed as ints

---

app.js
etc/config/c++.defaults.properties
etc/config/compiler-explorer.defaults.properties
etc/config/pascal.defaults.properties
lib/asm-raw.js
lib/asm.js
lib/asmregex.js
lib/base-compiler.js
lib/cl-support.js
lib/compiler-finder.js
lib/compilers/WSL-CL.js
lib/compilers/Wine-CL.js
lib/compilers/pascal.js
lib/demangler-cpp.js
lib/demangler.js
lib/exec.js
lib/pascal-support.js
lib/symbol-store.js
test/demangle-cases/bug-515.asm
test/demangle-cases/bug-515.asm.demangle
test/demangle-cases/bug-660.asm
test/demangle-cases/bug-660.asm.demangle
test/demangle-cases/bug-713.asm
test/demangle-cases/bug-713.asm.demangle
test/demangler-tests.js
test/pascal-tests.js
test/symbol-store-tests.js

Should fix https://github.com/mattgodbolt/compiler-explorer/issues/713 and https://github.com/mattgodbolt/compiler-explorer/issues/515
Todo
Check if it still works for
- n/a Go
- n/a Haskell
- n/a ispc

Demangling changes

---

etc/config/c.amazon.properties

As stated on #969, msvc supports adding `/TC` to compile as C, so we add them there for ease of use
Closes #969

Msvc in C compilers list

---

lib/demangler.js
lib/exec.js

Demangler output was truncated, so a lot of demangled labels were left out.
I tried adding the testcase, but that caused too much memory use in testing.
Demangling definitely is slow in these cases, but haven't found a way yet to speed it up.

Longtextdemanglefix

---

rust/Cargo.lock

`rustc-demangle` added macOS support in 0.1.5 or 0.1.6. I just ran `cargo update` to update all the dependencies of `rustfilt` so that demangling works on macOS.
Tested with Rust 1.21.1 on macOS 10.13.5.
Also, I double-checked the diff to make sure I wasn't deleting Go ;)

Update rustfilt dependencies to support demangling on macOS

---

static/sharing.js

Turns out `click.editable` isn't fired when another dropdown is clicked, meaning this callback is never called. When changed to `mouseup`, the callback is called and the Share menu is successfully closed.
Also, it looks like this could also be solved by specifiying the layout properly in `views/index.pug` (like the Other and Policies dropdowns are specified), but that seemed like a larger fix. Plus this got the job done :)
Fixes #1011

Fix nav-bar Share overlapping other dropdowns

---

etc/config/c++.amazon.properties

ellcc supports the same set of options as Clang to emit Intel syntax output, so I've added the necessary line to enable Intel syntax support

Add Intel syntax support for ELLCC. Fixes #1014

---

etc/config/llvm.default.properties

Just saw this while browsing the source code. I assume it was a typo?

fix typo in llvm.default.properties

---

etc/config/c++.amazon.properties

This is an old version which had a different directory structure
and as a result different include paths. Since this version is
quite old, I don't think it adds much value.
Removing it to avoid confusion among users.

nlohmann json: Remove version 2.1.1

---

etc/config/c++.amazon.properties

I added new version (branch) of CTRE library (there will be another pull request in Image repo)

CTRE with two different branches (for backward compatibility)

---

etc/config/compiler-explorer.amazon.properties
etc/config/compiler-explorer.beta.properties

`s3.amazonaws.com` doesn't support IPv6. The corresponding dualstack endpoint is `s3.dualstack.us-east-1.amazonaws.com` (note that `s3.amazonaws.com` is actually in the us-east-1 region). Refer to [S3 dualstack documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html) and [the S3 endpoint list](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for more information.

Change S3 endpoints to dualstack

---

lib/compiler-finder.js
lib/compilers/win32.js
lib/compilers/wsl-vc.js

Sometimes, it's important to be able to set environment variables for the VC++ compiler. This, specifically, is for experimental `-analyze` switches.

Add the ability to specify environment variables (on windows)

---

CONTRIBUTORS.md
etc/config/zig.amazon.properties
etc/config/zig.defaults.properties
examples/zig/Sum_over_array.zig
examples/zig/default.zig
lib/base-compiler.js
lib/compilers/zig.js
lib/languages.js
static/modes/zig-mode.js
static/panes/editor.js
views/head.pug

Closes #1060.
Should be self-explanatory.
I've added a `preProcess` hook in the base compiler to modify source prior to compilation. In the case of Zig, we want to unconditionally inject a cleaner panic handler function to minimize the verbosity of the output assembly. I considered `stubText` or adding an unconditional `stubTextAlways` property but this isn't runtime configurable based on other things (such as injecting a different handler based on the version). Right now we aren't doing anything smart so this could be a property.
I'll follow up with an accompanying PR on the image repository tomorrow.

Add zig support

---

etc/config/c++.amazon.properties

As suggested by @mgehre - https://github.com/mattgodbolt/compiler-explorer/pull/1090#issuecomment-424933075, this bumps the gcc toolchain version for clang trunk to 8.2.0.

Bump gcc toolchain to 8.2.0 for clang trunk

---

app.js
lib/handlers/api.js

It hit me that the defaultCompiler was missing from the API calls, so I added it to the /languages call.
I also added a new /api/libraries/:language to fetch the available libraries and version.
One thing that surprised me somewhat is that the library id/version isn't actually sent along with the compilation command, but only -I"include path" is added to the userArguments. Which is fine for C++, but I can imagine things might change once other languages get libraries added as well.
It's something to think about.

Add defaultCompiler to api/languages, and add api/libraries

---

etc/config/fortran.amazon.properties
etc/config/fortran.defaults.properties
lib/compilers/fortran.js

As suggest by @partouf this adds a compiler specific script for Fortran, moving compilation to the temp directory which holds the source. Doing this will enable the compiler to generate .mod files if needs be. 
This should fix #1123.

Adding Fortran specific compiler script to enable .mod files.

---

README.md
lib/base-compiler.js
lib/handlers/compile.js
static/panes/compiler.js

Recompile even if three's a backend cache too. Will mean we can enable file/s3 caching on the backends.

Ensure clicking reload forces a recompile on the backend

---

lib/compilers/golang.js

Related to https://github.com/mattgodbolt/compiler-explorer/issues/1142
With this change you can set the GL GO arguments to -m -l, and the escape analysis will show up in the output window.
It was previously filtered out.

Golang show "Stdout" in output

---

docs/WindowsNative.md
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
lib/asm-parser-vc.js
lib/asm-parser.js
lib/compilers/win32-vc.js
lib/compilers/win32.js
lib/compilers/wine-vc.js
lib/exec.js
lib/map-file-vs.js
lib/map-file.js
lib/pe32-support.js

Support for Binary mode for MSVC via objdump.
Requirements for binary mode are that the LIB environment variable contains the paths to at least (replace various version numbers):
* C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/**lib**/x64
* C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/**um**/x64
* C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/**ucrt**/x64
But since it requires the Windows SDK kit, it's not possible (afaik) to run it on the Amazon servers, so I disabled that for now.
So this PR is more of a heads up for @ubsan 
On Windows I have tested this with the objdump.exe from this mingw binary package: https://sourceforge.net/projects/mingw-w64/
Note that it isn't possible to show line colouring, as the VS map file does …

Binary support for MSVC

---

etc/config/c++.amazon.properties
lib/tooling/pahole-tool.js
static/panes/compiler.js
views/templates.pug

This PR adds the great [Pahole](https://linux.die.net/man/1/pahole) tool, a tool that shows the layout of data structures inside elf files, to Compiler Explorer as a compiler tool.
Depends on [compiler-explorer-image PR 138](https://github.com/mattgodbolt/compiler-explorer-image/pull/138)

Add pahole as compiler tool

---

lib/compilers/golang.js
test/golang-tests.js
test/golang/bug-901.output.asm
test/golang/labels.asm
test/golang/labels.output.asm

Rewrite PC jumps with labels so that it's clear where the jumps are to.
Labels are generated in the format `qualified_func_name_pc#`. With this addition the code was getting somewhat messy so I took the liberty of refactoring it a bit, I hope that's alright.
Thanks in advance for reviewing!

go: replace PC jumps with labels

---

CONTRIBUTORS.md
etc/config/c.amazon.properties

Using AT12.0 and clang in C language too since we have it compiled.
Thanks @mattgodbolt.

Add POWER AT12.0 and clang compilers for C based off existing crossbuild-ng

---

lib/cfg.js
lib/utils.js
test/cases/cfg-clang.split.json
test/utils-tests.js

Fixes incorrect label when there are multiple spaces between label and comment. See example in #887.

Trim trailing whitespaces when removing comments.

---

lib/base-compiler.js
lib/cfg.js
lib/compilers/ispc.js
lib/compilers/rust.js
lib/compilers/swift.js
lib/compilers/zig.js
test/cfg-tests.js

Code for handling clang should more or less work with other LLVM based compilers like rust,swift, zig. 
Locally verified that it works with rust and zig. For swift and ispc was able to only check the asm output in compiler explorer due to compiler installation being more difficult.
Also enabled cfg for gcc, it should work the same as g++.

Enable cfg for x86 LLVM based compilers and gcc.

---

etc/config/c++.amazon.properties

This accompanies the pull request for adding `clang-parmexpr` to the image. I did not run the tests against the image itself, but `make check` passes and `make` runs.
Thanks!

Adds clang-parmexpr compiler

---

etc/config/c++.amazon.properties

Closes #844
Seems to be GCC compatible, so it was pretty easy to add.
Haven't done binary support, so I have disabled that for now. (so including pahole)
I disabled MCA because it outputs 32bits asm (though it did work sometimes)

Support DJGGP compilers

---

lib/compilers/ocaml.js

This should fix the linking error during the compilation.

OCaml: add compiler flag preventing binary creation

---

etc/scripts/find-node
etc/scripts/find-yarn

By default FreeBSD does not have the Bourne-again shell (Bash)
installed.  Therefore, the system fails to execute two ``find'' scripts
(etc/scripts/find-node and etc/scripts/find-yarn) running by the
Makefile within the `.node-bin` and `.yarn-bin` targets.
I see nothing Bash-specific in those scripts.  Also I believe that
`[[ expression ]]` commands in those particular cases can be safely
replaced with the `test` built-in commands.
With these changes I can now run a local ``Compiler explorer'' instance
on FreeBSD.
Please review.

Make ``find'' scripts compatible with the Bourne shell

---

CONTRIBUTORS.md
lib/compilers/argument-parsers.js
test/compilers/argument-parsers-tests.js

Fixing #1273.
All compilers featured on https://godbolt.org support the command line option `-fno-crash-diagnostics` *except 3.0.0*.
- There are a few compilers with "clang" in the name that I couldn't place, I left those untouched.
- I couldn't test the setup because I don't have all compilers installed on my machine.

Prevent clang from creating unwanted temporary files

---

CONTRIBUTORS.md
lib/base-compiler.js
test/base-compiler-tests.js

This allows cfg to work even for cross gcc (with names like `foo-bar-gcc`).
+ I'm adding my name in the contributors :)

Change the check for cfg-able compilers

---

app.js
lib/storage/storage-null.js
views/templates.pug

This simply adds an `enableShort` option that enables/disables short links. The motivation behind this is that short links seem to be the only state feature, and disabling those will make compiler explorer stateless and very much possible to distribute across several machines, such as using Kubernetes.

Add option to toggle the availability of short links

---

CONTRIBUTORS.md
lib/languages.js
static/modes/asm-mode.js
static/modes/ptx-mode.js
static/panes/compiler.js

This PR is a follow-up to #1293 
If have added a possibility to define a separate monaco language definition for the disassembly in the output pane via a `monacoDisassembly` key in `lib/languages.js`. Previously 'asm' was hardcoded, which is still the fallback value if no custom language definition is given.
The `cuda` language now uses a custom `ptx` monaco language for disassembled code, which highlights registers and predicated instructions correctly.
Best regards: Sebastian

Fix cuda disassembly code highlighting

---

etc/config/rust.amazon.properties

This allows using llvm-mca with Rust directly.

Make llvm-mca available to Rust

---

etc/config/c++.amazon.properties

I thought I'd come back and revisit this, as I wanted to play around with compiler-explorer today and noticed it still doesn't support RISC-V.  There are a handful of existing issues
https://github.com/mattgodbolt/compiler-explorer/issues/334 : Clang support, which has been partially resolved and should be fully resolved by this commit.
https://github.com/mattgodbolt/compiler-explorer/issues/965 : GCC support, which should be fully resolved by this commit.
https://github.com/mattgodbolt/compiler-explorer/pull/964 : An obsolete pull request only containing the GCC support, that I closed because crosstool-ng didn't support RISC-V at that time.
https://github.com/mattgodbolt/compiler-explorer-image/pull/176 : A pull request to add a RISC-V GCC 8.2.0 to the image.
There's a lot of information …

Add Support for RISC-V GCC and 64-bit RISC-V LLVM

---

lib/compilers/ldc.js

I think it'd be nicer if the BaseCompiler code would also check for `<outputfile>.ll` but for reviewing I added the special code to `ldc.js`.
What's a little unfortunate is that the command to generate the LLVM IR will also create the ASM `.s` file, so it will overwrite the one already generated (or will things go wrong when the two LDC invokes are both writing to it at the same time...?). We can disable writing to the `.s` file when creating LLVM IR (`-output-s=false`) but then we'd have to change the compiler flags because the LLVM IR will be written to the output filename specified in those compiler flags...

Add LLVM IR view for LDC.

---

etc/scripts/find-node

If system's node is overriden by something in PATH, having NODE_DIR
empty will cause the script to still use node found in /bin/.
Only consider the first case if NODE_DIR is not empty.

Do not use system node by error

---

static/modes/pascal-mode.js

Should resolve #1352
Nested commenting styles like Pascal allows is not supported. Not entirely sure how to go about that.
But it's an overall improvement anyway.

Improved comment detection in pascal mode

---

etc/config/c++.amazon.properties

https://godbolt.org/z/5cq08h
Adding `-g0` does break code-to-source matching, but I think that's better than segfaulting (and people can always add back `-g` manually).

Add "-g0" to the P1144 compiler's command line, until I figure out what's wrong with DWARF

---

.eslintrc
CONTRIBUTORS.md
app.js
lib/base-compiler.js
lib/compilation-env.js
lib/compilers/argument-parsers.js
lib/handlers/compile.js
test/compilers/argument-parsers-tests.js

add something like the following to `compiler-explorer.local.properties`
```
compilerCacheConfig=OnDisk(./lib/storage/data/cache, 50)
```
Startup when the cache is empty is marginally slower, but subsequent startups can be an order of magnitude faster, because no compilers will be executed during startup.
With 70 compilers installed locally the reported startup time went from 11604ms to 1711ms.
With 3 compilers installed locally the reported startup time went from 1742ms to 1429ms.
Definitely useful during development, although in production the usefulness really depends on how fast S3 caching would be.  It may simply be faster to execute the compilers off EFS than to make several hundred round trips to S3.

Allow caching of compiler version and argument information to improve startup time

---

etc/config/c++.amazon.properties

Fixes #1418
Enabled and tested binary mode for all cross compilers
* Didn't test the WinCE one
* Some had problems linking, so I disabled it (risc-v, msp, ppc clang)

enable binary mode for crosscompilers where possible

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

The main side of https://github.com/mattgodbolt/compiler-explorer-image/pull/215 and https://github.com/mattgodbolt/compiler-explorer-image/pull/213, with 213 needing to still be merged to get that compiler added. As discussed in the comments of https://github.com/mattgodbolt/compiler-explorer-image/pull/215, adding a new Platform Specific group to make is possible to add more platform specific compilers in the future, with potential things like Arduino.

Add Raspbian and FRC compilers to supported compilers

---

lib/handlers/compile.js

When a node error occurs runtime, it will return an object with the error information but with .code
So check for stack first, that's obviously an internal error, else handle compiler errors, else etc

Improve unexpected errors' logging

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/223
Adds the 5.4.0 compiler from the arduino build, and platform specifics for arduino uno and arduino mega. These will allow #include <Arduino.h> as well for the platform specifics, with the proper things defined to make them work properly.

Add arduino compilers, with uno and mega platform specifics

---

etc/config/c.amazon.properties

This changes "carduinouno198" to "carduinouno189" in the name line. The typo caused the ID to be displayed as the name on godbolt.org.
I didn't really test anything (I'm actually doing this entire thing from the Github website :stuck_out_tongue:), but I doubt I managed to break anything by correcting this typo

Correct typo in /etc/config/c.amazon.properties

---

lib/base-compiler.js
static/panes/executor.js
views/templates.pug

Divides up the different parts of execution, and adds toggle buttons to turn those parts on and off.
**Just Stdout active**
**Arguments and Stdin**
**Everything on**
**Hidden labels**

Alternative UI layout for Executor pane

---

.gitignore
.travis.yml
Makefile
package.json
static/main.js

- Excludes `.github`, `.idea`, `.nyc_output`, `coverage` and `tests` from the dist output file generated by Travis.
- Makes the linter not waste time fixing the errors that it finds on the files (With the drawback of having to duplicate some lines. Maybe there's a way to pass arguments to npm scripts? Would be great to hear about those
- Tests should now run only once. The codecov report is generated directly from the test pass

Trims dist output and makes test run only once

---

static/themes/dark-theme.css
static/themes/default-theme.css

This should eventually be a patch for golden-layout.  I recreated the entire icon set for golden-layout and then went to submit a PR upstream only to find golden-layout is currently a bit of a mess.
Full icon set here for reference: https://gist.github.com/apmorton/56a1c54c20ada10e670066d2594d8bbb
Before/After at 400% zoom:

Replace golden-layout icons with SVG versions to improve high DPI displays

---

static/explorer.css

Override monaco line number cursor to work around comically large cursors on high DPI systems

---

package-lock.json
package.json
static/main.js
static/themes/dark-theme.css
static/themes/default-theme.css
views/monaco.pug
webpack.config.js

I bisected this back to 322086b923bcb40b1f336cc4ee49c9e97c71acc4, which introduces a client-side dependency on [String.prototype.endsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith), which is part of ES6 (and missing in IE11).
There is still at least one major UI issue with the site on IE11, but its "workaroundable" (and maybe not hard to fix, but I haven't looked yet).
You must resize the IE11 window in both width and height multiple times before the goldenlayout windows populate.
When the page first loads they will look like this:
I haven't done an exhaustive test of the site in IE11, but it at least loads and basic functionality works now.
Worth mentioning that es6-shim is almost 60k of javascript to pull in. It may be worth …

Fix support for IE11. Closes #1258

---

app.js
etc/config/compiler-explorer.amazon.properties
lib/handlers/health-check.js
package-lock.json
package.json
test/handlers/health-check-tests.js

Just happened in beta.
In nginx logs:
```
[04/Jul/2019:18:06:28 +0000] "GET /healthcheck HTTP/1.1" 200 32 "-" "ELB-HealthChecker/2.0"
[04/Jul/2019:18:06:32 +0000] "GET /beta HTTP/1.1" 499 0 "-" "Amazon CloudFront"
```
the node app continued to respond successfully to `/healthcheck` when all other requests would hang indefinitely (eventually resulting in 499 when the client hangs up).
Root cause was NFS mount being hung for some reason.
The following resolved the issue:
```
umount -l -f /opt
mount /opt
mount /opt/wine-stable
systemctl restart compiler-explorer
```
Perhaps `/healthcheck` should do one of the following:
- run a binary configurable via properties and expect exit code 0
- serve a static file configurable via properties
In either case we could put the corresponding file on the …

[BUG] /healthcheck doesn't detect NFS mount failure

---

docs/API.md
lib/base-compiler.js
lib/handlers/compile.js
lib/options-handler.js
static/libs-widget.js
static/panes/compiler.js
static/panes/conformance-view.js
static/panes/executor.js
test/options-handler.js

Change in the Compile API to add libraries instead of having to manually supply include paths.
Added a small change to properties path splitting on win32 (didn't want to break current unix implementation)
With these changes, the compilation and executable caching key will change, but link sharing should remain intact.
Fixes https://github.com/mattgodbolt/compiler-explorer/issues/1478

Compile API supplying libraries

---

app.js
lib/options-handler.js
views/head.pug

This allows the client options to be cached between requests that currently would not be.
For example, someone visits `https://godbolt.org` (so their cache is populated locally), and then clicks a shared link: `https://godbolt.org/z/xxxx`.  Before this change the shared link response also must include the entire contents of the client side options.
After this change only the "extra" client side options are included in the html content.
The otherwise largely invariant bulk being in `/client-options.js`, which can be cached client side.
Locally I measured approximately a 300ms decrease in response time for `/` when applying this change. (using `make run`, refreshing the page several times before measuring to ensure the app is hot).
Additionally, because we include no user-controlled options …

Move bulk of client side options to non-inlined script

---

lib/compiler-finder.js
lib/handlers/compile.js
package-lock.json
package.json

It is now also possible to use remotes that themselves have a `httpRoot` set.
`compilers=godbolt.org@443/staging`

Fix external compilers when httpRoot is set

---

docs/AddingATool.md
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
lib/base-compiler.js
lib/exec.js
lib/options-handler.js
lib/tooling/base-tool.js
lib/tooling/clang-query-tool.js
lib/tooling/clang-tidy-tool.js
lib/tooling/llvm-mca-tool.js
lib/tooling/pahole-tool.js
lib/tooling/readelf-tool.js
static/explorer.css
static/panes/compiler.js
static/panes/executor.js
static/panes/tool.js
static/themes/dark-theme.css
static/themes/default-theme.css
static/toggles.js
views/templates.pug

Current features:
* No more needing to add tool manually to the UI
* Extra textarea input that's stdin by default
* Internal rewrite of arguments passed to runTool changed to object with all the information any tool should need
* Vertical resizing for textarea stdin (also for execution)
* Pahole for Pascal FPC
Todo:
~~Support syntax highlighting for stdin~~ - this would make vertical resizing more problematic

Tool improvements

---

.eslintrc
app.js
etc/config/compiler-explorer.amazon.properties

This is one of the first steps in identifying long running synchronous code paths that are causing our ELB node failures.
Enabling this in production has very little performance impact, and should let us see how often our nodejs event loop is being blocked and for how long.
[At least one known case](https://godbolt.org/z/Rm0SnL) produces a event loop lag of 9 seconds on my local machine.
This basically works by taking the current time, setting a timeout for some number of milliseconds, and then measuring how long it has actually been once the callback fires. This happens continuously in a `setImmediate` loop, with `eventLoopMeasureIntervalMs` determining the desired measurement frequency.
`eventLoopLagThresholdWarn` and `eventLoopLagThresholdErr` are the lag duration in milliseconds that …

Add basic event loop lag logging capability

---

static/compiler-service.js
static/hub.js
static/policies/privacy.html
static/settings.js
views/popups.pug

Make explicit the fact we may wish to use people's code for debugging
and diagnosing CE issues. Puts a hard limit on a week for storing
people's code, and only in the case it caused an issue.
Comments welcomed on the wording, and the "one week" maximum. Is this long enough? Could we shorten it? Can we mechanically enforce (e.g. the "long query" bucket has a one-week autodelete or similar?)

Updates to Privacy Policy

---

package-lock.json
package.json
static/panes/editor.js

Escape has a nice solution, but Insert required some faking the keypress magic, unfortunately.
Toggle problem will be fixed with https://github.com/brijeshb42/monaco-vim/pull/37

Enable escape and insert to work properly in VIM mode

---

static/libs-widget.js
static/panes/compiler.js
static/panes/conformance-view.js
static/panes/executor.js

Makes use of the library listing on a specific compiler to change the list of libraries.
Adds update of libraries when changing compiler.
Only client-side changes, because we already had libraries per compiler.
Fixes https://github.com/mattgodbolt/compiler-explorer/issues/1572
Needs a bit more testing.
For conformance view only the libraries available in all selected compilers are listed.

Refresh libraries per compiler

---

etc/config/cuda.amazon.properties
lib/asm-parser.js
lib/base-compiler.js
lib/compilers/nvcc.js

- Enables "Compile to binary and disassemble the output" for CUDA source.
- Parses labels, line numbers, opcodes and disassembly.
- Fixes #946

Add basic support for CUDA native SASS assembly

---

static/explorer.css

Fixes dropdown menus not being displayed if they don't fit on the gl pane
I've tested this and I could not find any issues with it, but I'll let another pair of eyes check it out before merging because if there's any issue, it might be too subtle for me to notice.
Fixes #1441 & related issues reported on Slack

Set overflow:visible in lm_content

---

etc/config/c++.amazon.properties

This PR (hopefully?) adds support for the [NanoRange](https://github.com/tcbrindle/NanoRange.git) library, an independent implementation of the C++20 ranges proposals.
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/261

Add support for NanoRange

---

lib/compilers/ppci.js
lib/tooling/base-tool.js
test/ppci-tests.js

They are already allowed in nearly all places,
the only exceptions being PPCI and tools.
Additionally update PPCI argument blacklist
to include --html-report option.

Allow forward slash in all command line arguments

---

lib/tooling/base-tool.js
lib/tooling/clang-tidy-tool.js

This is following up on my posting on [compiler-explorer-development](https://groups.google.com/d/msg/compiler-explorer-development/Z9qpfvZQk1k/dw0slkh7AAAJ).
I saw undesired (for me) behaviour of compiler-explorer in when using clang-tidy, as shown in [this](https://godbolt.org/z/y2lJ6y) example.  While compilation with clang worked fine, clang-tidy shows a clang-diagnostic-error from missing headers - one that should be found through the settings of libraries.
I claim, when using clang-tidy, one wants to pass the include flags that are given to the compiler also to clang-tidy. Otherwise clang-tidy will fail to work properly (failing to find headers).
Similarly, I assume a user wants settings like (assuming unix/gcc command line interface) `-D... -mavx -std=c++14` when they are specified …

[WIP] pass include flags to clang-tidy

---

test/llvm-ir-parser-tests.js

This removes the 'error: Tried to pass maxLinesOfAsm as a language ID'.
Those are printed when the test creates a LlvmIrParser.

Fix a small error in llvm-ir-parser-tests.js

---

static/themes/dark-theme.css

The compiler output window used a lighter background color than all the other code windows, which decreased the text contrast. Also, the embedded compiler output boxes didn't have a color override, so they displayed as black on dark grey.
Should see if this helps with #1583.

Fix some dark theme backgrounds

---

etc/config/zig.amazon.properties
lib/compilers/zig.js
static/modes/zig-mode.js

this PR depends on mattgodbolt/compiler-explorer-image#272 and adds support for the newest version of zig, updates the syntax, and adds support for emitting llvm ir from zig.
Closes #1328 
on as side note: zig 0.4.0 and trunk seem to be broken but i can't get compiler-explorer to build locally to debug it :/.

Zig update

---

etc/config/c++.amazon.properties
lib/tooling/base-tool.js
lib/tooling/clang-tidy-tool.js
lib/tooling/compiler-dropin-tool.js

I'd like to run tools that are command line compatible with compilers.
More specifically that is [include-what-you-use](https://include-what-you-use.org/) which is clang based and uses the same CLI (with some additional `-Xiwyu --something` flags).
As discussed on slack, for this I need to remove the filter for `/` in the base tool (otherwise include paths don't reach the tool). It could be re-added in `runToolsOfType` in `base-compiler.js`, though as far as I understood the slack discussion there's a preference to be compatible between tools and compilers and allow `/`.
Obviously for this PR to be useful for godbolt.org include-what-you-use needs to be made available on the amazon instance…
For me locally it looks like that:

[WIP] add support for tools that use a compiler command line

---

etc/config/cppx.amazon.properties

Update the CPPX trunk language standard to C++20 to prevent issues with the consteval keyword not being registered.

Update CPPX trunk language standard to C++20

---

lib/asm-parser.js

Fixed an annoying thing in the unittests on Windows

bugfix replace single line /*comments*/

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

Hi folks,
The patch is pretty striaghtfoward (and passess make check) but I wouldn't be surprised if this uncovered issues with armclang++ and/or armflang, since they haven't been enabled before.  Can we try it out on beta?

Add C/Fortran support for Arm Compiler for Linux

---

lib/asm-parser.js
test/cases/bug-1229.asm.directives.labels.comments.json
test/cases/bug-1229.asm.directives.labels.comments.library.json
test/cases/bug-1285.asm.directives.labels.comments.json
test/cases/bug-1285.asm.directives.labels.comments.library.json
test/cases/bug-1285b.asm.directives.labels.comments.json
test/cases/bug-1285b.asm.directives.labels.comments.library.json

E.g. for such directive
.file   1 "/home/user" "example.c"
now will be constructed valid path:
'/home/user/example.c'
instead of this broken path:
'/home/user/ "example.c"'

Fix path handling for clang-style file directive

---

CONTRIBUTORS.md
lib/compiler-finder.js
lib/compilers/zig.js

This fixes #1689 by using the suggestion @andrewrk made.
This also properly disables the demangler for compilers that don't provide one.
(There was a bug where `path.normalize` would turn an empty string into `.`.)

Fix ASM output for the zig compiler

---

static/panes/ast-view.js
static/panes/compiler.js
static/panes/editor.js
static/panes/gccdump-view.js
static/panes/ir-view.js
static/panes/opt-view.js

> Closes #369
Save selections in the editors. This way the links or the embedded
views can scroll to and highlight the area of the saved selections.

Save the selections

---

lib/asm-parser.js
test/cases/kalray-hellow.asm
test/cases/kalray-hellow.asm.directives
test/cases/kalray-hellow.asm.directives.labels

If K1 MPPA compiler gets added someday (see https://github.com/mattgodbolt/compiler-explorer-image/pull/282 ), then this comment parsing tweak should be added.
K1 MPPA uses ;; as a bundle separator (same syntax as IA64,
if it gets added to CE someday...).
The bundle separator must be alone on the line, see for example:
```
ld $r6 = 16[$r20]
addx8d $r9 = $r2, $r5
addw $r10 = $r2, -1
;;
addd $r0 = $r6, $r9
addd $r17 = $r10, 1
cb.wlez $r2? .L3
;;
copyd $r15 = $r0
;;
maddd $r15 = $r17, -8
;;
```
Single ; or ;; followed by any non whitespace before eol still
considered a comment.

Handle K1 MPPA VLIW bundles in assembly

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Here's an attempt at implementing issue #1691
In theory this makes use of the new `gcc` and `g++` built as part of https://github.com/mattgodbolt/compiler-explorer-image/pull/288 - though I don't have the same filesystem layout (hopefully if I messed up the paths, the changes to fix things are obvious).
I've tested a version of this locally by coping and pasting similar lines into my `etc/config/c++.local.properties`.
I ran into an issue with `make check` where the various `test/cases/cfg-clang.*.json` were failing with slight changes in output reported.  I'm assuming that's an issue with the clang I've got installed at this end, and hopefully unrelated to this new code.
For options I put:
- `-fanalyzer` to enable the analyzer
- ` -fdiagnostics-urls=never` since ` …

Add gcc-static-analysis-trunk as a C and C++ compiler

---

CONTRIBUTORS.md
static/explorer.css

When there are enough tabs, you use a dropdown selection to pick the other tabs. This would display under the compiler selection dropdown list, making it very difficult to use.
The .lm_tab dropdown has its z-index set to 5 to show up on top, but it's stuck inside the .lm_header stacking context, so it can't render in front of that. Raising the z-index of that whole stacking context fixes things.
Fixes #1714

Ensure the tab dropdown shows in front

---

static/themes/dark-theme.css

The save/load builds a tabbed list using a .active class to select which tab to show. This class is also used for styling button highlights in pickers. We can remove the bare `.active` and `.active:hover` rules because they exactly match the `.btn-light.active` rules, and every other use of the `active` class also has a `btn-light` class attached to it.
Fixes #1718

Fix dark-mode save/load UI

---

static/explorer.css

This increases the size of the tab bar tabs and buttons on mobile, to make it easier to work entirely in tab mode. The media query for this button size begins at 768px because that's where the top bar UI switches to mobile mode.
Fixes #1717
Standard tab size:
New mobile tab size (~60px tall):

Make tab view tabs larger on mobile

---

static/themes/dark-theme.css

This adds some overrides for the hamburger menu styles in dark-mode, as well as some low-specificity rules for the `fa` icons. As far as I can tell, this doesn't overwrite the manually colored icons: the green and red checks and xs in the status bars seem to all be colored correctly with these rules.
**Before:**
**After:**
Fixes #1720

Fix the contrast on some dark-mode icons

---

lib/compilers/nim.js
test/nim-tests.js

Fix for https://github.com/mattgodbolt/compiler-explorer/issues/1760
Since 1.0.0 the object file in the nimcache folder has changed from `module_name.nim.lang_ext.o` to 
`@mmodule_name.nim.lang_ext.o`.
Tested for 1.0.4 (latest release), fixes the issue

Nim Fix, change in object file name

---

lib/tooling/clang-query-tool.js

This is needed to enable multi-line clang-query commands.
For example: https://godbolt.org/z/9GRpgM should work.

Use a file to execute clang-query commands

---

lib/handlers/asm-docs-api.js
lib/handlers/compile.js
lib/handlers/formatting.js
lib/handlers/health-check.js
lib/handlers/route-api.js
lib/handlers/source.js
lib/shortener-tinyurl.js
lib/storage/storage-remote.js
lib/storage/storage.js
test/handlers/api-tests.js
test/handlers/health-check-tests.js

I discovered res.send() will set cache control headers, content-size,
and content-type, and will to-json objects (setting type to app/json).
Refactored a few things, hit an issue where testing chai http doesn't
seem to want to remember the data (in health check tests); reading the
chai http docs I don't actually think it's supported. Was working by
fluke before.
Took the opportunity to use a few "extract method" in the IDE too to
remove duplicated code (that the IDE was also nagging me about...)

Use res.send() in most cases.

---

Makefile

When compiler-explorer is used as a submodule, it's git-dir is not
in .git.

Make dev target submodule proof

---

etc/config/c++.amazon.win32.properties

Just a small mistake in MSVC compiler name. Not great, not terrible.

Typo in MSVC compiler name (must be x64, not x86)

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties

Add options for compiling with clang for Arm - specifically Armv7,
Armv8 and Armv8.5 using clang 9 and trunk.
Signed-off-by: Dave Rodgman <dave.rodgman@arm.com>

Add arm clang menu options

---

app.js
etc/config/compiler-explorer.amazon.properties
package-lock.json
package.json

Since sentry retails the full request body when `allowStoreCodeDebug` is enabled this will allow us to observe and reproduce successful requests that take an excessive amount of time.
Should help with #1336

Log slow requests to sentry

---

etc/config/assembly.amazon.properties
etc/config/assembly.defaults.properties

fixes #1567 
only enables button so people can check/uncheck it to enable the binary codelens, doesn't change serverside handling

enable binary button in asm to allow codelens

---

etc/config/c.amazon.properties

As discussed in #1807, this adds Hedley to the list of libraries for C.
I couldn't really test this, so please be careful merging!  The libraries don't seem to work on my machine (Fedora 31); both with and without this patch I get an empty list.
I did notice that there are some extra values in this entry (copied from C++) that aren't present in the other C libraries.  I'm not sure if they're desirable or not here, but if not I'm happy to remove them.

Add Hedley to C libraries.

---

lib/logger.js
test/_setup.js
test/analysis-tests.js
test/base-compiler-tests.js
test/cache-tests.js
test/compilation-env.js
test/compiler-finder-tests.js
test/compilers/argument-parsers-tests.js
test/d-tests.js
test/filter-tests.js
test/golang-tests.js
test/handlers/api-tests.js
test/handlers/compile-tests.js
test/llvm-ir-tests.js
test/nim-tests.js
test/options-handler.js
test/pascal-tests.js
test/ppci-tests.js
test/properties-test.js
test/storage/storage-s3-tests.js
test/win-path-tests.js

- suppress log output when running the test suite
- part of this was having to move any log-generating code that was executing outside of test cases into `before` hooks
- optimize test runtime
- `filter-tests.js` was erroneously performing a lot of extra work by running `processAsm` before test case creation
- entire test suite runtime went from ~9s to ~2s on my machine
- fixed a few cases where assertions were happening outside `it` blocks
- these assertions were still happening, but were not actually part of a test case
- I'm not entirely sure what would happen if they failed - probably the entire test suite halting

Perform some general maintenance on the test suite

---

lib/compilers/ispc.js

AVX2 is the most actual target for performance tuning today, so it make sense to target it by default.

Change default target for ISPC to avx2-i32x8

---

static/modes/cuda-mode.js

CUDA has some more keywords beyond the three you listed; see the [programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html). I've added the missing ones (hopefully that covers them all).
**Note**: This PR is _untested_. I have never built or ran compiler explorer myself before. On the other hand, it's a one-liner, so you be the judge of what to do with it...

Added missing CUDA keywords

---

etc/config/d.amazon.properties

This fixes binary linking for LDC >= 1.19. Fixes https://github.com/mattgodbolt/compiler-explorer/issues/1872

Point LDC >= 1.19 to gcc for linking

---

static/toggles.js
views/templates.pug

This PR is as much a "what do you think of the look? as it is a code review. Here I'm trying to reduce the width of widgets in the compile window to help with mobile, as well as tidy up and remove confusion that people have had forever over what exactly `11010` means :)
In this PR:
* Output options are separated and placed on a drop-down:
- compile to binary
- Run the output
- Intel syntax
- Demangle
* Filtering options are separated and placed on a drop-down:
- Unused labels
- ...etc
I changed the "tool" icon to a screwdriver and used the cogs to configure output, and then a filter icon for the filters. The change to `toggles.js` is to prevent propagation which causes the dropdown to close every time you click a button.

Separate filters and output options

---

etc/config/fortran.amazon.properties

It's quite a while since I understood how all this worked, so I hope this doesn't break anything and is correct. I did not run a `make test`, failing to see what this could help for this particular change.
Since invoking `-x f95` for the more recent gcc compilers did work, I assume the gfortran compilers are still automatically installed.  
I did not touch the Intel compilers since I'm less sure those are installed.

Update gfortran compiler versions

---

etc/config/c++.amazon.properties

Add libs.namedtype.name=NamedType
trunk only, from joboccara/NamedType.git
into /opt/compiler-explorer/libs/NamedType
pending tests.
Did I miss anything?
Is it just `make check` to test?

c++.amazon.properties: add NamedType

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Kalray's core has been renamed from k1/k1c to kvx/kv3.
It has been decided to keep old compilers but to mark them
as obsolete.

Rename and update MPPA compiler

---

lib/compiler-finder.js
test/compiler-finder-tests.js

Should close #1949
Initially, I mentioned a prop on the compiler would probably a bad thing, but I realized that if a compiler doesn't support any libraries, you could say 'supportsLibraries=none'. Assuming no library is called none that is!

Limit libraries per compiler

---

examples/rust/Max_array.rs
examples/rust/Max_array_(Optimized).rs

Fix two Rust max_array examples. 
The previous examples failed to compile as `y` was not borrowed as a mutable reference but used to produce a mutable iterator. Changing from `iter_mut()` to `iter()` resolved this issue.

Fix Rust Max_array examples

---

lib/properties.js
test/example-config/cases.test.properties
test/properties-test.js

Parsing versions such as "1.10" results in a "1.1" float, incorrectly
changing the value.
Fixes #1980

Avoid parsing version properties as numbers

---

lib/tooling/PVS-Studio-tool.js

To support different platform options it's better the let pvs-studio-analyzer make the .cfg file by itself.

Turn on the automatic PVS-Studio.cfg generation

---

lib/tooling/PVS-Studio-tool.js

Exclude /opt and /usr for not analyzing the unnecessary files

Exclude directories for analysis

---

lib/compiler-finder.js
lib/options-handler.js
lib/tooling/base-tool.js

If a tool has an includeKey set, then for each compiler, this key is
looked up, and if not 'truthy', then the tool is disabled for that
compiler.

Tools includeKey

---

lib/asm-parser.js
test/cases/bug-1989_sparc.asm
test/cases/bug-1989_sparc.asm.directives.labels

Refs #1989
This only affected weak symbols as normal functions are caught by `definesGlobal`.  Perhaps there should probably be a `definesWeak` regex as well for catching `.weak myfunc` too.
See, for example, the difference between https://godbolt.org/z/rLvijD

Fix asm parser to recognize SPARC function definitions

---

lib/compilers/argument-parsers.js

Hosting on a site with nearly 200 cross compilers, pretty much all are without a capable assembler installed.  One bug I ran into was that when invoking `gcc --target-help` and others, the compiler still creates a dummy file to which the driver attempts to assemble it.  This naturally fails and so the GCC Tree/RTL feature is not picked up.
A few of the cross compilers are for Darwin i686/x86_64.  For both of these targets, `-masm=` is available as an option (it is picked up from the i386 target options).  But the darwin support code will reject it if present on the command-line.  So in order to properly disable, gcc needs to be ran again with `-masm=intel` passed, and if there's an error, we know it is really unsupported.

Pass -fsyntax-only when getting GCC options and test that -masm= is really supported

---

lib/base-compiler.js
lib/handlers/compile.js
static/panes/conformance-view.js

It avoids processing the asm parts if the user does not need it
Maybe another approach would be to always process it and delete it
from the served result, that way we could cache both versions
under the same key.
Test coming tomorrow before merging :)
Closes #2017

Add backend option skipAsm

---

lib/storage/storage.js
lib/utils.js
test/storage/storage-tests.js
test/utils-tests.js

Avoids most of the problems present with the current base64 implementation
Closes #1902

Make url hash a base32 encode

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This adds the [SIMDe](https://github.com/simd-everywhere/simde) library for C and C++. It is a header-only library. Note that I am not affiliated with the simde project. I'm just adding the library, because it would be useful for me and hopefully others too.
Please let me know if there is anything else I have to do.

Add SIMDe library

---

static/panes/editor.js

Hides the context menu when clicking somewhere else in the editor.
Will not hide when you click somewhere within the line number margin. There might be another event for that.
I think this only applies to the Touch interface, as touch/gestures is implemented separately (so they did try to make something out of mobile at some point ;-))

Mobile context menu bugfix

---

static/explorer.css

[Issue 2030](https://github.com/compiler-explorer/compiler-explorer/issues/2030) pointed out that modals are not centred. This pull request fixes that problem by applying `margin: 0 auto;` to the main modal element. In order to maintain the previous 1.75rem spacing around the dialog that stops it running up against the window border, I've added 1.75rem of padding around the parent element.

[ISSUE-2030] Fix modal padding and margin to properly centre dialogs

---

etc/config/fortran.amazon.properties

This is an effort to support LLVM flang compiler which is merged in LLVM project as of now.
The compiler has mostly support till semantic checks.So I think no assembly would be generated as of date.
The codegen to LLVM IR is a work in progress in another github repo, which is planned to be pushed here
in successive PR once the flang works well, and of course first PR.
The FIR branch would help in actual use of godbolt to developers, people interested in learning FIR/MLIR representations
and could help in doing some optimizations studying the IR.

[feature] Basic support for LLVM flang compiler.

---

etc/config/assembly.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

See https://github.com/compiler-explorer/infra/pull/375
I have not updated the default for Fortran since it was not pointing to the latest, is that an omission or intended?

Add GCC 10.2

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add latest release of Kalray MPPA Compiler: ACB 4.1.0 (GCC 7.5 based). Also
changed the displayed names for these compilers to add our own versions (ACB
4.1.0*) along with gcc's version.
Also note that 4.1.0-rc6 is the final version. I've kept the `-rc6` in the paths but
removed it from the displayed name.
It's available at :
https://github.com/kalray/build-scripts/releases/download/v4.1.0-rc6/gcc-kalray-kvx-v4.1.0-rc6.tar.gz

Update Kalray MPPA compiler

---

lib/base-compiler.js
static/components.js
static/panes/compiler.js
static/panes/gccdump-view.js
views/templates.pug

1. This Implements all options that are common for all versions of GCC between 4.0 and 10.2.
These are available in a "Options" drop-down menu on the GCC Tree Viewer pane.
- address
- slim
- raw
- details
- stats
- blocks
- vops
- lineno
- uid
- all
2. Dump passes have been moved into a drop-down menu "Passes" to keep the row tidy.
3. Add inter-procedural analysis dumps to GCC Tree Viewer.  The option -fdump-ipa-all has been around since GCC 4.0, though leaving it default unchecked in the UI.
4. Adds [ON] or [OFF] to the titles of all filter buttons by implementing GccDump.prototype.updateButtons.
Icons have been half randomly chosen.  For the Passes drop-down have used [fa-compass](https://fontawesome.com/v4.7.0/icon/compass), and for Options …

Allow changing the detail level of GCC dumps in TREE and RTL view

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
lib/base-compiler.js
lib/compilers/wine-vc.js
static/panes/executor.js
test/base-compiler-tests.js

Fixes #2180
Fixes #2026 
Fixes #1506

Filter compilers in execution panel

---

etc/config/go.amazon.properties
lib/compilers/golang.js

Fixes #2145 
(Not really sure why you have to repeat the .name properties for Go compilers, but they ain't pretty if you don't supply them a name)

Add WASM variants for GO

---

lib/asm-parser.js
test/filter-tests.js
test/filters-cases/bug-2164.asm
test/filters-cases/bug-2164.asm.directives.labels.comments.json
test/filters-cases/bug-2164b.asm
test/filters-cases/bug-2164b.asm.directives.labels.comments.json

Probably doesn't have to be in hasOpcode() as that's mainly to determine references to labels and .inst won't have that, but still.
Fixes #2164

.inst as an opcode

---

etc/config/c++.amazon.properties

This PR adds the excellent Enoki library to CE.
Enoki is a library for writing scalable, vectorised code. It's an interesting alternative to the already established libraries like xsimd or VCL. Adding it to CE will make it easier to publicly discuss (dis)advantages in the Codegen of the different SIMD libraries.
There's also a infrastructure PR here: https://github.com/compiler-explorer/infra/pull/402

Add Enoki library

---

etc/config/cuda.amazon.properties

See also https://github.com/compiler-explorer/infra/pull/408
Adds [libcudacxx](https://github.com/nvidia/libcudacxx) as an optional library when using CUDA.

Add libcudacxx CUDA library

---

etc/config/cuda.amazon.properties

See also https://github.com/compiler-explorer/infra/pull/407
I also added the missing `semver` from 10.2 so it would show up correctly.

Add CUDA 11 and 11 Update 1

---

lib/base-compiler.js
lib/compilers/win32.js
lib/handlers/compile.js
lib/options-handler.js
lib/tooling/base-tool.js
lib/tooling/clang-tidy-tool.js
lib/tooling/compiler-dropin-tool.js
lib/tooling/pvs-studio-tool.js
lib/utils.js
test/options-handler.js
test/tool-tests.js

Would enable #2212 to pass -DSPDLOG_COMPILED_LIB
Via adding
`libs.spdlog.options=-DSPDLOG_COMPILED_LIB`
at
https://github.com/compiler-explorer/compiler-explorer/pull/2212/files#diff-abd4fce8d3b41fa3f0e7581f14099250R1468

Support library options to be passed on to the compiler

---

.gitignore

Took the opportunity to organize and comment it a bit, so its not super clear what was removed in the diff.
```
*.bundle*.js
*.map
.travis-compilers
/coverage
/dist
static/dist
static/vs
```
Pretty much all of them now live under `/out`, (besides `.travis-compilers`, which just appears to be stale)
Due to recent changes in eslint configuration the existence of some of the above (stale) files can cause issues, and because they are still in .gitignore its very not-obvious that they should no longer exist in your working tree.

Organize .gitignore

---

app.js

Trivial change, but I am making this a PR since the old behavior may be desirable to others.
When running `make dev` webpack will now only print
```
info: Compiled successfully.
```
instead of the wall of output it normally prints.
If things go wrong it will still print diagnostics.

Disable webpack development middleware statistic logging

---

etc/config/cuda.amazon.properties

Add new versions of the Thrust/CUB libraries for CUDA.
These libraries are now distributed together and version locked, so this PR adds both under a `Thrust + CUB` label. The old standalone 1.8.0 version of CUB is now explicitly labeled as legacy.
See also compiler-explorer/infra#413.

Update the CUDA Thrust/CUB libraries.

---

static/explorer.scss

Fixes #2245
The following pr introduces:
- Add minimum height styling to the history modal.
@partouf I set the width to 80vw. Let me know if you think it should be adjusted, or any other changes are required.

History is broken fix

---

lib/compilers/zig.js

Hi.  
This PR updates Zig to use the newest command line interface introduced in ziglang/zig#6250 when running the trunk version as well as tagged versions greater than 0.6.0 (aka future releases).  
Please let me know if any changes are required, I have been testing this locally and it works like a charm.

Update Zig to use the new CLI

---

etc/config/c++.amazon.properties

The previous invocations of these compilers used an x86_64 gcc toolchain,
which prevented Clang from finding suitable headers and libs (eg stdlibc++),
which presented as bugs such as failures to find some C++ headers, and in
incorrect type sizes.
I've also added a sysroot option to the commandline.  This probably isn't
strictly neccessary right now, but it would be necessary if/when execution
support is added.
Change-Id: If6bc3c3d7eb548cd249850ca2992fc28ceb56559

Fixes to Armv7 and Armv8 Clang

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

The previous names only used the major versions.
This is in preparation for a change to add Arm Clang 10.0.1 and 11.0.0
Change-Id: Ie29e8690c3978fd002532d7020371d7c96b735d6

NFC: semantic names for the armv7 and armv8 clang config file entries

---

app.js
package-lock.json
package.json

If --metricsPort XX is supplied, run a server on port XX that
responds with metrics. Configure only default node metrics for
now; hope to get more interesting stats in soon.
Super lame we don't do any express stats (yet); but I tried some middleware and it broke everything.

Very simple metrics

---

lib/base-compiler.js

Pulled this out of my cmakeapi branch.
Needs some testing as it was amidst/before all kinds of other changes in our codebase.
Will also need to gather my thoughts as to what the strategy is here.
Primarily pulls out the `afterCompilation` steps, and some separate steps for building of executable, storing and loading from s3.

[untested] Some tiny refactoring for building executables

---

etc/config/c++.default.properties
etc/config/c.amazon.properties
test/example-states/default-state.json
test/utils-tests.js

RISC-V became a default backend in Clang 9.0. This commit enables the
use of the RISC-V backend for Clang in versions:
- 9.0.0
- 10.0.0
- 10.0.1
- 11.0.0
I also did a few other tidy-ups:
- I ensured that these could use more headers for rv64, by adding the
`--gcc-toolchain` and `--sysroot` args to point to the rv64 8.2.0
cross-compiled gcc toolchain (which is what seems to be done for arm).
- I updated the `-mabi` for rv-64 so it matches what that toolchain is
likely to have chosen as a default. I should check this, but I'm not
sure how I can (help?).
- I changed the config keys to introduce a hyphen, to match the arm
compiler keys.
- I'm not sure if older versions of CE-built clang also have RISC-V,
given that the clang-builder repo has `RISCV` in the experimental
targets to build. (PR …

[riscv] Enable More RISC-V Targets

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This change also enables `supportsBinary` (but not `supportsExecutable`)
on all the RISC-V targets (switching to the required objdump).
---
This depends on https://github.com/compiler-explorer/infra/pull/439

[riscv] Add RISC-V 32-bit Compiler

---

lib/handlers/api.js

This is something to be merged in a month or so. (will break clion plugin if user has not upgraded)
But I wanted to create the PR in case I forgot.

Stop using exe field in compilers api

---

etc/scripts/changelog.py

Hello! The changelog in production (`Other -> Changelog`) currently doesn't show anything and it looks like the `changelog.py` file had a silenced error. This MR fixes the problem that caused the silenced exception - splitting on the wrong character - and removes the grep filter. I'm not 100% what the filter was for (maybe to accumulate a list of bullet points from commit descriptions?) but listing the most recent commits seems fitting for a "changelog".
The alternative would be a hardcoded list of released features but that can't be automated 😄 
*The silenced error was an index out of bounds exception - splitting on the wrong character resulted in an array of size 1, and the next line attempted to access the second element.*

Fix changelog

---

etc/config/c++.amazon.properties
etc/config/c++.default.properties
etc/config/cuda.amazon.properties

@partouf As requested in https://github.com/compiler-explorer/infra/pull/452#issuecomment-748670710 I have added Eigen 3.3.9 *only* to all properties files where older versions have already been configured. This affects
- `c++.default.properties`
- `c++.amazon.properties`
You also asked about `cuda.amazon.properties`, where only `trunk` and `v3.3.4` had been configured. I have added the same versions as to the other files now, but be aware that I am not using CUDA with Eigen (and I am just a user of Eigen). I could not find any issues with CUDA mentioned in the change log, but I have *not tested this at all*.

Eigen 3.3.9

---

static/explorer.scss
static/panes/executor.js
views/templates.pug

Add text wrapping toggle to executor pane

---

views/options-filters.pug

I'm proposing setting the "Library Code" filter be enabled by default (I believe this is the correct change to make this happen). 
This change will improve the output of the MSVC compilers as they include a lot of 'external' code in their ASM output. 
To see the impact of this change toggle the "library code" filter with the following C++ using any of the MSVC compilers (e.g. "x64 MSVC v19.28")
```C++
#include <string>
void foo() { std::string s; }
```

Enable "libraryCode" Filter by Default

---

etc/config/c.amazon.properties
lib/compilers/_all.js
lib/compilers/tinyc.js

Would fix #246
Some things of note:

TinyC support

---

lib/asm-parser.js

Doesn't affect much in our parsing, but regex is incorrect and returned the wrong label name in case of `.weakext` (returned "ext" as labelname)

Fix regex for .weak and .weakext detection

---

etc/config/c++.defaults.properties

On ubuntu, you can install specific versions of the clang compiler and they
will be named similarly to the gcc compilers. Add these to the defaults file
so if they are there, they will be made available.

Add clang compilers to the defaults file

---

etc/config/c.defaults.properties

This converts the file to the new config format (AIUI) and adds more C
compilers commonly provided by package managers.

Add default installation locations for more C compilers

---

lib/tooling/base-tool.js
lib/tooling/clang-query-tool.js

I fought with this for a while. I tried executing the tool in a subdirectory; but this failed because it expects a compilation database where it can find it. I tried telling it where that was, but that didn't work.  I tried putting only the query_commands file in a subdirectory but I got some inexplicable errors.  So I went back to a unique filename per invocation.
I looked for other tools that would suffer the same problem, but I actually couldn't find any by looking at the usages of `writeFile`.  Other tools do write a file, but the contents comes from the compilatioInfo which would be identical for all tools running for that compiler. This is also the case with the compile_commands file in clang-query.
So while this isn't as robust as it could be, I think it fixes the immediate bug, …

Make the input file to clang-query unique so you can run multiple clang query tools

---

static/panes/tool.js

FWIW clang-query is the only tool in the repo that uses stdinHint

If an stdinHint is specified on a tool, when the tool opens, default to showing the stdin input

---

app.js

Dear compiler-explorer team
I tried to run compiler explorer on a linux machine and listen on unix socket instead of a port.
Works basically fine but I needed the changes below to be able to configure it properly.
**I don't know if this messes with some systemd integration (`systemdSocket` function call in `startListening`)**
Another problem occurs during logging (I assume) in production mode (works fine in dev-mode):
```
error: Internal server error: Cannot read property 'includes' of undefined {"domainThrown":true,"stack":"TypeError: Cannot read property 'includes' of undefined\n    at Proxy.anonymizeIp (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/lib/utils.js:161:12)\n    at Function.gdpr_ip (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/app.js:632:42)\ …
```

Allow to listen on unix socket instead of port

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Adding the following LLVM/Clang versions (in reverse semver order):
- 11.0.1
- 9.0.1
- 8.0.1
- 7.1.0
- 7.0.1
- 6.0.1
- 5.0.2
- 5.0.2
This follows up on:
- https://github.com/compiler-explorer/infra/pull/440
- https://github.com/compiler-explorer/infra/pull/455 (in progress)
Signed-off-by: Sam Elliott <sam@lenary.co.uk>

Clang Patch Support

---

etc/config/c.amazon.properties

I missed these in a previous PR.

Add RISC-V 64 Clang 11.0.1 and 9.0.1

---

etc/config/c++.amazon.properties

This is the last of the config for https://github.com/compiler-explorer/infra/pull/442 to expose it on the main site.

Clang Experimental Pattern Matching Support

---

static/explorer.scss
static/themes.js

The default codelens font stack is proportional which gets really irritating when counting bytes.
I've updated it so that is follows the font stack specified in settings (which is default monospace!)

Make codelens font follow settings

---

docs/API.md

This patch mentions my Emacs client for the API in the docs: https://github.com/mkcms/compiler-explorer.el

docs/API.md: Mention Emacs client

---

static/libs-widget-ext.js

The select on the library was not being updated if a library was deleted from the selected list.
I feel the solution is too hacky, so I wanted to see if @partouf came up with a better idea before merging this :)

Fully update the lib UI when a library is removed

---

app.js
docs/API.md
lib/handlers/api.js
lib/handlers/route-api.js
lib/storage/remote.js
static/sharing.js
test/handlers/api-tests.js

We still support /shortener (though will scrape logs to see when
we can remove).
The route under /api/shortener will have the CORS headers set up
properly for things like @foonathan's lexy visualiser.

Move /shortener to /api/shortener

---

etc/config/c++.amazon.properties

Adds a gcc version 10.2.1 option for embedded ARM (arm-none-eabi) targets, which corresponds to the 2020-q4-major release from ARM.
I have also opened a request for the infra project repository to add upstream's tarball URL and matching path.

Add ARM gcc 10.2.1 (arm-none-eabi)

---

static/panes/compiler.js
static/panes/executor.js
views/templates.pug

This should make the information (including links) in the compiler `notification` field more easy to discover and use.
It adds the info to the `i` popup below the compiler output, as shown:
Opinions welcome on whether the info should be in the title or the body. I put it in the title but if it's multiple lines with links, the body might be better?
This came from a request to expose the issue tracker for the clang experimental pattern matching compiler, so people could file issues if they came across them in the prototype.

Add Notification to Compiler Info Popup

---

etc/config/c++.amazon.properties

Library: https://github.com/soasis/text
I offered @ThePhD to make a PR.
ZSTD is a text encoding library for C++ that will serve as the basis
for a standard text encoding proposal.
As such availability on CE would increase usage experience !
Infra PR : https://github.com/compiler-explorer/infra/pull/466

Add ThePhD's text encoding library

---

.gitattributes

This should remove assembly test files from language stats leaving the project's main language as JavaScript.

.gitattributes: ignore assembly tests

---

docs/AboutLibraryPaths.md
lib/base-compiler.js
lib/compiler-finder.js
lib/compilers/clean.js
lib/compilers/win32.js
test/base-compiler-tests.js

Due to complications arising from compilers added in PR #2450 
The situation being that the compiler needed certain library paths, but only the 64 bit path as `LD_LIBRARY_PATH` - and during linking it would need both 64 and 32 for regular `-Wl,-rpath` library paths (to support `-m32`).
It turned out we mixed up some ldPath and libPath usages in the code that needed fixing.
Also included a doc, but not sure if it makes anything any clearer...
Todo:

Attempt at refactoring to better separate ldpaths and libpaths

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties
etc/config/fortran.amazon.properties

Add latest icc/icx/ifort/ifx
Delete the 2021.1.8, 2021.1.9 which were betas.
icc works, but the rest do not work because they require LD_LIBRARY_PATH set to:
/opt/compiler-explorer/intel-2021.1.2.63/compiler/latest/linux/compiler/lib/intel64_lin:
I could not see how to do it.
Requires https://github.com/compiler-explorer/infra/pull/470 to install the compilers.

add latest icc/icx/ifort/ifx

---

etc/config/c++.amazon.properties

I got the paths wrong in an earlier PR. I could not find anything that is broken because of this, but the paths are not valid.

fix lib paths for cpp

---

etc/config/cppx.amazon.properties

Fix for https://github.com/compiler-explorer/compiler-explorer/pull/2473#issuecomment-794883932, plus a switch to `c++20` instead of `c++2a` for `p12402`

Update language levels for active cppx reflection/meta branches

---

etc/config/c.amazon.properties

Add C compilers for intel 2021.1.2
C++ compilers were added in #2450

Add C compilers for intel 2021.1.2 release

---

lib/asm-parser.js
lib/base-compiler.js
lib/buildenvsetup/ceconan.js
lib/compilers/assembly.js
lib/compilers/dmd.js
lib/compilers/java.js
lib/compilers/nvcc.js
lib/compilers/pascal.js
lib/compilers/ptxas.js
lib/compilers/win32.js
lib/compilers/wine-vc.js
lib/exec.js
package-lock.json
package.json
static/explorer.scss
static/panes/compiler.js
static/panes/executor.js
static/timing-info-widget.js
test/exec-tests.js
test/filter-tests.js
views/popups.pug
views/templates.pug

API Request timing is displayed in the UI, but there have been some requests in the past to display more exact timings for the execution of user code (e.g. https://github.com/compiler-explorer/compiler-explorer/issues/2337)
Timing
Display in UI

Time all the things

---

etc/config/assembly.amazon.properties

Fixes #2387
Untested !
Note: I did not copy all arm compilers from c++.amazon.properties as some did not support binary mode, which is required for ASM language.

Add arm gnuas compilers

---

etc/config/assembly.amazon.properties
lib/compilers/_all.js
lib/compilers/assembly.js
lib/compilers/nasm.js

Fixes #2221
Doesn't show assembly for non-elf binaries because objdump does not seem to support it, but it compiles and I've added readelf to see at least "something" about the contents.
Also fixes #1804

Allow other nasm inputformat, add readelf to assembly

---

lib/base-compiler.js

icx/icpx are clang-based and the optimization output works for these compilers, too.
ifx does not accept -fsave-optmization-output. Need to check if they renamed the switch
compilerType=clang
isn't need, so I did not include in this commit
Addresses #2484

enable optimization output for icx/icpx

---

lib/asm-parser.js
lib/base-compiler.js
static/explorer.scss
static/panes/compiler.js
test/filter-tests.js
views/templates.pug

Adds an estimate of how many lines were filtered out when the result is empty (Maybe we could also add them for every compilation?)
Looks something like this
While it's not a fix for #2505 , it implements the suggestion given there by @dkm :)
Note that I had to `--no-verify` the commit because I couldn't bless the filter tests (And the approval PR is not yet merged in). Also, some work needs to be done to reduce the function where most of the edits take place - It has exceeded its max length of 50, but I just added an ingnore for now

Report back an estimate of filtered lines

---

CONTRIBUTORS.md
lib/base-compiler.js
lib/llvm-ast.js
static/panes/ast-view.js
test/ast/ctime.ast
test/ast/ctime.cpp
test/ast/square.ast
test/ast/square.cpp
test/base-compiler-tests.js
test/llvm-ast-parser-tests.js

Colors greatly help to navigate large AST dumps.
This PR adds a basic test for the LLVM AST parsing backend, factors it into a separate file taking inspiration from `llvm-ir.js`, and enables the colors of the AST dump in the same way they are drawn for the ASM and IR views.
The algorithm matching the source lines (to be more precise, spans of lines [from,to]) uses a trivial single-scan based on the `<line:x:x, line:x:x>` annotations for every AST node in the dump.
The algorithm does not take into account the hierarchy of the nodes and might occasionally miss some source lines corresponding to a node.

Colorize the LLVM AST to match the colors of the source

---

static/explorer.scss
static/main.js
views/index.pug
views/menu-policies.pug

This adds some bells to the policies dropdown when a new version of a policy is available.
It was initially made to adress #2464, but currently it still shows the privacy policy on first view, which does not fix the linked issue.
Ideas welcomed :)

Add bells to policies when a new version is available

---

lib/cache/multi.js

The motivating factor here is to potentially make our in-memory caching actually useful.
As it stands, our in-memory cache nearly always misses since the only way it will get populated is for unique new requests to an instance.

Propagate cache hits to higher levels in MultiCache

---

static/fontscale.js

As suggested by @apmorton, this change makes the new font selections use pixels instead of pt, so that everything works like Monaco now
Note that old links will still use pt those should not be affected
Closes #2457

Changes new font units to pixels

---

lib/cfg.js

This PR adds support for ARM branch instructions in the graph viewer. (Solution to #2013).
Clang uses `#` to mark immediates in ARM, which meant immediates were previously stripped out of the graph viewer, so comment stripping had to be removed.

support for arm instructions in graph viewer

---

CONTRIBUTORS.md
docs/AddingALibrary.md

Remove a reference and a link to the wiki from AddingALibrary.md since it is obsolete and the page does not exist.

Remove ref and link to the wiki

---

README.md

Reformat the existing video links, and add a link to Matt's CE YouTube playlist - to make existing info more discoverable...
(This is a bit of a workaround, pending a user guide - see #2557)

A link to CE playlist - and make videos easier to spot

---

README.md

This should make the headings more visible in the repo on GitHub - and it makes the magic hidden GitHub table-of-contents for README files easier to interpret.

Improve structure and grouping of headings in README

---

lib/llvm-ast.js
static/panes/ast-view.js
static/panes/compiler.js
static/panes/editor.js
static/panes/executor.js
static/panes/ir-view.js
static/panes/output.js
test/llvm-ast-parser-tests.js

Enable highlighting of spans of tokens in the source editor when the corresponding AST node is hovered over.
Enable the symmetric highlighting of the AST nodes corresponding to precisely the token being hovered over in the source editor.
In both cases `linked-code-decoration-column` marks the highlighted regions (in addition to `linked-code-decoration-margin` that works on the LOC granularity level).
Currently the `linked-code-decoration-column` style is "bold", so on the line highlighted with blue background, some tokens also become bold indicating the precise tokens corresponding to the AST node.
Incidentally, this also fixes the display of the span corresponding to a selected warning/error in the compiler output pane. Up until this change, only the first character has been highlighted …

Highlight individual tokens in the source file and the corresponding nodes in the LLVM AST pane

---

etc/config/assembly.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

I skipped Go since it only seems to have one per major version.
I also updated the default compiler; as well as the `demangler` & `objdumper` (I don't recall if changing these is a problem for the old links -- e.g. we didn't change it for 10.2)
`infra`: https://github.com/compiler-explorer/infra/pull/495

Add GCC 10.3

---

README.md

On my system running make giving errors and `npm run dev` work perfectly.

[NFC] Mention `npm run dev` in README.md

---

static/hub.js
static/panes/ast-view.js
static/panes/ir-view.js

This PR addresses #2513: expressing explicitly the dependency between the two callbacks and enforcing the right call order.
I am likely reinventing the wheel with `WrappedEventHub.prototype.mediateDependentCalls`, but I am not very familiar with the JS libraries and couldn't find anything quickly.

Express the dependency between "onColours" and "onCompileResult" explicitly

---

etc/config/c++.amazon.properties

This corresponds to a gcc-builder pull request to update the repo url: https://github.com/compiler-explorer/gcc-builder/pull/3

Update gcc contracts documentation URL

---

etc/config/c++.amazon.properties

This is one of three PRs adding support for the `contract-labels` branch of https://github.com/lock3/gcc . This likely depends on a related PRs in gcc-builder: https://github.com/compiler-explorer/gcc-builder/pull/4 , and infra: https://github.com/compiler-explorer/infra/pull/498 .
Please let me know if anything needs changed! :)

Add Lock3 gcc contract labels

---

etc/config/swift.amazon.properties

Adds Swift 5.4 as a compiler option. Infra PR: https://github.com/compiler-explorer/infra/pull/503

Add Swift 5.4

---

etc/config/assembly.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

Adds the new GCC 11.1 compilers.
I have not updated the default compilers yet, is that something that should be done?
Infra: https://github.com/compiler-explorer/infra/pull/504

Update for GCC 11.1

---

lib/llvm-ast.js
test/ast/bug-1346-typedef-struct.ast
test/ast/bug-1346-typedef-struct.cpp
test/llvm-ast-parser-tests.js

Sometimes top-level declarations contain multiple nested declarations in a single line. For example:
```
typedef struct x y;
```
In such cases some top-level declarations will not be endowed with a "line:" annotation, but have only "col:" specified as their location because they inherit the line from the previous AST node.
This PR extends the filtering regular expression to accept such cases.

Fix #1346: truncating nested top-level declarations

---

etc/config/rust.amazon.properties
lib/compilers/_all.js
lib/compilers/gccrs.js

Use default GCCCompiler values for GCCRS.

Create GCCRSCompiler class from GCCCompiler

---

etc/config/rust.amazon.properties

Only changing the name attribute was not enough.

Rename gccrs group id to really make it listed after rustc

---

static/compiler-service.js

Group names are upcased when displayed, but sort is still applied before.
Can be misleading when trying to order them (groupid are always lowcase).

Use case insensitive sort for group names

---

CONTRIBUTORS.md
etc/scripts/dis_all.py

Adds the option to pass optimization flags to `compile` when using Python in Compiler-Explorer.
This enables showing the removal of assertions from the code when using the `-O` or `-OO` flags in Python.
There are no tests as I failed to find tests for this specific part of the code. I hope this is OK.

Add support for Python optimization flags

---

etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties

To integrate newer OSACA version since version 0.4.0 has a bug with analyzing hex numbers in ARM assembly.
Also improves runtime and more instruction support
See also [PR in `compiler-explorer/infra`](https://github.com/compiler-explorer/infra/pull/508)

updated OSACA version to 0.4.2

---

docs/WindowsDelphi.properties
lib/compilers/_all.js
lib/compilers/pascal-win.js
lib/pe32-support.js

Delphi support refitted to work with latest CE version.
Intended to support people wanting to have Delphi in a local CE installation on Windows (and Wine might still work too, but not sure)
One thing I encountered that probably needs a solution, is that some compiler arguments are for example `-$O+` - at some point this gets interpreted as a variable and replaced by `-+`
Note for this to work objdump needs to be installed, instructions equal to that for MSVC binary mode support https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/WindowsNative.md#binary-mode

Somewhat working delphi support

---

lib/compilers/ldc.js

This changes the default LDC compile flag from `-g` to `-gline-tables-only`, such that the LLVM IR output does not contain `call void @llvm.dbg.declare` calls that (I think) most users are not interested in.  The old behavior can be restored by the user by passing `-g` (I think users are much more familiar with the `-g` option than the `-gline-tables-only` option). Line information is preserved so users can still see what IR lines correspond to user code lines.
I see that `clang` on CE also defaults to `-g`; the same change could be applied there.

LDC: use -gline-tables-only instead of -g by default

---

etc/config/rust.amazon.properties
lib/compilers/_all.js
lib/compilers/argument-parsers.js
lib/compilers/mrustc.js

Add the needed base for new mrustc compiler.
https://github.com/thepowersgang/mrustc
mrustc is transpiling Rust to C and is mainly used for bootstraping rustc.
This change treats the C output as the final product (as is assembly for
GCC/clang). It is not easily possible to automatically plug this C to other C
compilers to get assembly or executable.
fixes #2643

Initial support for mrustc

---

lib/compilers/mrustc.js

Defaults to bin, which will complain when there is no main(). But at the moment
compiler explorer has no way to compile the resulting C and get an executable.

mrustc: force crate_type to rlib

---

static/explorer.scss
views/index.pug

Inspired by a Twitter screenshot shared from someone who had a small screen size, this should remove the jumps in the navbar at those sizes.
Made it a PR to check that hiding the Sponsor text is actually ok before merging :)

Adjust media queries to avoid jumps in small screens

---

etc/config/cuda.amazon.properties
etc/config/cuda.defaults.properties
lib/compilers/_all.js
lib/compilers/clang.js

Clang `--cuda-device-only -c` produces the same kind of CUBIN output as `nvcc
-cubin` and can use nvdisasm to disassemble it.

Added support for SASS disassembly for clang as a CUDA compiler.

---

lib/tooling/pvs-studio-tool.js

Hello, 
My name is Maxim Stefanov (PVS-Studio, https://pvs-studio.com)
Recently, we moved to a new domain (www.viva64.com -> pvs-sudio.com)
Hence, we changed all links of the old website, but one link was left here.
I fixed the receiving of the documentation string without prefix linking to the website.
I'm ready to discuss the edits.

Corrected trim of the documentation link.

---

etc/config/c++.amazon.properties

Thanks for the awesome compiler explorer! Would be nice to add the Highway SIMD library.
make check reports: 918 passing (24s) 9 pending Tests pass
I successfully tested this locally after copying a git clone to /opt/compiler-explorer/libs/highway. The infra pull request is https://github.com/compiler-explorer/infra/pull/531. I am very unfamiliar with this stack, but please let me know if something can be improved.

Add Highway SIMD library

---

lib/tooling/pvs-studio-tool.js

Hello Matt,
I've done [PR](https://github.com/compiler-explorer/compiler-explorer/pull/2727) before. 
I apologize for my inattention (((
When receiving the text about PVS documentation, I mistakenly turned to the 'text' field.
Thank you very much for your understanding!

[fix] Corrected trim of the documentation link.

---

lib/aws.js
test/aws-tests.js

Note that if we want to use more variables to be loaded with `getConfig`, we'll have to add it to the list of paths in `loadAwsConfig()`.

Limit AWS SSM request to what we actually use

---

lib/base-compiler.js
lib/compilers/rust.js
lib/utils.js
test/utils-tests.js

I've pushed and opened this as a PR so I can be shown how to best approach some of this changes.
Obviously simply duplicating the parseOutput code is not good, but other than making it a compiler property
and overriding it in Rust, I could not think of any good solutions to avoid it.
Also, this assumes that the previous message only spans 1 line, which I don't know how good of an asumption it is.
Also, only the message links on mouseover to the code line. Should the `<source>` tag itself also link back?
¿Should the `warning:` prefixes be visible in the UI, or should we remove that bit?
Closes #2757 once it's finished

Initial sketch for how we could parse Rust output

---

.idea/inspectionProfiles/Project_Default.xml
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/zig.amazon.properties
lib/compilers/tinyc.js

As a PR mainly so I can have another pair of eyes to recheck the config changes.
This PR:
- Sorts the C & C++ libs and tools alphabetically
- Adds missing semver settings for some C++ Compilers
- Adds missing RSIC-V Clang versions
- Fixes how RISC-V Clang is configured. It's now less of a mess
- Adds missing Zig C & C++ compilers, along with Tincy changes
As you can see, I totally forgot to change branches before commiting them, so I had to branch off and now they are here. Sorry about that

Config changes

---

etc/config/openclc.amazon.properties
etc/config/openclc.defaults.properties
examples/openclc/default.cl
lib/languages.js
static/modes/openclc-mode.js
static/panes/editor.js

Closes #2741.
This PR adds support for OpenCL C as a language, with syntax highlighting and compilation using upstream Clang into Arm assembly.
Note that `etc/config/openclc.amazon.properties` adds the base options `-Dkernel- -D__kernel=` for the Arm targets. 
This is a workaround to prevent the Clang crash documented [here](http://llvm.org/PR50841). Once the bug is fixed,
this workaround can be removed.

Add OpenCL C language

---

etc/config/java.amazon.properties
lib/compilers/java.js
lib/compilers/kotlin.js

handleInterpreting is now properly overridden for the JVM based compilers.
Execution has been enabled for Java in the Amazon config

Fix execution for JVM compilers

---

lib/asm-parser.js
test/filters-cases/kalray-hellow.asm
test/filters-cases/kalray-hellow.asm.directives.approved.txt
test/filters-cases/kalray-hellow.asm.directives.comments.approved.txt
test/filters-cases/kalray-hellow.asm.directives.labels.approved.txt
test/filters-cases/kalray-hellow.asm.directives.labels.comments.approved.txt
test/filters-cases/kalray-hellow.asm.directives.labels.comments.library.approved.txt
test/filters-cases/kalray-hellow.asm.directives.library.approved.txt
test/filters-cases/kalray-hellow.asm.none.approved.txt

The KVX assembly uses ;; as the bundle separator, which can be a problem to
parse as ; is also commonly used as a comment marker.
Latest compiler version also add cycle information for opt level >= 1, which
confuses the current comment filter that treats the bundle separator as comment.
Tune the regex to treat the following :
addd $r12 = $r12, -96
get $r16 = $ra
;;      # (end cycle 0)
as non-comment. The ';;  #' is special-cased as non-comment.

Better handling of Kalray MPPA comment and bundle separator

---

etc/config/compiler-explorer.amazon.properties
etc/config/sponsors.yaml
lib/options-handler.js
static/main.js
views/sponsor-icons.pug

Optionally POST to a "pageload" endpoint with visible ces icons after five seconds of the page loading.

Add optional support for noting page loads with which icons are visible

---

etc/config/rust.amazon.properties
lib/compilers/_all.js
lib/compilers/rustc-cg-gcc.js

GCC backend for rustc is still in a very early state.
It is in the process of being merged in main rustc source:
https://github.com/rust-lang/compiler-team/issues/442
Currently reusing main rust compiler class and simply remove -Cllvm= argument if any (only for intel asm syntax).
Disabling binary until the result is more friendly (currently binary are too big).
refs #2683

Adding rustc-cg-gcc

---

etc/config/cpp_for_opencl.amazon.properties
etc/config/cpp_for_opencl.defaults.properties
examples/cpp_for_opencl/default.clcpp
lib/languages.js
static/modes/cpp-for-opencl-mode.js
static/panes/editor.js

Closes #2742 
This PR adds support for C++ for OpenCL as a language, with syntax highlighting and compilation using upstream Clang into Arm assembly.
Note that `etc/config/cpp_for_opencl.amazon.properties` adds the base options `-Dkernel= -D__kernel=` for the Arm targets.
This is a workaround to prevent the Clang crash documented [here](https://llvm.org/PR50841). Once the bug is fixed, this workaround can be removed.

Add C++ for OpenCL language

---

etc/config/kotlin.amazon.properties

Compiler update for the most recent Kotlin release which fixes some compiler bugs. Tested locally.
Infra: https://github.com/compiler-explorer/infra/pull/551

Add compilers for Kotlin 1.5.21

---

etc/config/c.amazon.properties
lib/compilers/_all.js
lib/compilers/cproc.js

Add support for cproc C11 compiler.
cproc is a lightweight compiler using the QBE backend.
Fixes #2755

Support cproc C11 compiler

---

etc/config/c++.amazon.properties

Associated infra change compiler-explorer/infra#558
The different sub-libraries under hotels-template-library are still under active development and don't have any version tags, so just trunk is necessary.
Ran `make check` locally and all tests/linters passed.

Add hotels-template-library

---

test/java-tests.js

Now that Java is running on CE again, it'd make sense to re-enable these tests. This patch also includes a fix for the javap parsing test: The local compilation environment variable was never set, causing env to be undefined inside testJava

Re-enable test suite for JavaCompiler

---

static/components.js
static/hub.js
static/panes/compiler.js
static/panes/flags-view.js
views/templates.pug

If you have a lot of compiler flags, you don't want to be editing
them in the tiny text box. So add a menu option above
'Popular Arguments' that lets you break out the flags into a
separate window, where you can edit them; one-per-line.
When this happens, the regular flags text box becomes disabled,
and the popular arguments dropdown is not populated.

Create a seperate window for editing compiler flags

---

lib/asm-parser.js
test/filter-tests.js
test/filters-cases/bug-2788.asm
test/filters-cases/bug-2788.asm.binary.directives.labels.comments.approved.txt
test/filters-cases/bug-2788.asm.directives.approved.txt
test/filters-cases/bug-2788.asm.directives.comments.approved.txt
test/filters-cases/bug-2788.asm.directives.labels.approved.txt
test/filters-cases/bug-2788.asm.directives.labels.comments.approved.txt
test/filters-cases/bug-2788.asm.directives.labels.comments.library.approved.txt
test/filters-cases/bug-2788.asm.directives.library.approved.txt
test/filters-cases/bug-2788.asm.none.approved.txt

Things like ARM jump tables put important data inline within a function. Such
data should be treated as a "strong" reference (e.g. a root use). For example:
```asm
sub     r3, r0, #65
cmp     r3, #19
ldrls   pc, [pc, r3, asl #2]
b       .L7
.word   .L8
.word   .L7
.word   .L6
.word   .L7
....etc...
.L7: some things
.L8: some other things
```
Without this change, the `.L8` label would be dropped as unused. But it's implicitly used
by the sequence of `.word`s in the middle of the function.
Closes #2788

Treat data definitions in the middle of functions as "strong"

---

etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties

Updated OSACA in CE to v0.4.5 to support some new instruction forms.
See also the related [PR #559 in `compiler-explorer/infra`](https://github.com/compiler-explorer/infra/pull/559)

updated OSACA version to 0.4.5

---

docs/AddingATool.md
etc/config/c++.defaults.properties
lib/options-handler.js
static/components.js
static/hub.js
static/panes/compiler.js
static/panes/tool-input-view.js
static/panes/tool.js
views/templates.pug

Similar to my other PR, in that I am adding a new Pane; but generally unrelated.
This makes it possible for a tool (I built this for clang-query) to have a separate Monaco Editor pane as its std input.  This is specified in the config file, and does **not** let the user choose between the old input or the new one.
It is not specified as the default in any of the supplied configs though, so this is latent code. Maybe you don't want to take code that is not used, or maybe you want to enable it for clang-query?

Allow a tool to have a separate monaco editor for it's stdinput

---

lib/base-compiler.js
lib/compilers/rust.js
lib/compilers/rustc-cg-gcc.js
static/components.js
static/hub.js
static/panes/compiler.js
static/panes/rustmir-view.js
views/templates.pug

Adds a new pane and processor for generating and showing Rust's MIR. This is my first time hacking on the front end. Let me know if there's anything that's missing.
I do not have any tests for this at the moment. I would appreciate some help in how to set up testing for this.
Fixes #2566 
/cc @ojeda

Add rustc MIR output view

---

lib/base-compiler.js
static/panes/compiler.js

Follow up to #2795
As @mattgodbolt pointed out in the previous PR I left a todo comment which isn't valid anymore.
In addition to that, the rust MIR button wouldn't disable ever. Both of these nits are fixed in this patch.

Fix Rust MIR button bug and remove invalid todo line

---

static/panes/compiler.js

Follow up to https://github.com/compiler-explorer/compiler-explorer/pull/2795#discussion_r675894577
The buttons for unsupported panes are now hidden in the UI.
This keeps the original behavior of disabling buttons while their views are open (the IR view button is disabled while IR is shown).

Hide panes that are not supported by a compiler

---

etc/config/circle.amazon.properties
etc/config/circle.defaults.properties
lib/compilers/circle.js

This PR add support for Intel ASM syntax, which was added to 129 build of circle.

Circle: Add support for Intel ASM syntax

---

static/panes/compiler.js

When you change editor language, a compile request would be sent even though the Source had not been changed yet (resulting for example in Java source being compiled with GCC, etc)
Editor will still probably trigger compilation twice depending on settings. (1. Editor code change, 2. Compilation request on language change (event in editor.js)) - but the result will be fetched from browser cache in most situations.

Delay compilation until editor sends compile request on language change

---

lib/compilers/zig.js

Unused function parameters (used in the custom panic handler) are now
compile errors.

Update to latest zig trunk

---

static/panes/gccdump-view.js

PR for https://github.com/compiler-explorer/compiler-explorer/issues/2831
I am sorry that I don't know any front end knowledge. So I didn't have the environment to run or test it. But this fix looks so reasonable. https://tom-select.js.org/plugins/virtual_scroll/#maxoptions
500 is chosen because the maximum index of passes is 331 for now (as far as I can tell). It should make no difference if we want to display all chosen passes.

Enlarge the field maxOptions of TomSelect

---

lib/compilers/ocaml.js

This should allow the compiler to actually compile executables
thanks @partouf for basically telling me exactly how to go about this
closes #2848

Override default compiler flags for OCaml

---

lib/base-compiler.js
lib/compiler-finder.js
lib/compilers/clang.js
static/components.js
static/explorer.scss
static/hub.js
static/panes/compiler.js
static/panes/device-view.js
test/compilers/clang-tests.js
views/templates.pug

Originall by @jcranmer-intel, submitted as #2306
Rebased and updated after a prolonged period of inactivity.
---
This is an incomplete pull request at the moment, but I feel it would be better to continue the conversation with some actual code behind it. This is to fix issue #2244 .
At the moment, I've tested this with a basic support for clang -fopenmp offload runs. Specifically, the example code I used would be the example here: https://godbolt.org/z/rvGeqc.
Starting with the UX: I implemented the device viewer pane using a slightly-modified copy of the IR viewer. It is insufficient at this moment; I haven't added support for device selection or device-specific arguments. Some of my testing identifies other issues: the same asm filters are applied to both the regular ASM view and the …

Add support for heterogeneous compute

---

etc/config/ocaml.defaults.properties
lib/compilers/ocaml.js

Hi again! This change should allow CE to execute OCaml code. Tested locally.
Changes:
- ocaml.default.properties:
- add the relevant flags for execution and emitting binaries
- add nicer version number reporting
- let CE know `objdump` can be used on ocaml objects
- ocaml.js:
- update optionsForFilter for both executable and object handling
- override the getter for executable to work within ocamlopt context

Make OCaml examples executable and objdumpable

---

etc/config/c++.amazon.properties
etc/config/circle.amazon.properties
etc/config/cuda.amazon.properties

Changed all configurations containing Eigen to include the newest upstream release v3.4.0.
I have only adapted the configuration to add the new version and did not run any tests locally.

Add Eigen v3.4.0 release

---

docs/AddingACompiler.md

> it ain't much but it's honest work
The compiler option documentation for `executionWrapper` is misleading, as turns out now it can allow custom scripts to run the output which is nice.
If I noticed it beforehand it would have saved me some time when configuring custom compiler, hence the PR as may save some time for others :)

* Fixed documentation for executionWrapper

---

static/modes/cpp-for-opencl-mode.js
static/modes/openclc-mode.js

The generic and __generic keywords are currently reserved in the OpenCL C
specification. They have already been added as keywords in Clang. Without
highlighting, it can seem as if generic is not an address space, as the
other address spaces are highlighted. This can be seen in the AST viewer
on Compiler Explorer. The lack of highlighting makes the AST less convenient
from a user-perspective.
C++ for OpenCL inherits address space behavior from OpenCL C v2.0 s6.5, so
this change applies to both OpenCL C and C++ for OpenCL.

Add generic keywords to OpenCL C and C++ for OpenCL

---

etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties

This PR adds Clang built with assertions enabled for OpenCL C and C++ for OpenCL.

Add Clang assertions trunk for OpenCL C and C++ for OpenCL

---

static/formatter-registry.ts
static/panes/editor.js
static/tsconfig.json

As discussed in #2818 and #2770; Monaco has its own document formatting functionality which does the same thing as our Ctrl + F9 keybinding.
This is an MVP implementation for using Monaco's own FormattingEditProvider.
The old Ctrl + F9 keybinding is now hidden as a monaco command, which will invoke the `editor.action.formatDocument` action, making the keymap backwards compatible.

Implement code document formatting through monaco

---

etc/config/cuda.amazon.properties

Features supported by newer CUDA versions and GPUs are usually a superset of the
features of the older versions. Using the most recent ones allows us to compile more
code.
* For NVCC, use the most recent GPU supported by particular CUDA version.
* For clang, pick the most recent supported CUDA version and GPU.

Reorganize CUDA compiler variants.

---

lib/base-compiler.js
lib/compilers/java.js

By refactoring handleInterpreting to receive the entire `key` argument from `handleExecution` we can access all of the files from the multifile-ui tree.
This will make sure the Java execution compiles all of the files and runs using the correct classpath.
Fixes #2877

Fix execution for Java with multifile ui

---

static/panes/tree.ts
views/templates.pug

* Makes the two buttons (stage/unstage) separate so the template
file has all the title etc in it.
* Hides/unhides to show the appropriate button only.
I'm not wed to this approach, but it saved putting the descriptions
into the source code.

Add tooltips to files in tree view.

---

CONTRIBUTORS.md
lib/asm-parser-vc6.js
lib/compilers/_all.js
lib/compilers/win32-vc6.js

Not sure how useful it is, but I managed to get MSVC6 working with
Compiler Explorer, so I figured I'd share my changes. MSVC6 can be
installed on Windows 10 with some coaxing and works fine in my
basic testing. I copied the existing MSVC files and made changes there
instead of trying to merge the two. That might be possible, I'm just not
well versed enough to know how to do it cleanly and if the changes
weren't going to be accepted I was going to to waste time on it.
Example MSVC6 assembly output:
```
TITLE   example.cpp
.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT   SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT   ENDS
_DATA   SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA   ENDS
CONST   SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST   ENDS
_BSS    SEGMENT DWORD USE32 PUBLIC 'BSS' …
```

Add support for Microsoft Visual C++ 6

---

etc/config/ocaml.amazon.properties
etc/config/ocaml.defaults.properties
lib/compilers/ocaml.js

This patchset doesn't _add_ much, besides an argument parser derived from Pascal's (for now) for similarities in interface.
Rather, it tries to remove things and give `ocaml.js` better chances at forward compatibility.
It also follows [this](https://github.com/compiler-explorer/compiler-explorer/issues/2855#issuecomment-898939931) comment wrt `*.defaults.properties` preferred minimalism.
To see the work in progress, check #2850

OCaml Improvements: objdump and a few refactorings

---

static/monaco-config.ts
static/tsconfig.json

Ports the extendConfig() utility to TypeScript to ensure proper types are passed in the overrides object. This is a non-functional change, and will only affect TypeScript callers (of which there are none at the time of writing).

 [NFC] Port monaco-config.js to TypeScript

---

lib/languages.js

Fixes #2934 
Renamed the dropdown name for CUDA to CUDA C++ as described in #2934

Rename CUDA to CUDA C++ in language dropdown

---

static/settings.interfaces.ts

Follow up to #2926 
Extends the FormatBase type to include the new Clang Format base styles.

Fix missing FormatBase variants in settings.interfaces.ts

---

static/monaco-config.ts

Now that the site settings are properly typed, we can strongly type the second argument to the extendConfig() function.

Properly type settings argument for monaco extendConfig()

---

static/tsconfig.json

Two files were missing from the tsconfig, and one was incorrectly sorted.
Maybe we should look into a different way to inform typescript of the files? Maybe with the `include` and `exclude` options?

Add missing tsconfig entries and alphabetically sort existing ones

---

static/panes/editor.js

Closes #2955
This re-binds the Monaco duplicate selection (or line) action to Ctrl + D

Bind duplicate selection to Ctrl + D

---

static/panes/executor.js

Partial fix for #2960 
Shows a warning in the alert system and cancels the execution request if the compiler does not support execution.
**As discussed on Discord:**
A more ideal approach would be to completely disable the "Execution only" button from the UI if the compiler doesn't execute.

Warn if Execution Only is added for compiler without execution

---

etc/config/java.amazon.properties
etc/config/kotlin.amazon.properties
etc/config/scala.amazon.properties

Adds an installer for the new OpenJDK 17
Looks like they dropped the semver for the version string so it's just `/opt/compiler-explorer/jdk-17`. I wrote it out as `17.0.0` for consistency, but the actual version name is just `17`... Thoughts?
Infra: https://github.com/compiler-explorer/infra/pull/591

Add Java OpenJDK 17

---

docs/AddingAFormatter.md
lib/base-formatter.js
lib/formatters/clang-format.js
lib/handlers/formatting.js
static/formatter-registry.interfaces.ts
static/formatter-registry.ts
static/tsconfig.json
test/base-formatter-tests.js

Fixes #2770 
Site settings for tab width and tabs vs spaces are now being used when sent to the /api/format APIs.
This patch also includes some tiny internal refactoring on the bits related to the formatting API.

Respect tab width and tabs/spaces settings for format APIs

---

lib/base-compiler.js
lib/compilers/rust.js
static/components.js
static/hub.js
static/panes/compiler.js
static/panes/rustmacroexp-view.ts
static/tsconfig.json
views/templates.pug

Fixes #2568 
Adds a new pane for producing the macro expansion of Rust code compiled with rustc.

Add rustc Macro Expansion view

---

static/panes/tree.ts

This PR fixes #2967 an XSS vulnerability in the custom output file input text, by escaping any html that gets passed in

2967: Escape string that gets passed as custom output filename

---

etc/config/c++.amazon.properties
etc/config/compiler-explorer.beta.properties
lib/base-compiler.js
lib/compilation-queue.js

* Always use the compilation queue, which ensures we don't
execute more native apps thn are configured, especially while
we're starting up.
* Guard the compilation queue from enqueueing stuff that was
already executing in a queue context. This is to prevent deadlock
though it's not always a problem (it's only if the caller awaits
the job, which is often the case).
Should mitigate the issues we had on Sep 30 2021, where nodes were
having trouble starting up due to the large amount of JVM-based
compilers. See #2977

Unconditionally use the compilation queue

---

static/colour.ts
static/tsconfig.json

This will convert ``static/colour.js`` to typescript (see #2981)
Changes are pretty much the same as with the other conversions I did.
Assumed that param ``colours`` in ``applyColours`` is of type ``number[]`` as this is the only fitting type.

Convert colour.js to typescript

---

lib/compilers/java.js

fix(java): show full asm output when using switch expression

---

static/panes/rustmir-view.ts

The pane would still show <no output> for unsupported compiler.
Let the onCompiler callback correctly write the message in case the compiler is
not supported.

Fix Rust MIR view to correctly display unsupported compiler

---

etc/config/cpp_for_opencl.amazon.properties
etc/config/cpp_for_opencl.defaults.properties
etc/config/openclc.amazon.properties
etc/config/openclc.defaults.properties
lib/compilers/_all.js
lib/compilers/spirv.js

Closes #2743.
This PR requires https://github.com/compiler-explorer/infra/pull/590.

Add support for generating SPIR-V assembly from OpenCL C and C++ for OpenCL

---

lib/compilers/ispc.js

Fixes #2970 
Implements LLVM IR output for the ispc compiler as requested in #2970

Implement LLVM IR output for ispc

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

KVX GCC is now based on GCC 9.4.1.
Release ACB 4.6.0 available at: https://github.com/kalray/build-scripts/releases/tag/v4.6.0

Add new version of KVX compiler

---

package.json
static/ansi-to-html.interfaces.ts
static/ansi-to-html.ts
static/tsconfig.json
test/ansi-to-html-tests.js

This will convert ``static/ansi-to-html.js`` to typescript (see #2981)
* Converted all javascript to typescript
* Added custom types for some inputs
* Added public interfaces to ``ansi-to-html-interfaces.ts``
* Updated ``static/tsconfig.json``
* Updated ``@types/underscore`` (this actually happened by mistake, thought the type definitions were not installed)
* Replaced ``var`` with ``let`` and ``const`` wherever possible
* Converted prototype function ``Filter`` to a more typescript-conform class
* Added proxy input types to make variables more strict
* Removed now-useless comments
* The whole module can be built with the changes made but
* **The tests will fail as the typescript code is not compiled to javascript before running the tests, thus they fail due to invalid javascript syntax** …

Convert ansi-to-html.js to typescript

---

lib/compilers/ada.js

GNAT is part of GCC and can handle the regular GCC options for dump files.

Enable GCC dump for the GNAT Ada compiler

---

lib/base-compiler.js
lib/compilers/crystal.js
lib/compilers/golang.js
lib/compilers/kotlin.js
lib/compilers/python.js
lib/compilers/ruby.js
lib/compilers/scala.js

This isn't exhaustive across the codebase, but it removed all property access after construction directly inside BaseCompiler and all subclasses.
One small step in the direction of separating fleet configuration from instance startup.

Avoid calling compilerProps after compiler object construction

---

static/panes/rustmacroexp-view.ts

Fixes the same issue as patched in #2999 for the Rust macro expansion view

Make Rust macro expansion view properly display unsupported compiler

---

etc/config/swift.amazon.properties

Adds Swift 5.5 as a compiler option. The associated infra PR is compiler-explorer/infra#604.

Add Swift 5.5.

---

lib/handlers/formatting.js

Fixes #3065 
The `useSpaces` and `tabWidth` fields now have defaults.

Implemement backwards compatability for Format API after #2957

---

static/alert.interfaces.ts
static/alert.ts
static/multifile-service.ts

(waiting for CppCon to merge)
The Alert component was not typed to have the `yes` callback handler accept the string which was entered by the user.
NFC - TypeScript only change

Make Alert.enterSomething's yes callback's type includes the answer

---

static/colour.ts

This function was incorrectly typed, as each bit of code that calls it creates an object with number-to-line mappings which is fed into this function.
I've also refactored the function to use JavaScript builtins instead of underscore utilities.

Make colour.ts take Record<number, number> and refactor it to drop underscore.js

---

app.js
etc/scripts/docenizer-java.js
lib/base-compiler.js
lib/compilers/argument-parsers.js
package-lock.json
static/load-save.js
static/multifile-service.ts
static/panes/tree.ts
test/cache-tests.js

We had a number of things that aren't await()ing their promises.
That led to non-deterministic compiler settings like Intel support.
I used the IDE to find them all and fix the ones that I thought looked
important.
More generally we should use tslint (once we're all typescript) to
ensure this more generally. I tried the eslint equivalent but it
either overreacted or didn't catch anything.
Closes #3085

    Await for things

---

etc/config/analysis.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/clean.amazon.properties
etc/config/cppx.amazon.properties
etc/config/cppx_blue.amazon.properties
etc/config/cppx_gold.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties
etc/config/haskell.amazon.properties
etc/config/ispc.amazon.properties
etc/config/llvm.amazon.properties
etc/config/pascal.amazon.properties
etc/config/rust.amazon.properties
etc/config/swift.amazon.properties
etc/config/zig.amazon.properties

Added new OSACA version 0.4.7 to godbolt.
This version fixes some minor bugs and introduces support for Cortex A72.
See also [PR 626](https://github.com/compiler-explorer/infra/pull/626) in compiler-explorer/infra

updated OSACA version

---

static/formatter-registry.interfaces.ts
static/formatter-registry.ts
static/settings.interfaces.ts

Fixes #3089
The formatter-registry will now use the site settings when querying the Format API. For compilers that do not support multiple styles, __DefeaultStyle is passed.

Actually use the setting style in the format api

---

lib/base-compiler.js
lib/compilers/ada.js
lib/compilers/argument-parsers.js
static/panes/compiler.js
static/panes/gccdump-view.js

This change allows for only dumping a single pass (the one selected). In order
to populate the list of available dumps, it now queries GCC for the enabled
passes.
It can still be misleading to users as a pass can be enabled but for some reason
does not dump anything. In order to avoid this, the only solution seems to be to
still dump all files and filter the list... This defeats the initial goal and
only adds complexity for the current compilers.
But this makes #2868 easier to implement (see #2985 that was a first attempt)
and if someday another libgccjit-based compiler is added, it could be easily
hooked to this.
It also changes the naming in the drop down menu. For example, instead of :
'009t.omplower' it now uses 'omplower (tree)' (ie.
'<pass-name> (tree|ipa|rtl)').
Fixes #3014 …

Refactor GCC dump handling

---

lib/base-compiler.js
lib/compilers/ada.js

Instead of having a dedicated invocation of the compilers, inject needed options
in the main compilation command and do everything in one run. This should fix
GNAT race condition on ALI file, save some CPU time and make the latency a bit
better. This can work as long as everything can really be done in one run (eg.
no incompatible options, no clash on stdout/stderr).
Add optionsForBackend in base compiler class that is meant to be overloaded by
compilers for injecting options based on current backend options. Use it for
GCC dumps (BaseCompiler) and GNAT expanded code.
Fixes #3041
References #3029

Refactor GCC dump and GNAT expanded code creation

---

package-lock.json
package.json

This dependency doesn't appear to be used anywhere. It was introduced in 70556a6c6597ac6c112497f1b3c4b07a4a3e1d9c as a event emitter replacement, but we're not using it anywhere in the codebase anymore.

Remove unused wolfy87-eventemitter dependency

---

static/panes/diff.js

This change allows for the selection of the GNAT (Ada) expanded code to
be used in the diff pane.

Enable diff view to use GNAT (Ada) expanded code

---

lib/base-compiler.js

The refactor from #3024 left all the output from -fdump-passes in
stderr. Filter it out before displaying it in the output pane.

Filter fdump-passes output from stderr before displaying

---

lib/base-compiler.js

Even when the compiler exits with an error, try to display the expanded
code.

Show GNAT expanded code pane even in case of compiler error

---

lib/base-compiler.js
lib/compilers/ada.js
lib/compilers/rust.js

The initial change from @nilehmann in #3107 has been refactored to simplify the rustc execution. It is now only called once instead of once for each output.

Honour rustc flags when emitting MIR and emit both assembly and MIR in the same execution

---

lib/compilers/rustc-cg-gcc.js

Beware that the way it is working causes several dump files to be empty. The
list of potential files is based on `-fdump-passes` output, but during the
actual compilation, some passes may or may not emit something (eg. a passe may
not be executed at all because it's not applicable). The drop down list will
contain some dump names that will simply display message like:
Pass 'cselim (tree)' was requested
but nothing was dumped. Possible causes are:
- pass is not valid in this (maybe you changed the compiler options);
- pass is valid but did not emit anything (eg. it was not executed).
This is expected and until someone has a better idea, this will be the case :)
fixes: #2868

Enable the GCC dump for the rustc using GCC backend

---

etc/config/crystal.amazon.properties

Requires compiler-explorer/infra#630. Should also fix the link failures with 1.2.0.

Add Crystal 1.2.2

---

etc/config/c++.defaults.properties
etc/config/c.defaults.properties
etc/config/fortran.defaults.properties

The *.default.properties files list only older C,C++ and Fortran compilers.
update gcc, clang and gfortran in the files: 
etc/config/c.defaults.properties
etc/config/c++.defaults.properties
etc/config/fortran.defaults.properties
gcc & g++: 9,10,11
clang & clang++: 11,12
gfortran: 8,9,10,11
These PR contain only the updates. The files need further cleanups, but this is not part of this PR.
(gcc 10.x vs g++ 10; gfortran contain "x64", but uses the native compiler. This is missing on the other compilers or should be removed for gfortran; ...)  
I can help here (for C, C++ and Fortran), but would like get some feedback first.

update gcc and clang in default properties

---

lib/base-compiler.js
lib/compilers/rust.js

Conflicting changes in #3109 and #3064 left the GCC dump of rustc broken.
Reapplied the changes and refactored how the -fdump-foo-pass= option is crafted.
Instead of using stdout, use an explicit file. Beware that this won't work with
older GCC version. Regular GCC is still using the 'dump all files' instead of
the targeted option, so it's not impacted by this limitation. Only rustc-cg-gcc
is currently using this mecanism and it's using a recent libgccjit.
Really fixes #2868

Fix and refactor rustc-cg-gcc GCC dump

---

CONTRIBUTORS.md
lib/compilers/erlang.js

For Erlang, format the output in the same way as the 'S' option
does. To achieve this, we use the `beam_listing` module, which is
undocumented but has been stable for many many years.

Format the output file for Erlang in a nicer way

---

static/multifile-service.ts

Chrome DevTools suggest that `.map()` does not exist here. I think that the right one is `.forEach()`.
https://stuk.github.io/jszip/documentation/api_jszip/for_each.html

Fix loading a zip project

---

etc/config/c++.amazon.properties

PR to add compilers is https://github.com/compiler-explorer/infra/pull/639
Tested it locally and `make check` is happy as well.
Fixes #1817

Add xtensa compilers for ESP32, ESP32-S2, ESP32-S3

---

lib/compilers/kotlin.js

Fixes the problem where any (reasonable) Kotlin JVM execution would fail with a NoClassDefFound error with kotlin.jvm.internal.Intrinsics.
The Kotlin execution is now packed into a jar with the Kotlin Standard Library and executed with `java -jar`.

Temporarily patch Kotlin runtime execution

---

lib/base-compiler.js
lib/compilers/rust.js
static/components.js
static/hub.js
static/panes/compiler.js
static/panes/rusthir-view.interfaces.ts
static/panes/rusthir-view.ts
views/templates.pug

Small refactoring for handling -Zunpretty calls:
- reuse options from main compiler invocation instead of crafting new ones.
- move some rust specific methods from base-compiler.js to rust.js
Now also handles HIR output in a dedicated pane.
Still a lot of copy/pasting from the macro expansion.
fixes #2567

rust: HIR dump and small refactor with macro expansion

---

etc/config/cpp_for_opencl.amazon.properties
etc/config/cpp_for_opencl.defaults.properties
etc/config/openclc.amazon.properties
etc/config/openclc.defaults.properties

Added clang-13 to OpenCL C and C++ for OpenCL.
Improved compilation speed by using '-fdeclare-opencl-builtins'
on the newer clang versions where applicable.

Added clang-13 to OpenCL and improved compilation speed.

---

lib/base-compiler.js

This handles the errors serverside.
Want to iteratively work on this, so we can have better user errors sooner rather than later.

Handle filecontent and filename errors

---

static/explorer.scss
static/panes/editor.js

As requested in #2410 the language dropdown now properly indicates that it is text-searchable.
This is a proof of concept with the same selector used for the compilers dropdown. It is an essential part of the CE UI which is why I'd like more opinions on it before moving forward with this change.

[PoC] Automatically enable text search for language dropdown

---

lib/handlers/assembly-documentation/router.js
lib/handlers/base-assembly-documentation-handler.js
test/handlers/api-tests.js
test/handlers/assembly-documentation/amd64-tests.js
test/handlers/assembly-documentation/api-tests.js
test/handlers/assembly-documentation/arm32-tests.js

Fixes #3167
This is a tiny adjustment to the assembly documentation API to include which architecture/opcode that was not found.
```diff
// GET /api/asm/amd64/not_an_op
- { "error": "Unknown opcode" }
+ { "error": "Unknown opcode 'not_an_op'" }
```
```diff
// GET /api/asm/notarch/mov
- { "error": "Unknown architecture " }
+ { "error": "No documentation for 'notarch'" }
```

Describe which opcode and arch that was not found

---

lib/base-compiler.js
lib/compilers/ada.js

Using -gnatDGL to get the expanded code also asks GNAT to emit debug
informations pointing to the .dg file containing the expanded code, breaking CE
that is using these info to map assembly and source lines. Using -gnatGL instead
avoids the breaking of asm/source mapping but emits the expanded code in stdout
instead of a plain file.
This change replaces -gnatDGL by -gnatGL and extracts the expanded code from
stdout.
fixes #3171

Fix source/assembly mapping when GNAT expanded code pane opened

---

lib/base-compiler.js

Both gimple and original dumps are missing because CE currently only checks for
dumps coming from a pass advertised in -fdump-passes.
Fix this by faking 2 lines as coming from -fdump-passes.
fixes #3180

Fix missing gimple and original tree dump in GCC dump

---

static/api/api.ts
static/api/formatting.interfaces.ts
static/formatter-registry.ts

Moves the API calls for the formatter API into the api.ts file along with the corresponding .interfaces.ts file

Move Formatter API fetching logic into api.ts

---

README.md

This adds a link in the Videos section of the README to the talk "Just
Enough Assembly for Compiler Explorer" which I gave at CppCon 2021.
(As mentioned on Twitter
https://twitter.com/knatten/status/1472937932814172160)

Add link to Assembly talk

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

In addition to 2022 & 2021.4 releases, I added some missing C compilers for earlier versions
Note that the version number in the package, icc version, and icx version are no longer in sync.
| package         | icc         | icx          |
| --------------- |--------- |---------- |
| 2022.0.1.71     |2021.5.0 |2022.0.0 |
| 2021.4.0.3201 |2021.4.0 |2021.4.0 |
Depends on https://github.com/compiler-explorer/infra/pull/652

add intel oneapi 2022, 2021.4 releases

---

package-lock.json
package.json

Just so we have ts-node and we can enable the new AMI without having the actual typescript changes, so we can always revert without having to mess with the AMI again after this

An ahead of typescript time patch

---

CONTRIBUTORS.md
etc/config/c++.amazon.properties
etc/config/c.amazon.properties

*This PR depends on https://github.com/compiler-explorer/infra/pull/650*
MRISC32 is an open Vector/RISC ISA (inspired by architectures such as Cray and MIPS). More information here:
* https://mrisc32.bitsnbites.eu
* https://github.com/mrisc32
* https://www.bitsnbites.eu/category/hardware-development/mrisc32
This adds C and C++ cross compilation targets for MRISC32, based on the MRISC32 GNU toolchain.
I have "kind of" tested the "amazon" setup locally:
* I ran `make ce && ./bin/ce_install install compilers` in infra (which downloaded the MRISC32 toolchain to my /opt/compiler-explorer folder).
* Then I added the relevant stuff to custom `c++.local.properties` and  `c.local.properties` files, ran `make dev` in a local clone of compiler-explorer, and verified that I could run the compiler. …

Add GCC compiler for MRISC32

---

lib/base-compiler.js
lib/compilers/ada.js
static/components.js
static/hub.js
static/panes/compiler.js
static/panes/diff.js
static/panes/gnatdebugtree-view.interfaces.ts
static/panes/gnatdebugtree-view.ts
views/templates.pug

Support for the GNAT Tree emitted by `-gnatdt` on stdout.
The pane is also available in the diff tool.

Ada: new pane for GNAT Debug Tree

---

lib/asm-parser.js

When compiling to binary and with the demangling enabled, the assembler parser
was not correctly matching the "labels". The labelRe regex is tailored from
matching against the real symbol names, before any demangling. In the
binary+demangle context, we rely on objdump doing both at once, feeding our
parser with demangled names.
Make the labelRe match anything of the form:
```
00000000123af    <every thing here is the label>:
```
fixes #3235

Fix parsing assembler from binary whent templates are used

---

etc/scripts/docenizerAVR.py
lib/handlers/asm-docs-avr.js
lib/handlers/assembly-documentation/avr.js
lib/handlers/assembly-documentation/router.js
test/handlers/assembly-documentation/avr-tests.js

This PR adds assembly documentation for the AVR architechture. Documentation is sourced from the [AVR Instruction Set Manual](https://ww1.microchip.com/downloads/en/DeviceDoc/AVR-InstructionSet-Manual-DS40002198.pdf).

Add AVR assembly documentation

---

etc/config/rust.amazon.properties

Installer for blog.rust-lang.org/2022/01/13/Rust-1.58.0.html
Infra: https://github.com/compiler-explorer/infra/pull/660

Install Rust 1.58.0

---

static/main.js

Fixes #3260 
I'm not too sure what change broke the changelog, but after a quick inspection it seems that we tried to pass the entire ESModule into JQuery which failed.
Only passing the actual content (default export) seems to work just fine.

Fix changelog not showing

---

lib/handlers/compile.js

Fix bug: /compile endpoint API errors should be 400s

---

package-lock.json

Remaining finds from `npm audit` require potential breaking changes.
**Before:** 11 vulnerabilities (3 low, 5 moderate, 3 high)
**After:** 6 vulnerabilities (4 moderate, 2 high)
```
ansi-regex  >2.1.1 <5.0.1
Severity: moderate
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install approvals@3.0.5, which is a breaking change
node_modules/mocha/node_modules/ansi-regex
node_modules/msee/node_modules/ansi-regex
msee  *
Depends on vulnerable versions of ansi-regex
Depends on vulnerable versions of marked
node_modules/msee
approvals  >=3.1.0-beta.1
Depends on vulnerable versions of msee
node_modules/approvals
strip-ansi  4.0.0 - 5.2.0
Depends on vulnerable versions of ansi-regex …
```

Run `npm audit --fix`

---

static/panes/compiler.js

I'm currently looking at a lot of assembly for parsing things, so I often have constants that represent ASCII characters. To save me the mental ASCII table lookup, I've extended the tooltip to show the ASCII character value, if applicable:
To simplify the code, I've changed the formatting order: it used to show the value as-is and then in decimal/hexadecimal (the other format). Now it always prints it in decimal, followed by hexadecimal, followed by ASCII.

Improve numeric tool tip to display character value

---

etc/config/ispc.amazon.properties

This should be merged after https://github.com/compiler-explorer/infra/pull/663, so ISPC 1.17.0 is available in the infra.
Fixes #3279

Add ISPC 1.17.0

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

MIPS GCC 9.3.0 from Codescape :
- https://codescape.mips.com/components/toolchain/2020.06-01/downloads.html
nanoMIPS GCC 6.3.0 from MediaTek:
- https://github.com/MediaTek-Labs/nanomips-gnu-toolchain/releases/tag/nanoMIPS-2021.11-02
refs #3282

Add 2 MIPS GCC based toolchains

---

etc/config/c.amazon.properties

This PR adds one line to the compiler configuration file, specifying that the MRISC32 GCC compiler outputs the "mrisc32" instruction set.

MRISC32 GCC should have instruction set "mrisc32"

---

lib/formatters/base.js
lib/formatters/clang-format.js
lib/formatters/gofmt.js
lib/formatters/index.js
lib/formatters/rustfmt.js
test/base-formatter-tests.js

As mentioned in https://github.com/compiler-explorer/compiler-explorer/pull/3247#issuecomment-1007636098, the BaseFormatter class now lives inside the /lib/formatters directory.

NFC: Move BaseFormatter into /lib/formatters

---

lib/tooling/strings-tool.js

If only binary output is selected without the execution, strings would complain
about missing file.

Fix strings tool calling wrt binary/executable targets

---

static/explorer.scss
static/panes/editor.js
static/settings.interfaces.ts
static/settings.js
views/popups.pug
views/templates.pug

As suggested by the linked issue, it adds both "Reformat Code" and "Do nothing" options.
The weird labeling allows to keep backwards compatibility for the setting, so that it will get the correct old behaviour
Closes #3266

Some more Ctrl-S behaviours

---

etc/config/ada.amazon.properties
etc/config/ada.defaults.properties
lib/compilers/ada.js

Add some comments around the command line options handling of GNAT.
Add strings tool for Ada.
Also enable binary and execution in the default config.

Add comments for GNAT handling of command line options and enable strings

---

etc/config/c++.amazon.properties

This adds the Derpstorm Clang ("Dang") compiler. It's meant to be the central place for all the proposal and other implementations I'll be cranking out over the months/years. It also hides the (old, unmaintained, barely compiling) `std::embed` of old. Hopefully, this will be the last time I have to bother you fantastic and lovely folks with something like this... 😅
In conjunction with:
- https://github.com/compiler-explorer/clang-builder/pull/30
- https://github.com/compiler-explorer/infra/pull/666

✨ Dang compiler addition!

---

etc/config/c++.amazon.properties

Unfortunately Clang 13 suffers the same as the Trunk versions. They have put the libc++ in a separate folder.
Assuming this will be the norm, maybe we should include it in the x86 group instead.

Add ldpaths for Clang 13 libc++

---

etc/config/c.amazon.properties

`clang_dang` has mostly C features right now, so we add it to the list of C compilers! I think this is the only file we have to edit, but do let me know if I messed this up at all!

✨ Add clang_dang as a C compiler!

---

etc/config/ada.amazon.properties
lib/compiler-finder.js
lib/compilers/ada.js

Add new adarts compiler properties used to set the RTS (if needed) to be used by
GNAT. This is needed as the cross compilers come with several RTS and you must
provide one.
Use Alire (https://alire.ada.dev/) cross compilers for ARM32 and RISC-V 64.

Add GNAT cross compiler from Alire project

---

static/panes/editor.js
static/settings.ts
views/popups.pug

Fixes #1801
Adds a new checkbox setting for automatically formatting the code upon compilation request. I added a note in the setting text indicating that it only runs for languages that have a formatter set up.

Add setting for automatically formatting on compilation

---

static/libs-widget.ts
static/options.interfaces.ts

The .used flag was not being cleared on version change for the other
versions of the same library
It's totally my bad. I broke it two months ago in #3077 
The functionality was there https://github.com/compiler-explorer/compiler-explorer/pull/3077/files#diff-449c94e1ad968cdcf587dae5e5dfc15bf5ded7dbbf1ef689c5677e7f503cd2a1L495 but I somehow missed that on the port,
and as found by @partouf while reproducing this, it was not easy to spot
Closes #3311

Fix libs widget selection properly updating

---

lib/compilers/ada.js

The property was incorrectly hardcoded in the AdaCompiler class.
As GNAT does not have an argument-parser, we can't rely on autodetecting the
-masm support. The easiest way is to simply define the intelAsm property for
GNAT compilers known to support it.
Fixes #3310

Ada: Fix intel filter active even for cross compilers

---

lib/base-compiler.js

This is an attempt/suggestion for resolving issue #1380 by turning off filters in the backend if -E is provided for C/C++ code.
Sir Walrus pointed out on the CE discord that though the handling of -E differs between compilers they all use -E for dumping preprocessor output so no special case handling is needed as far as turning off filters goes.

Improve -E support

---

etc/config/ada.amazon.properties

Remove incorrect (but harmless as unused) adarts property from Ada config file. This should not have been merged.

Remove leftover in config file

---

views/popups.pug

Looks like this
Which I think makes the popup more user firendly

Move each settings category to its own tab

---

lib/compilers/win32.js
lib/pe32-support.js

Library filter removed all assembly except for the labels in binary mode.
In case of win32 binary mode, use the binary parser and associate obj filenames even if theres no lineno info.
This way the library filter keeps working without having to disable the option. (because in normal mode library filter should work)

win32 binary library filter fix

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

objdumper was wrongly set to use native objdump for some targets:
- when binary is enabled, use a correct objdump (usually using one from the
equivalent cross-gcc toolchain)
- when binary is disabled, remove the property
refs #3327

Fix objdumper property for several cross compiler

---

static/panes/compiler.js
static/panes/tool.js

https://github.com/compiler-explorer/compiler-explorer/pull/3332/files#diff-cdc081b094f9b17444477d134e0c5b05df6db1e5f3536dfb057ca32cdd645750L82 removed the now unecessary workaround to change the codelens font family, but while [the API docs say that it defaults to the editor font](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IEditorOptions.html#codeLensFontFamily), that does not seem to be the case once the settings are updated, so we need to explicitly set them.

Change codeLens font on setting change

---

lib/handlers/compile.js
test/handlers/compile-tests.js

Check `req.body` being empty in addition to `source` being `undefined`.
One thing of note that I wasn't entirely sure about was that the error given when an empty body is passed, is seen as an internal server error, unlike other user errors like passing in a body with no content like `{}` - but I didn't want to change that behavior without asking about it. This also results in the output error being html even when posting with accept: application/json. I'd be happy to change that, just wanted to make sure of anything first.

Fixes check for empty request body

---

README.md
lib/asm-parser-dotnet.ts
lib/compilers/dotnet.ts

- Implement asm-parser for dotnet.
- Update the README.md to reflect language changes.
- Fix codegen perf issue while compiling code against intrinsics.
- Fix issue where there's an empty line after method signature.
Before/After unused labels filter:
Fixes #3325

Implement asm-parser for dotnet

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add cross GCC 11.2.0 for : s390x-linux, mips-linux, mips64-linux, ppc, ppc64 and
ppc64le for C, C++ and Ada.
Toggle supportsBinary for these targets for c/c++.
Small cleanup in Ada configuration for cross:
- credit Alire for riscv/arm
- disable binary/exec in group instead of compilers
refs #3282, #2470

Add cross GCC 11.2.0 for several targets + some tweaks

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Try to have a more homogeneous naming for some compilers and use
groups for different archs (e.g. MIPS/MIPS64).
fixes #3370

Minor cleanup/tidy of MIPS/POWER compilers

---

examples/python/default.py

Just realized that it does not have the classic square function like the rest of the languages

Changed Python default example to classical square

---

.husky/pre-commit
etc/config/cpp_for_opencl.amazon.properties
etc/config/openclc.amazon.properties
etc/scripts/orphancompiler.py

They were set to a group id, and https://github.com/compiler-explorer/compiler-explorer/blob/7e2eb51f8d0e5381d750cc158c1252c9cd8254fd/static/compiler-service.js#L67 triggers if no _compiler_ is found with such id, so the first compiler in the array was being used.
Also adds a check to the config script to ensure this does not happen again, and adds the script to the pre-commit (`time python3
etc/scripts/orphancompiler.py` is 50ms in my machine)

Fixes OpenCLs defaultCompilers to (prob.) intended ones

---

static/alert.ts
static/explorer.scss
static/load-save.ts
static/panes/compiler.js
static/panes/editor.js
static/panes/executor.js
static/panes/tree.ts
static/themes/dark-theme.scss
static/themes/default-theme.scss
views/popups.pug

Saw on Discord an example of dark theme error notification and realized that it could look better.
| light | dark |
|------|------|
|![imagen](https://user-images.githubusercontent.com/5364255/154989836-305c2cf8-e910-465e-b3e3-e95075b8da50.png)| ![imagen](https://user-images.githubusercontent.com/5364255/154989775-a21bc1f6-431b-472b-8e8f-33c2f0dd4424.png)|

Makes notification messages more readable

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Previous change split archs in different groups (e.g.
MIPS+MIPS64+MIPSEL+MIPS64EL) within a parent group (MIPSS) without giving them a
groupName property. All these groups inherit the groupName from their
parent group (e.g. MIPSS.MIPS64.groupName => "MIPS"), making the name
incorrectly duplicated.
Keep the group spliting but treat all these architectures as separate ones by
giveng each group a corresponding groupName.

Rename the PPC/MIPS groups accordingly to their architectures

---

static/explorer.scss
static/panes/editor.js
views/templates.pug

This PR is an attempted improvement for how the cursor position is displayed in the CE editor. It moves the cursor position display to the bottom-right corner of the editor:
Currently, the hiding/showing of the value can cause some funny behavior on small editors:
One consideration: It's tricky to get the background of this display synced with the theme and aligned with various components of the editor. A better solution would probably require diving into monaco widgets, I think this should work reasonably well most of the time though.

Position of cursor position

---

static/main.js
static/noscript.js
static/panes/compiler.js

Found them with WebStorm's code inspection.
We are using `String.substr` in a lot of places and that might be harder to replace, but this is a good first step

Remove some deprecated functions

---

lib/base-compiler.js
test/pp-output-cases/filter-tests.js

I noticed a little bug with preprocessor filtering when url #includes are used. It seems the expansion of the url include renames the source file to `<stdin>` so I've updated the filter to consider this a source marking.
https://godbolt.org/z/oq6b6r8ba, screenshot of the output:

Preprocessor output filtering enhancement

---

lib/base-compiler.js
lib/compilation-env.js

Not my greatest design moment, but putting it in the CompilationEnvironment
is a compromise between creating the handler in the compilation create()
and passing it into all the compilers' constructors.

Construct one FormattingHandler for all compilers

---

lib/compilers/clang.js

This PR adds the path to llvm-symbolizer to the environment used for executing binaries compiled with clang, implements #3023.

Improve clang asan output

---

static/modes/asm-mode.ts

Followup to #3403/ #3405, there's another string case to handle with a leading backtick as a quote:
(https://godbolt.org/z/EW63q8eqE)

Support MSVC's backtick strings

---

.eslintrc.yml
lib/compilers/clang.js
lib/compilers/spirv.js
lib/llvm-ast.js
lib/options-handler.js
lib/parsers/asm-parser-ewavr.js
lib/tooling/readelf-tool.js
lib/tooling/strings-tool.js
test/pp-output-test.js

This patch adds a linter rule to spot uses of `if(...)` vs `if (...)` (and same for `for`, `switch`, `while`, etc.)
I keep doing the first out of habit 😅

Add keyword-spacing eslint rule

---

static/hub.js
static/identifier-set.ts
tsconfig.frontend.json

In preparation for refactoring Hub to TypeScript, I've moved Ids out of the hub.js file and renamed it to IdentifierSet which is a bit more descriptive.

Move Ids out of hub.js

---

static/event-hub.ts
static/hub.js

Moves the WrappedEventHub into a separate file in preparation for refactoring Hub into TypeScript

Move WrappedEventHub out of Hub

---

lib/base-compiler.js

When compiling to binary the order of source files and linked libraries
can matter for some compilers (and linkers). Putting the input file
first avoids linking issues in these cases.

Moved inputFilename forward in compiler arguments

---

static/themes/dark-theme.scss

Small tweak for dark mode for the compiler options input field when flags view is open:
Old:
New:

Update disabled compiler options input background on dark mode

---

lib/base-compiler.js
static/panes/cfg-view.ts

Updates backend / frontend to disable graph output when -emit-llvm is provided, for now. Fixes #3465. Later I'd like to add support for cfgs for llvm's ir.

Disable graph output when -emit-llvm is provided

---

static/panes/editor.js

For really large sources the generated cppinsights URL can be too long for the server and result in an HTTP 414 error page. Not a big deal, this should be exceedingly rare anyway, but I've tried to improve the behavior here. The idea is for a large source that would break the URL the button can at least be a shortcut and the user can quickly copy-paste.

Improve cppinsights button for large sources

---

static/themes/dark-theme.scss
static/themes/default-theme.scss

https://github.com/compiler-explorer/compiler-explorer/blob/4db110ec51ff84c81f1e05cd18608768beaada6c/static/themes/dark-theme.scss#L486-L488
This rule causes the 'x' to disappear when hovering over it for plain white toast notifications. As far as I can tell `.close` is only used for toast close buttons so I think it's safe to remove.
I've also updated the close button's color to match the toast's text color (looks a little better to my eye).

Update toast .close coloring

---

static/panes/compiler.js

The 'Option -flto is being used without Compile to Binary.' unwise argument notification shows up even when compiling to binary currently. PR adds check for whether we're compiling to binary.

Bug fix for 'Option -flto is being used without Compile to Binary'

---

etc/config/c++.amazon.properties

This updates the configuration to add both HDF5 (1.12.1, 1.13.1) and
HighFive to the libraries available in CE. Since HDF5 is a shared object
library, these changes should go along with changes in infra.
See also PR here: https://github.com/compiler-explorer/infra/pull/695
The main question that is still open is how the paths should be exactly set. For the local setup I have verified that in principle all components play long well. But adjusting the paths for the `/opt/compiler-explorer` tree on the AWS instances I am flying blind.
More specifically:
- How do we deal with multiple libhdf5.so (coming from multiple library versions?)
- The headers had to be installed with a `post_stage` script (in the infra config), but I am not entirely sure where they actually end up?

Add HDF5 and HighFive libraries to amazon config

---

lib/base-compiler.js

Rationale is "user args", filename, then autogenerated.
Closes #3492. Hopefully doesn't introduce another issue.

Reorder user args first

---

examples/analysis/default.asm

The default code in the *Analysis* source editor always has been:
```asm
code_snippet:
vpslldq xmm1, xmm0, 3
vaddps xmm0, xmm0, xmm1
vmulps xmm1, xmm0, xmm0
dec rcx
jne code_snippet
```
Unfortunately, this is Intel syntax and OSACA only supports AT&T syntax so far.
This leads to an initial wrong assumption by OSACA (guessing it is aarch64) and consequently an useless output:
```
Open Source Architecture Code Analyzer (OSACA) - 0.4.7
Analyzed file:      /app/example.asm
Architecture:       A64FX
Timestamp:          2022-04-08 11:50:18
-------------------------- WARNING: No micro-architecture was specified -------------------------
A default uarch for this particular ISA was used. Specify the uarch with --arch.
See --help for more information. …
```

Change syntax of Analysis default from Intel to AT&T

---

app.js
lib/options-handler.js
static/lib-utils.ts
static/options.interfaces.ts
static/panes/compiler.js
static/panes/conformance-view.js
static/panes/executor.js

Problem:
In 2021 I tried to fix the problem of producing extremely large client-options.js files, because all the supported libraries got listed per library. We decided that there should be only 1 list of libraries and then have exceptions per compiler.
(https://github.com/compiler-explorer/compiler-explorer/commit/e24f724e47bcdc1e4acc7c62036a32282dc4e8af)
This saved a lot of megabytes, but obviously I somehow forgot about the fact that the Microsoft compilers would mess up this logic. Unfortunately this didn't show up asap, because the version of CE that Microsoft had was ancient and somehow it worked better. Until Microsoft updated to latest and didn't mention the libraries anymore per compiler, and we're now faced with a mismatch of the libraries that we have and disregarding the …

Fix for msvc library issue

---

static/widgets/pane-renaming.ts

Saw on Sentry that this was happening and decided to take a look. No idea where the "reject" comes from, but it's now gone. The default `no` callback is ok in this case
Fixes COMPILER-EXPLORER-8VJ

Fixes bad usage of alert system entersomething

---

etc/config/swift.amazon.properties

Adds Swift 5.6 as a compiler option. The associated infra PR is compiler-explorer/infra#706.

Add Swift 5.6.

---

static/main.js

Saw COMPILER-EXPLORER-7PV on Sentry. The linked full url seems to be missing things so probably the error is not on our side of cases like this, but I guess that at least letting the user load the page would be good.
Would a notification here of some sort make sense? Yes, right?

Catches the rison deserialization exception to allow page loads

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Both compilers were missing a name and were defaulting the their id.

Fix ppc64 GCC 11.2 names for C and C++

---

.gitattributes

Tiny fix, GH was crawing our avr and 6502 generated code.

Use pattern for asm-docs generated files in gitattributes

---

.github/workflows/test-and-deploy.yml
.prettierrc.yml
package.json
static/alert.interfaces.ts
static/alert.ts
static/analytics.ts
static/ansi-to-html.ts
static/codelens-handler.ts
static/colour.ts
static/compiler-picker.ts
static/event-hub.ts
static/formatter-registry.ts
static/global.ts
static/history.ts
static/hub.ts
static/lib-utils.ts
static/line-colouring.ts
static/local.ts
static/monaco-config.ts
static/motd.interfaces.ts
static/motd.ts
static/multifile-service.ts
static/noscript.ts
static/options.interfaces.ts
static/options.ts
static/settings.ts
static/sharing.ts
static/themes.ts
static/url.ts
static/utils.ts

Until now, the prettier formatting has been effectively disabled because we required a pragma comment to enable formatting. This PR enables prettier for the entire TypeScript part of the frontend.

Enable Prettier for TypeScript frontend

---

static/widgets/fontscale.ts
views/font-size.pug

This PR makes ctrl+click on the font scale widget reset the font scale to default. I also updated the tooltip for the button.
There are a couple of formatting changes here not done by me, I think it was automatically done by prettier?

Fontscale ctrl+click

---

etc/scripts/docenizers/docenizer.py
lib/asm-docs/generated/asm-docs-amd64.js
test/handlers/asm-docs-tests.js

This fixes a bug pointed out by Ali A. on discord with docs for `shr` not being found

Updated x86 docenizer to read adjacent tables

---

lib/compilers/solidity.js

As per the request here https://github.com/compiler-explorer/compiler-explorer/issues/3520
This PR is a small tweak to the Solidity support which aims to map asm instructions to lines of code. Solc attributes each instruction a range of characters from the source, sometimes this range can be quite large - e.g. a whole function, or even a whole contract. In these cases I just use the first line, which seems to work ok as if an instruction is attributed to an entire function then attributing it to the function sig instead has a similar effect.
I also found the tags (jumpdests) kind of hard to follow so this PR also replaces as many of those tags as possible with human readable function names.
Suggestions etc are most welcome, JS isn't really my thing!

Map solidity EVM assembly to lines of code

---

lib/base-compiler.js
lib/buildenvsetup/base.js

* compiler cache is keyed off of compiler's `mtime`
* `mtime` isn't set until `initialise()`
* buildenv was running stuff ahead of that, and so was being cached with a `null` `mtime`
* introduces a new `initialise()` call for `buildenv`
* now `throw` on trying to use compiler cache before mtime is set

Defer running buildenv stuff

---

CONTRIBUTORS.md
lib/compilers/solidity.js

This fixes compilation for compilers between 0.4.x and 0.8.x, and line numbers seem to work ok though some early compiler versions produce different line number mappings.

Fix Solidity compilers and line numbers in versions 0.4.x - 0.8.x

---

static/hub.ts

Fixes the following bug reported on discord:
> eirk — 
closing the compiler window and clicking add->Execution only doesn't seem to work anymore...
The issue is the `Sentry.captureMessage`:
```
Uncaught TypeError: T.default is undefined
findParentRowOrColumn hub.ts:273
```
Not sure what causes the Sentry issue but this reveals that findParentRowOrColumn and findParentRowOrColumnOrStack can return null so I've updated the typing and removed the sentry log.

Update typing in hub.ts

---

static/panes/ast-view.ts

Things such as LDC return the AST output as strings. Handle those cases too
Closes #3566

Handle astResults being strings

---

static/noscript.ts

Tiny regression from #3576 
Noscript.ts is compiled as its own target, therefore it also needs the jQuery import

Fix jquery import regression in noscript.ts

---

.github/workflows/test-and-deploy.yml
.github/workflows/test-win.yml
package.json
tsconfig.frontend.json

Ensures that there are no typescript errors when the regular test CI run is being performed.
This means we won't accidentally merge in frontend code that doesn't compile because the external contributors don't run the build-dist CI (which does the check when compiling)

Add npm script for noEmit compiling frontend and backend to catch ts errors

---

static/panes/editor.js

It used not to, so we linked to the unsecured version. https://quick-bench.com/ now works so we can update acordingly

Quickbench now supports https

---

etc/config/c++.amazon.properties

While not a fix, it could help in #3092 by adding an alternative version (IF it builds)

Add Benchmark 1.6.1

---

.github/ISSUE_TEMPLATE/bug_report.yml

Some bug reports have browser versions added that might be annoying to fill in cases where it's not really necessary. This PR tries to make it clear that those fields are optional in most cases.

Make it clear that OS/browser versions are optional in most cases

---

lib/compilers/java.js

Hello!
This patch implements a todo left behind with the Java implementation, as we can now detect the main methods for Java executions. This was a bit of a pain point for [Headline/discord-compiler](https://github.com/Headline/discord-compiler), as many folks struggled to find appropriate class names, so I figured I'd contribute this patch.
Most of this patch was derived from the previous `objdump()` implementation, but essentially we're just calling `javap` for lists of methods in each class file and hand picking ones that contain a main method. If this is a bit of a dirty implementation, I'd love hear feedback about how I can improve it (as well as adding tests).
It seems the linter went ahead and made other file changes, changes I didn't recognize until after it was committed. I …

Automatically detect Java entry points

---

static/panes/compiler.js
static/panes/executor.js
static/panes/pane.ts

This fixes #3616.
Printbugging triage:
```js
1651639870337 resize <-- w: 1277 h: 638 top: 70 bottom: 32 // resize information before drag
1651639879099 resize <-- w: 1277 h: 638 top: 0 bottom: 0   // drag
1651639881524 resize <-- w: 1277 h: 638 top: 0 bottom: 0   // drop
1651639883889 resize <-- w: 1277 h: 637 top: 70 bottom: 32 // first resize after drop (e.g. by resizing the window)
```
I guess somehow there's no `outerHeight` for these when golden layout is dragging them around, not sure why. What I've done to fix is `_.defer` in the resize function. The compiler and executor panes are directly affected and then I've made the change in pane.ts too for any other and all future panels.

Fix resize bug

---

static/explorer.scss
static/panes/cfg-view.ts
static/panes/output.ts
views/templates.pug

This seems to be the only way to restrict what gets selected.
The first listener is to check if the later Ctrl-A happens inside the output pane.
The only issue now is the fact that this is a global callback, and closing the pane might break it, but nothing seems to output in the console so... 🤞

Make Ctrl-A in output pane only select its contents

---

CONTRIBUTORS.md
lib/base-compiler.js
lib/llvm-opt-transformer.ts
package-lock.json
package.json

`make check` passes.   
Following [this concern](https://twitter.com/OfekShilon/status/1496593807500062721) I checked the differences between the original compiler-opt-info github version and the npm version, and they seem non-functional. So my fork includes a fix based on the github version.
Not sure whether `yarn` is essential in the generated packages-lock, and don't think it matters.
Closes #3275

Fix #3275 : move from compiler-opt-info to compiler-opt-info2

---

lib/handlers/api.js

This makes it so any other method other than the defined returns 405

Add 405 handlers for API endpoints

---

etc/config/ispc.amazon.properties

Adding ISPC v1.18.0.
Corresponding infra commit PR, which needs to be merged before this PR: https://github.com/compiler-explorer/infra/pull/716  (so ISPC v1.18.0 is available in the infra).

Add ISPC v1.18.0

---

static/analytics.ts

@jeremy-rifkin found that have not been receiving many analytic events since January 1st. This PR undoes the only two iffy changes made to the file in that time period, to see if it fixes the situation

Get GA script back to Google's default

---

docs/README.md

GCC allows more than RTL for its IR dumps, reflect that.

Documentation fixlet

---

etc/config/ada.amazon.properties
etc/config/assembly.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

GCC 12.1.0 has been released:
https://gcc.gnu.org/gcc-12/changes.html
fixes #3624

Add GCC 12.1.0

---

etc/config/compiler-explorer.defaults.properties
webpack.config.esm.js

* Enable persistent disk cache for webpack (we'll have to keep an eye on this...)
* Configure a default persistent compiler discovery cache in the `out` dir.

Development speedups

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This PR adds the [widberg clang compiler](https://github.com/widberg/llvm-project-widberg-extensions). This compiler is an experimental reverse engineering compiler being developed at the University of Massachusetts Lowell Computer Science Department. We believe that there will be great utility in being able to provide live links to code samples using the compiler in publications. The multi-repo organization of CE is somewhat unwieldy to an outsider like me, so I have undoubtably made a mistake in at least one of these PRs; thank you for any fixes you are able to provide.
Related PRs:
https://github.com/compiler-explorer/clang-builder/pull/35
https://github.com/compiler-explorer/infra/pull/721
https://github.com/compiler-explorer/compiler-workflows/pull/8

Add widberg compiler

---

lib/compiler-finder.js
static/panes/compiler.js

#3665 will add `instructionSet` to xtensa compilers, but it does not have asm docs associated, so the "Show asm documentation" context menu item will still show just to error out if pressed. This PR adds a way to let the page know not to even try.
Note that an even better way would be to automatically detect cases like this, but for now this is good enough

Have a way to disable asm docs if needed

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

This PR sets the instructionSet configuration key for all Xtensa compilers to "xtensa", which prevents Compiler Explorer from defaulting to x86 assembly documentation.
Fixes #3451.

Change Xtensa ISA to "xtensa"

---

static/panes/editor.js

This change brings the behavior of the linked line system in the editor more in-line with the handling in other panes and improves two little oddities in the editor:
Linked line decorations interfere with selection decorations which can make selections invisible:
Currently if a line is linked between an editor and other panes, hovering over other lines in the editor updates linked lines in other panes but doesn't update the linked lines in the editor which is a little surprising behavior.

Clear linked line in the editor on mouse move

---

static/ansi-to-html.ts
test/ansi-to-html-tests.js

This adds support for rgb ansi escape sequences. RGB handling is directly from https://github.com/rburns/ansi-to-html, contains changes from #3662 (now merged).

Support 24-bit rgb ansi sequences

---

examples/assembly/Sum_array_(AVX2).asm

I thought it would be nice to have an example in assembly that is basically as optimized as possible (at least, to the extent of my capability) and that is also commented explaining exactly how it works. This way people can easily compare examples of what the assembly output of compilers look like for summing integers and hand-written assembly that is theoretically better.
As for the code in the example itself, unlike some examples that do the same thing in C/C++/Rust, it handles arrays of any size. Vector instructions are always used in this example, even to handle the residual elements that are normally processed with a scalar loop at the end. For this reason, it is much faster (between 20-80% faster on my TR1950x for array sizes between 300 and 511) than clang's `-O3 -mavx2` output …

Add x86 assembly AVX2 sum array example

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Following https://github.com/compiler-explorer/gcc-cross-builder/pull/19
and https://github.com/compiler-explorer/infra/pull/725,
update C++ and C config files.
GCC versions for riscv32 and riscv64: 8.5.0, 9.4.0, 10.3.0 and 11.2.0.

Add new versions of GCC for rv32 and rv64

---

static/modes/ptx-mode.ts

Fixes a couple things I noticed while looking at ptx assembly
Before:
After:
(I didn't have the addresses on locally while testing, this PR doesn't remove those 😄)

Improve highlighting in ptx-mode

---

examples/cuda/default.cu

I think the cuda example should probably be using the block index and size information too

Update default cuda example

---

lib/toolchain-utils.js

prefer built-in `Array#find()` over lodash lib in
`lib/toolchain-utils.js` file

style: prefer built-in `Array#find()` over lodash lib

---

etc/config/c++.amazon.properties

Thanks to these PR:
https://github.com/compiler-explorer/gcc-cross-builder/pull/27
https://github.com/compiler-explorer/gcc-cross-builder/pull/26
we can add 11.3.0 and (fresh) 12.1.0.

Add 2 more versions of GCC for rv32 and rv64

---

static/explorer.scss

Linked code decoration is hardly visible.
To make it more visible, despite being rendered bold it now also gets colored in red.

Highlight linked code (decoration) in red

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Incorrect copy/paste, GCC riscv32 are -elf, not -linux.
refs #3677

Fix GCC riscv32 path

---

etc/config/ada.amazon.properties
etc/config/ada.defaults.properties
lib/compilers/ada.js

When compiling to binary or running the executable, extra options are inserted,
breaking some weak asumption in Ada/GNAT on where in the list is the
inputFilename.
Override prepareArguments() for GNAT and (more) cleanly handle the
options (split between gnatmake, compiler, binder and linker).
Also use 'gnatmake' as main compiler executable instead of 'gnat'.
Fixes #3709

Ada: Fix inputFileName at incorrect loc for binary and execution

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

ARM GNU Toolchain: 11.2-2022.02 for AArch32 bare-metal target (arm-none-eabi)
ARM GNU Toolchain: 10.3-2021.10 for AArch32 bare-metal target (arm-none-eabi)
ARM GNU Toolchain: 10.3-2021.07 for AArch32 bare-metal target (arm-none-eabi)
Signed-off-by: Ryan McClelland <rymcclel@gmail.com>

Add 3 new versions of GCC for ARM GNU Toolchain

---

etc/config/d.amazon.properties

And congrats on the 10th aniversary!
Infra: https://github.com/compiler-explorer/infra/pull/733

Add LDC 1.28.1 and 1.29.0, make 1.29.0 the new default

---

lib/compilers/ada.js

Need to jump in the dedicated directory, but then GNAT may write some files that
may conflict with ours: create a dedicated temp subdir to run GNAT.

Ada: fix compile to binary/execute within jail

---

static/panes/compiler.js
static/panes/executor.js

The #include <url> sources weren't being expanded when compiling via Tree/IDE mode.
Because it's an async process, I've used Promise.all() to wait to resolve all the files first before starting the compilation.

urls werent being expanded in tree/ide mode

---

lib/parsers/asm-parser.js
test/filters-cases/nvcc-example.asm.directives.approved.txt
test/filters-cases/nvcc-example.asm.directives.comments.approved.txt
test/filters-cases/nvcc-example.asm.directives.labels.approved.txt
test/filters-cases/nvcc-example.asm.directives.labels.comments.approved.txt
test/filters-cases/nvcc-example.asm.directives.labels.comments.library.approved.txt
test/filters-cases/nvcc-example.asm.directives.labels.comments.library.dontMaskFilenames.approved.txt
test/filters-cases/nvcc-example.asm.directives.library.approved.txt

Previously this filter did not correctly identify used labels in CUDA PTX output, which caused it to remove important labels.
Closes https://github.com/compiler-explorer/compiler-explorer/issues/1128 and https://github.com/compiler-explorer/compiler-explorer/issues/2886.

Fix unused label filter for CUDA PTX output

---

lib/utils.ts
test/utils-tests.js

Fixes #3719
Took a look at the source of https://www.npmjs.com/package/shell-quote and found out you can escape things with a \\ by default.

Allow hashes in arguments

---

etc/scripts/util/orphancompiler.py
lib/compiler-finder.js
lib/options-handler.js

In #3673, @dkm suggested to use `path.delimiter` to avoid os checks for directorly list separators. This PR uses the same solution in a few more places, and updates the `orphancompiler.py` checks to include libPath arrays not being empty

Sprinkle some path.delimiter around

---

package.json

This makes it so running checks will not spam the console with successful tests, and will only output errors.
I know that it will conflict with #3722, will fix as needed

Set minimal reporter in mocha test check

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/go.amazon.properties

GCC 9.5.0 has been released last week.
https://gcc.gnu.org/gcc-9/changes.html
refs https://github.com/compiler-explorer/compiler-explorer/issues/3731

Add GCC 9.5 for native C/C++/D/Go and Ada

---

.github/labeler.yml
etc/config/mlir.defaults.properties
examples/mlir/default.mlir
lib/base-compiler.ts
lib/compilers/_all.js
lib/compilers/mlir.ts
lib/languages.js
static/modes/llvm-ir-mode.ts
static/modes/mlir-mode.ts
views/resources/logos/mlir.svg

Partially addresses #3730
This PR contains a minimal implementation for running MLIR transforms and passes in Compiler Explorer.
**It currently supports:**
- Running passes and transforms with the mlir-opt command line
**It needs the following:**
- An actual monaco-editor mode, right now it's just copied LLVM's mode because a lot of operators are similar
- A better default example, right now it's just one test I found in the MLIR repository (maybe @siboehm has some ideas?)
- Infra installers and builders
- Probably a fair few other things I'm unable to name right now

Create minimal support implementation for MLIR

---

lib/base-compiler.ts

While investigating something else, I discovered that CE was objdumping binaries in CMake mode even when the user only asks for execution.
We have separate code for normal compilations that already takes this into account here by taking a different path https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/base-compiler.ts#L1988

Don't objdump when only executing cmake result

---

etc/config/typescript.amazon.properties
etc/config/typescript.defaults.properties
lib/compilers/_all.js
lib/compilers/typescript-native.js
lib/languages.js

Non-functional and non-shortlink-breaking change
Renames some of the TypeScript compiler textual names to TypeScript Native based on feedback on Discord

NFC: Rename TypeScript to TypeScript Native on website

---

etc/config/c++.amazon.properties

Proposing to add the B-Multi library to the live site. https://gitlab.com/correaa/boost-multi
Followed the steps as best as I could in https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md#adding-a-new-library-to-the-live-site
Feedback on improving the hooks and the organizations of files in the repository is welcome.
The goal is to include the library by doing `#include<multi/array.hpp>`.
This PR is related to infra's PR https://github.com/compiler-explorer/infra/pull/745

Add the gitlab bmulti library

---

etc/config/mlir.amazon.properties
examples/mlir/default.mlir
lib/languages.js

Also adds a tiny disclaimer to the default example because MLIRs text format isn't stable
(also changes the monaco output mode to mlir)

Enable MLIR for prod with 14.0.0 and 14.0.5

---

static/panes/editor.js

All the code was there to have tools output displayed as squiggles in the editor, but they were not taken into account.
If that was an overlook, this PR will fix it. If this was on purpose because some tools display a source location without us wanting it to be treated as an error, it might make sense to add a flag in the tools' configuration.

Display tool tags in the editor

---

static/panes/ast-view.ts
static/panes/editor.js

The Monaco tokenizer works with 0-based offsets, while both the decorations and the compiler error messages use 1-based offsets, making getTokenSpan return a shifted result. Most of that is compensated by the call sites of getTokenSpan, but there was a small bug for squiggles on single-character tokens and in the AST view for AST highlighting on mouse-over of contiguous tokens.

Fix token span calculations

---

etc/config/cuda.amazon.properties

Adds support for the [NVIDIA CUDA C++ runtime compilation library (NVRTC)](https://docs.nvidia.com/cuda/nvrtc/index.html) as a CUDA compiler. Available versions are the same as those for NVCC.
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/1870
Depends on https://github.com/compiler-explorer/infra/pull/734
cc @jrhemstad

Add NVRTC CUDA compiler

---

static/themes/dark-theme.scss

This `!important` is no longer necessary to display correctly (I think it was in earlier versions of Monaco) and it can override more important decorations. Also the default theme doesn't have it so it looks like an overlook.

Linked code background color doesn't need to be !important

---

lib/tooling/base-tool.js
test/options-handler.js

This change makes it possible to create a tool that would have a different output format (which I am doing).

Make tools output parsing overridable.

---

lib/utils.ts
static/panes/editor.js
test/utils-tests.js
types/resultline/resultline.interfaces.ts

Moving severity parsing logic next to the rest of the parsing allows customizing both severity and the tag message for some tools. It also seems a bit more homogeneous to me from an architectural point of view.

Move severity parsing with the rest of the output parsing.

---

static/panes/editor.js
types/resultline/resultline.interfaces.ts

The tool I'm trying to integrate can have markers that span more than one token and even when marking a single token, it already calculated the right span, so an additional calculation is redundant.

Add a way to trigger model markers on a range instead of a single token.

---

static/panes/editor.js
types/resultline/resultline.interfaces.ts

In Monaco, tooltips for markers can have one (1) link, as a treat.
This link has to be passed in the `code` field. This PR allows using this feature. The resulting tooltip with the link included looks as follow:

Make it possible to display a URL in marker tooltips.

---

static/panes/tool.js

The tool output editor doesn't allow clicking on URLs like the compiler editor. Adding a small regex replacement to emulate that.

Make URLs clickable in tools outputs.

---

static/panes/conformance-view.js
views/templates.pug

This should be fine for #3447.
The UI now looks like this:
This is what it was proposed in the issue:
Let me know if you would rather have the button in the place described in the screenshot above.

Implement copy compiler button in conformance view

---

docs/SystemdSocketActivation.md

StandardOutput=syslog is deprecated. Let's remove the setting altogether from the example so we rely on the default behavior instead which works exactly the same but doesn't trigger a warning from systemd.

Drop StandardOutput=syslog from systemd docs

---

static/themes/dark-theme.scss

Proposal to change the line highlight for dark mode, from:
to:
The former is barely visible if the screen is not well calibrated, which happens a lot during conference presentations for example.

Make line highlight more visible in dark mode.

---

lib/tooling/base-tool.js

As discussed with Matt, adding statistics at the tool level could give precious information to tool developers.

Get statistics on tools usage per language / compiler

---

.github/labeler.yml
etc/config/jakt.amazon.properties
etc/config/jakt.defaults.properties
examples/jakt/default.jakt
lib/compilers/_all.js
lib/compilers/jakt.ts
lib/languages.ts
static/modes/_all.ts
static/modes/jakt-mode.ts
types/languages.interfaces.ts

See https://github.com/SerenityOS/jakt for the language repository.
Jakt is a new, currently experimental, compiled programming language
designed for the SerenityOS project, especially for OO-style GUI
development. But if the language turns out to be useful, it will
probably be expanded to work for all kinds of systems programming in
SerenityOS.
It's current design for the forseeable future includes a transpilation step
to C++, using parts of the SerenityOS standard library (called AK)
as a runtime to provide underlying implementations for standard types
such as String, HashMap, Array, etc.
As of this point, there are two compiler implementations. The original
implementation is Rust-based, and a selfhosted Jakt compiler is being
developed to replace the Rust-based compiler soon. Then …

Add the jakt programming language

---

static/panes/compiler.js

if the two strings are the same if trimmed, then don't display the button to toggle between them

Skip full version button in info pane if not needed

---

static/widgets/load-save.ts
views/popups/load-save.pug

Adds a button to overwrite localstorage entries in load-save.
Needs some UI changes before it can be merged.
Closes #3876

Add overwrite option to load-save localstorage

---

static/panes/executor.js
static/settings.ts
views/popups/settings.pug
views/templates/panes/executor.pug

Now that this is here, maybe another toggle for tools would also be good
to have. Maybe even for the compiler itself.
And if we go that route, why not 1 for all three kind of panes?
Closes #3783

Adds way to disable executor recompilation on parameter change

---

static/panes/gccdump-view.ts

Fixes https://github.com/compiler-explorer/compiler-explorer/issues/3886
Tom-select recently changed their `clearOptions()` function to add a parameter, previously it did not take any parameters but we still passed `true` to it. https://github.com/orchidjs/tom-select/commit/049f5a65e444e6c861599c8971299ce3ed3a02f7#diff-a5b86ab78740a77920c9adb8e6fbccfab70018b535d22a39d2f2b91d5bd1c21aR1774

Fix gccdump

---

lib/llvm-opt-transformer.ts

Add DebugLoc data to opt remarks, in the simple form `(Line:Col)`. Eg the "(4:0)" here:

Temporary fix for #3856

---

lib/compilers/argument-parsers.js
lib/compilers/ldc.js

LDC does not quite copy Clang cmdline options, so it's best to implement its own parser.

Give LDC its own LDCParser for cmdline options.

---

lib/options-handler.js
static/panes/compiler.js
test/options-handler.js

That would allow replacing the default cog icon with a custom 16px high icon (which should probably always be white/black to avoid noise)

Allow having an icon for the tools.

---

static/panes/editor.js

This avoid errors like decorations leaking into lang changes..
Closes #1728

Clear editor decorations on lang change

---

static/panes/editor.js
static/quick-fixes-handler.ts
types/resultline/resultline.interfaces.ts

Monaco can provide quick fixes for errors. They appear as a small lightbulb at the beginning of the line, that you can click (or you can press Ctrl + ., or you can use the hover menu). When triggering the quick fix, the error will be fixed automatically.
With this PR, it becomes possible to attach fixes to ResultLine tags.
The way to pass information from the editor and the `CodeActionProvider` is inspired by codelens-handler.

Introduce quick-fixes.

---

lib/base-compiler.ts
lib/compilers/rust.ts

Also filters it with rust to remove the color==always flag as the first
implementation.
Closes #2420

Adds ability to detect incompatible options & userOptions

---

lib/llvm-opt-transformer.ts

Eliminate artifacts like this `f (0:0)`:
The previous PR is closed, gotta open a new one.

Small addition to #3908: Exclude bogus DebugLoc from opt remarks

---

.github/labeler.yml
CONTRIBUTORS.md
etc/config/circt.amazon.properties
etc/config/circt.defaults.properties
examples/circt/default.mlir
lib/compilers/_all.js
lib/compilers/circt.ts
lib/languages.ts
types/languages.interfaces.ts
views/resources/logos/circt.svg

This adds basic support for CIRCT as requested in #3825. The addition
is based on the similar additions for MLIR in #3733 and #3770.

Add basic CIRCT compiler support.

---

lib/formatters/clang-format.ts

clang-format inserts spaces after the URI scheme and before the hier-part. Remove the spaces to reform a valid URL.
For example, formatting the following code
```cpp
#include <https://localhost:8443/develop/json.hpp>
```
results in a broken https include:
```cpp
#include <https:  //localhost:8443/develop/json.hpp>
```
This could of course be done on the client side but might be a little messy. Let me know if that's preferable.
Fixes #2928.

Repair http(s) includes after formatting

---

etc/config/jakt.amazon.properties

The selfhosted compiler now always builds the transpiled C++ file,
so this flag doesn't exist any more.

Jakt: Remove -b flag

---

static/panes/compiler.js
views/templates/panes/compiler.pug

The dropdown autoclosing now properly works again, and removes some ES6 code from the compiler code (The better solution would be to move it to ts already, but those things are slow!)
This comes from #3910

Fixes small UI problems

---

etc/config/hlsl.amazon.properties

Noticed that the compilers were not being sorted by semver, so checked and saw they just specified the name.
This PR then creates a group, marks it as semver, and gives the compilers proper basenames.

Bring hlsl config to same style as other languages

---

static/panes/haskellcmm-view.ts
static/panes/haskellcore-view.ts
static/panes/pane.ts

Fixes #3951 
Must have missed them in the jquery webpack replacement PR somehow :cry:
Also removed an unused jquery import

Patch missing jquery imports

---

static/panes/conformance-view.js

This was making the error icon not show up
A static TS function was being called as a member function, but the IDE was not complaining :(
Also adds aditional check to avoid recompiling twice when the page loads up for the first time
Releated to the secondary issue reported in #2696 comments.

Fixes conformance view bug

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties

Add GCC 12.1.0 for cross targets:
- mips + mips64 + mipsel + mips64el
- powerpc + powerpc64 + powerpc64le
- s390x
- arm + arm64 (only add new languages)
- riscv32 + riscv64 (only add new languages)
- avr
- msp430
When possible, the following languages have been enabled:
- Ada (GNAT), except for targets supported by Alire
- D (GDC)
- Fortran (gfortran)
- C++
- C
refs #3729
refs #3761

Add cross GCC 12.1.0 for Ada, C++, C, D and Fortran

---

package.json

This removes the extra `npm run` from the check script so it can run as expected.
Regressed by https://github.com/compiler-explorer/compiler-explorer/pull/3847

Fix check script

---

app.js

I've been bitten by 
> [webpack-dev-middleware] wait until bundle finished: /
a few too many times thinking that the compilation would already be done.
Now it outputs an extra message when it stops compiling:

Makes webpack-dev-middleware notify on build finish

---

lib/compilers/rga.ts

RGA register analysis provided through shae.exe would mismatch the
emitted assembly if labels were present since labels don't correspond to
instructions. The modification in the emission here addresses this issue
(and may need to be disabled in future versions of RGA). With existing
issues though, it resolves issues in correspondence.
This commit also fixes an issue where the RGA error output (if present)
was stomped over by a different log line.

Improve RGA register analysis association

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

Add native GCC 12.2.0 for Ada, C, C++, D, Fortran and Go.
refs #3973

Add native GCC 12.2.0

---

CONTRIBUTORS.md
lib/parsers/llvm-pass-dump-parser.ts
static/panes/llvm-opt-pipeline.ts
types/compilation/llvm-opt-pipeline-output.interfaces.ts
views/templates/panes/llvm-opt-pipeline.pug

This adds a debug info filter option so its possible to see debug info across the opt pipeline when desired. Most people probably do not want to see this info, so the filter is enabled by default (info removed by default), matching the current behaviour.
CC @jeremy-rifkin

Add debug info filter option to LLVM opt pipeline viewer

---

lib/base-compiler.ts
lib/compilers/rust.ts
lib/compilers/zig.js
types/libraries/libraries.interfaces.ts

As discussed in #3966, this fixes the types for `.path` and `.options`. They are now properly used as arrays everywhere

Fixes wrong types in libraries.interfaces.ts

---

lib/handlers/api.js
lib/handlers/compile.js

Now that we return 405 if the method is not supported, calling next() in the handlers will output that instead of 404, so we send those manually.
Also fixes some weird code repetition

Bring back old behaviour of 404 on missing compiler

---

lib/parsers/llvm-pass-dump-parser.ts

For the LLVM opt pipeline viewer, the first machine pass that LLVM outputs has the same MIR before and after, making it seem like it did nothing, but really it has transformed the program from IR to MIR. It's helpful to highlight that change and ensure it appears in the passes list.
The diff view is a bit wild (effectively the entire content has changed), but I think that's okay since it reflects reality.
CC @jeremy-rifkin

Ensure first MIR pass marked as changed

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

Add oneapi 2022.1 release
enable execution of sycl programs by setting libpath. See https://github.com/compiler-explorer/compiler-explorer/issues/2246
Depends on compilers being installed with https://github.com/compiler-explorer/infra/pull/793

oneapi 2022.1 release

---

etc/scripts/find-node

See #3995, seems we can't install on lower node any more. Our README says 16 too

Set our minimum node to 16

---

static/panes/llvm-opt-pipeline.ts
static/panes/output.ts
static/panes/pp-view.ts
static/widgets/toggles.ts

This changes Toggles to only take on state for what it controls. Prevents toggles.get() from clobbering other state with stale values later on. There is a chance this might break something but as far as I can tell no component relies on Toggles taking on (and later returning) the full state its given.

Toggles state

---

lib/compilers/_all.js
lib/compilers/clang.js

Enable running sycl and openmp offload programs with icx compiler by enabling the opencl that comes with the compiler. Thanks to @partouf for finding the env variable that was missing.
I extended clang because icx is clang based and I also want to enable the device support that is partially implemented for clang.

use openCL from icx install

---

static/modes/cppp-mode.ts

Quick fix for #4012 until https://github.com/microsoft/monaco-editor/pull/3286 is merged and deployed
Fixes #4012

Add AVX 512 types to C++ syntax highlighting

---

lib/base-compiler.ts
lib/demangler/llvm.ts
lib/exec.js
lib/parsers/llvm-pass-dump-parser.ts
static/panes/llvm-opt-pipeline.ts
test/exec-tests.js
types/compilation/compilation.interfaces.ts
types/compilation/llvm-opt-pipeline-output.interfaces.ts

Updated the llvm opt pipeline and exec.js code to provide better diagnostics for compilations that timeout and other internal errors.
Closes #4007

LLVM opt pipeline improvements with slow execution

---

lib/compilers/spirv.js
lib/parsers/asm-parser-spirv.js
lib/parsers/asm-parser-spirv.ts

Only look at operator OpLine
Also filter OpLine and 'OpExtInst %void %<> Debug*'

add parser for spirv debug information

---

lib/base-compiler.ts
lib/compilers/beebasm.ts
lib/compilers/dotnet.ts
lib/compilers/pony.ts
lib/compilers/rga.ts
lib/compilers/rust.ts
lib/exec.ts
test/base-compiler-tests.js
test/exec-tests.js
types/compilation/compilation.interfaces.ts
types/execution/execution.interfaces.ts

Changed `exec.js` to typescript, adding types to at least the exported functions, and then the fallout of those choices.
Things to note:
* base-compiler then required some conversion steps to convert from `UnprocessedExecResult` to `BasicExecutionResult` (`stdout` and `stderr` as arrays) and then to a `CompilationResult`
* I did this with some functions that do `{...input, morestuff}`, which copies the object - probably not the best idea, but not sure if there's a good alternative that is both readable and as fast as before. _Any ideas?_
* Also the names of the functions are not great. `Any ideas?`
* Also noticed either a bug in the code or the test, but I changed the test. I'm not sure how that ever actually worked, because a compiler run always results in `stdout` and `stderr` to be …

tsify exec.js

---

.github/workflows/test-win.yml

A better alternative would be to override prettier `endOfLine` setting to `auto` in this case, but that's more convoluted to implement.
This does not change any behaviour for Windows users and should fix the false positives in PR tests

Ask git to use LF line endings in windows CI

---

lib/instructionsets.ts
test/instructionsets-tests.js

TLDR: Problem fixed, don't name your properties `default`
I'm getting this error locally and I'm clueless on what's going on:
```
$ npm run test
> compiler-explorer@0.0.3 test
> mocha -b
/opt/compiler-explorer/cemain/lib/instructionsets.ts:26
default;
^
SyntaxError: Invalid or unexpected token
at Object.m._compile (/opt/compiler-explorer/cemain/node_modules/ts-node/src/index.ts:1618:23)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

tsify instructionsets

---

lib/utils.ts

No need to recreate the object for every compilation, even if the RE gets compiled only once

Move RE creation outside function scope

---

etc/config/openclc.amazon.properties
etc/config/openclc.defaults.properties
lib/compilers/_all.js
lib/compilers/clspv.js
lib/compilers/clspv.ts
lib/parsers/asm-parser-spirv.ts

This is a PR based on #4013.
It will also need to have clspv built by the nightly jobs.
It is not using the `spirv` workflow it is different:
- spirv: `cl -> bc -> spv -> spvasm`
- clspv: `cl -> spv -> spvasm`
Ref #3992

add compiler: skeleton for clspv

---

docs/API.md

Hi. I've been working on a neovim plugin for compiler explorer lately and it's finally in a state that I am somewhat satisfied with. Hope that it is fine if I add it here near the other editor plugins. At the moment it allows you to do compiles, formats and show tooltips asynchronously.

Add neovim plugin to rest api docs

---

etc/config/ada.amazon.properties
etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/d.amazon.properties
etc/config/fortran.amazon.properties
etc/config/go.amazon.properties

Add newly released GCC 12.2.0 for our existing cross-compilers.
Along with the update, more languages have been enabled where possible.
Tried languages C++, D, Ada, Objective-C, Objective-C++, Fortran and Go.
Updated targets: arm arm64 avr mips mips64 msp430 powerpc powerpc64 powerpc64le
s390x riscv32 riscv64 mipsel mips64el
closes #3973

Add several GCC 12.2.0 cross compilers

---

etc/config/c++.amazon.properties
lib/base-compiler.ts
lib/options-handler.js
lib/tooling/_all.js
lib/tooling/base-tool.interface.ts
lib/tooling/base-tool.ts
lib/tooling/compiler-dropin-tool.js
lib/tooling/llvm-cov-tool.ts
lib/utils.ts
static/panes/tool.js
test/options-handler.js
types/compilation/compilation.interfaces.ts

Moves base-tool to ts, but this is a min effort one
Fixes an issue with tools.js pane.
onCompileResult did not reset the plainContentRoot for toolResults, if no languageId is defined for the current function

Adds llvm-cov tool

---

etc/config/hlsl.amazon.properties
etc/config/hlsl.defaults.properties

N.B I don't really know what I'm here, just copying vaguely what #3961 did, and what is in `etc/config/c.amazon.properties`. What is the `.defaults.properties` and what does it do? do I need to update it too?
cc @llvm-beanz What options should I be setting here? I could add `-triple dxil-pc-shadermodel6.3-library` but that would preclude writing non-library dxil modules wouldn't it?

Fix issue #4060 Add clang15/clang_trunk as HLSL compilers

---

etc/config/swift.amazon.properties

Adds Swift 5.7 RELEASE as a compiler option, removes the nightly compiler.
The associated infra PR is compiler-explorer/infra#811.

Add Swift 5.7

---

lib/handlers/compile.js

The website is unusable when this error occurs, but the startup just continues, which is a pain to debug.

"compilertype not found" should be fatal

---

lib/base-compiler.ts
lib/compiler-finder.js
static/compiler-service.ts
static/options.interfaces.ts
static/panes/diff.ts
types/compilation/compilation.interfaces.ts
types/compiler.interfaces.ts

As discussed here https://github.com/compiler-explorer/compiler-explorer/pull/4044/files#diff-ad70709cafce13a26acf40e47dced8fe40d1540f4ca54a282aa6afde39675176R140 - some types were missing.
Are now more complete-ish

add compilationinfo and related types

---

etc/config/c++.amazon.properties
lib/compiler-finder.js
static/panes/compiler.js
views/templates/panes/compiler.pug

This solves the issue discussed on Discord about us not having a way to properly show compiler licenses, by adding a button in the bottom bar of the compiler pane that shows an alert with:
- An optional preamble (In case some clarification is needed in a per-case basis)
- The license name and a link to it
Feel free to suggest better wording for the template text

Add license info button to compilers

---

static/settings.ts
static/themes.ts

With this new setting, we query the browser every time the settings change and set default/dark based on the `prefers-color-scheme: dark` response.
Note that this is different from the initial guessing we do to set the site to default/dark based on the same query, as that one does not get updated after being initialized.
My only question now is if this should be the new default, which I dont think is the case, but it's better to ask
Closes #4057

Add System theme setting

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties

Add Kalray's freshly tagged 4.8 and 4.9 releases.
Also cleanup the install path for these compilers + their versionning.
Kalray is using its own version for its toolchain (4.x.y) and is not
synchronized with the underlying GCC.
fixes https://github.com/compiler-explorer/compiler-explorer/issues/4066

Add Kalray KVX compilers 4.8 and 4.9 and cleanup

---

lib/base-compiler.ts
lib/compilers/zig.ts
lib/compilers/zigcc.ts
lib/compilers/zigcxx.ts

This should fix versions from 0.6.0 to 0.9.0 not being able to emit assembly but we only checking for version 0.6.0. As far as I can tell, 0.9.0 fixed the issue (https://github.com/ziglang/zig/issues/8153), so that one now does not force binary mode

Move zig compiler files to TS and fix zigc{xx} semver comparisons

---

lib/compilers/z88dk.ts
static/panes/compiler.js
views/popups/miracleemu.pug
views/popups/popups.pug

Depends on https://github.com/mattgodbolt/Miracle/pull/13
Debugger half overlaps the screen when activated, but we can probably add some fixes to that at a later time.
Code tested: https://github.com/z88dk/z88dk/blob/master/examples/sms/test.c with just `+sms` as compiler argument + binary mode

add miracle emulator for z88dk sms files

---

etc/config/c++.amazon.properties
static/panes/compiler.js

This is a bit WIP, but I want to merge soon as this file is a rather busy.
For this file, some of the things left to do are:

Add some initial licenses to C++ compilers

---

lib/parsers/asm-parser-ewavr.js

This PR fixes a bug in the IAR EW assembly parser that broke the filtering if comments are included in the source code.
Previously, it incorrectly detected comments as file names.
I.e...
```cpp
// Type your code here, or load an example.
int square(int num) {
return num * num;
}
```
...led to an empty assembly.
The PR extends the file name recognition regex in a way that it doesn't match source code comments.

Fix comment being recognized as a filename in IAR EW parser

---

static/widgets/site-templates-widget.ts

#4072 added the `system` theme which can break resolving the appropriate screenshots when using the `system` theme

Add support for system theme for site templates

---

.github/labeler.yml
docs/AddingALanguage.md
etc/config/racket.amazon.properties
etc/config/racket.defaults.properties
examples/racket/default.rkt
lib/compilers/_all.js
lib/compilers/racket.ts
lib/languages.ts
types/languages.interfaces.ts
views/resources/logos/racket.svg
webpack.config.esm.js

This adds basic support for the [Racket](https://racket-lang.org/) language and compiler. Most compiler pane options are disabled for now. The user's module is compiled with `raco make` and then decompiled with `raco decompile` (with `disassemble` package installed) to get the assembly for the module.
Racket toolchain `infra` PR: https://github.com/compiler-explorer/infra/pull/832

Add basic Racket support

---

etc/config/c++.amazon.properties
etc/config/c.amazon.properties
etc/config/fortran.amazon.properties

Add 3 configs for sh targets:
- old 4.9.4 unknown-elf (c/c++)
- 9.5 linux (c/c++/fortran)
- 12.2.0 linux (c/c++/fortran)
Old compiler were specificaly requested for Dreamcast hacking.
Not enabling D as it's not functional.
fixes #94

Add sh config

---

.eslintrc.yml
lib/base-compiler.ts
lib/llvm-opt-transformer.ts
static/.eslint-ce-static.yml
webpack.config.esm.js

@partouf found in https://github.com/compiler-explorer/compiler-explorer/pull/4131#discussion_r990840471 that a console statement passed the eslint checks.
Turns out, the check was not there anymore.

Add no-console to eslint checks

---

static/compiler-service.ts
static/event-map.ts
types/compilation/compilation.interfaces.ts

@MarkusJx pointed out that there were `unknown` fields for which we do have typing info

Improve event-map types

---

CONTRIBUTORS.md
docs/API.md

Fixed issue #3075
**Description:**
Improved clientstate API documentation describing need for unicode conversion

docs(api): improved clientstate API documentation describing need for unicode conversion

---

lib/base-compiler.ts
lib/compilers/rust.ts

This _might_ be the fix for the linked issue, as I wrote in the original issue:
The issue is that we expected rustc to always output the llvm-ir in a `output.ll`, as we normally call it with `-o output.s --emit asm --emit llmv-ir`, which makes it warn us with:
```
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type
warning: 1 warning emitted
```
and then rustc goes ahead and creates both the `output.s` and `output.ll` files.
In the binary case, we only ask it to emit llvm-ir, so it interprets that the passed `-o output.s` is for the llvm-ir. In hindsight it makes some sense, but this flew under our radar until now
Now the issue is that, afaik (Im no expert in llvm), we now get the expected ir:
but most of the file …

Fix --emit llvm-ir when asked to emit binary mode
