- examples/go/max_array.go
- static/index.html
The example Go code was not valid.
> Fix example Go code

- static/compiler.js
Signed-off-by: Ola Jeppsson <ola@adapteva.com>
> ui: Fix mime type for C code

- examples/rust/max_array_opt.rs
- examples/rust/sum_over_array_opt.rs
Also remove trailing whitespaces.
> Fix Rust examples for current nightly

- static/index.html
Just copied from the C starting example.
> Add default D code template for first time page loading

- app.js
Use already defined compareOn function.
I'm working on gcc-explorer, expect more pull request from me :-)
> Remove code duplication.

- app.js
- lib/compile.js
This allows for custom postProcess tools after builds have completed.
> Support config of postProcess tool

- d/Makefile
This fixes the build when DMD is present or the DMD env var is set.
> Fix up D build some more

- lib/compile.js
- package.json
I used this to fix include paths containing spaces on windows.
> Better handling of command line arguments when invoking compiler.

- etc/config/d.amazon.properties
LDC 1.1.0 was just released!
Thanks @mattgodbolt  :-)
> Add LDC 1.1.0

- static/index.html
- static/main.js
As per the email that I sent you with the concept @mattgodbolt I open this PR (I don't know if you accept PRs by the way. Sorry if not!)
You mentioned somehting about merging all compilers into a switcheable one, but for the moment I think this may work?
Note that the beta link is being used (as this is going to the beta branch) and that they don't support https
Should I use non beta links? Or submit this to a different branch?
This closes #259
> Links to other supported languages on the top right menu

- static/compiler.js
We now check if we actually have some assembly to link. Fixes #324
I suppose this totally fixes the issue, but who knows...
> Fix for #324

- static/sharing.js
- static/urlshorten-google.js
Explaining that it's probably because of length limits. 
This is a temporary solution while Matt creates a local shortener.
As always, any feedback is welcomed. I used an alert because is the only thing that we currently have. 
@mattgodbolt maybe should I create a templante for something like https://www.w3schools.com/bootstrap/bootstrap_alerts.asp that autofades after X seconds and stacks on the bottom of the screen?
> An alert is issued when the URL shortener fails

- static/explorer.css
- static/fontscale.js
- views/font-size.pug
Probably not mergeable on this state, but feedback is appreciated, as I did this in 30 mins and I'm not sure the quality is any better than "Meh".
I made this as a way to warm up my knowledge of the UI in preparation for the clang format thingy 
I would like to know what would be needed to be added  for this feature to be acceptable.
Closes #340
> First implementation of Font Size By DropDown

- README.md
the post endpoint was wrong. This one is confirmed to work.
> Update post api documentation

- etc/config/d.amazon.properties
See https://github.com/mattgodbolt/compiler-explorer-image/pull/17
> Add LDC 1.2.0

- static/opt-view.js
As discussed with @jaredwy , I open a pr instead of pushing to master so he can check it out in case I fucked up somewhere
> Each optviewer is now independant from the others

- static/ispc-mode.js
- views/example.ispc
This should be the last tiny annoying patch, I promise.
ISPC only gets updated once or twice a year so it should be low-maintenance from now on.
> Final round of tweaks for ISPC integration

- etc/config/d.amazon.properties
See also https://github.com/mattgodbolt/compiler-explorer-image/pull/28
> Add LDC 1.3.0

- CODE_OF_CONDUCT.md
Contributors: please read, and let me know if you have any questions.
> Added a Code of Conduct

- etc/config/d.amazon.properties
@RabsRincon 
Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/31
> D: add the mir algorithm and glas libraries

- etc/config/d.amazon.properties
Image changes here: https://github.com/mattgodbolt/compiler-explorer-image/pull/41
> D: Add LDC 1.5.0 and make it the default.

- lib/base-compiler.js
- static/compiler.js
- static/components.js
- static/explorer.css
- static/gccdump-view.js
- static/hub.js
- views/templates.pug
First prototype for getting dump from GCC.
There are still some known problems with this code and I'm new to js :) Please don't panic.
This PR is mainly so that you can see if this is going in the correct direction or not.
I'll squash and clean everything before it can be merged :)
See #561 .
> Get dump files from GCC (both tree and rtl)

- static/fpc-mode.js
> Fpc syntaxhighlight bugfix

- etc/config/c++.amazon.properties
Depends on this pull request for the live image: https://github.com/mattgodbolt/compiler-explorer-image/pull/49
> Added cppcoro library

- lib/compilers/pascal.js
- lib/pascal-support.js
- lib/symbol-store.js
- test/pascal-tests.js
- test/symbol-store-tests.js
> Minor refactoring pascal code

- etc/config/d.amazon.properties
Image update: https://github.com/mattgodbolt/compiler-explorer-image/pull/52
> Add LDC 1.6.0 and make that the D default

- lib/utils.js
- static/ansi-to-html.js
- static/output.js
`ansi-to-html` is not found in Bower, so I added it directly to `static`.
There are other packages which seem to do similar things, but I am not sure if any of them support streaming over multiple lines.
> Added support for colorized output

- lib/asm.js
- test/cases/bug-725_rust.asm
- test/cases/bug-725_rust.asm.directives.labels
> Data starts with \s*, not just anywhere else

- lib/handlers/compile.js
compiler.exe is not defined in remotes
> fix remote

- CONTRIBUTING.md
- README.md
- Roadmap.md
> Fixed minor typos in the README

- lib/base-compiler.js
- lib/compilers/argument-parsers.js
- test/compilers/argument-parsers-tests.js
Without the fix this testcase resulted in the same behaviour, so I assume this is correct. I have no GDC to test.
> testcase and fix for #738

- package.json
Tried this change locally and I didn't notice any issues
> Upgrade to newer version of Express

- etc/config/assembly.amazon.properties
- etc/config/assembly.defaults.properties
- examples/assembly/default.asm
- lib/asm-raw.js
- lib/compilers/assembly.js
- lib/exec.js
- lib/languages.js
> [WIP] Basic setup for nasm and gnu as

- lib/compilers/assembly.js
supportsBinary causes filter button issues, but it doesn't have to be on for things to work
> Asm changes

- etc/config/c++.amazon.properties
I'm putting in a PR to the sister repo as well: https://github.com/mattgodbolt/compiler-explorer-image/pull/64
> Add Brigand metaprogramming library

- etc/config/c++.win32.properties
- etc/config/ispc.defaults.properties
- lib/base-compiler.js
- lib/compilers/WSL-CL.js
- lib/compilers/Wine-CL.js
- lib/compilers/assembly.js
- lib/compilers/default.js
- lib/compilers/fake-for-test.js
- lib/compilers/gcc.js
- lib/compilers/golang.js
- lib/compilers/haskell.js
- lib/compilers/ispc.js
- lib/compilers/ldc.js
- lib/compilers/pascal.js
- lib/compilers/rust.js
- lib/compilers/swift.js
- lib/handlers/compile.js
- test/pascal-tests.js
- test/win-path-tests.js
Skips initialise() in the constructor, but calls it from handlers/compiler.js
> Es6unittest

- etc/jshintrc.client
- etc/jshintrc.server
- lib/asm.js
- lib/compilers/pascal.js
- lib/handlers/asm-docs-api.js
- lib/pascal-support.js
- static/ast-view.js
- static/compiler.js
- static/conformance-view.js
- static/editor.js
- static/fontscale.js
- static/opt-view.js
so that everyone uses === it also updates === for any static files that didn't use it.
> adding eqeqeq into our jshint files,

- lib/base-compiler.js
- lib/compilers/assembly.js
> Assembler bugfix

- etc/config/c++.amazon.properties
Companion PR to https://github.com/mattgodbolt/compiler-explorer-image/pull/69.
> Installed xtensor dependencies

- etc/config/d.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/72
> Add LDC 1.8.0 and set it as default

- lib/compilers/ldc.js
This is an alternative to #868 . Don't know which one you like best :-)
> Enable CFG (Graph Output) for LDC.

- static/urlshorten-google.js
> [Trivial] Fix whitespace

- .eslintrc
- app.js
- lib/base-compiler.js
- lib/exec.js
- lib/handlers/compile.js
- lib/pascal-support.js
- static/.eslintrc
- static/ast-view.js
- static/cfg-view.js
- static/compiler.js
- static/diff.js
- static/editor.js
- static/gccdump-view.js
- static/opt-view.js
- static/settings.js
This is mostly a rearrangement of the code, so it shoud have not broken anything (I've tested as much as I can, so hopefuly there are no errors)
This also fixes some code duplicates in some of the views. Note that exceeding 120 chars per line / 50 statements will now fail the tests
This PR is here so you can take a look in case I've missed something.
If nothing goes wrong, this can be merged soon
> Enforce max-statement/line & further unify UI

- static/compiler.js
- views/templates.pug
Requesting a PR from Jared as this touches `static` and I don't want to cause any upset :)
> Compact compiler buttons

- etc/config/d.amazon.properties
Accompanying image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/74
> Add LDC 1.9.0

- etc/config/c++.amazon.properties
Hopefully this is correct, do let me know if I've made a mistake, or you feel like something should be renamed.
> Add RISC-V support

- static/compiler.js
- static/explorer.css
- static/themes/dark-theme.css
- static/themes/default-theme.css
It now features a nice hide/show system.
This is an idea I have had to aliviate the problem of "too many versions" installed. It's a PR because I'm not happy at all with how it looks and as its style can be vastly improved, I tought a PR would be the best way to find some help with it :)
> Change libs dropdown style

- etc/config/c++.amazon.properties
> Add a link to a blog post explaining what auto-NSDMI are

- lib/demangler.js
- test/demangler-tests.js
Not sure if this breaks anything. But might fix #1045
> Fix incorrect regular expression for jmp calls

- etc/config/c.amazon.properties
> Add clang 7.0.0 for C too

- lib/compilers/zig.js
> Stop Zig compiler creating C header files

- etc/config/c++.amazon.properties
Pass --gcc-toolchain argument like clang trunk does.
> lifetime: Use libstdc++

- etc/config/c++.amazon.properties
> lifetime: use gcc 8.2

- etc/config/zig.amazon.properties
Corresponding image commit is here: https://github.com/mattgodbolt/compiler-explorer-image/pull/115.
> Add zig 0.3.0 compiler

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
> Enabled ctbignum in library configuration and updated contributors.md

- lib/clientstate-normalizer.js
- lib/clientstate.js
- test/state/andthekitchensink.json.normalized
- test/state/conformanceview.json
- test/state/conformanceview.json.normalized
- test/state/twocompilers.json.normalized
- test/statenormalisation-tests.js
I forgot about conformance view.
Also includes a bugfix for when using multiple editors with opt/ast/etc views.
> Support conformanceview for shortlink and resetlayout

- examples/clean/qsort.icl
> bugfix clean example file

- lib/clientstate-normalizer.js
- lib/clientstate.js
- lib/compilers/clean.js
Fixes some lint issues, and adds extra error message detection for clean
> Clean fixes

- etc/config/c.amazon.properties
> Add icc 19 to C too

- etc/config/c++.amazon.properties
Already submitted a PR against *-images*. check passes. Fingers crossed!
Thanks!
> Add CNL library to C++

- etc/config/fortran.amazon.properties
I thought I'll try to add ifort as well. Of course I couldn't test it. I'm also not sure if #896 would be a problem here as well.
> Trying to add ifort to the list of Fortran compilers.

- etc/config/compiler-explorer.amazon.properties
- lib/options-handler.js
- package.json
- static/main.js
- yarn.lock
See #1109, and the discussion therein. Will need a separate PR to move the cookie consent itself to using cookies (ironically).
> Move privacy configuration to a cookie with a configurable domain

- etc/config/c++.amazon.properties
> Add godbolt.ms as a remote compiler explorer!

- static/compiler-service.js
Adds more detailed error to help identify issue #1130
> check for 504 status for gateway errors

- static/panes/compiler.js
> Autoselect Bin if needed when Exec is selected

- lib/cfg.js
> Fix graphviewer issue with llvm compilers

- etc/config/haskell.amazon.properties
Not sure how to make sure that the GHC 8.6.2 is actually installed.
> Add GHC 8.6.2

- etc/config/d.amazon.properties
Image update: https://github.com/mattgodbolt/compiler-explorer-image/pull/135
> Add LDC 1.12.0 and set it as new default

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- lib/compilers/clang.js
Fixes #690
Not sure if this can cause issues, probably not, but testing required.
> Set working directory for Clang

- lib/base-compiler.js
- lib/compilers/dmd.js
- lib/compilers/pascal.js
- lib/compilers/zig.js
- static/panes/compiler.js
As part of the journey to improve execution support, this is my attempt at separating the steps.
I think I succeeded, but it might be a bit of a mess, still. So comments are welcome.
> Separation compilation and execution

- static/explorer.css
- static/main.js
- static/panes/editor.js
- static/themes/dark-theme.css
- static/themes/default-theme.css
- views/index.pug
- views/templates.pug
I added a few style changes to the navbar, and content change to make it clearer how to add a new editor. 
I'm working on adding the ability in the "Add new" dropdown to also add here, as that's my goto when I don't know what to click.
I'm not familiar with `*.pug` style templates, and I don't know to make a new source code appear by clicking a button inside the source code. 
Closes #1162
> New code button

- etc/config/go.amazon.properties
> Add go cross compilers and powerpc64{,le} gccgo

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
This should work once https://github.com/mattgodbolt/compiler-explorer-image/pull/129 is accepted and compilers are built. I hope I got all the paths right.
> Extending properties for c, c++, and fortran to list newer ARM cross-compilers

- static/panes/compiler.js
- views/templates.pug
Fixes #1221 
Based on the changes by @RabsRincon in https://github.com/mattgodbolt/compiler-explorer/commit/61ea4918e005fdb13880c1c147002363bcc34707
> fix version popup copypastability

- etc/config/d.amazon.properties
image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/154
> Add LDC 1.13.0

- etc/config/d.amazon.properties
Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/150
> Add LDC latest CI

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
Add googletest to the available libraries
> Add googletest http://www.github.com/google/googletest

- static/panes/editor.js
It should fix #1241, but I have not had enough time to test it (That's why it's open as a PR)
It's a bit rough around the edges, but I think it should be mergable (Maybe?)
> Make editor formatting undoable

- lib/compilers/argument-parsers.js
> Fix masm flag detection for ARM compilers

- etc/config/ocaml.amazon.properties
- etc/config/ocaml.defaults.properties
- examples/ocaml/default.ml
- examples/ocaml/max_array.ml
- examples/ocaml/sum.ml
- lib/compilers/ocaml.js
- lib/languages.js
- static/modes/ocaml-mode.js
- static/panes/editor.js
A very basic OCaml support. Editor mode may (and shall) be improved, a demangler will be added later.
> OCaml language support

- lib/base-compiler.js
- lib/compilers/wine-vc.js
- lib/exec.js
> Customcwdalways

- etc/config/d.amazon.properties
Image update: https://github.com/mattgodbolt/compiler-explorer-image/pull/168
> Add LDC 1.14.0 and make it the new default.

- etc/config/c.amazon.properties
> Add gcc 8.3.0 for C too

- lib/storage/storage.js
- package.json
- test/storage/storage-tests.js
- yarn.lock
Minimal implementation of what I could come up with on the train to avoid profanities on the subhashes
Closes #1297
> Implement profanity check on subhashes

- etc/config/swift.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/180
> Add Swift 5

- etc/config/c.amazon.properties
>  Add Clang 8 for C too & make GCC toolchain selection consistent

- etc/config/d.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/190
> Add LDC 1.15.0

- etc/config/rust.amazon.properties
> Add Rust 1.34.0

- etc/config/zig.amazon.properties
https://github.com/mattgodbolt/compiler-explorer-image/pull/191
> Zig 0.4.0 released

- static/colour.js
- static/colours.css
- static/explorer.css
- static/panes/compiler.js
- static/panes/editor.js
- static/panes/ir-view.js
- static/panes/output.js
- static/themes/dark-theme.css
- static/themes/default-theme.css
This PR tries to improve the interlinking between panes which are aware of the origin of its source (In other words, they use highlighting back to the original source). It should all just work, but I'm concerned about one bit of code, so that's why this is a PR.
Note that this also changes the styling for linked lines of codes (They now resemble @steveire's which I really liked). I'd like to know if this one looks better than the old one for the rest.
Fixes #1313
> Improve pane interlinking

- lib/csp.js
- test/csp-tests.js
> add compiler-explorer.com to csp thingymabob

- etc/config/java.amazon.properties
Depends on https://github.com/mattgodbolt/compiler-explorer/pull/1396 and https://github.com/mattgodbolt/compiler-explorer-image/pull/214
> Add java 11 and 12 to amazon properties

- etc/config/pascal.defaults.properties
- lib/compilers/pascal.js
- lib/demangler-pascal.js
- test/pascal-tests.js
> rename pascal-support to demangler-pascal

- etc/config/rust.amazon.properties
Do not merge before https://github.com/mattgodbolt/compiler-explorer-tools/pull/1
> Update to stable rust: 1.35.0

- etc/config/ocaml.amazon.properties
Should be merged after https://github.com/mattgodbolt/compiler-explorer-image/pull/222 (if there are no issues with the compilers)
> OCaml: Add OCaml 4.08.0

- etc/config/rust.amazon.properties
See also https://github.com/mattgodbolt/compiler-explorer-tools/pull/2
> Update to stable rust: 1.36.0

- etc/config/d.amazon.properties
See also https://github.com/mattgodbolt/compiler-explorer-image/pull/231
> Add LDC 1.16.0 and make it default

- etc/config/ispc.amazon.properties
mattgodbolt/compiler-explorer-image#229
> Add ispc trunk

- etc/config/cuda.amazon.properties
I haven't done any additional testing on this; let me know if there's anything I should do.
See also https://github.com/mattgodbolt/compiler-explorer-image/pull/232
> Add CUDA 10.0, 10.1, and 10.1 Update 1

- lib/base-compiler.js
- lib/cache/on-disk.js
- lib/handlers/compile.js
- lib/handlers/health-check.js
- package-lock.json
- package.json
fs-extra already does what we were asking the package to do
I've opened the PR so @partouf can check it in case that this would cause some problems when merging #1503 (I have refrained from moving more stuff to async/await until that PR is closed so the merge goes smoother :) )
> Completely remove need for denodeify

- static/loadSave.js
Fixes #1514
The loadSave gets constructed really early, too early
> Load modal on demand instead of on startup

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/241
> Add FRC 2020 and Raspbian Buster compilers

- etc/config/pascal.defaults.properties
- lib/compilers/pascal.js
- lib/demangler-pascal.js
- test/pascal-tests.js
> change fpc demangler instantiation, fix #1528

- etc/config/c.amazon.properties
> Add gcc 9.2 for C too

- lib/compiler-arguments.js
- lib/compilers/argument-parsers.js
- lib/compilers/rust.js
- lib/handlers/api.js
- lib/handlers/compile.js
- test/handlers/api-tests.js
* Fixed some Rust argument parser issues and added --C help parsing.
* Fixed some ISPC argument parsing issues
* Added new API for optimizationArguments
* Added get for the argument api's
Unable to test Rust locally, will have to do it on a beta unless someone else can test it.
Not sure yet how to maybe show optimization arguments in the client UI.
> Argument parser fixes and new API

- Makefile
Copy paste from make dev, but with added --debug
> Make debug

- lib/handlers/health-check.js
> should this work?

- static/main.js
I don't really understand where or how it went wrong, it might have something to do with the PR's involved with switching to a new webpack thing, but there were a lot of changes there, so who knows really.
> [WIP] Analytics maybe fix

- .travis.yml
> Distribute js/css to s3

- app.js
- views/_layout.pug
- views/embed.pug
- views/index.pug
- views/meta.pug
Additionally move the javascript code blocks to
the end of the html body, instead of the header.
This is generally good practice, but it also fixes
an issue with the cookie consent overlay due to
a html element not existing on the page at the time
of script execution.
Fixes remaining issue in #1569
> Use pug template inheritance

- etc/config/d.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/256
> Add LDC 1.17.0 and make it the default D compiler

- test/statenormalisation-tests.js
> extra clientstate tests

- etc/config/swift.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/259
> Add Swift 5.1

- etc/config/c++.amazon.properties
> Add support for benri

- etc/config/c.amazon.properties
Fixes #1533 
Required image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/262
> Support for shared lib cs50 for C

- etc/config/c++.amazon.properties
> Add gcc-arm-none-eabi 8.3.1

- lib/compilers/zig.js
> Fix zig output filename

- etc/config/c++.amazon.properties
- lib/base-compiler.js
- lib/tooling/compiler-dropin-tool.js
- test/tool-tests.js
> Iwyuincludefixes

- etc/config/c++.amazon.properties
Left as a PR for @ThePhd to cast an eye over the name, text and link. Don't merge yet please :)
> Add @ThePhD's std::embed gcc. Wording and link subject to change

- etc/config/c++.amazon.properties
This PR should be all that's necessary for the std::embed branch in Clang!
> Update properties to include std::embed for Clang

- etc/config/d.amazon.properties
> Add LDC 1.18.0 and make it default D compiler

- etc/config/rust.amazon.properties
See also https://github.com/mattgodbolt/compiler-explorer-tools/pull/5
>  Update to stable rust: 1.39.0

- etc/config/cuda.amazon.properties
See also https://github.com/mattgodbolt/compiler-explorer-image/pull/286
> Add CUDA 10.1 Update 2 and make it the default

- etc/config/c++.amazon.properties
- lib/tooling/clang-format-tool.js
> Add clang-format tool

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Compiler is built, installed, and ready to go on amazon already.
@dkm any concerns with the display names I chose for the compiler?
> Add Kalray MPPA K1 GCC Compiler

- etc/config/rust.amazon.properties
See also: 
* https://github.com/mattgodbolt/compiler-explorer-tools/pull/6
* https://github.com/mattgodbolt/compiler-explorer-image/pull/290
> Rust: Update to 1.40.0

- lib/base-compiler.js
- lib/llvm-ir.js
> conform llvmir result to asmparser result

- etc/config/c++.amazon.properties
(I'm the author/maintainer of P1144 and of the trivially-relocatable branch deployed on CE.)
> Update the URL displayed for the "P1144" (trivially-relocatable) branch

- static/history-widget.js
- static/history.js
- static/loadSave.js
- static/main.js
- views/index.pug
- views/popups.pug
Way to keep an automated record of your coding history in localstorage.
What I want to do;
> History (localstorage)

- lib/languages.js
- static/modes/nim-mode.js
Hi! I'm from the Nim community. Big shout out to @DaemonSnake and @RabsRincon for adding Nim support.
I tried and failed to get Godbolt support working for Nim a while ago. But, I did get syntax highlight support working, so at least I can contribute that :-)
> Added Monaco editor syntax highlight support for Nim.

- etc/config/c++.amazon.properties
Relates to this [PR](https://github.com/mattgodbolt/compiler-explorer-image/pull/302)
> Updated gsl library to version v2.1.0

- static/modes/nim-mode.js
> Fix some edge cases around bracket tokenization in the Nim syntax definition for monaco. Closes #1781

- etc/config/d.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/303
> Add LDC 1.19.0 and bump the default version

- etc/config/swift.amazon.properties
Image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/304
> Add Swift nightly builds

- etc/config/c++.amazon.properties
> Add etl (embedded template library)

- etc/config/c++.amazon.properties
> Remove 'trunk' from etl paths

- etc/config/rust.amazon.properties
See also:
* https://github.com/mattgodbolt/compiler-explorer-tools/pull/7
* https://github.com/mattgodbolt/compiler-explorer-image/pull/309
> Rust: update to 1.41.0

- etc/config/d.amazon.properties
Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/312
> Add LDC 1.20.0 and make it the default D compiler

- static/codelens-handler.js
- static/panes/compiler.js
* Fixes console errors since last Monaco upgrade.
* Also fixes issue with multiple compilers and now shows different lenses per compiler/model.
> global codelenshandler and fixes to lensmodel

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Also, some cleanup of Arm compiler names, and added Arm clang to the C compilers list.
> Arm Clang 10

- etc/config/swift.amazon.properties
Image pr: https://github.com/mattgodbolt/compiler-explorer-image/pull/327
> Add Swift 5.2

- examples/rust/Max_array.rs
- examples/rust/Max_array_(Optimized).rs
- examples/rust/Sum_over_array.rs
- examples/rust/Sum_over_array_(Optimized).rs
This Pull Request
- formats the Rust examples idiomatically
- uses idiomatic code
- uses only safe code without compromising on performance
- makes them compile on stable
> Improve the Rust examples

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
It's header only so there wasn't really much to do. I just used the entries for nlohmann::json as a template since the integrations for the two libraries are very similar.  
I also added myself to CONTRIBUTING.md on the advice of the helpful PR template message :)
Related: mattgodbolt/compiler-explorer-image/pull/329
> Adding toml++

- lib/base-compiler.js
- lib/toolchain-utils.js
- lib/tooling/compiler-dropin-tool.js
Fixes #1780 
Reused code from compiler-dropin-tool to find out the toolchain path
> Add toolchain librarypaths to -Wl,-rpath

- etc/config/c++.amazon.properties
Requires [this](https://github.com/mattgodbolt/compiler-explorer-image/pull/337) PR to merged as well.
> Update GSL library to version 3.0.1

- lib/compilers/java.js
- test/java-tests.js
> fixed JavaCompiler

- etc/config/compiler-explorer.amazon.properties
- lib/base-compiler.js
- test/options-handler.js
> Dont reset LD_LIBRARY_PATH by default (only for prod)

- etc/config/rust.amazon.properties
See also: 
- https://github.com/compiler-explorer/compiler-explorer-tools/pull/8
- https://github.com/mattgodbolt/compiler-explorer-image/pull/341
> Bump rust to 1.43.0

- etc/config/ada.amazon.properties
- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/cuda.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/llvm.amazon.properties
> Use trunk binutils for demangling and objdump of trunk gcc and clang compilers

- etc/config/c.amazon.properties
> Make gcc 10.1 the default for C too

- etc/config/execution.amazon.properties
- etc/config/execution.defaults.properties
- etc/nsjail/sandbox.cfg
- lib/exec.js
See #1440
Created a new PR because its on a branch on this repo (so I can try it out on staging)
> Add sandbox support for nsjail

- etc/config/ada.amazon.properties
- examples/ada/Square_Executable.adb
- examples/ada/default.adb
- lib/base-compiler.js
- lib/compilers/ada.js
> enables binary+execution for ADA

- etc/config/c.amazon.properties
- lib/compilers/sdcc.js
no -g support, that was the main thing that the extra file for is
> SDCC Support

- etc/config/c.amazon.properties
The config name was incorrect for the C compiler.
> Fix Kalray MPPA KVX compiler

- docs/AddingACompiler.md
- docs/AddingALibrary.md
- docs/WindowsLocal.properties
Update the Windows setup doc and add doc to setup msvc compiler on linux host
> Update the Windows setup doc and add doc to setup msvc compiler on linux host

- lib/tooling/PVS-Studio-tool.js
Make the PVS-Studio-tool use the proper compiler executable for getting *.i-files.
> George gribkov pvs studio tool

- lib/tooling/PVS-Studio-tool.js
Return from PVS-Studio-tool if compilation failed
> Return from PVS-Studio-tool if compilation failed

- static/explorer.css
My take on completely responsive modal dialogs (Load/Save, Settings, Sponsors, Policies).
I have only tested these values manually with the chrome dev-tools.
Hopefully I put all the right values at the right places.
I need to setup node to test this locally.
> make modal dialogs responsive

- lib/asmregex.js
Closes #2032
@cppchedy seems tro have found this some years ago https://github.com/compiler-explorer/compiler-explorer/issues/629#issuecomment-346849392
> Support numeric labels

- package-lock.json
- package.json
- static/main.js
fixes #2016
I hate it, but it works
🤷
> Prevent editor selection changes from overwriting shortlink url

- app.js
- lib/clientstate-normalizer.js
- lib/clientstate.js
- static/main.js
- static/panes/editor.js
- static/presentation.js
- test/state/andthekitchensink.json.normalized
- test/state/conformanceview.json.normalized
- test/state/executor.json.normalized
- test/state/twocompilers.json
- test/state/twocompilers.json.normalized
- views/index.pug
> [WIP] Mobile View-only mode

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Not sure if I'm doing this right — feedback welcome! How do I test this locally?
Depends on https://github.com/compiler-explorer/infra/pull/350.
> Add libuv to C & C++ libraries

- docs/API.md
> Add link to QCompilerExplorer frontend

- etc/config/d.amazon.properties
> Add LDC 1.22.0 and make it the default D compiler

- etc/config/c++.amazon.properties
I based myself on previous similar PR. Please let me know if it is missing anything. :)
> Add Fastor to C++ libraries

- etc/config/rust.amazon.properties
See https://github.com/compiler-explorer/infra/pull/366
> Add Rust 1.45.0

- views/meta.pug
I think... It works on my old android
> fix zooming on android

- views/index.pug
> Fix GitHub sponsor link

- lib/base-compiler.js
- lib/buildenvsetup/buildenvsetup-base.js
- lib/buildenvsetup/buildenvsetup-ceconan.js
- lib/buildenvsetup/buildenvsetup-cliconan.js
Should improve  #2081
uses execCompilerCached
> Improve startup speed instances

- static/panes/editor.js
> cppreference search action

- etc/config/rust.amazon.properties
See https://github.com/compiler-explorer/infra/pull/379
> Rust 1.45.2

- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/llvm.amazon.properties
See https://github.com/compiler-explorer/infra/pull/382
> Add LLVM 10.0.1

- etc/config/d.amazon.properties
> Add LDC 1.23.0 and make it the default D compiler

- etc/config/c++.amazon.properties
> Add pipes library

- static/panes/executor.js
> Add ANSI color code support on executor pane

- static/monaco-config.js
- static/panes/ast-view.js
- static/panes/compiler.js
- static/panes/diff.js
- static/panes/editor.js
- static/panes/gccdump-view.js
- static/panes/ir-view.js
- static/panes/opt-view.js
- static/panes/tool.js
Make the editors extend a base config instead of repeating them everywhere
> Add base monaco editor config

- static/components.js
- static/panes/compiler.js
- static/panes/executor.js
- views/templates.pug
Got the idea from Niall on Slack
I'm concerned about the button placement, maybe it breaks someone's muscle memory for the other panes?
> Add executor button to compiler that inherits it

- docs/API.md
- lib/compiler-finder.js
- lib/handlers/api.js
- test/handlers/api-tests.js
Fixes #2168
note: `'extensions', 'monaco'` added to keep unit tests working.
> Compilers API changes

- etc/config/go.amazon.properties
- lib/compilers/golang.js
> [WIP] Golang GO support binary + execution

- app.js
- lib/handlers/api.js
- lib/handlers/compile.js
- lib/handlers/noscript.js
- test/handlers/compile-tests.js
> Fix curl API

- etc/config/pascal.amazon.properties
- lib/compilers/pascal.js
> Add FPC 3.2.0

- lib/handlers/noscript.js
> Noscript default compiler

- static/components.js
- static/panes/compiler.js
- static/panes/executor.js
> Copy compiler arguments for 'Executor from this'

- etc/config/c++.amazon.properties
Will merge but not publish to prod until decent amount of binaries have been uploaded to conan
> Add libunifex trunk

- etc/config/swift.amazon.properties
Adds the Swift 5.3 compiler. Infra pr: https://github.com/compiler-explorer/infra/pull/399
> Add Swift 5.3

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/go.amazon.properties
- lib/tooling/strings-tool.js
> Add strings tool

- etc/config/c++.amazon.properties
Hope this works. (I did run `make check`)
Related to:
https://github.com/compiler-explorer/infra/pull/405
best regards,
Niek
> Added cppitertools

- etc/config/compiler-explorer.defaults.properties
- lib/base-compiler.js
Unless delay is explicitly turned on in the properties
> Sometimes folders weren't cleaned up after compilation/execution

- CONTRIBUTORS.md
- static/themes/dark-theme.scss
Fixes #2251 
The PR introduces the following changes:
- Added input:focus styling to the dark theme.
> Dark mode compiler arguments input text-color fix

- examples/nim/default.nim
Nim has Dead Code Elimination always enabled, so we have to either use the square proc, or export it, which is the same as the Zig example does, so I did the same.
There's also another Nim-related thing - by default Nim does not pass -g to the C compiler (debug info), for that you need to pass "--debugger:native" - would it make sense if I we that for Nim by default?
> Make Nim example actually work

- lib/compilers/nim.js
Sorry for a lot of PRs, but I don't want to mix different things in a single PR :)
This one just adds debug info to Nim so you can actually see what assembly code corresponds to what Nim code.
> Nim debuginfo

- etc/config/rust.amazon.properties
See: https://github.com/compiler-explorer/infra/pull/418
> Add Rust 1.47.0

- etc/config/ocaml.amazon.properties
Related PR: https://github.com/compiler-explorer/infra/pull/422
> Add OCaml 4.11.1 and update patch versions of older compiler versions

- etc/config/cuda.amazon.properties
Adds configurations for the 3.0.1 and `dev` branch of [NVTX ](https://github.com/NVIDIA/NVTX)
> Add NVTX CUDA library

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Change-Id: Ice34c191adf832d1e874f3ba8fbec7c81ef1f125
> Added Clang 10.0.1 and 11.0.0 for Arm

- .idea/runConfigurations/All_Mocha_Tests.xml
- lib/cache/base.js
- lib/cache/from-config.js
- lib/cache/in-memory.js
- lib/cache/multi.js
- lib/cache/null.js
- lib/cache/on-disk.js
- lib/cache/s3.js
- lib/compilation-env.js
- test/cache-tests.js
As discussed in Discord - would love a quick check over. I should probably test the counters themselves... thoughts appreciated.
> Add stats for caches

- etc/config/cuda.amazon.properties
> Compile CUDA with multiple versions of clang.

- etc/config/d.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/429
> Add LDC 1.24.0 and make it the default D compiler

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
> Add python as a library for C and C++

- etc/config/analysis.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/clean.amazon.properties
- etc/config/cppx.amazon.properties
- etc/config/cppx_blue.amazon.properties
- etc/config/cppx_gold.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/haskell.amazon.properties
- etc/config/ispc.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- etc/config/swift.amazon.properties
- etc/config/zig.amazon.properties
Update to OSACA v0.3.11 to fix issues mentioned in https://github.com/compiler-explorer/compiler-explorer/issues/2319
See also PR in compiler-explorer/infra (https://github.com/compiler-explorer/infra/pull/433)
> osaca version bump to fix https://github.com/compiler-explorer/compiler-explorer/issues/2319

- etc/config/analysis.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/clean.amazon.properties
- etc/config/cppx.amazon.properties
- etc/config/cppx_blue.amazon.properties
- etc/config/cppx_gold.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/haskell.amazon.properties
- etc/config/ispc.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- etc/config/swift.amazon.properties
- etc/config/zig.amazon.properties
improved OSACA performance and support for more ARM instructions
> Update OSACA to 0.3.12

- lib/compilers/zig.js
I somehow missed this in my previous PR switching zig to use the new CLI.  
Thanks for the heads up @LemonBoy
> Fixed zig trunk LLVM IR output

- etc/config/cuda.amazon.properties
Adds new versions of the CUDA Thrust/CUB libraries.
> Add Thrust/CUB 1.11.0.

- etc/config/analysis.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/clean.amazon.properties
- etc/config/cppx.amazon.properties
- etc/config/cppx_blue.amazon.properties
- etc/config/cppx_gold.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/haskell.amazon.properties
- etc/config/ispc.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- etc/config/swift.amazon.properties
- etc/config/zig.amazon.properties
Updated OSACA with new instructions and parser improvements for Rust compiler generated code (see https://github.com/RRZE-HPC/OSACA/issues/57).
Related to [PR in the `compiler-explorer/infra`](https://github.com/compiler-explorer/infra/pull/451) repository.
> updated OSACA version

- etc/config/c.defaults.properties
> Support libcodefilter for C

- etc/config/zig.amazon.properties
> zig: add 0.7.0 and 0.7.1 versions

- etc/config/rust.amazon.properties
See https://github.com/compiler-explorer/infra/pull/454
> Add Rust 1.49.0

- docs/AddingATool.md
- lib/options-handler.js
- lib/tooling/base-tool.js
- lib/tooling/clang-format-tool.js
- lib/tooling/clang-query-tool.js
- lib/tooling/clang-tidy-tool.js
- lib/tooling/compiler-dropin-tool.js
- lib/tooling/pvs-studio-tool.js
- static/panes/compiler.js
This args field is show in the UI inside the Arguments input.
I decided to make it a PR because I'm rusty as heck and might have broken something unintentionally :)
Closes #2395
> Adds args field to tools

- etc/config/rust.amazon.properties
> Add Rust 1.50.0

- app.js
- lib/logger.js
- package-lock.json
- package.json
May want to wait on this for https://github.com/JaniAnttonen/winston-loki/issues/47
Also need to packer and terraform a new AMI before deploying this.
> Add loki log transport

- etc/config/nim.amazon.properties
Related: https://github.com/compiler-explorer/infra/pull/467
> [FEATURE] Nim v1.4.4

- lib/demangler/cpp.js
- test/demangle-cases/bug-1336-first-20000-lines.asm.demangle
I skipped the tests on this commit so that I could push it,
and add the tests at a later date.
I do this because I'm not sure this does not break unreleated
stuff so I wanted to make the changes visible before fixing the tests
Closes #2439
> Add support for more cases of verbose demangling

- lib/exec.js
> fix compiler firejail execution with ldPath

- etc/config/cuda.amazon.properties
Adds version 1.12.0 of the Thrust/CUB CUDA library bundle.
> Add Thrust/CUB 1.12.0 to CUDA libraries.

- static/libs-widget-ext.js
> library search matches on name before match on description

- lib/cache/from-config.js
- lib/cache/multi.js
> Fix undefined stats logging

- lib/base-compiler.js
> add compilers ldpath to cached requests

- etc/config/ocaml.amazon.properties
Relevant PR: https://github.com/compiler-explorer/infra/pull/472
> Update OCaml to 4.10.2,4.11.2,4.12.0

- etc/config/c++.amazon.properties
Appears to work when tested locally
> Add trompeloeil C++ mocking framework

- etc/config/c++.amazon.properties
goes along with https://github.com/compiler-explorer/infra/pull/474
Add the entt library.
Tested locally and the "make check" tests (not that I modified anything they test).
> add entt library

- lib/compilers/fake-for-test.js
- lib/handlers/compile.js
- test/handlers/compile-tests.js
> Let api compile also detect aliased compilers

- etc/config/ocaml.amazon.properties
We will probably have to wait to deploy the infrastructure.
> Add ocaml4120flambda and set as default OCaml compiler

- etc/config/rust.amazon.properties
See https://github.com/compiler-explorer/infra/pull/477.
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
> Rust 1.51.0

- etc/config/analysis.amazon.properties
- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Merge after https://github.com/compiler-explorer/infra/pull/478
See #799
> Add clang-assertions-trunk compiler

- etc/config/c++.amazon.properties
These are the last two requests in:
https://github.com/compiler-explorer/compiler-explorer/issues/2195
I created these new lines by copying-and-pasting the text for immer, by the same author.
> Add lager and zug libraries by @arximboldi - #2195

- etc/config/c++.amazon.properties
I put together two examples showcasing jsoncpp, in the hope it proves useful for anyone starting out with the library:
* https://godbolt.org/z/o1W1jofna : make a json object then output to styled string
* https://godbolt.org/z/rfPajea5G : load a std::string into json and access some elements
> Add a couple of examples for jsoncpp

- static/panes/ast-view.js
Highlight the linked lines between the LLVM AST pane and other panes.
Highlight the first source line (and linked lines in other panes, such as assembler or LLRM IR) corresponding to a node in the LLVM AST line when it is under a mouse cursor.
Highlight all the LLVM AST lines that are relevant to the given source line.
> [frontend-only] Highlight the linked lines between the LLVM AST and other panes

- etc/config/c++.amazon.properties
Add an example for pugixml (#2537)
https://godbolt.org/z/bE3WPhMYq
> Add an example for pugixml (#2537)

- etc/config/compiler-explorer.defaults.properties
- lib/base-compiler.js
- lib/compiler-finder.js
- lib/compilers/assembly.js
- lib/compilers/dmd.js
- lib/compilers/pascal.js
- lib/compilers/win32.js
- lib/compilers/wine-vc.js
- lib/objdumper/_all.js
- lib/objdumper/base.js
- lib/objdumper/binutils.js
- lib/objdumper/default.js
- lib/objdumper/elftoolchain.js
- lib/objdumper/index.js
- lib/objdumper/llvm.js
- test/base-compiler-tests.js
> Support ELF Tool Chain and LLVM objdump

- etc/config/execution.beta.properties
- etc/nsjail/execute.cfg
- etc/nsjail/sandbox.cfg
- lib/exec.js
- test/exec-tests.js
Work in progress, but thought I'd make this PR up early for comments and "zomg no don't do that" etc
> Add support for nsjail compiler executions

- etc/config/c++.amazon.properties
- etc/config/fortran.amazon.properties
Needs https://github.com/compiler-explorer/infra/pull/492
> add oneapi 2021.2.0

- etc/config/assembly.amazon.properties
- etc/config/compiler-explorer.amazon.properties
- etc/config/compiler-explorer.defaults.properties
- lib/base-compiler.js
- lib/compilers/assembly.js
- lib/tooling/readelf-tool.js
- static/timing-info-widget.js
> Link into executable for Assembly language

- .github/labeler.yml
This makes the labeler action a bit more useful
Made it into a PR so someone can review, just in case I misplaced any compiler :)
> Add lang labeler filters

- etc/config/c++.amazon.properties
This is the CE patch that goes with https://github.com/compiler-explorer/infra/pull/499
> Update for OFW inclusion

- etc/config/c.amazon.properties
Fix issue [2559](https://github.com/compiler-explorer/compiler-explorer/issues/2559)
> Add missing webasm target for clang in C

- etc/config/nim.amazon.properties
Add nim compiler version `1.4.6`. Related: https://github.com/compiler-explorer/infra/pull/501
> [FEATURE] Nim v1.4.6

- etc/config/ada.amazon.properties
- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/rust.amazon.properties
Updated all (global) objdumpers and demanglers too.
Infra: https://github.com/compiler-explorer/infra/pull/505
> Add GCC 11.1

- etc/config/rust.amazon.properties
Add gccrs-snapshot config pointing to the daily build.
> Add GCCRS support in the Rust config

- etc/config/c++.amazon.properties
Companion to https://github.com/compiler-explorer/infra/pull/509
> Add kiwaku to CE

- etc/config/rust.amazon.properties
infra: https://github.com/compiler-explorer/infra/pull/511
> Rust 1.52.0

- etc/config/analysis.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/clean.amazon.properties
- etc/config/cppx.amazon.properties
- etc/config/cppx_blue.amazon.properties
- etc/config/cppx_gold.amazon.properties
- etc/config/d.amazon.properties
- etc/config/fortran.amazon.properties
- etc/config/go.amazon.properties
- etc/config/haskell.amazon.properties
- etc/config/ispc.amazon.properties
- etc/config/llvm.amazon.properties
- etc/config/pascal.amazon.properties
- etc/config/rust.amazon.properties
- etc/config/swift.amazon.properties
- etc/config/zig.amazon.properties
See also [PR #514 in `compiler-explorer/infra`](https://github.com/compiler-explorer/infra/pull/514)
> updated OSACA version to 0.4.3

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/516
> Add LDC 1.25.1 and 1.26.0

- static/sharing.js
> remove link caching and other useless code

- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
GCC 8.5 was just released, 8.4 was released a couple months ago.
https://github.com/compiler-explorer/infra/pull/519
> GCC 8.4 and 8.5

- lib/clientstate-normalizer.js
- lib/clientstate.js
- test/state/executorwrap.json
- test/state/executorwrap.json.normalized
- test/statenormalisation-tests.js
> Add wrap to clientstate executor

- CONTRIBUTORS.md
Used `git log --encoding=utf-8 --full-history --reverse "--format=format:%an;%ae"` and uniquing the lines to find where I should place myself in the list. cheers!
> Add Johan Engelen to contributors.md

- etc/config/nim.amazon.properties
Add nim compiler version 1.4.8. Related: https://github.com/compiler-explorer/infra/pull/525
> `[FEATURE] Nim v1.4.8`

- etc/config/assembly.amazon.properties
- etc/config/cuda.amazon.properties
Add Cuda Version 11.3.0 and 11.3.1.
Also update ptxas assembly from 11.0.2 to 11.3.1
Check also: https://github.com/compiler-explorer/infra/pull/524
> Add CUDA 11.3.X and ptxas 11.X

- app.js
- lib/handlers/route-api.js
Fixes #2655
Fixes #2670
Not sure what to name the call for #2670 - it's currently `/unstored`
> New calls for embed and code

- etc/config/c++.amazon.properties
- lib/compilers/_all.js
- lib/compilers/zigcxx.js
As requested by #2707
It still has the same problems found in #2434,
which that will get fixed in Zig 0.8.1
> Add Zig c++

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/529
> Rust 1.53.0

- etc/config/zig.amazon.properties
- lib/base-compiler.js
- lib/compilers/zig.js
This is the first Zig library added to the site, so this implementation
might be broken in unexpected ways
Closes #2525
The infra companion is https://github.com/compiler-explorer/infra/pull/534
> Adds Zig-args

- static/compiler-picker.js
- static/panes/executor.js
I don't really like this solution, but I haven't been able to come
up with a cleaner one, so unless someone finds a better way,
this will have to do
Closes #2730
> Adds a way for panes to filter compilers

- static/main.js
- static/panes/compiler.js
- static/panes/editor.js
- static/panes/executor.js
- static/settings.js
- static/timing-info-widget.js
- views/popups.pug
- views/templates.pug
It also removes some duplicated code concerning the settings while at it
> Simplify timing chart handling

- etc/config/cuda.amazon.properties
Adding new versions of these CUDA libraries. See also compiler-explorer/infra#538
> Add Thrust/CUB 1.12.1 and 1.13.0.

- etc/config/c++.amazon.properties
taoJSON is in beta, so only the trunk version at this time.
Corresponding infra PR:  
https://github.com/compiler-explorer/infra/pull/547
> add taoJSON

- etc/config/c++.amazon.properties
- etc/config/fortran.amazon.properties
Requires   https://github.com/compiler-explorer/infra/pull/548
I tested with a local instance.
> add oneapi 2021.3 release

- etc/config/openclc.amazon.properties
This PR adds Clang 12 support for OpenCL C.
> Add Clang-12 for OpenCL C

- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/llvm.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/550
> LLVM 12.0.1

- static/themes.js
> Update themes.js to tweak identifier color

- lib/asm-parser-crystal.js
- static/modes/asm-mode.js
* Fixes detection of Crystal quoted labels with escaped quotation marks
* Makes assembly view highlight lines starting with quoted labels properly
> Improve handling of Crystal's quoted labels

- lib/options-handler.js
- static/libs-widget-ext.js
- test/options-handler.js
Needs a review for the wording when no libs are available
This comes from a suggestion form #2778
> Adds .hidden for libraries

- static/history.js
- static/main.js
- static/sharing.js
> Ensure history is updated on every change. Closes #2762

- etc/config/haskell.amazon.properties
Closes #2786
This needs first to check if the changes on https://github.com/compiler-explorer/infra/pull/554 are ok
> Adds GHC 8.10.5 & 9.0.1

- static/components.js
- static/panes/compiler.js
- static/panes/flags-view.js
- static/panes/tool-input-view.js
- static/panes/tool.js
> Minor cleanups

- package-lock.json
- package.json
- static/tsconfig.json
- webpack.config.esm.js
Extracted from multifile branch. Doesn't include ts examples
> Enable typescript for clientside static scripts

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/569
> Rust 1.54.0

- .github/labeler.yml
- etc/config/ruby.amazon.properties
- etc/config/ruby.defaults.properties
- etc/scripts/ruby/disasm.rb
- examples/ruby/default.rb
- lib/compilers/_all.js
- lib/compilers/ruby.js
- lib/languages.js
- static/modes/asmruby-mode.js
- static/panes/compiler.js
- webpack.config.esm.js
[Ruby](https://www.ruby-lang.org/en/) is...
> A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.
This PR is largely inspired from the current Python support. The editor syntax is borrowed from Monaco and a minimal one is made for the disassembly output.
Related: compiler-explorer/infra#563
> Add support for Ruby 2.5 - 3.0

- etc/config/c++.amazon.properties
corresponding infra PR: https://github.com/compiler-explorer/infra/pull/561
> add scnlib 0.4

- static/main.js
Firefox kept complaining. This is a PR because I need someone to doublecheck that this does not break anything before merging,
just in case it's a case of "Works on my machine" :tm:
> Set sameSite: 'strict' for cookies

- static/panes/compiler.js
Untested
But should fix https://sentry.io/organizations/compiler-explorer/issues/2573192707/?environment=prod&project=102028&referrer=alert_email
> bugfix asm keyword

- etc/config/d.amazon.properties
Infra PR: https://github.com/compiler-explorer/infra/pull/572
> Add LDC 1.27.1 and make it the default compiler

- lib/handlers/compile.js
> new counters for cmake and bugfix executeCounter

- lib/handlers/compile.js
- static/panes/compiler.js
- static/panes/executor.js
> Cmakeproms

- etc/config/cuda.amazon.properties
See the discussion in this pull request for the details:
https://github.com/compiler-explorer/compiler-explorer/pull/2860
> Use default GPU target for CUDA compilation w/ NVCC

- etc/config/circle.amazon.properties
Add circle-131 with --gcc-toolchain switch support. Enables C++20
> Add circle-131 with --gcc-toolchain switch support. Enables C++20

- package.json
- static/alert.ts
- static/compiler-service.js
- static/explorer.scss
- static/libs-widget-ext.js
- static/main.js
- static/multifile-service.ts
- static/panes/compiler.js
- static/panes/conformance-view.js
- static/panes/editor.js
- static/panes/executor.js
- static/panes/gccdump-view.js
- static/panes/tool.js
- static/panes/tree.ts
- static/settings.js
- static/sharing.ts
- static/themes/dark-theme.scss
- static/themes/default-theme.scss
- static/tsconfig.json
- static/utils.ts
- views/popups.pug
- views/templates.pug
One thing led to another and ended up changing lots of smaller things.
Besides the UI stuff, there's a bit of code cleanup.
The idea is that you _don't_ notice any of the changes individually if you're not looking for them,
but it leaves a better impression overall.
As a PR so someone can check if that's the case, or if I broke something unexpectedly
> Some general UI touches

- static/panes/editor.js
Untested
Wonder if we should make this easier to extend for other languages
> [WIP] Clean's equivalent of cppreference

- static/panes/conformance-view.js
> fix skipasm

- lib/base-compiler.js
- static/multifile-service.ts
> support cmake for fortran

- etc/config/c++.amazon.properties
Companion PR: https://github.com/compiler-explorer/infra/pull/593
https://github.com/apache/xerces-c/ / https://xerces.apache.org/
> Add xerces-c v3.2.3

- etc/config/assembly.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/llvm.amazon.properties
LLVM and Clang 13.0.0 releases
Infra: https://github.com/compiler-explorer/infra/pull/599
> Install LLVM/Clang 13

- .github/workflows/test-and-deploy.yml
> Tag builds

- test/java-tests.js
- test/java/lookupswitch-bug-2995/Main.asm
- test/java/lookupswitch-bug-2995/input.java
- test/java/lookupswitch-bug-2995/output.asm
Adds a Java assembly test case for issue #2995 which was resolved in #2996
> Create test case for #2995

- lib/languages.js
- lib/options-handler.js
- static/panes/editor.js
It's recalculated every time the compilers change
Fixes #2960
But @supergrecko was already on it. I might have a worse solution so please feel free to refactor it for yourself.
I'll add tests as soon as I get free time again, and then merge if nothing blocks it
> Adds supportsExecute language option

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
A few missing entries that were left after rebasing my branch.
> A few extra Clang 13.0.0 entries

- etc/config/python.amazon.properties
Python 3.10.0 was released as the next stable version today.
> Add python 3.10 and make it the default.

- etc/config/cuda.amazon.properties
closes https://github.com/compiler-explorer/compiler-explorer/issues/1294
> Use cu++filt as the nvcc demangler

- CODE_OF_CONDUCT.md
> Updated Code of Conduct

- etc/config/cuda.amazon.properties
See https://github.com/compiler-explorer/infra/pull/621
> Add CUDA 11.4, 11.4.1, 11.5

- etc/config/cuda.amazon.properties
> Add Thrust and CUB 1.13.1, 1.14.0, and 1.15.0.

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
cc compiler-explorer/infra#628
> Update xsimd library version and paths

- static/panes/compiler.js
- static/settings.interfaces.ts
- static/settings.js
- views/popups.pug
Closes #2974 
Also adds a setting to disable the codelens from showing up in the compilers
> Add some new minor settings

- lib/base-compiler.js
- test/base-compiler-tests.js
This seems to be working, but I might be missing some edge case somewhere
Closes #3045
> Modify the path include guard to fix some false-positives

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/640
> Rust 1.57.0

- etc/config/c++.amazon.properties
As requested by @partouf here: https://github.com/compiler-explorer/infra/pull/641#issuecomment-985730640
> Add tbb 2021.4.0

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
Companion to https://github.com/compiler-explorer/infra/pull/642
> Add Raberu library

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
> mp-coro library added

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/648
> Add LDC 1.28.0 and make it the default compiler

- gh-dist-files.txt
> attempt at bugfixing deployment

- etc/config/c++.amazon.properties
Closes #3050.
Related: https://github.com/compiler-explorer/infra/pull/654
> Add Serenity's Lagom libraries

- static/analytics.ts
- static/global.ts
- static/options.interfaces.ts
Not sure that the changes are correct, will test in staging and merge once I make sure they are ok
> Move GA to ts

- LICENSE
> license update to github template

- etc/config/crystal.amazon.properties
Related: https://github.com/compiler-explorer/infra/pull/659
> Add Crystal 1.3.1

- docs/AddingALanguage.md
> Fix broken link to Monaco editor languages

- etc/config/c++.amazon.properties
Hopefully prevents more ldpath issues in the future
Fixes #3236
> Group together all the clang trunks

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/zig.amazon.properties
> * Adds Zig 0.9.0

- static/panes/compiler.js
I think this will do it for #3111.
> Add warning for -flto flag

- CONTRIBUTORS.md
- etc/config/c++.amazon.properties
Add jsoncpp 1.9.5
Companion PR on Infra: https://github.com/compiler-explorer/infra/pull/664
> add jsoncpp 1.9.5

- etc/config/c++.amazon.properties
- etc/config/circle.amazon.properties
Add https://github.com/hosseinmoein/DataFrame
Companion PR: https://github.com/compiler-explorer/infra/pull/665
> Add hosseinmoein/DataFrame

- static/explorer.scss
- static/panes/editor.js
- static/settings.ts
- views/popups.pug
- views/templates.pug
It was easier to just create a new PR, as I had some problems with the old one. The changes have already been reviewed so I guess there should be no major things blocking this from getting merged
> Reimplement more options for Ctrl-S

- static/panes/editor.js
- static/settings.ts
- static/sharing.ts
- views/popups.pug
Copy of #3295. 
Had to recreate the PR since I had some troubles rebasing my changes on top of #3297. Hopefully it is fine now 😄.
> Option to create a short link with Ctrl+s silently

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
> Add clang13.0.1

- etc/config/c++.amazon.properties
> Add llvm 13.0.1 (thanks @matsjla)

- lib/base-compiler.js
- static/panes/executor.js
We were catching an exception but giving no info that it happened, so it was a bit tricky to track down
Closes #3069
> Fixes Executor pane for Python (+ possibly more)

- etc/config/dart.amazon.properties
- etc/config/dart.defaults.properties
- Add `dartaotruntime` as the execution wrapper
- Enable execution
> Add Dart execution wrapper

- etc/config/dart.amazon.properties
- lib/asm-parser-dart.js
- lib/compilers/dart.js
This adds some more dart versions (depends on https://github.com/compiler-explorer/infra/pull/675)
> Add more dart versions

- .github/workflows/test-and-deploy.yml
- etc/scripts/orphancompiler.py
As a PR just in case I didn't take into account something
> Adds compiler check to ci workflow

- etc/config/ada.amazon.properties
> Fix (again) name in GNAT compiler

- static/timing-info-widget.js
Fixes darkplus theme detection for timing info widget
> Fix timing info widget dark theme check

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/684
> Rust 1.59.0

- app.js
> Add graceful shutdown

- static/widgets/load-save.ts
- views/popups.pug
I quickly hacked this so there actually might be a better way to implement it
Closes #3410
> Adds a way to delete localstorage saved files

- package-lock.json
> npm update all the things

- lib/parsers/asm-parser-dart.js
- lib/parsers/asm-parser.js
- test/filters-cases/sass-binary.asm
- test/filters-cases/sass-binary.asm.binary.directives.labels.comments.approved.txt
- test/filters-cases/sass-binary.asm.directives.approved.txt
- test/filters-cases/sass-binary.asm.directives.comments.approved.txt
- test/filters-cases/sass-binary.asm.directives.labels.approved.txt
- test/filters-cases/sass-binary.asm.directives.labels.comments.approved.txt
- test/filters-cases/sass-binary.asm.directives.labels.comments.library.approved.txt
- test/filters-cases/sass-binary.asm.directives.labels.comments.library.dontMaskFilenames.approved.txt
- test/filters-cases/sass-binary.asm.directives.library.approved.txt
- test/filters-cases/sass-binary.asm.none.approved.txt
> Handle lines with no opcodes

- static/noscript.ts
- webpack.config.esm.js
Moves the noscript stuff to TypeScript as well as updating the webpack entry
> Move static/noscript.js to TypeScript

- etc/config/c++.amazon.properties
https://github.com/compiler-explorer/infra/pull/687
> Add jsoncons

- CONTRIBUTORS.md
- examples/cuda/Add_two_arrays.cu
- examples/cuda/Max_array.cu
- examples/cuda/Sum_over_array.cu
Changes include  1 commit altering/adding the following files :
- `examples/cuda/`
- [Add_two_arrays.cu](https://godbolt.org/z/YazozoTha): (new file) element-wise add add 2 arrays and put the resultant in `result` array.
- [Max_array.cu](https://godbolt.org/z/bWxfzo1K5): (new file) use parallel reduction to find find maximum element in the array.
- [Sum_over_array](https://godbolt.org/z/jW6n74oT6): (new file) use parallel reduction to find the sum of the entire array.
- `CONTRIBUTORS.md`
- append my name at the end of the file
---
- working compiler explorer links are embedded in the file names above.
- Changes passed all the checks ( run via `make check` ) on my local machine.
Please let me know if there is something that isn't right or if something needs changing.
Thanks :)
> Add examples for CUDA (#921)

- static/explorer.scss
- static/themes/dark-theme.scss
- static/themes/default-theme.scss
Improved style for light mode:
> Improved cursor position display for light mode

- etc/config/typescript.amazon.properties
- lib/compilers/typescript.js
CC @ODuzhar - these are the fixes I made. I was unable to get any assembly output - is that not an option that works?
> Some fixups for typescript

- lib/clientstate.js
> Fix invalid typeof expression

- static/noscript.ts
Addresses #3453 
While I don't think it's very exploitable, it's also a very easy fix :)
> Fix DOM text reinterpretation issue

- etc/config/typescript.defaults.properties
adjust compiler path with infra (typescript-native)
> adjust compiler path with infra

- static/event-hub.ts
Tiny regression fix where I ended up splitting arguments into event, ...args :)
> Fix regression in #3462

- static/motd.interfaces.ts
- static/motd.ts
For https://github.com/compiler-explorer/infra/pull/693
> Add update specific motd message

- lib/base-compiler.js
- lib/compilers/nim.js
> Adds overridable orderArguments function

- static/compiler-picker.ts
- static/event-hub.ts
- static/hub.ts
- static/multifile-service.ts
- static/panes/ast-view.ts
- static/panes/cfg-view.ts
- static/panes/gnatdebug-view.ts
- static/panes/gnatdebugtree-view.ts
- static/panes/ir-view.ts
- static/panes/opt-view.ts
- static/panes/pane.ts
- static/panes/pp-view.ts
- static/panes/rusthir-view.ts
- static/panes/rustmacroexp-view.ts
- static/panes/rustmir-view.ts
- static/panes/tree.ts
Uses the new Hub and EventHub typescript types other places in the codebase
(followup to #3470)
> Use Hub and EventHub types in codebase

- lib/buildenvsetup/base.js
Fixes #3483 
Matches exception for icx that's in the builder script https://github.com/compiler-explorer/infra/blob/main/bin/lib/library_builder.py#L167
> bugfix library matching icx

- etc/config/rust.amazon.properties
> Rust 1.60.0

- etc/config/crystal.amazon.properties
Related: compiler-explorer/infra#701
> Add Crystal 1.4.0 and 1.3.2

- static/settings.ts
> Resolve @typescript-eslint/no-unnecessary-condition warnings for settings.ts

- static/alert.ts
- static/ansi-to-html.ts
- static/api/formatting.interfaces.ts
- static/codelens-handler.ts
- static/compiler-picker.ts
- static/formatter-registry.ts
- static/hub.ts
- static/lib-utils.ts
- static/line-colouring.ts
- static/multifile-service.ts
- static/sharing.ts
- static/themes.ts
- static/widgets/timing-info-widget.ts
> Resolve @typescript-eslint/no-unnecessary-condition for static/*.ts files

- etc/config/java.amazon.properties
- etc/config/kotlin.amazon.properties
- etc/config/scala.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/707
> Use OpenJDK 18

- static/themes/dark-theme.scss
> Added dark theme styling for modal close buttons

- static/hub.ts
Not too useful, but I guesses that better them being there than missing
> Add missing types in hub.ts

- static/options.interfaces.ts
- static/widgets/libs-widget.ts
It appears `Library::examples` can be undefined after all (happens with msvc compilers)
> Fix for lib-widget.ts

- static/.eslintrc.js
With #3535 all warnings are resolved and this can now be an error
> Set @typescript-eslint/no-unnecessary-condition to error

- etc/config/crystal.amazon.properties
> Update Crystal 1.4.0 -> 1.4.1

- etc/config/compiler-explorer.no-s3.properties
> Use a persistent cache for compilers on discovery

- .github/workflows/test-and-deploy.yml
- etc/scripts/build-dist.sh
> Test and build distribution simultaneously

- views/templates.pug
> add descriptions for some buttons in the executor window

- lib/base-compiler.js
Closes #3555 (thanks @Callum-Shipton)
> Throw on bad mtime

- .github/workflows/test-and-deploy.yml
- .github/workflows/test-win.yml
> Use setup-node's built-in cache

- app.js
- package-lock.json
- package.json
Hushes "Uncontrolled data used in path expression".
> Sanitize filename

- .eslintrc.yml
- .idea/codeStyles/Project.xml
- app.js
- lib/base-compiler.js
- lib/buildenvsetup/ceconan.js
- lib/clientstate-normalizer.js
- lib/compiler-arguments.js
- lib/compiler-finder.js
- lib/compilers/ada.js
- lib/compilers/clean.js
- lib/compilers/dotnet.ts
- lib/compilers/erlang.js
- lib/compilers/nim.js
- lib/demangler/base.js
- lib/exec.js
- lib/handlers/api.js
- lib/handlers/assembly-documentation.ts
- lib/logger.js
- lib/tooling/clang-tidy-tool.js
- lib/tooling/pvs-studio-tool.js
- package.json
- test/demangler-tests.js
- test/exec-tests.js
- test/java-tests.js
- test/storage/storage-s3-tests.js
- test/tool-tests.js
First attempts at getting prettier and eslint to agree on most things, and apply a few changes to key files.
Apologies in advance for all the merge conflicts.
> Unify comma configuration; and apply format to some files.

- app.js
- lib/exec.js
Asynchronously set up WINE and don't wait for it to finish until we actually need it (if we do).
> Async WINE setup

- lib/compilers/dart.js
- lib/compilers/ldc.js
- lib/compilers/scala.js
- lib/compilers/solidity.js
- lib/compilers/zig.js
- lib/compilers/zigcc.js
- lib/compilers/zigcxx.js
- lib/options-handler.js
- lib/utils.ts
- test/options-handler.js
- test/utils-tests.js
Did not run prettier nor the linter to avoid a hard-to-read diff, but will do so before merging after I've ensured every change is ok
> All semver comparisons now ensure it's safe to do so

- app.js
- package-lock.json
- package.json
> Remove sentry tracing

- lib/asm-docs/arm32.ts
> Handle missing asm information

- static/alert.ts
- static/event-hub.ts
- static/hub.ts
- static/sharing.ts
> Import sentry correctly

- static/alert.ts
- static/motd.ts
- static/noscript.ts
- static/panes/pp-view.ts
- static/panes/tree.ts
- static/sharing.ts
- static/widgets/fontscale.ts
> Remove unecessary jquery imports in ts files

- etc/config/compiler-explorer.amazon.properties
- lib/base-compiler.js
> Optionally log the compiler cache keys and accesses

- Makefile
> Make `make` run the site similar to prod.

- static/panes/compiler.js
I made a whitespace change and then commited it to force a reformat. This it to help the PR #3585 whose change is obscured in some automatic formatting.
> Manually reformat panes/compiler.js to help with #3585

- CONTRIBUTORS.md
- lib/base-compiler.js
- static/components.js
- static/hub.ts
- static/panes/compiler.js
- static/panes/haskellstg-view.interfaces.ts
- static/panes/haskellstg-view.ts
- views/templates.pug
> add a view for Haskell STG intermediary output #3571

- static/.eslintrc.js
- static/hub.ts
- static/panes/tree.ts
It started as simply moving away from the `requires()`, but after changing some `any` to their corresponding files, I ended up going through the whole file
> Improve the TS implementation of the Tree pane

- static/panes/cfg-view.interfaces.ts
- static/panes/cfg-view.ts
- static/panes/pane.ts
This updates the cfg view to be more in line with the rest of the TS codebase.
I had to do some changes which I'm not too sure about, but at least the code is in a much better spot
> Improve the TS implementation of the cfg view

- static/formatter-registry.ts
- static/panes/compiler.js
> Fix wrong setting check for asm docs

- lib/base-compiler.js
- lib/compilation-env.js
> Move cache logging into a place where we have the key

- lib/compilers/clang.js
Fixes #3564
Forces dwarf4 unless otherwise set.
> Clang force dwarf4

- static/ansi-to-html.ts
- test/ansi-to-html-tests.js
> handle vt100 reverse video escape code

- etc/config/compiler-explorer.amazon.properties
> Finally fix...I think...the startup cache issue we had been seeing

- static/generated/changelog.pug
> fix linking to commits in the changelog

- lib/base-compiler.js
- lib/compilers/haskell.js
- static/components.js
- static/hub.ts
- static/panes/compiler.js
- static/panes/haskellcmm-view.interfaces.ts
- static/panes/haskellcmm-view.ts
- static/panes/haskellcore-view.interfaces.ts
- static/panes/haskellcore-view.ts
- static/panes/haskellstg-view.ts
- views/templates.pug
> add GHC Core and Cmm views #3571

- .github/workflows/test-and-deploy.yml
So sentry has the intermediate nonsense too. Hopefully pretty straightforward
> Fix sentry

- lib/compilers/java.js
I'm not sure if this is the best way to handle the case where the compilation fails and execution can't happen - I'm not familiar enough with all the intertwined parts here.
> Fix for #3637

- etc/scripts/parsed_pug_file.js
- static/generated/cookies.pug
- static/generated/privacy.pug
Also introduces some protectiion from accidental poicy hash changes
> Fix policy links

- static/panes/compiler.js
- static/panes/editor.js
> Make tabbed panes active when reveals are sent

- .github/workflows/test-win.yml
- package-lock.json
- package.json
> Use our own fork of approvals to fix a bunch of security warnings.

- etc/scripts/parsed_pug_file.js
- static/generated/cookies.pug
- static/generated/privacy.pug
Reinstates the policy stuff and makes the hash not sensitive to the last change times etc. Also fixes the policy links
> Take two of policy stuff

- static/ansi-to-html.ts
- static/panes/executor.js
- static/panes/output.ts
- static/panes/tool.js
- test/ansi-to-html-tests.js
> Reset stream styles between outputs

- static/main.js
> Respect the default language setting when doing code and ui reset

- .github/workflows/test-and-deploy.yml
- .github/workflows/test-win.yml
- CONTRIBUTING.md
- Makefile
- package.json
This script isn't used by any of our CI infrastructure, and is pretty useless because it just writes to stdout
> Remove unused prettier format script

- etc/config/c++.amazon.properties
> Add toml11 library

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/730
> Rust 1.61.0

- package-lock.json
- package.json
> Update vim keybinds

- lib/compilers/argument-parsers.js
> Make Clang parser logic shorter

- static/alert.ts
> Removed sentry log

- app.js
So that things such as `make dev EXTRA_ARGS="--language c,cpp"` are possible. Maybe should change it to allow language(s)?
> Allow multiple languages with --language

- .github/labeler.yml
- etc/config/fortran.amazon.properties
- lib/base-compiler.d.ts
- lib/compilers/_all.js
- lib/compilers/flang.ts
I currently don't have enough free storage space to test this properly, so I'll do it directly in staging.
Closes #3476
> First try at fixing flang

- views/index.pug
Sorry I hate to make a pr for such a little thing
> Quick change to an aria-labelledby

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
> Add new C and C++ ARMs cc @TamarChristinaArm

- etc/config/c++.amazon.properties
This PR adds a library I've been working on. It isn't header-only so we don't have to add it if it complicates things too much. Twin PR of https://github.com/compiler-explorer/infra/pull/739
> Add libassert

- lib/base-compiler.ts
Want to measure this for a week or so on grafana before switching on the c++ asm-parser
> add counter for dump&parse time

- etc/config/c++.amazon.properties
Hi, I'm interested in adding support for the C++ library, mfem: https://mfem.org
I'm trying to follow the instructions here: 
https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md 
but I don't fully understand all of the details
the companion PR for compiler-explorer/infra is https://github.com/compiler-explorer/infra/pull/741
> adding mfem library

- static/panes/editor.js
Fixes an issue with conformance views: They aren't respecting editor language at the moment.
Cause of the bug: Me a couple months ago 🤦‍♂️
> Fix issue with conformance views

- static/hub.ts
- static/panes/compiler.js
- static/panes/executor.js
Looks like some es6+ code slipped in. Also fixes a type problem in hub.ts
> Fix unexpected es6 code in /static

- static/main.js
Hello, I added the alert as an ```Alert.notify```, everything seems ok according to ```make check```.
> Add an alert to fix #3518

- static/panes/compiler.js
- static/panes/editor.js
Fix to https://github.com/compiler-explorer/compiler-explorer/pull/3647
> fix tab selection

- etc/config/c++.amazon.properties
> Add library avr-libstdcpp

- etc/config/c++.amazon.properties
> enable external asm-parser for binary mode

- static/panes/compiler.js
> Resolve #3786

- examples/ada/default.adb
complication unit => compilation unit
> Fix typo in Ada example

- app.js
Fix filters, and use full string match in alias too (not sure why it was a substring before)
> Fix filters

- app.js
- etc/config/c.amazon.properties
> Fix for morello

- static/monaco-config.ts
Closes #3698
From my testing this looks good, I don't think this breaks anything
> Improve wrapping of variable width fonts

- static/panes/editor.js
A previous fix of mine added squiggles for warnings generated by tools. This fix was slightly wrong in that it displayed the compiler instead of the tool, as the source of the error, in the tooltips. This fixes it.
> Fix tag source for tools.

- etc/config/c++.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/754
> Add MLIR libraries

- lib/keyed-type.interfaces.ts
- lib/keyed-type.ts
- types/execution/execution.interfaces.ts
Also discovered and fixed a bug with the TypicalExecutionFunc type
> Port lib/keyed-type.js to TypeScript

- lib/tooling/base-tool.js
> fix bug when creating error response

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/763
> Rust 1.62.0

- package-lock.json
> Freshen some deps

- static/themes/dark-theme.scss
> Add dark theme styling for webkit scrollbars

- etc/config/crystal.amazon.properties
Related: compiler-explorer/infra#766
> Add Crystal 1.5.0

- package-lock.json
> npm upgrade

- lib/tooling/base-tool.js
> Changes to prometheus counters

- lib/compilers/ldc.js
I am not able to test this locally myself. I've copied and modified the code from rust.ts and clang.ts.
> Enable LLVM optimisation pipeline viewer for LDC + ASan symbolizer

- lib/compilers/nvcc.js
> fix for pre v11 nvcc

- etc/config/ada.amazon.properties
- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
Add GCC 10.4.0 native.
fixes #3815
> Add GCC 10.4.0 native (x86_64)

- etc/config/c++.amazon.properties
Signed-off-by: Matheus Izvekov <mizvekov@gmail.com>
> Add clang "resugar" experimental variant (#3903)

- lib/llvm-opt-transformer.ts
> Fix `[object Object]` opt remarks display 

- static/panes/tool.js
Not sure how that happened because I was testing it while changing the PR, but somehow the patch that made its way in main had the wrong variable name in a few places.
> Fix variable name error.

- static/panes/pane.interfaces.ts
- static/panes/pane.ts
Also moves PaneCompilerState to pane.interfaces.ts
> fix: use interfaces in pane.ts and related files

- static/panes/editor.js
Closes #3931
But function is currently unused
> Fix selection fn signature

- etc/config/c++.amazon.properties
> Added description for libs.etl

- etc/config/d.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/774
> Add LDC 1.30.0 and make it the new default

- views/templates/panes/compiler.pug
> ✏️ [UI] Fix small UI typo

- lib/base-compiler.ts
Mostly to help #3961, but changed some I found along the way.
Lots of work still needed here, but babysteps :)
> Adds some ts typings to base-compiler.ts

- lib/compilers/wine-vc.js
- lib/exec.js
Two small commits that enable execution on wine-vc compilers.
> Fix execution on wine-vc compilers

- lib/compiler-finder.js
Needs to be tested in staging so we can check how many compilers are affected
Closes #3983
> Ensure displayed name is `name` if set

- lib/compilers/llc.js
- lib/compilers/opt.js
do not think that llc and opt have any good option for noDiscardValueNames so now that option do nothing.
> Add llvm opt pipeline for llc and opt

- static/widgets/toggles.ts
> Fix bug with state being undefined

- lib/compilers/clang.ts
> typescriptify clang.js

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- lib/base-compiler.ts
- lib/compilers/clang.ts
- lib/llvm-ir.js
- static/panes/device-view.js
- types/asmresult/asmresult.interfaces.ts
As described in https://github.com/compiler-explorer/compiler-explorer/issues/2244 - I have tested icx and clang so that it produces bundles and have tried to get them unbundled for the device view.
The device code is disassembled to LLVM-IR. In #2244 it is also discussed to convert possible gpu code to for example spir-v, I have not done this here yet.
The following things should work with these changes:
Using Clang
https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkDWBA9kQA44A26qAMiQB2wAK4lg6AJIATEAQCkAJgBCylS1G1k7APKjkHAwDEe6ISSLpGzAGZn6sdDJw7UskAEYs93h%2B%2B%2B5pbW6AAelhy8AHQEHBxYoEy4tFJCBNyiMs6MAAzMOLQAsiQ4QgDKrKKoBNYMecm6HOa5zNzCwB5MAJRdyQDCxRQACqisAFboBMiMnsxjXlhC6ADupn5ySr3cjACszEItWKyMACoY6ADUygDMs1jTdQw9WAjoJFmo%2BL1kXjtRAGwAFgAnDslAB2HaApQADh2nk81yw2wYgOYRC8O …
> Unbundle and disassemble device code

- lib/parsers/asm-parser.js
Also adds initial support for the cv_loc stuff discussed in Discord
For #4028 but does not close it as it's only minimal support
> Moves most re creations to the asm-parser constructor

- lib/parsers/asm-parser-spirv.ts
> asm-parser-spirv: take OpNoLine into account

- etc/config/crystal.amazon.properties
> Update Crystal 1.5.0 to 1.5.1

- app.js
- static/panes/editor.js
For #4030 but does not close it, needs more investigation
> Guard against missing buildResult in executor response

- lib/compilers/clspv.ts
This commit will need to be merged only once `clspv` has been update with a newest version supporting this option.
> compilers: clspv: add -g

- lib/tooling/llvm-cov-tool.ts
> Try to fix the llvm-cov ld issue by using compiler options

- etc/config/c++.amazon.properties
> Add tl::expected library

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/822
> Rust 1.64.0

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/fortran.amazon.properties
- etc/scripts/util/propscheck.py
- etc/scripts/util/propschecktest.py
- etc/scripts/util/test/cases/duplicate_lines.properties
Before this PR, we just checked if the whole line was the same, but this skipped the cases where a copy-paste correctly modified the prop value but left the prop key without modification
> Add better duplicated key check & fix those issues

- static/settings.ts
- static/sharing.ts
- views/popups/settings.pug
This is what came to mind when I read the issue, but might have (read: totally has) some cases for which it does not properly work.
I can't come up with a better way to implement this
Closes #3870
> First draft at keeping status per tab

- etc/config/compiler-explorer.defaults.properties
> Bump cv compiler count

- lib/compilation-queue.js
bowing to Austin's sensibilities on how best to do metrics for this kind of thing.
> Add stats for queue

- static/panes/compiler.js
Seems to work ok with more than one copy
Closes #4112
> Do not disable opt pipeline viewer when it opens

- etc/config/crystal.amazon.properties
> Add Crystal 1.6.0

- .github/workflows/browserslist.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/label.yml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-frontend.yml
- .github/workflows/test-win.yml
> Workflow bump v2 v3 checkout

- etc/config/c++.amazon.properties
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/1670
Infra PR: https://github.com/compiler-explorer/infra/pull/847
> add copperspice 1.8.0

- lib/options-handler.js
- lib/utils.ts
- static/widgets/libs-widget.ts
- test/options-handler.js
Might be a bit overkill, but this works the same as the compiler ordering
Closes #4142
> Sort libs based on semver

- static/panes/compiler.js
#4113 worked in testing because of my local setup (I'm guessing). Otherwise it changed something unreleated
> Properly allow for multiple opt pass panes

- static/styles/explorer.scss
- views/index.pug
I think this looks a bit better, but feel free to close if anyone thinks otherwise
> Makes li sponsor a btn-info

- lib/base-compiler.ts
- package-lock.json
- package.json
- static/components.ts
- static/event-map.ts
- static/panes/compiler.ts
- static/panes/conformance-view.ts
- static/panes/device-view.ts
- static/panes/editor.ts
- static/panes/opt-view.interfaces.ts
- static/panes/opt-view.ts
- static/panes/output.ts
- static/panes/pane.ts
- static/widgets/toggles.ts
- types/compilation/compilation.interfaces.ts
- types/compiler.interfaces.ts
The recent TS PRs #4105 #4132 #4143 had some issues still. This PR aims to fix all I can find. As a PR now to be able to disucuss them before I'm done checking all 3 PRs
> Try to fix main

- lib/compilers/ada.ts
Convert the ada compiler code to typescript.
> ada: move to typescript

- lib/base-compiler.ts
- lib/tooling/base-tool.interface.ts
- lib/tooling/base-tool.ts
- static/panes/compiler.ts
- test/llvm-pass-dump-parser-tests.js
- types/compilation/compilation.interfaces.ts
- types/compiler.interfaces.ts
> Fix typing and usage of tools

- static/panes/compiler.ts
> Fix ASM spam in the sentry logs

- static/panes/compiler.ts
and fix up some things where previously we had odd null checks that somehow became .get() (which means it worked exactly once)
> Use non-private ways of context menu

- static/components.interfaces.ts
- static/components.ts
- static/panes/compiler.ts
- static/panes/device-view.interfaces.ts
- static/panes/device-view.ts
- static/panes/editor.ts
- types/compilation/compilation.interfaces.ts
- types/resultline/resultline.interfaces.ts
Required fixing a bunch of types
> Change auto-open device-view to only when there's device asm

- lib/sponsors.interfaces.ts
- lib/sponsors.ts
- static/main.js
- test/sponsors-test.js
> Convert sponsor.js to sponsor.js, update tests to be more targeted.

- etc/config/sponsors.yaml
- lib/sponsors.interfaces.ts
- lib/sponsors.ts
- static/main.js
- test/sponsors-test.js
- views/bits/sponsors-content.pug
> Support multiple sponsor descripts

- static/panes/compiler.ts
- static/panes/conformance-view.ts
You can actually send a function that returns the config as the second parameter
> Stop beliving the lies of GL's .d.ts

- lib/base-compiler.ts
- lib/exec.ts
Brings over the await fixes from #4204
> Port @trxcllnt improvements to awaiting

- etc/config/c++.amazon.properties
- lib/base-compiler.ts
- lib/demangler/nvhpc.ts
- lib/exec.ts
<details><summary>Adds nvc++ as a C++ compiler:</summary><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/178183/198147097-4365e480-2eba-4aa6-9108-7d18c2273b24.png"><img src="https://user-images.githubusercontent.com/178183/198147097-4365e480-2eba-4aa6-9108-7d18c2273b24.png" alt="image" style="max-width: 100%;"></a></details>
Related infra PR: https://github.com/compiler-explorer/infra/pull/855
> Add `nvc++` as a C++ compiler

- etc/config/c++.amazon.properties
Adds [SeqAn3](https://github.com/seqan/seqan3/) as a C++ library.
Related PR: https://github.com/compiler-explorer/infra/pull/856
> Add SeqAn3 C++ library

- .idea/codeStyles/Project.xml
- static/styles/themes/dark-theme.scss
This allowed me to collapse some redundant rules, and by lexocigraphically sorting them they are now (I think) easier to maintain. There are no style changes
> Use more scss-isms in dark-theme

- etc/config/crystal.amazon.properties
> Update Crystal 1.6.0 -> 1.6.1

- lib/compilers/assembly.ts
When converting to TS I noticed the types did not compute, had to override buildExecutableInFolder instead of buildExecutable.
Will also be better for https://github.com/compiler-explorer/compiler-explorer/issues/4160 which I'll do on-top of these changes after this.
> Typescriptify compilers/assembly.js and fix mistake overriding the wrong function

- static/panes/ast-view.ts
- static/panes/compiler.ts
- static/panes/device-view.ts
- static/panes/editor.ts
- static/panes/ir-view.ts
- static/settings.ts
- views/popups/settings.pug
It's been a while, but this should close #3487 by adding a new setting that avoids removing the line linking after 5 seconds
> Allow line linkings to be highlighted forever

- etc/config/rust.amazon.properties
Infra: https://github.com/compiler-explorer/infra/pull/862
> Rust 1.65.0

- views/index.pug
> Fix broken Rest UI button

- static/sharing.ts
Fixes cloning window not using the most up-to-date state
> Save state on blur

- etc/nsjail/execute.cfg
> Increase nsjail /tmp max size

- static/panes/compiler.ts
- static/panes/executor.js
- static/panes/output.ts
- types/compilation/compilation.interfaces.ts
> Fix errorResponse return value

- lib/parsers/asm-parser-cc65.ts
- lib/parsers/asm-parser-spirv.ts
- lib/parsers/asm-parser.ts
- test/filters-cases/bug-1285.asm.none.approved.txt
- test/filters-cases/gcc-x86-vector.asm.none.approved.txt
- test/filters-cases/intsize.asm
- test/filters-cases/intsize.asm.binary.directives.labels.comments.approved.txt
- test/filters-cases/intsize.asm.directives.approved.txt
- test/filters-cases/intsize.asm.directives.comments.approved.txt
- test/filters-cases/intsize.asm.directives.labels.approved.txt
- test/filters-cases/intsize.asm.directives.labels.comments.approved.txt
- test/filters-cases/intsize.asm.directives.labels.comments.library.approved.txt
- test/filters-cases/intsize.asm.directives.labels.comments.library.dontMaskFilenames.approved.txt
- test/filters-cases/intsize.asm.directives.library.approved.txt
- test/filters-cases/intsize.asm.none.approved.txt
- test/filters-cases/intsize.c
- types/asmresult/asmresult.interfaces.ts
> Bugfix Map usage

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
Add new TI C6x config for C and C++ (c6x-elf).
fixes #1806
> Add c6x config

- etc/config/c++.amazon.properties
Adds both missing versions
Closes #4141
> Add fmt 9.0.0 & 9.1.0

- static/panes/compiler.ts
> Hide scroll to source context menu if line has no source

- CONTRIBUTORS.md
- lib/parsers/asm-parser.ts
> Add missing data definition directives (fixes #4275)

- static/multifile-service.ts
- static/panes/editor.ts
- static/panes/tree.ts
- static/styles/explorer.scss
- views/templates/panes/tree.pug
Initial working version.
Fixes #4244
> File drop support

- static/panes/tree.ts
> reset file input after loading

- lib/base-compiler.ts
- static/widgets/timing-info-widget.ts
- types/compilation/compilation.interfaces.ts
- types/compilation/llvm-opt-pipeline-output.interfaces.ts
- types/execution/execution.interfaces.ts
Supporting efforts related to #4283
> Added llvm opt pipeline timing info

- etc/config/python.defaults.properties
- lib/base-compiler.ts
Types had a missmatch when they were interpreted
Also updated the default python versions available to local users
> Fix execution for interpreted languages

- etc/config/c++.amazon.properties
Related infra PR: https://github.com/compiler-explorer/infra/pull/877
> Add NVHPC SDK 22.11

- etc/config/crystal.amazon.properties
> Update Crystal 1.6.1 -> 1.6.2

- etc/scripts/docenizers/docenizer-evm.py
- lib/asm-docs/evm.ts
- lib/asm-docs/generated/asm-docs-evm.js
> Add support for evm opcode documentation

- etc/config/c++.amazon.properties
- etc/config/c++.gpu.properties
- etc/config/compiler-explorer.gpu.properties
This worked for cuda, and reaing the discovery code I think it should "just" work here too.
> Move nvc++ to gpu instance

- app.js
- lib/base-compiler.ts
- lib/compiler-finder.js
> Don't try and set up buildenv or external parser if remote

- etc/nsjail/execute.cfg
> Bump the amount of temp disk space available for NVidia c++

- static/panes/compiler.ts
- static/panes/diff.ts
- static/panes/editor.ts
- static/panes/pane.ts
- static/panes/tool-input-view.ts
Avoids some duplication in code, even tho it does some unecessary work in some other panes
> Fetch settings in initializeGlobalDependent

- lib/compilers/dotnet.ts
Include F# library pack in packageSource.
> Fix F# build failure

- lib/compilers/dotnet.ts
- check return code of restore
- set env vars to prevent file size blowout
> Fixes for .NET 7

- etc/config/c++.amazon.properties
- etc/config/c.amazon.properties
- etc/config/zig.amazon.properties
Update config for C, C++ and Zig.
fixes #4357
> Add Zig 0.10.0

- etc/config/circle.amazon.properties
This library with C++ compiler already
library source and details here: https://gitlab.com/correaa/boost-multi
> Add Multi library to Circle compiler

- etc/config/cpp_for_opencl.amazon.properties
- etc/config/openclc.amazon.properties
Update C++ for OpenCL and OpenCL C with
clang-14 and clang-15 compilers.
> Add clang-14 and clang-15 to OpenCL

- package-lock.json
All tests pass. `make` worked, and I checked a few languages and dialogs. All seems ok.
> Bump all minor versions - npm update

- lib/parsers/asm-parser.ts
> AsmParser implements IAsmParser

- lib/base-compiler.ts
- lib/compilers/fake-for-test.ts
- lib/handlers/compile.ts
- types/compilation/compilation.interfaces.ts
- types/compiler.interfaces.ts
just a minimal change that doesn't break anything
> first bits of compiler interface

- lib/compilers/carbon.ts
I tried to add types too, but I think that should be a separate PR (as base-compielr lacks them too)
> Ts-ify carbon

- lib/compilers/argument-parsers.ts
Minimal type annotations, just the basic conversion as we discussed in discord
> Ts-ify argument parsers

- lib/compilers/carbon.ts
Just a small pr to make the linter happy
> Fix carbon.ts linter errors

- lib/compiler-finder.ts
- lib/properties.ts
First pass at converting the compiler finder to ts
> Tsify compiler finder

- lib/compiler-finder.ts
- lib/options-handler.ts
- types/cache.interfaces.ts
> Tsify options-handler

- lib/base-compiler.ts
> fix interpreting with multiple files

- static/panes/cfg-view.ts
> Fix cfg chrome render bug

- package-lock.json
- package.json
- static/panes/cfg-view.ts
- tsconfig.frontend.json
- views/templates/panes/cfg.pug
Part 1 of implementing #4419 (cc @Saldivarcher)
There's a design decision to be made as far as themes go, should the export be theme-aware? At the moment it is and I've added a background rect to the svg to insert the pane's background color.
> Add svg exports for cfgs
